- deploy/.goreleaser.yml
> release filenames should not include version numbers, only os and arch

- cmd/kots/cli/install.go
- cmd/kots/cli/pull.go
- go.mod
- pkg/base/helm.go
- pkg/base/render.go
- pkg/pull/pull.go
- pkg/upstream/fetch.go
This fixes #25 by adding support for --set on the CLI for helm charts
> Support setting helm values

- .buildkite/pipeline.yml
- deploy/.goreleaser.snapshot.yml
- deploy/.goreleaser.yml
also run 'make snapshot-release' within CI
> build darwin and windows binaries without cgo

- pkg/image/image.go
- pkg/upstream/push_images.go
> Support 3 forms of dockerhub image tags

- pkg/kotsadm/postgres_objects.go
this fixes issues with DigitalOcean (and presumably other environments too)
> set fsgroup for postgres pod

- pkg/kotsadm/api_objects.go
> RBAC policy from kots install should be able to read encryption secret

- go.mod
- pkg/image/builder.go
- pkg/image/image.go
- pkg/image/image_test.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
- pkg/upstream/write_images.go
go.mod updates
also add a solution for docker hub images like 'nginx' that lack a domain
> never write images to files when pulling, upload them immediately

- go.mod
- pkg/image/builder.go
- pkg/image/image.go
- pkg/image/image_test.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
- pkg/upstream/write_images.go
Reverts replicatedhq/kots#186, restores replicatedhq/kots#183
> Revert "Revert "never write images to files when pulling, upload them immediately""

- go.mod
- pkg/kotsadm/operator.go
instead of just checking if it's a not found error
> check all errors when getting operator clusterRoleBinding

- pkg/k8sutil/kustomization.go
fixes https://github.com/replicatedhq/kots/issues/205
> sort kustomization to improve version diffs

- ffi/online.go
This moves some code from typescript (kotsadm) over to here.
> Rewrite config in kots

- pkg/kotsadm/api.go
- pkg/kotsadm/api_objects.go
- pkg/kotsadm/is_openshift.go
- pkg/kotsadm/kotsadm.go
- pkg/kotsadm/minio_objects.go
- pkg/kotsadm/operator.go
- pkg/kotsadm/operator_objects.go
- pkg/kotsadm/postgres_objects.go
- pkg/kotsadm/schemahero_objects.go
- pkg/kotsadm/web.go
- pkg/kotsadm/web_objects.go
Also, ~provide CPU/memory requests and limits~, and don't fail to create the operator deployment if a restricted operator role already exists
> Don't force specific user IDs on OpenShift

- pkg/image/builder.go
> allow disabling image privacy check security for development environments

- pkg/template/config_context_test.go
> add link to ship dep resolution code as reference 

- pkg/template/config_context.go
log errors decrypting passwords when creating config context
> decrypt password outside of config value dep resolution loop

- kotskinds/apis/kots/v1beta1/application_types.go
- pkg/kotsadm/kotsadm.go
- pkg/kotsadm/kotsadm_objects.go
- pkg/kotsadm/kotsadm_test.go
- pkg/kotsadm/operator.go
- pkg/kotsadm/operator_test.go
This fixes #409 by implementing the proposal
> Support requireMinimialRBAC flag

- cmd/kots/cli/admin-console.go
- cmd/kots/cli/install.go
- pkg/k8sutil/portforward.go
- pkg/upload/upload_license.go
> Try 8800, but fall back to other ports

- pkg/template/builder.go
- pkg/template/config_context.go
This reverts commit e854461c82e0f6aebee9153222510a5dc6346704.
perhaps we should turn on CI for all prs, even if not into master
> Revert "remove possibility of forgetting to add context in future"

- .github/workflows/build-test.yaml
and don't run again every time that a commit is used in a pr
> run CI when you push to a branch

- integration/replicated/pull_test.go
filed as #462 to fix and enable
> disable flaky test

- cmd/kots/cli/download.go
- pkg/logger/logger.go
> Change default download path to cwd instead of ~

- cmd/kots/cli/install.go
- pkg/kotsadm/configvalues.go
- pkg/kotsadm/configvalues_objects.go
- pkg/kotsadm/license.go
- pkg/kotsadm/main.go
- pkg/kotsadm/types/deployoptions.go
- pkg/pull/pull.go
- pkg/upstream/admin-console.go
This PR also includes a little cleanup on `kots install` flags.
> Write config values to a secret

- cmd/kots/cli/pull.go
Tested against GCR with _json_key authentication
> add flags for registry auth (fixes #488)

- docs/proposals/object-store.md
Assigning @marccampbell but would also love to hear from @divolgin and @emosbaugh since y'all have done a lot of work with custom S3 endpoints -- what other parameters do you think we might need to consider?
> adding proposal for external object store

- pkg/template/config_context.go
- pkg/template/config_context_test.go
fixes panic encountered with the beta linter: https://github.com/replicatedhq/replicated/issues/123
> template functions should not panic when license is nil

- kotsadm/web/src/components/apps/AppSnapshots.jsx
> Showing disconnected message on snapshots when connection is lost

- kotsadm/operator/pkg/client/hooks.go
> Don't leave orphaned pods when deleting jobs

- .gitignore
- Makefile
- deploy/.goreleaser.yaml
> Static build and makefile should match goreleaser

- go.mod
- go.sum
- kotsadm/go.mod
- kotsadm/go.sum
- kotsadm/operator/go.mod
- kotsadm/operator/go.sum
This doesn't handle the ffi function - that's being moved to golang in another PR
> update troubleshoot to v0.9.33 in kots/kotsadm/operator

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
> Removing rollback button on versions that were never deployed

- kotsadm/operator/pkg/client/deploy.go
- kotsadm/operator/pkg/client/gvkn.go
> Delete objects in different namespaces

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/apps/Dashboard.jsx
- kotsadm/web/src/components/apps/DashboardCard.jsx
- kotsadm/web/src/components/modals/UpdateCheckerModal.jsx
- kotsadm/web/src/scss/components/watches/WatchVersionHistory.scss
- kotsadm/web/src/utilities/utilities.js
> Update checker modal design

- kotsadm/kustomize/overlays/dev/minio/statefulset.yaml
- kotsadm/operator/kustomize/base/kustomization.yaml
- kotsadm/operator/kustomize/base/rbac.yaml
Adding in the rbac, and the minio statefulset was missing a serviceName
> Cleanup dev env

- kotsadm/pkg/apiserver/server.go
- kotsadm/pkg/handlers/redact.go
- kotsadm/pkg/handlers/troubleshoot.go
- kotsadm/pkg/redact/redact.go
- kotsadm/pkg/redact/redact_test.go
implements https://github.com/replicatedhq/kots/pull/569
> redact spec api

- kotsadm/migrations/tables/app.yaml
- kotsadm/pkg/handlers/update_checker_spec.go
- kotsadm/pkg/updatechecker/updatechecker.go
- kotsadm/web/src/components/modals/UpdateCheckerModal.jsx
> default automatic updates to be every 4 hours

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/scss/utilities/tooltip.scss
> Show invalid YAML error on version histories

- kotsadm/pkg/handlers/update.go
- kotsadm/pkg/updatechecker/updatechecker.go
> fix duplicate releases in automatic update checks

- kotsadm/pkg/supportbundle/filetree.go
> show troubleshoot directories names instead of paths

- kotsadm/web/src/utilities/utilities.js
> fix snapshots daily schedule cron expression

- kotsadm/web/src/components/apps/AppConfig.jsx
- kotsadm/web/src/components/apps/AppDetailPage.jsx
- kotsadm/web/src/components/tree/KotsApplicationTree.jsx
> fix kotsadm app config and view files page titles

- cmd/kots/cli/upstream-upgrade.go
> Fix update check response struct in 'kots upstream upgrade' command

- kotsadm/web/src/components/BackupRestore.jsx
- kotsadm/web/src/components/UploadLicenseFile.jsx
- kotsadm/web/src/scss/components/UploadLicenseFile.scss
> Updated upload license view, empty backup view

- kotsadm/pkg/online/online.go
- kotsadm/web/src/components/UploadAirgapBundle.jsx
- kotsadm/web/src/components/UploadLicenseFile.jsx
> trigger preflights from the api not the ui

- kotsadm/web/src/components/UploadLicenseFile.jsx
> Hide restore option when uploading license

- kotsadm/api/src/troubleshoot/troubleshoot_store.ts
> sort support bundles descending

- kotsadm/api/src/snapshots/resolvers/parseBackupLogs.ts
- kotsadm/api/src/snapshots/resolvers/veleroClient.ts
- kotsadm/web/src/components/apps/AppSnapshotDetail.jsx
> Show snapshot warnings and hide errors/warnings block if there are empty

- kotsadm/pkg/handlers/update.go
- kotsadm/pkg/updatechecker/updatechecker.go
- kotsadm/pkg/upstream/upstream.go
- kotsadm/pkg/version/version.go
> ability to deploy latest update when checking for updates

- kotsadm/api/src/snapshots/resolvers/veleroClient.ts
> Volumes names in volumes snapshot list

- pkg/template/static_context.go
Adds a NodeCount template function that returns the number of nodes currently in the target cluster.
Resolves #696.
> Add NodeCount function

- kotsadm/web/src/components/snapshots/SnapshotStorageDestination.jsx
> Show provider dropdown as a label if only one option available

- kotsadm/api/src/snapshots/graphql/snapshot_types.ts
- kotsadm/api/src/snapshots/resolvers/parseBackupLogs.ts
- kotsadm/api/src/snapshots/snapshot.ts
- kotsadm/web/src/components/apps/AppSnapshotDetail.jsx
- kotsadm/web/src/queries/SnapshotQueries.js
> Fix - failed kots snapshots hooks are shown as completed

- kotsadm/pkg/preflight/execute.go
- kotsadm/pkg/preflight/preflight.go
- kotsadm/web/src/components/PreflightResultPage.jsx
> auto-deploy first app version

- kotsadm/web/src/components/UploadLicenseFile.jsx
- kotsadm/web/src/scss/components/UploadLicenseFile.scss
> Restoring to the old upload license view

- kotsadm/pkg/airgap/airgap.go
- kotsadm/pkg/airgap/update.go
- kotsadm/pkg/handlers/config.go
- kotsadm/pkg/handlers/upload.go
- kotsadm/pkg/license/license.go
- kotsadm/pkg/online/online.go
- kotsadm/pkg/registry/registry.go
- kotsadm/pkg/upstream/upstream.go
- kotsadm/pkg/version/version.go
> create app version archive before the db record

- kotsadm/web/src/components/UploadLicenseFile.jsx
> Upload license flow fixes

- kotsadm/api/src/snapshots/resolvers/veleroClient.ts
> Correct volume name on restore

- kotsadm/web/src/components/apps/AppSnapshotRestore.jsx
> Fix blank restore failed screen

- kotsadm/pkg/apiserver/server.go
- kotsadm/pkg/handlers/preflight.go
- kotsadm/pkg/preflight/preflight.go
- kotsadm/web/src/components/PreflightResultPage.jsx
> ability to rerun preflight checks

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/scss/components/watches/WatchVersionHistory.scss
> Disable version if there is no commit hash when diffing releases

- kotsadm/web/src/components/troubleshoot/SupportBundleAnalysis.jsx
- kotsadm/web/src/components/troubleshoot/SupportBundleRow.jsx
> Adding loader when downloading a bundle

- kotsadm/api/src/troubleshoot/troubleshoot_store.ts
- kotsadm/web/src/components/troubleshoot/GenerateSupportBundle.jsx
closes https://github.com/replicated-collab/swimlane-replicated/issues/55
> Show latest instead of oldest support bundle when a new one is collected

- pkg/template/license_context.go
- pkg/template/license_context_test.go
> Include support for built-in license attributes in LicenseFieldValue template

- ffi/main.go
- ffi/online.go
- ffi/updatedownload.go
- integration/replicated/generate.go
- integration/upload/generate.go
- kotsadm/pkg/handlers/download.go
- kotsadm/pkg/version/archive.go
- pkg/base/write.go
- pkg/pull/archive.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
- pkg/upload/archive.go
- pkg/upstream/types/types.go
> Add yaml errors to file tree

- kotsadm/web/src/components/apps/AppDetailPage.jsx
- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/modals/ShowDetailsModal.jsx
- kotsadm/web/src/components/shared/FileTree.jsx
- kotsadm/web/src/components/tree/KotsApplicationTree.jsx
> Viewing invalid yaml files

- kotsadm/web/src/components/apps/AppSnapshotDetail.jsx
- kotsadm/web/src/components/apps/AppSnapshotRow.jsx
- kotsadm/web/src/components/apps/AppSnapshots.jsx
- kotsadm/web/src/components/modals/DeleteSnapshotModal.jsx
- kotsadm/web/src/components/modals/RestoreSnapshotModal.jsx
- kotsadm/web/src/scss/components/snapshots/AppSnapshots.scss
> More confirmation before restoring

- cmd/kots/cli/install.go
- cmd/kots/cli/pull.go
- pkg/kotsadm/api_objects.go
- pkg/kotsadm/kotsadm_objects.go
- pkg/kotsadm/proxy.go
- pkg/kotsadm/types/deployoptions.go
- pkg/pull/pull.go
- pkg/upstream/admin-console.go
- pkg/upstream/types/types.go
- pkg/upstream/write.go
> Use proxy info from environment in kotsadm API

- kotsadm/api/src/kots_app/graphql/kots_app_types.ts
- kotsadm/api/src/kots_app/kots_app.ts
- kotsadm/web/src/queries/AppsQueries.js
- kotskinds/apis/kots/v1beta1/config_types.go
> support when field for config groups

- kotsadm/pkg/handlers/snapshots.go
- kotsadm/pkg/snapshot/store.go
> fix other s3 compatible storage for snapshots

- kotsadm/api/src/snapshots/resolvers/veleroClient.ts
fixes https://github.com/replicatedhq/kots/issues/910
> use empty string for prefix if not defined

- kotsadm/pkg/handlers/config.go
- kotsadm/pkg/handlers/upload.go
- kotsadm/pkg/license/license.go
- kotsadm/pkg/registry/registry.go
- kotsadm/pkg/render/render.go
- pkg/midstream/write.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
Fixes https://github.com/replicatedhq/kots/issues/903
Fixes https://github.com/replicatedhq/kots/issues/479
> Render upstream directory when kots upload command is used

- pkg/kotsadm/affinity.go
- pkg/kotsadm/api_objects.go
- pkg/kotsadm/kotsadm_objects.go
- pkg/kotsadm/operator_objects.go
- pkg/kotsadm/restore_job.go
- pkg/kotsadm/schemahero_objects.go
> Prevent scheduling on arm64 nodes

- kotsadm/web/src/Root.jsx
- kotsadm/web/src/components/apps/AppDetailPage.jsx
- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/modals/ErrorModal.jsx
- kotsadm/web/src/components/shared/AirgapRegistrySettings.jsx
- kotsadm/web/src/components/shared/NavBar.jsx
- kotsadm/web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
- kotsadm/web/src/components/troubleshoot/GenerateSupportBundle.jsx
- kotsadm/web/src/components/troubleshoot/SupportBundleAnalysis.jsx
- kotsadm/web/src/components/troubleshoot/SupportBundleList.jsx
- kotsadm/web/src/scss/components/apps/AppVersionHistory.scss
> Error handling updates

- .github/workflows/proaction.yaml
Uses https://proaction.io to create PRs and keep the actions updated.
> Automate GitHub Workflow updates

- kotsadm/pkg/license/license.go
- kotsadm/pkg/updatechecker/updatechecker.go
- kotsadm/pkg/upstream/upstream.go
- pkg/pull/peek.go
- pkg/pull/pull.go
if the app archive fails to update, then the license may be out of date there
> pull updates with app license from DB, not from app archive

- kotsadm/web/src/components/apps/AppSnapshots.jsx
- kotsadm/web/src/components/troubleshoot/GenerateSupportBundle.jsx
> Stop polling when disconnect modal appears

- kotsadm/web/src/components/apps/AppSnapshotRestore.jsx
> In progress restore status

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
> Rolling back is leaving status deployed on previously deployed version

- kotsadm/kurl_proxy/cmd/main.go
- kotsadm/kurl_proxy/go.mod
- kotsadm/kurl_proxy/go.sum
Also prefer server cipher suites
> Kurl proxy min tls version is 1.2

- cmd/kots/cli/install.go
- cmd/kots/cli/reset-password.go
- pkg/kotsadm/kotsadm.go
- pkg/kotsadm/main.go
- pkg/kotsadm/types/deployoptions.go
* Ensure airgap flags in configmap
* Ensure console password is set when running headless install
* Fix infinite loop in pod restart
> Headless install fixes

- kotsadm/pkg/airgap/airgap.go
- kotsadm/pkg/config/config.go
- kotsadm/pkg/handlers/config.go
- kotsadm/pkg/online/online.go
- kotsadm/pkg/store/ocistore/version_store.go
- kotsadm/pkg/store/s3pg/version_store.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
- pkg/upstream/fetch.go
- pkg/upstream/replicated.go
- pkg/upstream/replicated_test.go
> Provide registry info for template builder

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/apps/Dashboard.jsx
- kotsadm/web/src/components/apps/DashboardCard.jsx
fixing issue: https://github.com/replicatedhq/kots/issues/704
> Version card check for updates

- kotsadm/web/src/components/AirgapUploadProgress.jsx
- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/apps/AppVersionHistoryHeader.jsx
- kotsadm/web/src/components/apps/AppVersionHistoryRow.jsx
- kotsadm/web/src/components/apps/DashboardCard.jsx
> Version history cleanup

- .github/workflows/build-test.yaml
This won't block a merge or show a failure yet. This will report every CRITICAL and HIGH CVE detected by trivvy
> Add image scanning to build

- kotsadm/web/src/components/apps/AppConfig.jsx
> config screen - cancel current request on live render

- kotsadm/web/src/components/shared/FileTree.jsx
Result: https://share.getcloudapp.com/7Ku8EDz5
> Clicking on a redaction should scroll to active file

- pkg/kotsadm/operator_objects.go
This label will be injected as part of the admin console upgrade process
> fix admin console operator disaster recovery upgrade

- kotsadm/web/src/components/snapshots/SnapshotDetails.jsx
> Total capture snapshot time fix

- kotsadm/pkg/snapshot/restore.go
- kotsadm/pkg/snapshot/types/types.go
- kotsadm/web/src/components/apps/AppSnapshotRestore.jsx
> Incorrect seconds when restoring volumes from application backups fix

- kotsadm/web/src/components/snapshots/SnapshotSchedule.jsx
> showing error when updating snapshot schedule

- kotsadm/web/src/components/snapshots/Snapshots.jsx
https://share.getcloudapp.com/4guJvqvl
> Preparing snapshot when starting

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/apps/Dashboard.jsx
> checking for updates errors

- kotsadm/web/src/components/snapshots/SnapshotDetails.jsx
> total capture time fix

- kotsadm/pkg/apiserver/server.go
- kotsadm/pkg/handlers/redeploy.go
- kotsadm/web/src/components/apps/AppDetailPage.jsx
- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/apps/AppVersionHistoryRow.jsx
- kotsadm/web/src/scss/utilities/buttons.scss
> ability to redeploy failed deployment

- kotsadm/web/src/components/apps/AppSnapshots.jsx
- kotsadm/web/src/components/snapshots/SnapshotSettings.jsx
- kotsadm/web/src/components/snapshots/Snapshots.jsx
- kotsadm/web/src/scss/components/snapshots/AppSnapshots.scss
- kotsadm/web/src/scss/utilities/icons.scss
> warn if velero is not 1.5.1

- kotsadm/web/src/Root.jsx
- kotsadm/web/src/components/apps/AppSnapshots.jsx
- kotsadm/web/src/components/shared/NavBar.jsx
- kotsadm/web/src/components/snapshots/Snapshots.jsx
- kotsadm/web/src/scss/components/shared/NavBar.scss
- kotsadm/web/src/scss/components/snapshots/AppSnapshots.scss
> clarity between instance snaphosts vs application snapshots

- kotsadm/pkg/user/user.go
Otherwise, if the user deletes the secret and recreates it with `kubectl kots reset-password`, the login code will fail due to the labels map being nil.
> check for nil secret labels map before reading/writing

- kotsadm/web/src/components/snapshots/Snapshots.jsx
> show snapshot errors

- cmd/kots/cli/remove.go
- cmd/kots/cli/root.go
- kotsadm/pkg/apiserver/server.go
- kotsadm/pkg/handlers/app.go
- kotsadm/pkg/store/ocistore/app_store.go
- kotsadm/pkg/store/s3pg/app_store.go
- kotsadm/pkg/store/store_interface.go
```
kubectl kots remove myapp-1 -n default
• Removing application myapp-1
• Application myapp-1 has been removed
```
```
kubectl kots remove myapp-1 -n default
• Removing application myapp-1
Error: app with slug myapp-1 not found
```
```
kubectl kots remove myapp -n default
• Removing application myapp
Error: failed to remove app, command may be retried with --force flag: version 0 is deployed
```
```
kubectl kots remove myapp -n default --force
• Removing application myapp
• Application myapp has been removed
```
> kots remove command for apps

- kotsadm/pkg/handlers/license.go
- kotsadm/pkg/license/license.go
- kotsadm/pkg/store/ocistore/license_store.go
- kotsadm/pkg/store/s3pg/license_store.go
- kotsadm/pkg/store/store_interface.go
- kotsadm/web/src/components/UploadLicenseFile.jsx
> block adding same license twice

- kotsadm/web/src/components/apps/AppVersionHistoryRow.jsx
> redeploy currently deployed app

- kotsadm/web/src/components/UploadLicenseFile.jsx
> uploading license error fix

- cmd/kots/cli/identity.go
- cmd/kots/cli/ingress.go
- cmd/kots/cli/install.go
- kotsadm/pkg/handlers/identity.go
- pkg/identity/config.go
- pkg/identity/deploy.go
- pkg/kotsadm/main.go
> validate identity config connection

- kotsadm/web/src/components/apps/AppVersionHistory.jsx
> fix copy on confirm deploy/rollback modal

- kotsadm/pkg/airgap/airgap.go
- kotsadm/pkg/airgap/update.go
- kotsadm/pkg/handlers/config.go
- kotsadm/pkg/handlers/identity.go
- kotsadm/pkg/handlers/preflight.go
- kotsadm/pkg/handlers/registry.go
- kotsadm/pkg/handlers/upload.go
- kotsadm/pkg/license/license.go
- kotsadm/pkg/online/online.go
- kotsadm/pkg/preflight/preflight.go
- kotsadm/pkg/render/helper/appfile.go
- kotsadm/pkg/render/render.go
- kotsadm/pkg/socketservice/socketservice.go
- kotsadm/pkg/store/s3pg/version_store.go
- kotsadm/pkg/upstream/upstream.go
- pkg/base/render.go
- pkg/base/templates.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
- pkg/template/application_context.go
- pkg/template/builder.go
- pkg/template/identity_context.go
- pkg/template/identity_context_test.go
- pkg/upstream/replicated.go
- pkg/upstream/replicated_test.go
https://github.com/replicatedhq/kots-idp-example-app/commit/e0665aa8ee5a93195388f73e3473816fe1693fa0
> Identity service name and port

- kotsadm/web/src/Root.jsx
- kotsadm/web/src/components/apps/AppDetailPage.jsx
- kotsadm/web/src/components/apps/AppIdentityServiceSettings.jsx
- kotsadm/web/src/components/apps/AppRegistrySettings.jsx
- kotsadm/web/src/components/apps/AppSettings.jsx
- kotsadm/web/src/components/identity/IdentityProviders.jsx
- kotsadm/web/src/components/shared/SubNavBar/SubNavBar.jsx
- kotsadm/web/src/config-ui/subNavConfig.js
> app level access

- kotsadm/web/src/components/identity/IdentityProviders.jsx
> Hide app url

- kotsadm/web/src/components/shared/FileTree.jsx
- kotsadm/web/src/components/troubleshoot/AnalyzerFileTree.jsx
> Hide top level support bundle dir

- kotsadm/web/src/components/identity/AddRoleGroup.jsx
- kotsadm/web/src/components/identity/IdentityProviders.jsx
- kotsadm/web/src/components/identity/RBACGroupPolicyRow.jsx
- kotsadm/web/src/scss/components/identity/IdentityManagement.scss
> Admin console and app RBAC groups

- kotsadm/web/src/components/identity/RBACGroupPolicyRow.jsx
> fix rbac group name display on rbac group rows

- kotsadm/pkg/handlers/login.go
- kotsadm/web/src/components/SecureAdminConsole.jsx
> Show friendly message when user is not in a group

- kotsadm/web/src/components/apps/AppConfig.jsx
- kotsadm/web/src/components/apps/AppVersionHistory.jsx
- kotsadm/web/src/components/apps/AppVersionHistoryRow.jsx
- kotsadm/web/src/scss/components/watches/WatchConfig.scss
- kotsadm/web/src/scss/utilities/icons.scss
> Config screen messages

- kotsadm/web/src/components/identity/AddRoleGroup.jsx
- kotsadm/web/src/scss/components/identity/IdentityManagement.scss
> centering adding roles modal

- kotsadm/web/src/components/identity/IdentityProviders.jsx
- kotsadm/web/src/scss/components/identity/IdentityManagement.scss
> Identity configuratio form style cleanup

- kotsadm/web/src/components/identity/IdentityProviders.jsx
- kotsadm/web/src/components/identity/RBACGroupPolicyRow.jsx
- kotsadm/web/src/scss/utilities/flexbox.scss
> Safari flexbox fixes

- kotsadm/web/src/components/apps/AppLicense.jsx
> License UI - entitlements fields multiline support

- kotsadm/pkg/handlers/license.go
- kotsadm/web/src/components/apps/AppLicense.jsx
- kotsadm/web/src/scss/utilities/typography.scss
> Monospace license fields type text

- kotsadm/web/src/components/snapshots/SnapshotDetails.jsx
> Moment js browser issue fix snapshots total capture time

- kotsadm/web/src/components/apps/ClusterNodes.jsx
- kotsadm/web/src/components/apps/NodeRow.jsx
> update cluster reporting rows. Add feedback for draining a node

- .github/workflows/build-test.yaml
The action has changed, and these appear to be the new params
> Update attributes in docker action to be compatible

- kotsadm/kustomize/overlays/dev/deployment.yaml
- kotsadm/pkg/k8s/kotsadm.go
- kotsadm/pkg/snapshot/backup.go
- kotsadm/web/src/components/snapshots/SnapshotDetails.jsx
> show proper completed time on snapshot detail page

- kotsadm/pkg/kurl/kurl_nodes.go
- kotsadm/pkg/kurl/types/types.go
- kotsadm/web/src/components/apps/ClusterNodes.jsx
- kotsadm/web/src/components/apps/NodeRow.jsx
- kotsadm/web/src/scss/components/apps/AppVersionHistory.scss
> add label to row if its a master node

- web/src/components/apps/Dashboard.jsx
- web/src/components/apps/DashboardCard.jsx
- web/src/scss/utilities/forms.scss
> Dashboard snapshot button fix

- cmd/kots/cli/restore.go
- cmd/kots/cli/velero.go
- pkg/handlers/backup.go
- pkg/handlers/snapshots.go
- pkg/informers/informers.go
- pkg/k8s/kotsadm.go
- pkg/k8sutil/kotsadm.go
- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/store.go
- pkg/kotsadmsnapshot/velero.go
- pkg/snapshot/backup.go
- pkg/snapshot/restore.go
- pkg/snapshot/velero.go
- web/src/Root.jsx
- web/src/components/BackupRestore.jsx
- web/src/components/apps/Dashboard.jsx
- web/src/components/modals/BackupRestoreModal.jsx
- web/src/components/snapshots/AppSnapshots.jsx
- web/src/components/snapshots/GettingStartedSnapshots.jsx
- web/src/components/snapshots/SnapshotInstallationBox.jsx
- web/src/components/snapshots/SnapshotSchedule.jsx
- web/src/components/snapshots/SnapshotSettings.jsx
- web/src/components/snapshots/SnapshotStorageDestination.jsx
- web/src/components/snapshots/Snapshots.jsx
- web/src/components/snapshots/SnapshotsWrapper.jsx
> Snapshots - Support minimal RBAC

- web/src/components/apps/Dashboard.jsx
- web/src/components/modals/SnapshotDifferencesModal.jsx
> Learn about differences modal snapshots

- web/src/components/apps/AppVersionHistoryHeader.jsx
- web/src/components/apps/DashboardCard.jsx
- web/src/components/config_render/ConfigGroup.jsx
- web/src/components/config_render/ConfigRender.jsx
- web/src/utilities/utilities.js
> Improved config links from app dashboard and currently deployed version

- web/src/components/apps/AppLicense.jsx
> Successfully showing license boolean fields

- go.mod
- go.sum
- pkg/image/builder.go
- pkg/kotsadm/push_images.go
- pkg/kotsadm/types/pushkotsadmoptions.go
This reverts commit 613a07396f3eb9da7d927d8bc9a5e531f8574787.
> Revert "Use containerregistry package to copy images"

- web/src/components/config_render/ConfigInput.jsx
- web/src/scss/components/config-render/config-base-styles.scss
> Displaying default config value

- .github/workflows/build-test.yaml
- .github/workflows/kotsadm.yaml
**actions/setup-node to v2.1.5** (https://github.com/replicatedhq/kots/pull/1584)
**docker/build-push-action to v2.3.0** (https://github.com/replicatedhq/kots/pull/1521)
> github actions dependencies

- web/src/components/PreflightResultErrors.jsx
- web/src/components/PreflightResultPage.jsx
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/modals/ErrorModal.jsx
- web/src/components/snapshots/AppSnapshots.jsx
- web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
- web/src/components/troubleshoot/GenerateSupportBundle.jsx
- web/src/components/troubleshoot/SupportBundleAnalysis.jsx
- web/src/components/troubleshoot/SupportBundleList.jsx
- web/src/components/troubleshoot/UploadSupportBundleModal.jsx
> Back to the dashboard button on error modal

- web/src/components/PreflightResultPage.jsx
- web/src/components/gitops/GitOpsRepoDetails.jsx
- web/src/components/troubleshoot/PreflightsProgress.jsx
- web/src/scss/components/AirgapUploadProgress.scss
- web/src/utilities/utilities.js
> Add progress bar while preflight checks are running

- pkg/handlers/registry.go
include the hostname and username
> improve 'failed to test push access' log line

- .github/workflows/kotsadm.yaml
- migrations/Dockerfile.skaffold
- migrations/deploy/Dockerfile
- migrations/fixtures/Makefile
This reverts commit 8b483ba9d56f82e80f90ea60ab8b7887c21fd389.
> Revert "Bump schemahero to 0.12.1"

- .github/workflows/build-test.yaml
- deploy/postgres/Dockerfile
- migrations/deploy/Dockerfile
- migrations/kustomize/overlays/dev/postgres.yaml
- pkg/kotsadm/objects/postgres_objects.go
This reverts commit 234b1ca56db4b08c63a3c348942721b70f2852b6.
> Revert "Move postgres to alpine and bump schemahero to 0.12.1"

- pkg/store/kotsstore/session_store.go
- moved lock to top level exported functions (so exported functions cannot call each other)
- secret update is now a get and an update because it's possible for resource version to drift
> Better session management

- pkg/gitops/gitops.go
- pkg/handlers/gitops.go
Modifying the initialization step in Gitops for the kotsadm backend to interpret an empty branch name as using the default (frontend work in separate PR). 
Init is always called on update or create from the frontend so it is relatively safe operation. Also from a performance standpoint, we can use the existing close with talking to the remote twice. The only downside is that changing the default branch will require a manual update, but imagining this to be rare for customers.
Tested on Github and Gitlab. Since it's vanilla git, not too worried about other compatibility.
> feat(kotsadm): use default branch for gitops when none provided

- web/src/components/PreflightResultPage.jsx
- web/src/components/troubleshoot/PreflightsProgress.jsx
Progress bar is much nicer while running preflight checks.
> preflight progress bar shows more natural progression

- pkg/kurl/kurl_nodes.go
- pkg/kurl/kurl_nodes_test.go
- pkg/kurl/node_join.go
This allows all host preflights to run.
> Add host flags to join scripts

- pkg/snapshot/store.go
The Azure plugin doesn't like have extra configuration parameters when you switch from S3:
```
time="2021-04-07T01:53:42Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = config has invalid keys [s3Url publicUrl region s3ForcePathStyle]; valid keys are [resourceGroup storageAccount subscriptionId blockSizeInBytes storageAccountKeyEnvVar bucket prefix caCert]" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/vendor/github.com/vmware-tanzu/velero/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/vendor/github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys …
```
> fix(kotsadm): clean switch from s3 to azure snaps

- pkg/upload/upload.go
Improve messaging when running upload from the wrong directory
> Improve messaging when running upload

- kotskinds/apis/kots/v1beta1/helmchart_types.go
- kotskinds/apis/kots/v1beta1/helmchart_types_test.go
- pkg/base/replicated.go
Merge base values with overlay values if the keys are unique. if the keys conflict, overlay takes precendence.
if nothing is specified in base and overlay, values.yaml takes effect
> Merge base values with overlay values  

- web/src/components/snapshots/AppSnapshots.jsx
- web/src/components/snapshots/SnapshotInstallationBox.jsx
- web/src/components/snapshots/Snapshots.jsx
> Check for restic version before listing snapshots

- pkg/handlers/registry.go
- web/src/components/shared/AirgapRegistrySettings.jsx
> Required registry namespace

- pkg/handlers/troubleshoot.go
- pkg/store/kotsstore/kots_store.go
- pkg/store/kotsstore/supportbundle_store.go
- pkg/store/ocistore/oci_store.go
- web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
> Uploaded airgap bundles don't have redactor info

- pkg/docker/registry/auth.go
- pkg/handlers/registry.go
> Honor read-only flag when validating registry credentials

- pkg/handlers/config.go
app config was not rendered before validation, so the `when` keys had templates in them instead of values.
> render config before validation for setting config from cli

- web/src/components/apps/AppLicense.jsx
- web/src/scss/components/apps/AppLicense.scss
> Fixed large license fields

- pkg/api/handlers/types/types.go
- pkg/gitops/gitops.go
- pkg/handlers/app.go
- pkg/handlers/gitops.go
- web/src/components/apps/AppGitops.jsx
- web/src/components/gitops/GitOpsDeploymentManager.jsx
- web/src/components/gitops/GitOpsRepoDetails.jsx
- web/src/utilities/utilities.js
> gitops - add support for bitbucket server

- web/src/components/apps/AppConfig.jsx
- web/src/components/shared/SubNavBar/SubNavBar.jsx
- web/src/config-ui/subNavConfig.js
This change is updating config tab to go to the deployed config instead of latest.
> Navigating to latest deployed config from subnav

- web/src/components/troubleshoot/SupportBundleCollectProgress.jsx
> Fixing typo

- .github/workflows/kotsadm.yaml
All other images are scanned on all branches
> Scan postgres images on all branches

- migrations/tables/app_downstream_version.yaml
- pkg/preflight/types/types.go
- pkg/store/kotsstore/migrations.go
- pkg/store/kotsstore/preflight_store.go
- pkg/store/kotsstore/version_store.go
- web/src/components/PreflightRenderer.jsx
- web/src/components/PreflightResultPage.jsx
- web/src/components/snapshots/SnapshotStorageDestination.jsx
> UI handles preflights skipped with unattended installs

- pkg/handlers/registry.go
CLI already allows pushing to anonymous registries.  This makes UI uploads behave the same.
> Don't require registry password

- cmd/kots/cli/install.go
> Restore terminal cursor when install exits

- pkg/logger/logger.go
> fix: human-readable timestamps

- .github/workflows/kotsadm.yaml
- Makefile
- hack/deploy-kgrid.sh
Push the KOTS version CRD to gitops repo for kgrid tests on staging and prod
> Trigger kgrid tests on release

- cmd/kots/cli/pull.go
- kotskinds/apis/kots/v1beta1/helmchart_types.go
- kotskinds/client/kotsclientset/fake/register.go
- kotskinds/config/crds/kots.io_airgaps.yaml
- kotskinds/config/crds/kots.io_applications.yaml
- kotskinds/config/crds/kots.io_configs.yaml
- kotskinds/config/crds/kots.io_configvalues.yaml
- kotskinds/config/crds/kots.io_helmcharts.yaml
- kotskinds/config/crds/kots.io_identities.yaml
- kotskinds/config/crds/kots.io_identityconfigs.yaml
- kotskinds/config/crds/kots.io_ingressconfigs.yaml
- kotskinds/config/crds/kots.io_installations.yaml
- kotskinds/config/crds/kots.io_licenses.yaml
- pkg/airgap/airgap.go
- pkg/airgap/update.go
- pkg/base/base.go
- pkg/base/render.go
- pkg/base/replicated.go
- pkg/base/replicated_test.go
- pkg/downstream/write.go
- pkg/kotsadmupstream/upstream.go
- pkg/midstream/write.go
- pkg/online/online.go
- pkg/pull/pull.go
- pkg/registry/registry.go
- pkg/render/render.go
- pkg/rewrite/rewrite.go
> No more common base

- pkg/supportbundle/spec.go
- support-bundle.yaml
This endpoint of goldpinger produces json like:
```
{"hosts":[{"hostIP":"10.138.0.127","podIP":"10.32.0.7","podName":"goldpinger-qbpdg"},{"hostIP":"10.138.15.194","podIP":"10.32.12.11","podName":"goldpinger-zsg6q"}],"responses":{"goldpinger-qbpdg":{"HostIP":"10.138.0.127","OK":true,"PodIP":"10.32.0.7","response":{"podResults":{"goldpinger-qbpdg":{"HostIP":"10.138.0.127","OK":true,"PingTime":"2021-06-23T23:46:09.709Z","PodIP":"10.32.0.7","response":{"boot_time":"2021-06-23T19:43:58.525Z"},"status-code":200},"goldpinger-zsg6q":{"HostIP":"10.138.15.194","OK":true,"PingTime":"2021-06-23T23:45:58.463Z","PodIP":"10.32.12.11","response":{"boot_time":"2021-06-23T23:10:18.578Z"},"response-time-ms":1,"status-code":200}}}},"goldpinger-zsg6q":{"HostIP":"10.138.15.194","OK":true,"PodIP":"10.32.12.11"," …
```
> collect and analyze data from goldpinger

- migrations/tables/app_downstream_output.yaml
- pkg/api/downstream/types/types.go
- pkg/handlers/deploy.go
- pkg/handlers/downstream.go
- pkg/store/kotsstore/downstream_store.go
> Show helm output in UI

- cmd/kots/cli/get.go
- pkg/print/app.go
> Implement cli method to get deployed version

- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/scss/components/apps/AppVersionHistory.scss
> better handling of status' when preflight checks were skipped

- .github/workflows/build-test.yaml
- cmd/kots/cli/pull.go
- pkg/pull/pull.go
- Fixes pull command to not look for Helm charts
- Makes test build components in parallel
- Adds a test for kots pull command
> Fix kots pull command

- kotsadm/operator/pkg/client/client.go
- kotsadm/operator/pkg/client/deploy.go
Errors weren't being returned from `ensureResourcesPresent`. Tried to simplify this to remove the send in multiple places. Could be simplified further if we always send back the result w/ stdout,stderr, but I kept the existing functionality where those are only returned on error.
> fix(operator): surface deployment errors

- .github/workflows/kotsadm.yaml
On merge to master this will rebuild the kURL kotsadm addon alpha package.
> Build kURL kotsadm alpha addon package

- .github/workflows/deploy.yaml
- Makefile.build
- cmd/kots/cli/experimental-off.go
- cmd/kots/cli/experimental-on.go
- cmd/kots/cli/root.go
- cmd/kots/cli/run.go
- deploy/.goreleaser.yaml
binary sizes with goreleaser:
```
$ ls -lh dist/kots_*
dist/kots_darwin_amd64:
total 75M
-rwxrwxr-x 1 divolgin divolgin 75M Aug  3 20:02 kots
dist/kots_experimental_linux_amd64:
total 296M
-rwxrwxr-x 1 divolgin divolgin 296M Aug  3 20:02 kots
dist/kots_linux_amd64:
total 68M
-rwxrwxr-x 1 divolgin divolgin 68M Aug  3 20:02 kots
```
> Build experimental binary

- pkg/api/handlers/types/types.go
- pkg/handlers/app.go
- web/src/components/SecureAdminConsole.jsx
[CH36190](https://app.clubhouse.io/replicated/story/36190/existing-cluster-airgap-bundle-upload-page-sometimes-shows-up-for-embedded-cluster-installs)
> fix: always show embedded workflow when kurl registry is detected

- cmd/kots/cli/download.go
- cmd/kots/cli/upload.go
- integration/upload/upload_test.go
- pkg/upload/upload.go
[CH33701](https://app.clubhouse.io/replicated/story/33701/kots-cli-add-output-formatting-option-for-json-and-status-field-if-possible)
> feat: add json output to upload and download cli cmds

- hack/dev/Dockerfile.skaffold
Was causing an error with a non-existent user.
> Remove check scripts from Skaffold container

- cmd/kots/cli/backup.go
- cmd/kots/cli/restore.go
- pkg/snapshot/backup.go
- pkg/snapshot/restore.go
[CH33701](https://app.clubhouse.io/replicated/story/33701/kots-cli-add-output-formatting-option-for-json-and-status-field-if-possible)
> feat: add json output for backup and restore cmds

- cmd/kots/cli/upstream-upgrade.go
- pkg/upstream/upgrade.go
[CH33701](https://app.clubhouse.io/replicated/story/33701/kots-cli-add-output-formatting-option-for-json-and-status-field-if-possible)
> feat: add json output to upstream upgrade cmd

- pkg/midstream/write.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
[CH #](https://app.clubhouse.io/replicated/story/37042/charts-with-private-images-that-use-the-usehelminstall-flag-fail-to-deploy)
> Create separate image pull secret for individual charts

- web/src/components/apps/Dashboard.jsx
- web/src/components/apps/DashboardCard.jsx
- web/src/scss/components/watches/Dashboard.scss
- web/src/scss/utilities/colors.scss
> UI: application status informers modal

- go.mod
- go.sum
- pkg/supportbundle/analyze.go
- pkg/supportbundle/spec.go
- support-bundle.yaml
Include weave report analyzer in default bundle spec
> Troubleshoot 0.13.9

- .github/workflows/build-test.yaml
- .github/workflows/kotsadm.yaml
https://app.shortcut.com/replicated/story/37175/ci-should-fail-on-image-cves-that-do-not-meet-our-policy
> add medium severity to tests

- .github/workflows/build-test.yaml
Reverts replicatedhq/kots#2148
> Revert "chore: enable slack notifications for nightly builds"

- .github/workflows/build-test.yaml
kind/chore
Rather than adding branch rules to require each validate-* job to succeed I'm adding one additional job that needs all others. This way I dont have to list all jobs in the branch protection rules for master. 
Fixes #
NONE
```release-note
NONE
```
NONE
> Add job to validate that all validate-* jobs succeed

- .github/workflows/release.yaml
> action build-release no more container

- .github/workflows/alpha.yaml
> CI alpha workflow unused job

- .github/workflows/release.yaml
> Don't use actions/containers

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
kind/documentation
Provide guidelines on how to submit a pull request and the kinds of things we look for prior to approving the request.
Fixes #37099
Yes, contributors now have guidelines about the kinds of things required in order to get a pull request merged. 
```release-note
Added pull request guidelines to CONTRIBUTING.md doc.
```
The PR _is_ documentation :+1:
> Pull Request Guidelines

- .github/workflows/release.yaml
Removing these since they're still not working.
> chore: remove job and took from slack notifications

- kustomize/overlays/dev/deployment.yaml
- pkg/apiserver/server.go
- pkg/handlers/handlers.go
- pkg/handlers/middleware.go
- pkg/logger/clilogger.go
- pkg/operator/client/hooks.go
Cleaning up some noisy logging, terminal logging, and adding logger to mux router.
kind/chore
The goal is to improve information contained in support bundles.
Fixes #
See comments
```release-note
NONE
```
NONE
> Clean up logging and log failed API requests

- go.mod
- go.sum
- pkg/supportbundle/spec.go
- pkg/supportbundle/spec_test.go
fixes collecting cluster resources in minimal rbac installations
```release-note
* fixed a bug that caused collecting cluster resources for the support bundle to fail in installations that require minimal RBAC priviliges.
```
NONE
> fix collecting cluster resources in minimal rbac installations

- actions/copy-assets/Dockerfile
Updating local GA to use alpine:latest because we are seeing image pull errors with GCR.
kind/chore
More stable CI
Fixes #
```release-note
NONE
```
NONE
> Switching to alpine due to image pull errors from gcr

- .github/workflows/codespaces.yaml
kind/chore
Fixes the codespace prebuild action
NONE
NONE
> chore(ci): fix codespace action env

- .github/workflows/codespaces.yaml
- kurl_proxy/kustomize/base/service.yaml
- skaffold.yaml
Fixes codeserver dev env with broken kurl-proxy
kind/chore
Kurl-proxy is broken on local dev environments.
NONE
NONE
> chore: fix skaffold proxy and ports

- .github/workflows/nightly.yaml
kind/chore
Explain usage of personal access token in comment
Fixes #NONE
```release-note
NONE
```
NONE
> Explain usage of github pat in action

- Makefile
- deploy/Dockerfile.dex
kind/chore
Just some cleanup
Fixes #NONE
```release-note
NONE
```
NONE
> Build Dex image from dockerfile

- go.mod
- go.sum
Update to latest Troubleshoot release, v0.13.16
Fixes #
```release-note
Fixed a bug that caused Admin Console memory usage increase significantly while collecting support bundle.
```
NONE
> Troubleshoot v0.13.16

- pkg/preflight/execute.go
This makes preflight checks logging more visible, logging start, end, and error messages.
Fixes #
```release-note
Changed preflight check logs to `info` level for progress messages and to `error` level for error messages.
```
NONE
> Preflight checks logging more visible

- .devcontainer/Dockerfile
- .devcontainer/config/k3d-cluster.yaml
- .devcontainer/first-run-notice.txt
- .devcontainer/library-scripts/meta.env
- .devcontainer/library-scripts/replicated-debian.sh
- .devcontainer/library-scripts/replicated-userspace.sh
- .devcontainer/lifecycle-scripts/onCreate.sh
- skaffold.yaml
kind/chore
Some optimizations to codespaces that will skaffold deploy faster.
NONE
NONE
> optimize build

- .github/workflows/release.yaml
kind/chore
Trigger kgrid tests on nightly releases.
Fixes #
```release-note
NONE
```
NONE
> Trigger kgrid on tag

- pkg/supportbundle/defaultspec/spec.yaml
kind/bug
A passing outcome added to node check, which is shown when all nodes are "Ready".
Fixes #
```release-note
NONE
```
NONE
> Add a passing outcome to node check

- .vscode/launch.json
- Makefile
- Makefile.build
- hack/dev/Dockerfile.skaffold
- kustomize/overlays/dev/deployment.yaml
- kustomize/overlays/dev/dlv-service.yaml
- kustomize/overlays/dev/kustomization.yaml
- skaffold.yaml
kind/chore
This PR add the go debugger, `dlv` to the `kotsadm`  container when run through the skaffold deployment.
NONE
NONE
> chore(dev): add dlv to kotsadm skaffold

- Makefile
- pkg/api/downstream/types/types.go
- pkg/handlers/app.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/downstream_store.go
- pkg/store/store_interface.go
> Sort releases by semver if available

- hack/dev/Dockerfile.skaffold
- pkg/template/depgraph.go
- pkg/template/depgraph_test.go
kind/bug
Fixes #
```release-note
Fixes a bug associated with Config Item dependencies not being discovered when combining Replicated and Non-Replicated template functions.
```
NONE
> fix: dependency graph for non-repl template functions

- pkg/api/downstream/types/types.go
> Disambiguate sorting for versions with the same semver

- web/src/components/modals/UpdateCheckerModal.jsx
> add note to dropdown regarding automatic install only happening for valid semver versions

- pkg/supportbundle/defaultspec/spec.yaml
kind/chore
Include Weave Net logs in the support bundle which can be helpful in debugging issues
Fixes NONE
```release-note
Weave net container logs are now included in the default KOTS support bundle
```
NONE
> Include weave logs in support bundle

- hack/dev/Dockerfile.skaffold
- hack/dev/Dockerfile.skaffoldcache
- pkg/airgap/update.go
- pkg/api/downstream/types/types.go
- pkg/api/downstream/types/types_test.go
- pkg/api/handlers/types/types.go
- pkg/handlers/app.go
- pkg/handlers/gitops.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/downstream_store.go
- pkg/store/store_interface.go
- web/src/components/apps/DashboardVersionCard.jsx
> Sort versions on semver and sequence

- pkg/kotsadm/objects/kotsadm_objects.go
kind/bug
Makes it so that ALL the containers in kotsadm have a security context
Fixes #
```release-note
Include a previously-missing security context for the restore-db container within the kotsadm pod
```
NONE
> include a security context for the restore-db container in kotsadm

- pkg/api/downstream/types/types.go
- pkg/api/downstream/types/types_test.go
> Fix bubble sort

- pkg/kotsadmlicense/license.go
- pkg/store/kotsstore/license_store.go
- pkg/store/kotsstore/version_store.go
- pkg/store/store_interface.go
> Base license change on latest version

- pkg/handlers/config.go
- web/src/components/apps/AppConfig.jsx
> Save use correct versions when viewing and saving settings

- pkg/handlers/registry.go
> Updating registry should use the correct base version

- pkg/airgap/update.go
- pkg/kotsadmupstream/upstream.go
- pkg/store/kotsstore/sql.go
- pkg/store/kotsstore/version_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/version_store.go
- pkg/store/store_interface.go
- pkg/version/version.go
> Remove duplicate function

- web/src/components/shared/SubNavBar/SubNavBar.jsx
> View files takes user to top release as sorted by semver

- .github/workflows/release.yaml
> Ignore errors when cleaning up TestIM instances

- pkg/handlers/app.go
- pkg/handlers/registry.go
- pkg/kotsadmlicense/license.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/downstream_store.go
- pkg/store/store_interface.go
> UI features are based on semver sorting order

- pkg/handlers/config.go
- web/src/components/apps/AppConfig.jsx
- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/AppVersionHistoryRowClassic.jsx
> Allow editing pending semver versions

- pkg/api/downstream/types/types.go
- pkg/version/version.go
> mocked version should be at the top of the list not the bottom

- pkg/handlers/garbage_collect_images.go
- pkg/registry/images.go
See :https://github.com/goharbor/harbor/issues/11929#issuecomment-828892005
> Upload empty file to work around rook issue

- pkg/operator/client/deploy.go
kind/bug
Fixes #
```release-note
```
> use the RestoreLabelSelector to delete PVCs instead of generating a new one

- pkg/operator/client/deploy.go
- pkg/operator/client/deploy_test.go
> properly build label selectors

- pkg/operator/client/deploy.go
Fixes random test error that expects label string to be in a certain order.
kind/chore
Fixes random test error
Fixes #
```release-note
NONE
```
NONE
> Stabilize label order so tests don't fail randomly

- pkg/operator/client/deploy.go
kind/chore
Fix tests better
Fixes #
```release-note
```
> Actually use sorted keys

- .github/workflows/regression.yaml
kind/bug
Fix a pipeline error
```release-note
NONE
```
NONE
> Checkout step was defaulting to master instead of main

- kotskinds/apis/kots/v1beta1/license_types.go
- pkg/api/handlers/types/types.go
- pkg/handlers/app.go
- pkg/pull/signature.go
- web/src/components/apps/AppDetailPage.jsx
uses a license field as a feature flag for enabling the new admin console ui
```release-note
NONE
```
NONE
> new KOTS UI feature flag using the license

- kotskinds/apis/kots/v1beta1/license_types.go
- pkg/api/downstream/types/types.go
- pkg/api/downstream/types/types_test.go
- pkg/pull/signature.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/kotsstore/version_store.go
- pkg/template/license_context.go
kind/chore
Semver ordering of releases will be done only if it's enabled on the channel.
Fixes #
```release-note
NONE
```
https://github.com/replicatedhq/kots.io/pull/611 (needs minor updates)
> Use semver flag from license

- pkg/base/replicated.go
copy of https://github.com/replicatedhq/kots/pull/2373, but internal branch
> Fixing recursive merge

- .github/workflows/build-test.yaml
kind/chore
Tests are broken. This PR attempts to work around the issue and fix the tests.
Fixes NONE
```release-note
NONE
```
NONE
> Add multi-namespace-yeti-redis-registry secret to redis-test namespace

- .github/workflows/alpha.yaml
- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
- pkg/image/builder.go
- pkg/pull/pull.go
kind/bug
This fixes kots pull cli to properly inject image pull secrets when using useHelmInstall true.
Fixes NONE
```release-note
Fixed the `kots pull` cli command to properly inject imagePullSecrets when using Helm Charts with useHelmInstall set to true.
```
NONE
> Validate kots pull fix

- .github/workflows/build-test.yaml
kind/chore
As the title says
Fixes NONE
```release-note
NONE
```
NONE
> More fixes for master branch renaming to main

- .github/workflows/build-test.yaml
kind/chore
Pin testim cli to 3.206.0 to fix flakey tests
Fixes NONE
```release-note
NONE
```
NONE
> Pin testim cli to 3.206.0 to fix flakey tests

- cmd/kots/cli/get-config.go
This PR adds a flag to `kubectl kots get config` that decrypts passwords.
Fixes #
```release-note
Add a `--decrypt` flag to `kubectl kots get config`
```
https://github.com/replicatedhq/kots.io/pull/633
> add a '--decrypt' flag to 'kubectl kots get config'

- .github/workflows/codespaces.yaml
kind/chore
Fix failing Github Action
None
None
None
> chore: remove WestEurope to fix failing action

- pkg/base/write_images.go
kind/bug
When rewriting images on config and registry updates, we need to ignore images that use templates because all templated images should be included in `additionalImages` list in the application manifest.
Fixes #
```release-note
NONE
```
NONE
> Don't fail on templated images in SupportBundle spec when saving config

- pkg/store/kotsstore/license_store.go
- web/src/components/apps/DashboardLicenseCard.jsx
type::chore
Cleaning up style bugs
Upload license ability from dashboard
Yes, cleaning up CSS styles 
```release-note
Cleanup to CSS and resolving style issues
```
NONE
> version history dashboard css cleanup

- web/src/components/apps/DashboardVersionCard.jsx
type::chore
Cleaning up style bugs
Redeploy button on dashboard version card
Yes, cleaning up CSS styles 
```release-note
Cleanup to CSS and resolving style issues
```
NONE
> redeploy button on dashboard current version

- pkg/operator/applier/kubectl.go
type::chore
Fixes [SC-40225](https://app.shortcut.com/replicated/story/40225/kubernetes-1-23)
NONE
NONE
> chore: update dry-run commands for k8s 1.23

- web/src/components/apps/AppVersionHistory.jsx
type::chore
Showing 
Yes, fixing a bug that was introduced in the new UI where progress of airgap bundle uploads was not shown
```release-note
Show airgap bundle upload status on version history page
```
NONE
> show airgap upload progress on version history page

- web/src/components/apps/DashboardSnapshotsCard.jsx
type::bug
Fixes an issue where the dashboard snapshot card would not show the correct configured storage destination
Yes
```release-note
Fixes an issue where the dashboard snapshot card would not show the correct configured storage destination
```
NONE
> snapshot card on dashboard shows correct snapshot destination

- hack/dev/Dockerfile.skaffold
- hack/dev/Dockerfile.skaffoldcache
- pkg/apiserver/server.go
- web/Dockerfile.skaffold
Fixes a skaffold deployment issue
NONE
NONE
> Fix skaffold deployment issue

- hack/dev/Dockerfile.okteto
Fix Okteto deployment issue
NONE
NONE
> Okteto fix

- .github/workflows/build-test.yaml
This reverts commit 862cb29cdb3a7354b41b2320db33ff1ccf6d6ef8.
Fixes #
```release-note
```
> Revert "test sbom"

- .github/workflows/release.yaml
> Run raw commands that sbom generator uses for debugging

- .github/workflows/release.yaml
> Download artifact needed to build sbom

- .github/workflows/release.yaml
> Fix dependencies for tagged build

- .github/workflows/build-test.yaml
- deploy/Dockerfile
- hack/dev/Dockerfile.okteto
- hack/dev/Dockerfile.skaffold
type::feature
Adds support for kubernetes 1.22 in KOTS.
Fixes [SC-36576](https://app.shortcut.com/replicated/story/36576/kubernetes-1-22)
```release-note
Adds official Kubernetes 1.22 support.
```
Yes, link TBD
> feat: add k8s 1.22 support

- .github/workflows/build-test.yaml
> fix k8s versions

- .github/workflows/build-test.yaml
> chore(ci): fix velero for legacy tests on 1.22

- pkg/handlers/deploy.go
type::feature
Adds the ability to block deploying a certain release if the current KOTS version is incompatible with the KOTS version required by the release.
```release-note
Adds the ability to block deploying a certain release if the current KOTS version is incompatible with the KOTS version required by the release.
```
NONE
> Check KOTS version compatibility with the version specified in the application spec

- cmd/kots/cli/install.go
- pkg/buildversion/buildversion.go
- pkg/handlers/deploy.go
- pkg/kotsutil/kots.go
type::feature
Adds the ability to block installing a certain application if the current KOTS version is incompatible with the KOTS version required by the app.
```release-note
Adds the ability to block installing a certain application if the current KOTS version is incompatible with the KOTS version required by the app.
```
TBD
> Check KOTS version compatibility with the app during the installation

- pkg/handlers/deploy.go
type::chore
```release-note
NONE
```
NONE
> Remove unused 'IncompatibleKotsVersion' field from the response

- cmd/kots/cli/install.go
- cmd/kots/cli/pull.go
- pkg/airgap/airgap.go
- pkg/airgap/update.go
- pkg/automation/automation.go
- pkg/handlers/airgap.go
- pkg/handlers/license.go
- pkg/kotsadm/objects/configmaps_objects.go
- pkg/kotsadm/types/deployoptions.go
- pkg/kotsadmupstream/upstream.go
- pkg/kotsutil/kots.go
- pkg/online/online.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
- pkg/upstream/fetch.go
- pkg/upstream/replicated.go
- pkg/upstream/types/types.go
type::chore
This change will check for the KOTS version compatibility with the application release at an earlier stage (e.g. before processing and pushing the images, etc..)
```release-note
NONE
```
NONE
> Check KOTS version compatibility on pull

- README.md
- web/package.json
- web/src/components/apps/AppConfig.jsx
- web/webpack.config.dist.js
- web/webpack.config.js
- web/yarn.lock
> Fixing some problems

- web/src/components/apps/Dashboard.jsx
Fix issue caused by a regression of the build changes
NONE
NONE
> Replace window.env with process.env

- kotskinds/apis/kots/v1beta1/application_types.go
- kotskinds/config/crds/kots.io_applications.yaml
- kotskinds/schemas/application-kots-v1beta1.json
- pkg/kotsutil/kots.go
type::feature
Use target/minimum kots versions instead of a specific kots version
```release-note
NONE
```
NONE
> Use target/minimum kots versions instead of a specific kots version

- pkg/supportbundle/spec.go
type::bug
license.yaml file included in support bundles was serialized using the standard yaml package, which resulted in signature to be output as a byte array instead of a base64 string.
Fixes #
```release-note
* Fixes an issue that caused license file included in support bundle to contain a long array of integers instead of string int he signature field.
```
NONE
> Use proper serializer for license file in support bundle

- web/src/utilities/utilities.js
type::bug
Handles multi yaml docs when looking for app spec in airgap bundle
```release-note
NONE
```
NONE
> Handle multi yaml docs when looking for app spec in airgap bundle

- .github/workflows/build-test.yaml
type::tests
Add min/target kots version testim tests
```release-note
NONE
```
NONE
> Add min/target kots version testim tests

- cmd/kots/cli/get-config.go
type::feature
kubectl kots get config should use sane defaults
```release-note
* Defaults `kubectl kots get config --appslug` to the deployed application if there is only one in the namespace.
* Defaults `kubectl kots get config --sequence` to the sequence of the latest available version.
```
[Docs PR](https://github.com/replicatedhq/kots.io/pull/663)
> Kiraboyle/sc 40359/kubectl kots get config should use sane defaults

- cmd/kots/cli/install.go
- pkg/handlers/app.go
- pkg/kotsutil/kots.go
- pkg/upstream/replicated.go
type::chore
Improves incompatibility error message for new installs
```release-note
NONE
```
NONE
> Improve incompatibility error message for installs

- .dockerignore
- .stignore
- Makefile
- hack/dev/Dockerfile.okteto
- okteto.yml
Added dev mode to kotsadm Okteto
NONE
```release-note
NONE
```
NONE
> Add dev mode kotsadm

- .github/workflows/build-test.yaml
- .gitignore
Tests that the Okteto dev environment wasn't broke in a feature branch
Fixes #40894
NONE
```release-note
NONE
```
NONE
> Add testing for Okteto

- go.mod
- go.sum
type::chore
Updates troubleshoot dependency to latest
Fixes #
```release-note
NONE
```
NONE
> Update troubleshoot to v0.28.1

- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
type::chore
Attempt to resolve flakiness with new Testim version.
NONE
NONE
> chore(ci): update testim version to latest

- .github/workflows/regression.yaml
type::tests
Adds tests for k3s and rke2 based clusters
Fixes #
```release-note
NONE
```
NONE
> Add k3s and rke tests

- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
type::tests
user master branch instead of main for testim since testim's default and main branch is called master and that can't be changed yet.
```release-note
NONE
```
NONE
> use master branch instead of main for testim

- pkg/apiserver/server.go
Fixes #
```release-note
Fix uploading preflight results from the CLI
```
> reinclude the preflight status endpoint used by cli preflights

- pkg/apiserver/server.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
This PR adds a unit test to prevent a route from being inadvertently removed in the future.
Fixes #
```release-note
NONE
```
> add a test to ensure the preflight status endpoint is not removed

- hack/dev/skaffoldcache.Dockerfile
type::chore
```release-note
NONE
```
NONE
> fix skaffold make cache

- pkg/upstream/upgrade.go
type::chore
Improves the deployment message displayed by the CLI for the `kots upstream upgrade` command.
```release-note
NONE
```
NONE
> Improve upstream upgrade command deploy message

- .github/workflows/release.yaml
type::tests
improve kots-range-version test
```release-note
NONE
```
NONE
> update range-kots-version test

- pkg/handlers/download.go
type::improvement
checks if the version exists before trying to re-download.
```release-note
NONE
```
NONE
> check if version exists before downloading

- hack/CONTRIBUTING.md
- hack/build-ttl.sh
- hack/dev/okteto.Dockerfile
- hack/dev/skaffold.Dockerfile
type::chore
Fix make commands
Fixes #
```release-note
NONE
```
NONE
> Fix make commands

- web/src/components/shared/ConfigureGraphs.jsx
- web/src/components/shared/modals/ConfigureGraphsModal.jsx
> fix the incorrect svc endpoint in the modal

- cmd/kotsadm/cli/api.go
- go.mod
- go.sum
- pkg/handlers/deploy.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/handlers/update.go
- pkg/kotsadmupstream/upstream.go
- pkg/kotsutil/kots.go
- pkg/pull/pull.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/kotsstore/version_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/version_store.go
- pkg/store/store_interface.go
- pkg/upstream/replicated.go
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/AppVersionHistoryRow.jsx
> updated to account for new minKotsVersion logic

- pkg/handlers/handlers.go
- pkg/handlers/update.go
- pkg/kotsadm/updates.go
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/DashboardVersionCard.jsx
> modal with upgrade progress

- pkg/logger/clilogger.go
- web/src/components/apps/DashboardVersionCard.jsx
> same UI for dashboard page

- pkg/handlers/update.go
- pkg/kotsadm/updates.go
- pkg/kotsutil/kots.go
- pkg/pull/pull.go
- pkg/store/kotsstore/downstream_store.go
- pkg/upstream/replicated.go
> Remove debugging stuff

- cmd/kotsadm/cli/api.go
- go.mod
- go.sum
- pkg/api/downstream/types/types.go
- pkg/handlers/deploy.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/handlers/update.go
- pkg/handlers/update_test.go
- pkg/kotsadm/updates.go
- pkg/kotsadmupstream/upstream.go
- pkg/kotsutil/kots.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/kotsstore/version_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/version_store.go
- pkg/store/store_interface.go
- pkg/upstream/replicated.go
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/DashboardVersionCard.jsx
type::feature
Support for Admin Console upgrades using web UI.
Fixes #
This is a hidden feature for now and has to be enabled using an undocumented feature flag.
```release-note
* Adds experimental support for Admin Console upgrades using web UI
```
NONE
> Automatic admin console updates

- .github/workflows/build-test.yaml
type::tests
Adds a test for testing backups and restores
```release-note
NONE
```
NONE
> Backup and restore test

- .github/workflows/regression.yaml
type::tests
Fixes state lock issue with k3s regression test
Fixes #
```release-note
NONE
```
NONE
> New state file for k3s test

- okteto.yml
Improve developer environment
NONE
NONE
```release-note
NONE
```
NONE
> Add resource limits for kotsadm

- pkg/license/license.go
type::bug
Fixes an issue where the same license can be installed more than once in some cases.
```release-note
Fixes an issue where the same license can be installed more than once in some cases.
```
NONE
> Prevent installing the same license twice

- cmd/kots/cli/install.go
- pkg/airgap/airgap.go
- pkg/automation/automation.go
- pkg/handlers/license.go
- pkg/kotsadm/objects/configmaps_objects.go
- pkg/kotsadm/types/deployoptions.go
- pkg/kotsutil/kots.go
- pkg/online/online.go
- pkg/online/types/types.go
- pkg/pull/pull.go
- pkg/upstream/fetch.go
- pkg/upstream/replicated.go
- pkg/upstream/replicated_test.go
- pkg/upstream/types/types.go
type::feature
This allows specifying an app version label during the initial license install.
Fixes #
```release-note
* Added support for installing a specific application release.
```
https://github.com/replicatedhq/replicated-docs/pull/232
> Allow specifying version label at initial install

- .github/workflows/build-test.yaml
type::tests
Adds a test for the app-version-label cli flag for the kots install command
```release-note
NONE
```
NONE
> Test for app-version-label cli flag

- pkg/appstate/deployments.go
- pkg/appstate/statefulsets.go
- pkg/appstate/types/types.go
- pkg/appstate/types/types_test.go
- web/src/components/apps/AppStatus.jsx
- web/src/components/apps/Dashboard.jsx
- web/src/scss/components/watches/Dashboard.scss
type::feature
Extends the ability of status informers to detect if the application is being updated.
```release-note
Extends the ability of status informers to detect if the application is being updated.
```
NONE
https://www.loom.com/share/c4d77fc56f0f4815862a34ce9bbc0b7f
> Improve status informers to detect updates

- .github/workflows/regression.yaml
Fix a test
NONE
Fixes #
NONE
```release-note
NONE
```
NONE
> Fix k3s regession test

- pkg/version/version.go
Sometimes, app version deploys hang or otherwise fail. Having a log line saying that they are being deployed would help identify these errors.
Fixes #
```release-note
```
> log every time that an app version is deployed

- kotskinds/apis/kots/v1beta1/airgap_types.go
- pkg/airgap/update.go
- pkg/airgap/update_test.go
- pkg/api/version/types/types.go
- pkg/cursor/cursor.go
- pkg/handlers/app.go
- pkg/handlers/config.go
- pkg/handlers/deploy.go
- pkg/handlers/gitops.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/kotsstore/version_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/downstream_store.go
- pkg/store/ocistore/version_store.go
- pkg/store/store_interface.go
- pkg/updatechecker/updatechecker.go
- pkg/upstream/fetch.go
- pkg/upstream/fetch_test.go
- web/src/utilities/airgapUploader.js
- web/src/utilities/utilities.js
Block airgap bundle upload if prerequisite versions are not installed
type::feature
Fixes #
```release-note
* Adds support for required versions in airgap installs.
```
NONE
> Check all prerequisites exist before installing airgap bundle

- pkg/operator/operator.go
type::chore
Adds restore name to error messages for easier troubleshooting.
Fixes #
```release-note
NONE
```
NONE
> Better error messages for restores

- .github/workflows/build-test.yaml
type::chore
This will upload a support bundle to s3 when testim tests fail to aid in debugging.
Fixes NONE
```release-note
NONE
```
NONE
> Upload support bundle to s3 when testim tests fail

- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/DashboardVersionCard.jsx
> show earliest required version as latest available on dashboard

- cmd/kots/cli/install.go
- pkg/pull/pull.go
- pkg/upstream/replicated.go
type::bug
When installing a previous app release, kots should pull metadata for that release.
Fixes #
```release-note
* Fixes an issue that could cause wrong metadata to be used at application install time when `--app-version-label` flag is used.
```
NONE
> Pull version specific metadata if specified  when installing app

- .github/workflows/build-test.yaml
type::tests
test with 2 k3s versions intsead of 1
```release-note
NONE
```
NONE
> test with 2 k3s versions

- .github/workflows/build-test.yaml
type::tests
This is a test for the new `--use-minimal-rbac` command line flag
Fixes #
This is not a testim test.
```release-note
NONE
```
NONE
> Test for minimal RBAC command line override

- .github/workflows/build-test.yaml
type::tests
adds validate-minimal-rbac-override to validate-success step
```release-note
NONE
```
NONE
> add validate-minimal-rbac-override to validate-success step

- pkg/store/kotsstore/supportbundle_store.go
type::bug
Fixes an issue which causes the support bundle analysis and/or redactions to not show up in the troubleshoot page in the admin console in some cases.
```release-note
Fixes an issue which causes the support bundle analysis and/or redactions to not show up in the troubleshoot page in the admin console in some cases.
```
NONE
> add a lock when updating the support bundle secret during generation

- web/src/scss/utilities/base.scss
type::chore
Better handling of scrolling to element when clicking on a config item from the sidebar so that the element is visible and not hidden under the nav bar
Fixes #
```release-note
Fixed an issue on the config editor page that caused an element to be hidden under the navbar when the corresponding config item was clicked on from the sidebar.
```
> better offset for clicking to config elements

- go.sum
- pkg/airgap/airgap.go
- pkg/handlers/config.go
- pkg/online/online.go
- pkg/operator/operator.go
- pkg/preflight/preflight.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/downstream_store.go
- pkg/store/store_interface.go
type::bug
Fixes automated deployments for initial versions that don't require configuration.
Fixes #
```release-note
NONE
```
NONE
> Make sure version status is "pending" before deploying

- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/DashboardVersionCard.jsx
type::tests
move version action button tooltip outside of the button to fix regression tests
```release-note
NONE
```
NONE
> move version action button tooltip outside of the button

- web/src/components/snapshots/SnapshotSchedule.jsx
type::tests
clears previous snapshot schedule confirm message timeout so that message stays on
```release-note
NONE
```
NONE
> clear previous snapshot schedule confirm message timeout

- pkg/snapshot/store.go
type::bug
This PR resolves two issues related to AWS instance role snapshots.  First, the AWS region was not properly being set.  Second, the instance role settings failed to update because the `cloud-credentials` secret was not present in the velero namespace.  This PR introduces changes to set the AWS region regardless of whether instance role is checked or not.  Additionally, it modifies the instance role settings to maintain the `cloud-credentials` secret rather than deleting it, but instead pass empty credentials.
Fixes [SC-34090](https://app.shortcut.com/replicated/story/34090/aws-instance-profiles-no-longer-work-with-snapshots-using-velero-1-6)
See comment [here](https://github.com/replicatedhq/kots/pull/2665/files#diff-5fd0feaeb57eeb6c8ee806d3890dc462f9fc48bde743d4ee3096524cceaa8f0 …
> aws instance role snapshot settings

- web/src/components/apps/AppDetailPage.jsx
type::bug
Fixes refreshing app data after certain actions like checking for updates, deploying a version, etc...
```release-note
NONE
```
NONE
> Fix refreshing app data after checking for updates or doing other actions in the version history page

- web/src/components/apps/AppVersionHistory.jsx
type::bug
Don't include the latest version in the total count of other available versions
```release-note
NONE
```
NONE
> Don't include the latest version in the total count of other available versions

- .github/workflows/build-test.yaml
- cmd/kots/cli/docker.go
- integration/replicated/tests/kitchen-sink/expected/overlays/midstream/pullsecrets.yaml
- integration/replicated/tests/kitchen-sink/expected/overlays/midstream/secret.yaml
- pkg/docker/registry/registry.go
- pkg/handlers/config.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/handlers/registry.go
- pkg/image/builder.go
- pkg/kotsadm/version/kotsadm_version.go
- pkg/logger/clilogger.go
- pkg/midstream/midstream.go
- pkg/midstream/write.go
- pkg/pull/pull.go
- pkg/rewrite/rewrite.go
type::bug
When DockerHub credentials are created/update, this will create a new app version with the new pull secret.
Fixes #
```release-note
* Fixes an issue that caused instances to run into DockerHub's rate limiting after running the [ensure-secret](/reference/kots-cli-docker-ensure-secret) command
```
NONE
> Update app when new docker hub credentials are create/updated

- .github/workflows/build-test.yaml
type::tests
Add test for validating the version history pagination
```release-note
NONE
```
NONE
> Add test for validating the version history pagination

- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/license.go
- pkg/handlers/mock/mock.go
- pkg/kotsadmlicense/license.go
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/apps/AppLicense.jsx
- web/src/components/apps/AppVersionHistory.jsx
- web/src/scss/components/apps/AppLicense.scss
type::feature
Adds the ability to switch from a community license to a different license from the same application.
```release-note
Adds the ability to switch from a community license to a different license from the same application.
```
Yes, TBD
> Adds the ability to switch from a community license to a different license from the same application

- .github/workflows/build-test.yaml
type::tests
Adds a test for changing a license
```release-note
NONE
```
NONE
> Add change license test

- web/src/components/snapshots/SnapshotSchedule.jsx
- web/src/components/snapshots/SnapshotSettings.jsx
type::tests
Increase snapshot settings success message timeout to fix race condition in regression tests
```release-note
NONE
```
NONE
> Increase snapshot settings success message timeout

- .github/workflows/release.yaml
type::feature
No
```release-note
Generate minio and no-minio kotsadm bundles for airgap/existing installs.
```
> Generate minio and nominio kotsadm bundles

- .github/workflows/build-test.yaml
- pkg/app/app.go
- pkg/updatechecker/updatechecker.go
type::bug
Releases promoted while updates are being processed will be missed if semantic versioning is enabled
```release-note
Fixes an issue where some releases could be missed if they were promoted while other releases are being downloaded and semantic versioning is enabled
```
NONE
> Releases promoted while updates are being processed will be missed if semantic versioning is enabled

- okteto.Dockerfile
Reduce build size for docker image in Okteto
Fixes #NONE
```release-note
NONE
```
NONE
> Improve Okteto build size/time

- pkg/apiserver/server.go
- pkg/handlers/session.go
- pkg/session/expired_session.go
- pkg/store/kotsstore/session_store.go
- pkg/store/mock/mock.go
- pkg/store/ocistore/session_store.go
- pkg/store/store_interface.go
type::feature
feature: add a cron job to purge expired sessions
Fixes # [SC-34580](https://app.shortcut.com/replicated/story/34580/kots-jwt-timeouts-are-too-long-non-oidc-login)
```release-note
Adds a cron job to purge expired sessions which runs daily.
```
NONE
> feature: add a cron job to purge expired sessions

- pkg/kotsutil/kots.go
- pkg/store/kotsstore/version_store.go
This PR templates the `app.k8s.io/v1beta1 Application` type, allowing URLs to change based on config options or license fields.
Fixes #
```release-note
Allow templating within the app.k8s.io/v1beta1 Application type.
```
> template sig-apps application object

- go.mod
- pkg/persistence/persistence.go
- pkg/store/kotsstore/registry_store_test.go
This PR provides a framework for other tests that hit code that requires access to a SQL backend.
Fixes #
```release-note
```
> add a unit test that relies on a mock sql client

- web/src/components/PreflightResultPage.jsx
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/apps/Dashboard.jsx
- web/src/components/shared/modals/SkipPreflightsModal.jsx
Reverts replicatedhq/kots#2716
> Revert "when user ignores preflights during installation, deploy the application"

- pkg/docker/registry/images_test.go
- pkg/docker/registry/registry_test.go
type::chore
We need to up our unit test coverage
Fixes #
This adds ~8% more coverage to the docker/registry package
```release-note
NONE
```
NONE
> add some unit tests

- Makefile
- pkg/print/fs-lvp-velero-config.go
> update local-volume-provider to v0.3.1

- .github/workflows/build-test.yaml
This PR combines the build-kots and build-kotsadm steps, as they were different primarily in what make commands they ran.
Fixes #
```release-note
```
> combine build-kots and build-kotsadm ci steps

- pkg/api/downstream/types/types.go
- pkg/handlers/app.go
- pkg/handlers/mock/mock.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/store_interface.go
> Return number of skipped and remaining versions

- .github/workflows/metrics.yml
- kurl_proxy/okteto.Dockerfile
- migrations/okteto.Dockerfile
- okteto.Dockerfile
- web/okteto.Dockerfile
Add metrics for build size
Fixes #NONE
NONE
```release-note
NONE
```
NONE
> Build metrics

- cmd/kots/cli/get-versions.go
- pkg/api/downstream/types/types.go
- pkg/handlers/app.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/store_interface.go
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/DashboardVersionCard.jsx
- web/src/components/shared/Pager.jsx
type::feature
Improves the UX of the pagination on the version history page.
Fixes #
Video demo of paging and dynamically setting of results per page: https://www.loom.com/share/625bdf3b28134739b6fdb98da5369257
```release-note
Adds the ability to dynamically set the number of results per page when browsing the version history for an application.
```
NONE
> ux improvements to pagination on version history page

- web/src/components/PreflightResultPage.jsx
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/apps/Dashboard.jsx
- web/src/components/shared/modals/SkipPreflightsModal.jsx
type::feature
Deploy application when a user chooses to ignore preflights and deploy.  We need this because the previous flow of choosing ignore preflights and continue was a confusing for some users as they expected their app to deploy when choosing this option.
Fixes #
https://app.shortcut.com/replicated/story/36852/skip-preflight-checks-on-initial-install-does-not-install-app
Ran against nightly regression tests.  Tested deploy functionality in okteto.
```release-note
Automate deployment of application when preflights are ignored.
```
> ignore preflights and deploy application

- .github/workflows/build-test.yaml
Followup to https://github.com/replicatedhq/kots/pull/2745
Fixes #
```release-note
```
> get logs from correct namespace

- README.md
- migrations/README.md
- migrations/okteto.yml
- migrations/tables/.stignore
Add Okteto information to READMEs
Add the ability to dev on migrations in Okteto
Fixes #47013
NONE
```release-note
NONE
```
> Adding the ability to dev on migrations in Okteto

- pkg/handlers/deploy.go
type::bug
Don't attempt to deploy a version only if it's the currently deployed version
This was affecting rollbacks since versions would already be marked as "deployed"
```release-note
NONE
```
NONE
> Don't deploy only if it's the currently deployed version

- cmd/kots/cli/reset-tls.go
type::feature
Allow user to annotate kurl proxy TLS secret at the time it is reset, so they don't have to refer to kURL documentation for additional steps.
Fixes #
```release-note
* Adds the ability to allow uploading new TLS certificates used by kURL proxy using the [reset-tls](/reference/kots-cli-reset-tls) command.
```
https://github.com/replicatedhq/replicated-docs/pull/291
> Allow anntating the kurl proxy TLS secret using kots CLI

- migrations/tables/.stignore
type::chore
Latest release of schemahero cannot handle files other than yaml when generating plan.  There a fix in schemahero repo, but there is no release with it yet.
Fixes #
```release-note
NONE
```
NONE
> Remove files that break schemahero

- pkg/password/password.go
type::chore
updated api error message for kots change pw
Fixes #
```release-note
NONE
```
NONE
> update error messages for kots change pw api

- cmd/imagedeps/image-spec
- cmd/imagedeps/main.go
- cmd/imagedeps/main_test.go
- cmd/imagedeps/tag-finder.go
- cmd/imagedeps/testdata/schemahero/.image.env
- cmd/imagedeps/testdata/schemahero/constants.go
- cmd/imagedeps/testdata/schemahero/input-spec
type::core
This adds schemahero to [imagedeps](https://github.com/replicatedhq/kots/tree/main/cmd/imagedeps) so that the script is able to find and update the .image.env file with the latest release.
Fixes #
Part of [SC-46822](https://app.shortcut.com/replicated/story/46822/update-needed-for-kurl-add-ons-and-kots-for-security-fixes)
```release-note
NONE
```
NONE
> Added schemahero to imagedeps so it's included in .image.env

- .github/workflows/build-test.yaml
type::chore
This will allow for changes in workflow from non-forks to reflect in the workflow run itself.
Fixes NONE
```release-note
NONE
```
NONE
> changes to workflow in pr should run in ci

- .github/PULL_REQUEST_TEMPLATE.md
type::chore
Adds a 'Steps to reproduce' section to the pull request template which helps other contributors validate the changes.
```release-note
NONE
```
NONE
> Add 'Steps to reproduce' section to the pull request template

- .github/workflows/alpha.yaml
- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
type::chore
This should speed up builds by caching go modules in actions
Fixes NONE
```release-note
NONE
```
NONE
> Actions cache go modules

- .github/workflows/build-test.yaml
also wrap a naked command in a while loop
This improves the error messaging for the validate-kots-pull suite, and fixes a potentially empty command.
Fixes #
```release-note
```
> improve error logs for validate-kots-pull

- .github/workflows/alpha.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
also remove 'container' override for some build jobs
Fixes #
```release-note
```
> change all workflows to use an ubuntu 20.04 base image instead of a mix of 18.04 and 20.04

- .github/workflows/alpha.yaml
- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
type::chore
Debugging why go caching is not working
Fixes NONE
NONE
NONE
```release-note
NONE
```
NONE
> Separate go caches

- .github/workflows/release.yaml
> add checkout action to goreleaser step

- migrations/deploy/Dockerfile
> add schemahero entrypoint

- .github/workflows/build-test.yaml
This adds a test to exercise https://github.com/replicatedhq/kots/pull/2743.
Fixes #
```release-note
```
> add a test to validate helm install weights are respected

- .github/workflows/release.yaml
> add package libbtrfs-dev to goreleaser build

- .github/workflows/build-test.yaml
This adds an on-pr test for https://github.com/replicatedhq/kots/pull/2746.
Fixes #
```release-note
```
> add on-pr test for yamlescape

- cmd/kots/cli/install.go
Fixes #
```release-note
NONE
```
NONE
> update kots install wait-duration flag to have the proper description

- go.mod
- go.sum
> Update troubleshoot dep

- pkg/operator/helm.go
- pkg/operator/operator.go
type::bug
When application specifies `additionalNamespaces` but does not included any non-helm resources, secrets will not be applied to additional namespaces.
Fixes #
```release-note
* FIxes a bug that would cause image pull secrets to not be created in additional namespaces when only Helm charts are used by the application.
```
NONE
> Ensure secrets when only Helm is used with no other specs

- .github/workflows/build-test.yaml
type::tests
improves the test
```release-note
NONE
```
NONE
> improve no-redeploy-on-restart test

- pkg/handlers/config.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/store_interface.go
type::bug
Fixes the initial version source message when updating the config
```release-note
NONE
```
NONE
> Fix initial version source message when updating the config

- pkg/operator/operator.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/mock/mock.go
- pkg/store/store_interface.go
type::bug
marks the restore version as the current version and deployed after partial restore
```release-note
NONE
```
NONE
> mark as current version and deployed after partial restore

- .github/workflows/metrics.yml
Fix a bug that was introduced with the recent okteto build v2 changes
Fixes #48070
None
None
```release-note
NONE
```
NONE
> Seanrester/sc 48070/kots metrics pipeline failing after the introduction

- web/src/utilities/utilities.js
fixes an issue where airgap bundle upload was hanging at 0%
Fixes [SC-47965](https://app.shortcut.com/replicated/story/47965/airgap-bundle-upload-gets-stuck-at-0)
```release-note
Fixes an issue where uploading the airgap bundle using the admin console hangs at 0%.
```
NONE
> fix airgap bundle upload hanging at 0%

- .github/workflows/trigger-regression-test.yaml
Fix regression test run
Fixes # NONE
NONE
```release-note
NONE
```
NONE
> Fix regression test not triggering

- pkg/operator/client/client.go
- pkg/operator/operator.go
- pkg/store/kotsstore/downstream_store.go
- pkg/version/version.go
removes the deploy loop from the operator so that everything happens adhoc
```release-note
NONE
```
NONE
> improvement: remove deploy loop from the operator

- deploy/Dockerfile
- deploy/okteto/okteto-v2.Dockerfile
- deploy/okteto/okteto.Dockerfile
- hack/dev/skaffold.Dockerfile
Fixes #
```release-note
kotsadm now includes helm v3.8.2
```
> upgrade to helm v3.8.2

- .github/workflows/alpha.yaml
- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
- Makefile
Speed up okteto build
Fixes NONE
```release-note
NONE
```
NONE
> No longer fmt and vet in make kots command

- go.mod
- go.sum
Fixes regression causing e2e tests to fail
Fixes NONE
```release-note
NONE
```
NONE
> Upgrade troubleshoot to v0.34.0

- .github/workflows/release.yaml
Add missing branch trigger for release workflow
Fixes #48196
NONE
NONE
```release-note
NONE
```
> Add branch trigger for release workflow

- e2e/kots/kots.go
- e2e/testim/client.go
Fixing misleading error when testim fails.
Changes message from:
```
No future change is possible.  Bailing out early after 10.010s.
Expected
<int>: 1
to match exit code:
<int>: 0
```
To:
```
No future change is possible.  Bailing out early after 10.012s.
Run testim tests failed with non-zero exit code
Expected
<int>: 1
to match exit code:
<int>: 0
```
Fixes NONE
```release-note
NONE
```
NONE
> Testim failure message

- .github/workflows/regression.yaml
Make it so regression doesn't fail if terraform workspace already exists
Fixes #
```release-note
```
> Don't fail regression if workspace already exists

- web/src/components/shared/NavBarDropdown.jsx
While resolving Testim test issues, I noticed that one of the links in the new navbar wasn't triggering due to a conflict of event listeners. This PR fixes that.
N/A
```release-note
```
> fix: fix bug where create new application button wasn't working

- web/src/components/apps/Dashboard.jsx
updates error message when license is expired on the dashboard version card
Fixes #
https://app.shortcut.com/replicated/story/46164/when-a-license-is-expired-and-you-try-to-check-for-updates-the-error-message-is-a-strange-syntax-error-instead-of-a-meaningful
1. have an expired license
2. click on check for update
```release-note
```
None
None
> update error message if license is expired

- .github/workflows/regression.yaml
Fix a regression test bug where the terraform workspace wasn't being select properly
Fixes #
```release-note
NONE
```
NONE
> Fix regression test bug

- e2e/Makefile
- e2e/e2e_test.go
- e2e/hack/Dockerfile
- e2e/kots/kots.go
- e2e/nightly_test.go
- e2e/registry/commands.go
- e2e/testim/client.go
- e2e/testim/inventory/inventory.go
- e2e/testim/inventory/test.go
- e2e/util/util.go
Fixing registry tests failing in the e2e tests
NONE
NONE
```release-note
NONE
```
> Fixing registry tests failing in the e2e tests

- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
Sometimes when you want to re-run the workflow the tags have already expired. 
Fixes #
```release-note
```
> Set ttl.sh image expiry to 12h from 2h

- web/src/components/apps/AppVersionHistory.jsx
- web/src/scss/utilities/colors.scss
- web/src/scss/utilities/utilities.scss
- web/src/scss/variables.scss
Improves the UX on the version history page when new versions are available.
Loom showing a demo of the updates: https://www.loom.com/share/cdaeba03eb6c4385816073105efcdadd
create new releases and pull them into the admin console. Ensure that the correct latest available version is pinned to the top and if there are no updates available it should show "application up to date"
```release-note
Improved UX on the version history page when the application is up to date or if there are new available versions.
```
> updating ux of how application updates are shown on version history

- .github/workflows/regression.yaml
- .github/workflows/release.yaml
- README.md
- actions/regression-test-cleanup/index.js
Adding regression test to the build-test workflow
Fixes #49260
NONE
NONE
```release-note
NONE
```
NONE
> Seanrester/sc 49260/remove the need for a GitHub release for

- go.mod
- go.sum
- pkg/preflight/preflight.go
- pkg/store/kotsstore/app_store.go
Bumps troubleshoot to 1.36.0.  No material changes.
Fixes #
```release-note
NONE
```
NONE
> Troubleshoot v1.36.0

- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
- e2e/e2e_test.go
- e2e/nightly_test.go
- e2e/testim/inventory/inventory.go
- e2e/velero/cli.go
Add a regression test to the build-test workflow
Fixes #NONE
NONE
NONE
```release-note
NONE
```
> Add a regression test to the build-test workflow

- pkg/kotsutil/kots.go
Adds kurl installer spec to kots kinds
Fixes #
```release-note
NONE
```
NONE
> Add installer to kots kinds

- .github/workflows/build-test.yaml
- e2e/testim/inventory/inventory.go
- e2e/velero/cli.go
Velero is installed by the regression test. Do not install it in the e2e test framework.
Fixes NONE
```release-note
NONE
```
NONE
> Regression test does not need velero

- .github/actions/generate-support-bundle/action.yml
- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
- e2e/e2e_test.go
- e2e/testim/inventory/inventory.go
Migrate e2e tests to new go framework
Fixes NONE
```release-note
NONE
```
NONE
> Migrate rest of e2e tests to new go framework

- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/DashboardVersionCard.jsx
Adds a check to see if preflight icon should be rendered. 
Fixes #
https://app.shortcut.com/replicated/story/50841/preflight-icons-are-visible-and-trigger-preflights-when-app-has-no-preflights
1. Create a release without preflight yaml and promote it
2. create an application
3. view dashboard and version history should not have  "view preflight check" icon 
4. create another release with preflight yaml and promote it
5. view dashboard and version history for view preflight check icon 
NONE
```release-note
```
NONE
> remove preflight icon if app has does not have preflight spec

- e2e/kots/kots.go
- pkg/handlers/snapshot_logs.go
- pkg/kotsadm/main.go
- pkg/kotsadm/postgres.go
- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/download.go
- pkg/kotsadmsnapshot/restore.go
- pkg/snapshot/velero.go
Simplify code. Fix leaked file.
Fixes NONE
```release-note
NONE
```
NONE
> Simplify Velero download logs

- .github/workflows/regression-test-cleanup.yaml
- actions/regression-test-cleanup/action.yml
- actions/regression-test-cleanup/dist/index.js
- actions/regression-test-cleanup/index.js
If too many tests run in 24 hours we run into resource quotas in aws. Make this configurable.
> Input CLEANUP_INTERVAL_HOURS for regression-test-cleanup workflow

- .github/workflows/regression-test-cleanup.yaml
Scheduled workflow is failing https://github.com/replicatedhq/kots/runs/7130980544?check_suite_focus=true
> Set default CLEANUP_INTERVAL_HOURS for scheduled workflow

- go.mod
- go.sum
This resolves CVE-2022-26945, CVE-2022-30321, CVE-2022-30322, CVE-2022-30323
Fixes #
```release-note
NONE
```
NONE
> Resolve CVEs in go-getter (imported via troubleshoot)

- pkg/template/static_context.go
Fixes detecting the 'openShift' distribution in minimal rbac
Fixes #
the distribution template function was trying to list nodes _before_ checking if it's an openshift cluster, and listing nodes does not work in minimal rbac mode, so i just moved that to the top.
```release-note
- Fixes an issue where the [Distribution](/reference/template-functions-static-context#distribution) template function returns an empty string in minimal RBAC installations running on OpenShift clusters.
```
NONE
> fix detecting 'openShift' distribution in minimal rbac

- e2e/minio/install.go
Lock Minio version in E2E suite to prevent auto updating
```release-note
NONE
```
NONE
> Lock Minio version in E2E suite to prevent auto updating

- pkg/handlers/app.go
- pkg/handlers/status.go
- pkg/handlers/update.go
- pkg/helm/updates.go
- web/src/components/apps/DashboardVersionCard.jsx
Partially implements checking for updates in Helm managed mode
Fixes #
```release-note
NONE
```
NONE
> Check for updates works from Dashboard in Helm mode

- Makefile
- actions/kubectl-versions/action.yml
- actions/kubectl-versions/dist/index.js
- actions/kubectl-versions/package-lock.json
- actions/kubectl-versions/package.json
This PR fixes the kubectl-versions github action by adding an `action.yml` file.  Also, this action has javascript dependencies, so they must be bundled using `@vercel/ncc` (see: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github).
Fixes [SC-49928](https://app.shortcut.com/replicated/story/49928/remove-unsupported-kubectl-versions-from-the-container-image)
Run the action.  Example: https://github.com/replicatedhq/kots/runs/7359490527?check_suite_focus=true
```release-note
NONE
```
NONE
> fix kubectl-versions github action

- pkg/handlers/app.go
- pkg/helm/charts.go
- pkg/helm/helm.go
In Helm mode:
- adds previously installed versions on Version History page
- show release status
- adds revision numbers
Fixes #
```release-note
NONE
```
NONE
> Add sequences, previous releases, and release status on Version History page

- README.md
- pkg/handlers/app.go
- pkg/handlers/handlers.go
- pkg/handlers/helm.go
- pkg/handlers/platform_license.go
- pkg/helm/cache.go
Fixes license loading from replicated.app when in Helm managed mode.
Fixes #
```release-note
NONE
```
NONE
> Fix loading license when deployed

- pkg/helm/cache.go
Don't use current directory to store temporary data.  Admin console does not run as root and will unlikely to have write permissions anywhere outside of system's temp directory.
Fixes #
```release-note
```
> Don't use current dir as temp storage

- pkg/apiserver/server.go
- pkg/helm/cache.go
Right now Helm mode only works with cluster scoped access.  This change allows it to work in limited RBAC mode.
Fixes #
```release-note
NONE
```
NONE
> Don't list namespaces in limited RBAC mode

- pkg/updatechecker/updatechecker.go
- pkg/updatechecker/updatechecker_test.go
Enabling automatic deployments when semantic versioning is not enabled does not automatically deploy new versions if the version label is not a valid semver. This PR will allow the automatic deployment to go through even if the version label is not a valid semantic version.
This PR also addresses another issue where any new version would be automatically deployed even if it's not a new upstream release (e.g. a config change, license change, etc...).
Fixes #
```release-note
Fixes an issue where non-semantic version automatic deployments do not work when version labels are not valid [SemVer](https://semver.org/).
```
NONE
> fix: non-semantic version automatic deployments do not work when version labels are not valid semantic versions

- pkg/handlers/app.go
- pkg/handlers/config.go
- pkg/handlers/handlers.go
- pkg/handlers/helm.go
- pkg/handlers/license.go
- pkg/handlers/platform_license.go
- pkg/handlers/update.go
- pkg/helm/cache.go
- pkg/helm/charts.go
- pkg/helm/updates.go
- pkg/license/license.go
- pkg/util/util.go
Adds functionality to Sync License button in Helm managed mode.
Fixes #
```release-note
NONE
```
NONE
> Sync license now works in Helm mode

- Makefile
- README.md
- pkg/handlers/app.go
- pkg/handlers/update.go
- pkg/helm/cache.go
- pkg/helm/updates.go
Fixes Version History page
- the top update is now shown twice as it's supposed to be
- added "Upstream Update" text
- fixed empty grey div on update rows
- added release sequences, which improve page behavior overall
Fixes #
```release-note
NONE
```
NONE
> Fixes for Version History page in Helm mode

- cmd/kots/cli/install.go
- cmd/kots/cli/upstream-upgrade.go
- cmd/kots/cli/velero.go
- pkg/api/reporting/types/types.go
- pkg/handlers/garbage_collect_images.go
- pkg/handlers/snapshots.go
- pkg/handlers/update.go
- pkg/identity/deploy.go
- pkg/image/minio.go
- pkg/installers/installers.go
- pkg/kotsadm/main.go
- pkg/kotsadm/metadata.go
- pkg/kotsadmsnapshot/backup.go
- pkg/kotsutil/kots.go
- pkg/kotsutil/kurl.go
- pkg/kurl/configmap.go
- pkg/kurl/kurl_nodes.go
- pkg/kurl/types/types.go
- pkg/registry/images.go
- pkg/reporting/app.go
- pkg/reporting/util.go
- pkg/s3/s3.go
- pkg/snapshot/filesystem.go
- pkg/snapshot/restore.go
- pkg/snapshot/store.go
- pkg/supportbundle/spec.go
- pkg/template/static_context.go
Add ability for KOTS to report on kurl node total and ready counts via headers.
Additionally:
- consolidate iskurl functions
- cache iskurl result
- handle rbac errors from iskurl function
Fixes NONE
```release-note
NONE
```
NONE
> Report kURL node total and ready counts

- pkg/handlers/troubleshoot.go
- web/src/components/troubleshoot/GenerateSupportBundle.jsx
- Fixes errors on Troubleshoot page in Helm managed mode
- Shows a support bundle command that works with OCI registry source
Result of running the command:
```
$ kubectl support-bundle oci://vendor-registry-v2-divolgin.okteto.repldev.com/okteto-kots/unstable
WARN[0000] unknown type: application/vnd.unknown.config.v1+json 
support-bundle-2022-07-21T14_55_12.tar.gz
```
Fixes #
```release-note
NONE
```
NONE
> Fix errors on troubleshoot page in Helm managed mode

- web/okteto.yml
- fixes the out of memory error that keeps happening in the dev environment 
Fixes #
```release-note
```
> expands pvc size from 2Gi

- pkg/helm/cache.go
Temp directory was missing the execute permission, which cause access errors when generating/saving new app config
Fixes #
```release-note
- (Alpha) Fixes a bug that caused errors when trying to generate upgrade commands from the Config page in Helm-managed mode
```
NONE
> Temp values directory needs execute permission

- .github/workflows/release.yaml
fix tag for non alpha
Fixes #
```release-note
```
> missing dollar sign in env var read

- pkg/apiserver/bootstrap.go
- pkg/apiserver/server.go
- pkg/handlers/handlers.go
- pkg/handlers/ports.go
- pkg/reporting/app.go
- pkg/store/kotsstore/registry_store.go
- pkg/store/kotsstore/supportbundle_store.go
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/hooks/useIsHelmManaged.js
- web/src/components/hooks/useIsHelmManaged.test.jsx
Removes dependency on Minio and Postgres in Helm managed mode.
Fixes #
```release-note
NONE
```
NONE
> Don't use Minio and Postgres in Helm managed mode

- web/src/components/apps/Dashboard.jsx
This PR fixes the issue where when a user selects a different app, the license/customer updated. 
Fixes # https://app.shortcut.com/replicated/story/54170/license-name-does-not-update-when-switching-between-apps
1. Create 2 applications with two separate customers
2. Switch between the two
3. notice that the license/customer name is changes
```release-note
NONE
```
NONE
> Fix: update customer when user changes app

- pkg/apiserver/bootstrap.go
This PR fixes an issue where legacy encryption keys from older installations were not being added to the list of known decryption keys.  This resulted in issues when restoring backups that were taken from a cluster that upgraded from a version of KOTS < 1.59.0 to a newer version.  The old encryption key from the installation was not loaded during the bootstrapping of the identity config and therefore resulted in the following error: `failed to init identity config: failed to get password value: failed to decrypt: cipher: message authentication failed`.  This PR adds a check for this legacy encryption key during the identity config bootstrapping so that it will be added to the list of known decryption keys, if it exists.
Fixes [SC-53698](https://app.shortcut.com/replicated/story/53698/ensur …
> fix: add installation encryption key to decryption ciphers if present

- deploy/okteto/okteto-v2.Dockerfile
`python3-pip` dependency in Okteto Dockerfile was inadvertantly changed to `python-pip`. Reverting this change.
> python-pip -> python3-pip

- web/src/Root.jsx
- web/src/components/apps/AppDetailPage.jsx
- web/src/components/shared/NavBar.jsx
- web/src/components/shared/NavBarDropdown.jsx
This PR hides "Add New Application" from dropdown when running in helm managed mode.
Fixes #
https://app.shortcut.com/replicated/story/51186/add-new-application-button-should-not-be-present-in-helm-mode
See attached screenshot from a KOTS instance running in helm managed mode , "Add Application" is not present
```release-note
```
NONE
> dont show add application in dropdown when  in helm mode

- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
- cmd/kots/cli/admin-console.go
- e2e/Makefile
- e2e/e2e_test.go
- e2e/kots/kots.go
- e2e/testim/client.go
- e2e/testim/inventory/inventory.go
- e2e/testim/inventory/test.go
> Adding Helm based tests

- web/src/Root.jsx
- web/src/components/SecureAdminConsole.jsx
check is helm managed after login so navbar can be rendered correctly 
Fixes #
```release-note
```
> check is-helm-managed after login

- pkg/api/downstream/types/types.go
- pkg/api/downstream/types/types_test.go
- pkg/handlers/app.go
- pkg/helm/cache.go
- pkg/helm/updates.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/kotsstore/version_store.go
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/DashboardVersionCard.jsx
Changes are forHelm managed mode only:
1. Installed revisions are sorted by revision number in descending order, similar to `helm history` output. Pending updates are still listed in semver order, but separately from installed revisions (some UI work still pending)
2. `Sequence` label changed to `Revision`
3. Pending updates no linger have sequence/revision number displayed
4. Various fixes to update cache.
Fixes #
```release-note
* Fixes versions ordering on the [version history](/enterprise/updating-apps#update-an-application-in-the-admin-console) page in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
> Version history page in helm mode fixes

- web/src/components/UploadAirgapBundle.jsx
- web/src/components/apps/AppVersionHistoryRow.jsx
- web/src/components/apps/Dashboard.jsx
- web/src/components/apps/DashboardVersionCard.jsx
- web/src/components/config_render/ConfigFileInput.jsx
- web/src/components/shared/NavBar.jsx
- web/src/components/shared/NavBarDropdown.jsx
- web/src/components/snapshots/SnapshotDetails.jsx
- web/src/components/troubleshoot/GenerateSupportBundle.jsx
- web/src/scss/components/config-render/config-base-styles.scss
- run linting on main so unrelated changes aren't in another pr 
Fixes #
```release-note
none
```
none
> fix linting issues

- pkg/airgap/airgap.go
- pkg/app/types/app.go
- pkg/app/types/helm_app.go
- pkg/app/types/types.go
- pkg/handlers/app.go
- pkg/handlers/helm.go
- pkg/handlers/preflight.go
- pkg/handlers/troubleshoot.go
- pkg/helm/cache.go
- pkg/helm/charts.go
- pkg/kotsutil/kots.go
- pkg/online/online.go
- pkg/operator/client/client.go
- pkg/operator/operator.go
- pkg/preflight/preflight.go
- pkg/redact/app.go
- pkg/render/helper/appfile.go
- pkg/supportbundle/helm.go
- pkg/supportbundle/spec.go
- pkg/supportbundle/supportbundle.go
Support bundles that run from UI now have dynamically added collectors, analyzers, and redactors.
Original collectors:
Custom redactor:
Redaction result
Evaluated channel name template:
Fixes #
```release-note
* Adds dynamic kots collectors, analyzers, and custom redactors when collecting support bundles from the [troubleshoot](/enterprise/troubleshooting-an-app#create-a-support-bundle-using-the-admin-console) page in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
> Add default kots collectors and analyzers when running support bundle from UI

- web/src/components/modals/ChangePasswordModal/ChangePasswordForm.jsx
- web/src/components/shared/forms/InputField.jsx
- web/src/scss/components/shared/forms/InputField.scss
Shows password rules when changing password 
Fixes # https://app.shortcut.com/replicated/story/54964/show-password-complexity-rules-when-changing-password-in-ui
1. Click on change password at the top right 
```release-note
NONE
```
None
> Show password rules

- kotskinds/apis/kots/v1beta1/helmchart_types.go
- kotskinds/apis/kots/v1beta1/helmchart_types_test.go
- pkg/app/types/helm_app.go
- pkg/handlers/config.go
- pkg/handlers/config_test.go
- pkg/handlers/helm.go
- pkg/helm/cache.go
- pkg/helm/charts.go
- pkg/helm/config_values.go
- pkg/helm/helm.go
- pkg/helm/helm_test.go
- pkg/kotsutil/kots.go
- pkg/reporting/app.go
Values entered on the config screen should be stored in ConfigValues, not in Config.
Fixes #
```release-note
NONE
```
NONE
> Store Helm config values in ConfigValues kind

- deploy/Dockerfile
- deploy/okteto/okteto-v2.Dockerfile
- deploy/okteto/okteto.Dockerfile
- hack/dev/skaffold.Dockerfile
> rename env var to kustomize4

- .github/workflows/build-test.yaml
This PR adds a step to the build-test workflow that tests a basic kots install of an application that uses an image with both a tag and digest.
Fixes #
```release-note
```
> chore: add validate tag and digest to build-test

- .github/workflows/require-pr-labels.yaml
Blocks merge if necessary PR labels are missing
Fixes #
```release-note
NONE
```
NONE
> Require PR labels

- .github/workflows/kurl-addon-kots-publish.yaml
Trigger kotadm addon generate as part of the kots release process
NONE
NONE
```release-note
NONE
```
NONE
> Trigger kotadm addon generate as part of the kots release process

- pkg/handlers/downstream.go
- pkg/helm/cache.go
- pkg/helm/charts.go
- web/src/components/UploadAirgapBundle.jsx
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/snapshots/SnapshotDetails.jsx
- web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
This PR implements deploy logs API response for KOTS when running in helm managed mode
Fixes #
https://app.shortcut.com/replicated/story/54248/404-returned-when-trying-to-view-deploy-logs
```release-note
Show deploy logs of helm charts when running in [Helm managed mode (Alpha)](/vendor/helm-install).
```
Loom: https://www.loom.com/share/9ea4867e71fc4087b572d9f7d53b7c20
> implement deploy logs view for helm managed mode

- actions/copy-assets/go.mod
- actions/copy-assets/go.sum
- kurl_proxy/go.mod
- kurl_proxy/go.sum
This PR resolves CVE-2021-44716 in the kurl_proxy image.  It also makes the same module update for the `copy-assets` github action.
```
kurl_proxy (gobinary)
Total: 1 (HIGH: 1, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬───────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                           Title                           │
├──────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────────────────────────┼───────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2021-44716 │ HIGH     │ …
```
> fix: resolve CVE-2021-44716 in kurl_proxy

- web/src/components/UploadAirgapBundle.jsx
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/DashboardVersionCard.jsx
- web/src/components/shared/SubNavBar/SubNavBar.jsx
- web/src/components/snapshots/SnapshotDetails.jsx
- web/src/features/AppConfig/components/AppConfig.jsx
- web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
https://app.shortcut.com/replicated/story/55913/updates-to-text-in-deploy-modal-on-version-history-page
https://app.shortcut.com/replicated/story/55914/updates-to-text-in-redeploy-modal-on-version-history-page
https://app.shortcut.com/replicated/story/55915/updates-to-text-in-rollback-modal-on-version-history-page
https://app.shortcut.com/replicated/story/55881/update-wording-for-deploy-modal-on-dashboard-for-newly-available-version
[sc-55913]
[sc-55914]
[sc-55915]
[sc-55881]
- for helm managed mode 
```release-note
- (alpha) improve copy on helm install instructions 
```
NONE
> copy updates

- web/src/features/AppConfig/components/AppConfig.jsx
- remove deprecated lifecycle method from AppConfig
- none
- none
none- this is a refactor 
none
> remove componentWillMount from AppConfig

- web/src/components/SecureAdminConsole.jsx
- web/src/components/UploadAirgapBundle.jsx
- web/src/components/apps/DashboardVersionCard.jsx
- web/src/components/shared/SubNavBar/SubNavBar.jsx
- web/src/components/snapshots/SnapshotDetails.jsx
- web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
- remove deprecated lifecycle method from `SecureAdminConsole`
- none
load the app 
none- this is a refactor 
none
> remove componentWillMount from SecureAdminConsole

- web/src/components/apps/Dashboard.jsx
- web/src/features/AppConfig/components/AppConfig.jsx
- fixes minor bug related to fetching app for dashboard. I believe this is what is causing the tests to fail in the react 18 upgrade. 
- none
none
> fix failing fetch

- web/src/components/apps/Dashboard.jsx
- web/src/features/Dashboard/api/getDashboard.jsx
- web/src/features/Dashboard/api/getDashboard.test.jsx
- web/src/features/Dashboard/index.js
- update dashboard to load data with a hook 
none - refactor 
none
> Rianfowler/sc 52399/upgrade kots to react 18 9

- web/src/components/apps/AppGitops.jsx
- web/src/components/apps/DashboardGitOpsCard.jsx
- web/src/components/gitops/GitOpsDeploymentManager.jsx
- web/src/components/gitops/GitOpsRepoDetails.jsx
- web/src/components/gitops/SetupProvider.jsx
- web/src/components/gitops/modals/ConnectionModal.jsx
- web/src/components/gitops/modals/DisableModal.jsx
- web/src/config-ui/subNavConfig.js
- web/src/images/enabled.svg
- web/src/images/not_enabled.svg
- web/src/images/warning.svg
- web/src/scss/components/gitops/GitOpsDeploymentManager.scss
- web/src/scss/components/gitops/GitOpsSettings.scss
- web/src/scss/components/gitops/GitopsPrism.scss
- web/src/scss/utilities/forms.scss
- web/src/scss/utilities/icons.scss
- web/src/scss/utilities/modals.scss
- web/src/styles/common.js
UI updates to the GitOps workflow to improve ease of use. 
https://www.loom.com/share/0a48eae6e3834b53a479b64f1598b3f2
Fixes # https://app.shortcut.com/replicated/story/55403/improve-the-gitops-ux
```release-note
UI updates to the GitOps workflow to improve ease of use. 
```
** will add later
> Miawong/sc 55403/improve the gitops ux

- web/src/components/apps/Dashboard.jsx
Reverts replicatedhq/kots#3077
> Revert "refactor Dashboard into SFC"

- .github/workflows/regression.yaml
This PR slightly refactors the regression test matrix to tear down the test infrastructure on re-run so that each re-run has pristine infrastructure.
```release-note
NONE
```
NONE
> Destroy test instance before retry to ensure clean environment

- .github/workflows/tag-helm-chart.yaml
consolidate staging and prod stags in a single job that runs once release is fully finalized.
Fixes #
```release-note
```
> consolidate ci for creating prod and staging tags for helm chart

- README.md
- pkg/updatechecker/updatechecker.go
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/Dashboard.jsx
- web/src/components/modals/AutomaticUpdatesModal.jsx
Removes the "Enable automatic deployment" option from the update checker settings dialog in Helm managed mode because it's not supported.
Fixes #
```release-note
* Removed unsupported options from the ["Configure automatic updates"](/enterprise/updating-apps#configure-automatic-updates) dialog because it's not supported in [Helm managed mode (Alpha)](/vendor/helm-install)
```
NONE
> No automatic deploys when Helm managed

- .github/workflows/regression.yaml
Fixes race condition with workspace where jumpbox would not be turned up.
Fixes #
```release-note
NONE
```
NONE
> out-of-order steps on infra turn-up

- web/src/components/apps/AppDetailPage.jsx
- removes logging statement 
none
none
none
> remove console log

- web/src/components/apps/Dashboard.jsx
- this error popped up in the console in the new webpack update. 
none
- load dashboard 
```release-note
- fix error handling bug frontend dashboard 
```
> get body before setting error state

- .github/workflows/regression.yaml
Revert the regression test workflow to using stateful workspace select; will address with reusable workflow refactor later
Fixes #
```release-note
NONE
```
NONE
> Revert TF env change pending workflow refactor

- web/package.json
- web/src/components/snapshots/SnapshotStorageDestination.tsx
- improves type checking on SnapshotStorageDestination.tsx
n/a
n/a
n/a
- no, only add some small refactors 
NONE
> narrow types on SnapshotStorageDestination.tsx

- pkg/airgap/types/types.go
- pkg/app/types/helm_app.go
- pkg/handlers/app.go
- pkg/handlers/helm.go
- pkg/handlers/update.go
- pkg/handlers/update_checker_spec.go
- pkg/helm/helm.go
- pkg/online/online.go
- pkg/online/types/types.go
- pkg/store/kotsstore/app_store.go
- pkg/store/kotsstore/kots_store.go
- pkg/store/kotsstore/task_store.go
- pkg/store/mock/mock.go
- pkg/store/store_interface.go
- pkg/updatechecker/updatechecker.go
- web/src/components/modals/AutomaticUpdatesModal.jsx
This PR implements checking for updates for helm charts when running in helm managed mode.
Fixes #
https://app.shortcut.com/replicated/story/54318/helm-mode-automatic-update-checks-don-t-happen
This also includes some minor FE changes.  Namely, default to default not custom, and set certain text in the modal based on what mode KOTS is running in.
```release-note
Adds ability to automatically check for new chart versions that are available when running in [Helm managed mode (Alpha)](/vendor/helm-install).
```
> auto update checks for helm charts

- web/src/components/modals/AutomaticUpdatesModal.jsx
- removes linting issue 
none 
none
> fix linting issue

- pkg/handlers/update_checker_spec.go
fix assignment to nil map
Fixes #
```release-note
```
> fix assignment to nil map

- web/src/components/config_render/ConfigCheckbox.jsx
- web/src/components/config_render/ConfigCheckbox.tsx
Current change
Fixes #
```release-note
Fixes checkbox alignment in config page. 
```
NONE
> Miawong/sc 57193/fix checkbox alignment on config page

- web/src/components/apps/AppDetailPage.jsx
- web/src/features/AppConfig/components/AppConfig.jsx
Show error message when required config is missing
Fixes #
```release-note
* Fixes a bug that caused errors to be not displayed on the [config page](/vendor/config-screen-about#admin-console-config-tab) when values for required config items are missing in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
> Show error when required config is missing

- web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Hide `Revision` label on the Version History page for pending Helm releases.
Fixes #
```release-note
NONE
```
NONE
> Don't show Revision text on pending Helm releases

- pkg/automation/automation.go
- pkg/handlers/config.go
- pkg/handlers/helm.go
- pkg/handlers/license.go
- pkg/helm/charts.go
- pkg/helm/license.go
- pkg/helm/updates.go
- pkg/kotsadmlicense/license.go
- pkg/license/license.go
- pkg/pull/pull.go
- pkg/replicatedapp/api.go
- pkg/replicatedapp/api_test.go
- pkg/replicatedapp/cursor.go
- pkg/replicatedapp/upstream.go
- pkg/replicatedapp/upstream_test.go
- pkg/updatechecker/updatechecker.go
- pkg/upstream/fetch.go
- pkg/upstream/replicated.go
- pkg/upstream/replicated_test.go
- web/src/components/apps/Dashboard.jsx
When checking for updates in Helm managed mode, the license will be synced first.
Fixes #
```release-note
* Fixes an issue that caused the license to not be synced when checking for application updates in [Helm managed mode (Alpha)](/vendor/helm-install).
```
> Sync license before checking for updates in Helm mode

- web/src/components/apps/AppVersionHistory.jsx
Only show pending updates in the `"New version available"` row in Helm managed mode.
Fixes #
```release-note
* Fixes a bug that caused currently deployed version to be temporarily shown as a new update while an update check is running in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
> Don't try to show updates until they are downloaded

- pkg/operator/operator.go
Fixes an error log typo that looks like below
```
{"level":"info","ts":"2022-09-21T05:56:23Z","msg":"restore complete, marking version ********** as deployed[]"}
{"level":"error","ts":"2022-09-21T05:56:24Z","msg":"failed to handle restoe for app **********: failed to handle undeploy completed: failed to check restore \"**********\" complete: failed to mark app version as deployed: Rollback is not supported."}
{"level":"info","ts":"2022-09-21T05:56:26Z","msg":"restore complete, marking version ********** as deployed[]"}
{"level":"error","ts":"2022-09-21T05:56:26Z","msg":"failed to handle restoe for app **********: failed to handle undeploy completed: failed to check restore \"**********\" complete: failed to mark app version as deployed: Rollback is not supported."}
```
```release-note …
```
> fix: Update error log message

- web/src/features/AppConfig/components/AppConfig.tsx
- web/src/features/AppConfig/styles/index.js
Fixes #
```release-note
NONE
```
NONE
> fix arrow icon rotation

- .github/workflows/alpha.yaml
fix gihub actions
Fixes #
```release-note
NONE
```
NONE
> Fix githib actions yaml

- .github/actions/kurl-addon-kots-publisher/action.yml
- .github/actions/kurl-addon-kots-publisher/index.js
- .github/workflows/kurl-addon-kots-generate.yaml
- .github/workflows/kurl-addon-kots-publish.yaml
- .github/workflows/kurl-addon-kots-test.yaml
- deploy/kurl/kotsadm/template/generate.sh
Adds/improves support for generating, testing and releasing the kotsadm kurl package .
Fixes NONE
```release-note
NONE
```
NONE
> Improved support for generating, testing and releasing the kurl package

- .github/workflows/kurl-addon-kots-publish.yaml
- .github/workflows/kurl-addon-kots-test.yaml
- KOTS kURL add-on release testgrid run priority 1
- Fix kurl-addon-test workflow
> KOTS kURL add-on release testgrid run priority 1

- .github/workflows/kurl-addon-kots-generate.yaml
- .github/workflows/kurl-addon-kots-publish.yaml
- .github/workflows/kurl-addon-kots-test.yaml
Workflow env context isn't always available. Use inputs directly.
> Use workflow context inputs over env

- web/src/components/config_render/ConfigGroup.jsx
- web/src/features/AppConfig/components/AppConfig.tsx
- web/src/scss/components/watches/WatchConfig.scss
Fixes #
```release-note
NONE
```
NONE
> add classname to config elements

- .github/actions/kurl-addon-kots-publisher/.babelrc
- .github/actions/kurl-addon-kots-publisher/dist/index.js
- .github/actions/kurl-addon-kots-publisher/index.js
- .github/actions/kurl-addon-kots-publisher/package-lock.json
- .github/actions/kurl-addon-kots-publisher/package.json
- .github/actions/kurl-addon-kots-publisher/publisher.js
- .github/actions/kurl-addon-kots-publisher/test/publisher.js
- .github/workflows/kurl-addon-kots-generate.yaml
- .github/workflows/kurl-addon-kots-publish.yaml
Sort and dedupe versions.json
Use correct credentials
> Fix kurl-addon-publish-action

- .github/workflows/kurl-addon-kots-publish.yaml
- .github/workflows/kurl-addon-kots-test.yaml
> Fixes to kurl add-on workflows

- .github/actions/kurl-addon-kots-publisher/dist/index.js
- .github/actions/kurl-addon-kots-publisher/index.js
- .github/workflows/kurl-addon-kots-publish.yaml
- deploy/kurl/kotsadm/template/base/install.sh
- deploy/kurl/kotsadm/template/base/postgres.yaml
- deploy/kurl/kotsadm/template/testgrid/k8s-docker.yaml
- Fix kurl-addon-kots-publisher action call
- Bring kots addon up to date
- Fix error assignment to constant variable
> Fix kurl-addon-kots-publisher action call

- pkg/updatechecker/updatechecker.go
- web/src/components/apps/AppVersionHistory.jsx
- web/src/components/apps/Dashboard.tsx
- web/src/components/apps/DashboardVersionCard.jsx
In Helm managed mode, when checking for updates, the API will return the "license expired" message.
Fixes #
```release-note
* Fixes an issue where checking for updates from the [version history](/enterprise/updating-apps#update-an-application-in-the-admin-console) page would not show the "License is expired" error when the check fails due to an expired license in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
> Show license expired message on Version History page

- web/src/components/apps/Dashboard.tsx
- web/src/components/shared/AirgapRegistrySettings.tsx
Fixes # [sc-58965]
```release-note
NONE
```
NONE
> Miawong/sc 58965/adding typechecking to registry

- .github/actions/kurl-addon-kots-test/action.yml
- deploy/kurl/kotsadm/testgrid-os-spec.yaml
Use only ubuntu 22 rather than all of os-firstlast.yaml spec
> Pass in custom testgrid os spec to validate kurl add-on

- .github/actions/kurl-addon-kots-publish/action.yml
- .github/workflows/kurl-addon-kots-publish.yaml
- .github/workflows/release.yaml
Test kurl add-on on merge to main
> Test kURL add-on on merge and release

- .github/workflows/release.yaml
Conditionally test kurl addon on merge to main if changes to deploy/kurl
> Conditionally test kurl addon on merge to main if changes to deploy/kurl

- .github/workflows/regression.yaml
- .github/workflows/release.yaml
Use kURL kotsadm add-on package for release regression tests
> Use kURL kotsadm add-on package for release regression tests

- web/src/features/Auth/components/SecureAdminConsole.tsx
- fixes bug where successful identity service login routed to login page
Fixes #
```release-note
- Fixes an issue where identity service login would redirect to login page after successful login 
```
none
> Fix identity service login

- deploy/kurl/kotsadm/hack/Makefile
- deploy/kurl/kotsadm/template/base/install.sh
various kURL add-on dev environment fixes
> No kots binary in dev env

- .github/actions/kurl-addon-kots-publish/action.yml
- .github/actions/kurl-addon-kots-test/action.yml
- .github/workflows/build-test.yaml
- .github/workflows/kurl-addon-kots-test.yaml
- .github/workflows/release.yaml
Separate out and leverage reusable actions
> Cleanup kurl addon github actions

- deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-proxy.yaml
- deploy/kurl/kotsadm/template/base/install.sh
- deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-proxy.yaml
Relates to https://github.com/replicatedhq/kURL/pull/3554
Fixes NONE
```release-note
Fixes an issue that could cause embedded installations to fail with error "yaml: did not find expected node content" when installing behind an HTTP_PROXY.
```
NONE
> NO_PROXY env value invalid yaml with starts with comma

- web/src/components/apps/DashboardSnapshotsCard.tsx
Fixes # [sc-59400]
```release-note
NONE
```
NONE
> add typechecks to dashboard snapshots card

- web/src/components/modals/AutomaticUpdatesModal.tsx
- web/src/types/index.ts
Fixes # [sc-59400]
```release-note
NONE
```
NONE
> Adds typechecking to AutomaticUpdatesModal

- cmd/kots/cli/plugin.go
- cmd/kots/cli/preflight.go
- cmd/kots/cli/root.go
Adds plugin command with preflight subcommand stub
Fixes #
```release-note
```
> init plugin command with preflight stub

- .github/dependabot.yml
- cmd/imagedeps/README.md
- pkg/handlers/handlers.go
- pkg/policy/policies.go
- web/src/components/Head/KotsPageTitle.tsx
- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/apps/DashboardVersionCard.tsx
- web/src/components/gitops/GitOpsFlowIllustration.jsx
- web/src/features/Gitops/components/SetupProvider.jsx
Fixes #
https://app.shortcut.com/replicated/story/60437/space-missing-between-two-words-on-diff-why-modal
https://app.shortcut.com/replicated/story/42586/github-and-gitops-should-be-stylized-correctly-and-consistently
```release-note
- fixes a bug where GitHub and GitOps are shown in pascal case
- fixes space missing between two words on diff Why? modal
```
> style GitHub and GitOps in pascal calse

- web/src/components/apps/AppLicense.tsx
- converts AppLicense component into a functional component so that hooks can be used in it
https://app.shortcut.com/replicated/story/50084/fix-multi-app-ux
none - refactor 
none
> convert applicense into functional component

- web/src/features/Gitops/components/AppGitops.jsx
- web/src/features/Gitops/components/AppSelector.jsx
- web/src/features/Gitops/components/GitOpsProviderSelector.jsx
- web/src/features/Gitops/components/GitOpsRepoDetails.jsx
- web/src/features/Gitops/components/SetupProvider.jsx
- web/src/features/Gitops/constants.js
- web/src/features/Gitops/utils.js
- web/src/scss/components/gitops/GitOpsDeploymentManager.scss
- web/src/scss/components/gitops/GitOpsSettings.scss
- web/src/scss/utilities/base.scss
- Some pages in the admin console, don't have the same look as others. 
- This PR updates GitOps to look similar to other pages. 
- In preparation of custom branding css feature, this PR adds a few global classnames that will allow for vendors to style admin console. 
- This update changes a few GitOps' element's classname to the global classnames. 
- This PR also fixes the icon that has a circular border, allowing square icons. 
Fixes # https://app.shortcut.com/replicated/story/60191/standardize-the-look-of-the-gitops-page
[sc-60439] https://app.shortcut.com/replicated/story/60439/icon-on-gitops-page-still-has-circle-around-it
```release-note
NONE
```
NONE
> Miawong/sc 60191/standardize the look of the gitops page

- hack/dev/skaffoldcache.Dockerfile
This PR updates the `skaffoldcache.Dockerfile` to go 1.19 since kots was also updated to go 1.19.
Fixes #
```release-note
NONE
```
NONE
> update skaffold cache dockerfile for go 1.19

- web/src/components/apps/AppDetailPage.tsx
- web/src/features/Dashboard/components/Dashboard.tsx
- web/src/features/Dashboard/index.ts
- Refactors Dashboard into functional component so we can use hooks in it 
https://app.shortcut.com/replicated/story/50084/fix-multi-app-ux
none- refactor 
none
> Rianfowler/sc 50084/convert Dashboard into functional component 

- web/src/Root.tsx
- repairs metadata fetching so that it is done before login 
https://app.shortcut.com/replicated/story/60761/admin-console-does-now-show-app-icon-on-initial-login
- install application that has custom icon defined in the application spec
- logout of kots
- you should see the custom icon 
```release-note
- fix an issue where custom app icons were not showing on login page
```
none
> fetch metadata before login

- .fossa.yml
- .github/workflows/pr-license-scan.yaml
- README.md
- web/package.json
- web/yarn.lock
Adds FOSSA license scanning on PR and status badge.
```release-note
NONE
```
NONE
> Nickmeyer/sc 53201/fossa pr license check

- web/src/features/Dashboard/components/Dashboard.tsx
- web/src/features/Dashboard/components/DashboardVersionCard.tsx
- fixes airgap uploader 
Fixes #
Uploaded an invalid airgap bundle to test fix: 
none
none
> fix airgap uploader

- pkg/supportbundle/defaultspec/spec.yaml
Adds flannel collectors and analyzers to our default troubleshoot spec
> Troubleshoot flannel collectors and analyzers

- .github/workflows/pr-license-scan.yaml
Old key inadvertently deleted.
Fixes #
```release-note
```
> Update FOSSA API key

- pkg/handlers/config.go
When templates are evaluated, the sequence is always incremented by 1 since a new version will be created.  However this should not happen for the initial config screen.  The initial version sequence will remain 0 and the `Sequence` template function should return 0.
This uses the same logic to create context that's used when creating new version.
Fixes #
```release-note
* Fixes the issue that caused [`Sequence`](/reference/template-functions-license-context#sequence) template function to return 1 instead of 0 during initial configuration.
```
NONE
> Sequence template function should return 0 for initial version

- deploy/kurl/kotsadm/template/base/tmpl-secret-rqlite.yaml
- go.mod
- go.sum
- migrations/kustomize/overlays/dev/rqlite.yaml
- migrations/kustomize/overlays/okteto/rqlite.yaml
- pkg/kotsadm/objects/secrets_objects.go
Updates gorqlite connector to fix load balancing after scaling rqlite up to multiple replicas
Fixes #
```release-note
```
> Update gorqlite connector to fix load balancing after scaling rqlite up to multiple replicas

- pkg/snapshot/store.go
- pkg/snapshot/store_test.go
This PR refactors the code that updates the existing snapshot store into its own method so that it can be unit tested.  Coverage was added for the local-volume-provider store permutation.
n/a
In general, the pattern of instantiating a k8s client within a function makes it difficult to unit test that function since it requires a cluster context.  This PR instantiates the client outside of the new function so that a fake k8s client can be used for unit testing.
`make test`
```release-note
NONE
```
NONE
> add unit test coverage for snapshot store

- pkg/handlers/registry.go
- web/src/components/shared/AirgapRegistrySettings.tsx
Support removing private registry info (image rewrites) from application.
Fixes #
```release-note
* Adds ability to remove registry info from the Registry settings page.
```
NONE
> Allow removing registry settings

- web/src/features/AddNewApp/components/InstallWithHelm.tsx
- web/src/features/App/api/useLicense.ts
- web/src/features/Dashboard/api/useNextAppVersion.ts
- web/src/features/Dashboard/api/useSelectedAppClusterDashboard.ts
- web/src/features/Gitops/hooks/useApps.js
- redirect from helm install page if there is an app installed 
https://app.shortcut.com/replicated/story/60232/the-install-with-helm-screen-should-automatically-redirect-to-apps-page-when-a-chart-is-installed
with your kots install in helm mode, you can just navigate directly to /install-with-helm to test the redirect behavior. 
```release-note
- fixes an issue where kots would not redirect from `/install-with-helm` automatically after an application is installed 
```
none
> add poll for apps in helm install component

- cmd/kots/cli/pull.go
- pkg/pull/pull.go
- pkg/upstream/fetch.go
- pkg/upstream/helm.go
- pkg/upstream/types/types.go
Removes code used for deprecated `kots pull helm` command. 
Fixes # [SC-47336](https://app.shortcut.com/replicated/story/47336/remove-code-for-install-helm-chart-from-kots-alpha-experiment)
```release-note
NONE
```
NONE
> remove code for deprecated 'kots pull helm' command

- .github/workflows/pr-license-scan.yaml
Transitions FOSSA to a centrally-managed composite action so that alterations to the process can be made in one place if needed. Transition to `pull_request_target` event to provide access to the API key secret. This is generally safe because the code is not executed.
Fixes #
```release-note
NONE
```
NONE
> Transition FOSSA to centrally-managed action

- web/src/components/config_render/ConfigGroup.jsx
- web/src/features/AppConfig/components/AppConfig.tsx
- web/src/features/AppConfig/styles/index.js
- web/src/scss/components/watches/WatchConfig.scss
Fixes # https://app.shortcut.com/replicated/story/61292/standardize-the-look-of-the-config-page
```release-note
Redesign Config page to standardize the look of Admin Console. 
```
NONE
> Miawong/sc 61292/standardize the look of the config page

- .github/workflows/pr-license-scan.yaml
Corrects the ref checked out for forked PRs; the prior ref was incomplete in that context.
Fixes #
```release-note
NONE
```
NONE
> correct checked out ref for FOSSA tests

- cmd/kots/cli/reset-password.go
- pkg/kotsadm/main.go
- pkg/kotsadm/secrets.go
- pkg/upstream/admin-console.go
- pkg/util/password_prompt.go
Updates the kotsadm reset password command to show the password requirements
Fixes #44454
```release-note
NONE
```
NONE
> shows password complexity rules for resetting kotsadm password

- web/src/components/snapshots/SnapshotSchedule.jsx
Fixes an issue where configuring snapshot schedules in Firefox didn't work
Fixes #
```release-note
Fixes an issue where configuring snapshot schedules in Firefox didn't work
```
NONE
> Fix configuring snapshot schedule in firefox

- .github/workflows/build-test.yaml
This PR addresses an issue with branch protection where the `validate-success` step would be skipped if the `validate-*` PR tests did not run, triggering branch protection success.  With these changes, the `validate-success` step will always run and checks that the `validate-pr-tests` step was run successfully and that the `validate-kurl-addon` step was either successful or was skipped (if no changes were made to the addon).
Example of skipped `validate-success` from fork: https://github.com/replicatedhq/kots/actions/runs/3437864499
Example of skipped `validate-success` from branch where tests are passing (but `validate-kurl-addon` skipped): https://github.com/replicatedhq/kots/actions/runs/3473232691
Fixes branch protection in preparation for work on …
> add intermediate step to validate pr tests

- web/src/components/modals/ViewSnapshotLogsModal.jsx
- web/src/components/snapshots/AppSnapshots.jsx
- web/src/components/snapshots/GettingStartedSnapshots.jsx
- web/src/components/snapshots/SnapshotDetails.jsx
- web/src/components/snapshots/SnapshotRow.jsx
- web/src/components/snapshots/SnapshotSchedule.jsx
- web/src/components/snapshots/SnapshotStorageDestination.tsx
- web/src/components/snapshots/Snapshots.jsx
- web/src/scss/components/snapshots/AppSnapshots.scss
- web/src/scss/utilities/base.scss
snapshot list
snapshot details 
snapshot settings
Fixes # https://app.shortcut.com/replicated/story/60461/standardize-the-look-of-the-snapshots-page
Snapshots have to be run on codeserver
```release-note
Standardize and redesign Snapshots UI
```
NONE
> Miawong/sc 60461/standardize the look of the snapshots page

- pkg/handlers/app.go
Add Helm mode handling on initial console login.
Fixes #
```release-note
* Fixes an issue that causes the login button to be stuck in the "Logging in" state in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
> Fail gracefully in Helm mode on initial login

- Makefile
- README.md
- deploy/okteto/okteto-v2.Dockerfile
- okteto-v2.yml
Currently, debugging KOTSADM api using okteto isn't possible
Fixes #
add kotsadm debugger for okteto v2
`launch.json` file for vscode debugging
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "Connect to kotsadm",
"type": "go",
"request": "attach",
"mode": "remote",
"remotePath": "/go/src/github.com/replicatedhq/kots",
"port": 2353,
"host": "127.0.0.1"
}
]
}
```
```release-note
NONE
```
NONE
> add kotsadm debugger for okteto v2

- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
- Makefile
- deploy/kurl/kotsadm/hack/Makefile
- e2e/README.md
- hack/build-ttl.sh
- kurl_proxy/Makefile
- migrations/build-ttl.sh
Keep build images around for 24 hours instead of 12.
Fixes #
```release-note
NONE
```
NONE
> Keep untagged images for 24 hours instead of 12

- .github/workflows/release.yaml
kgrid tests right now fail because we no longer make nightly releases.  Disabling this until it's fixed.
Fixes #
```release-note
NONE
```
NONE
> Disable kgrid until it's fixed

- web/src/components/modals/ShowLogsModal.jsx
- web/src/components/selection.json
- web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
- web/src/components/troubleshoot/SupportBundleList.tsx
- web/src/components/troubleshoot/SupportBundleRow.tsx
- web/src/scss/components/troubleshoot/GenerateSupportBundle.scss
- web/src/scss/components/troubleshoot/SupportBundleList.scss
- web/src/scss/utilities/prism.scss
- web/src/scss/utilities/utilities.scss
- Update the "generate a support bundle" icon to be an outlined icon. 
- When clicking "generate a support bundle" in SupportBundleList view, it will pop up a modal to generate a new support bundle. 
- Remove "share" icon when support bundle is progress 
- "Generate a support bundle" link will be disabled and its opacity will be turned to .5. 
Modal 
Run with command 
File dropped 
Fixes # https://app.shortcut.com/replicated/story/62536/design-feedback-on-updated-troubleshoot-page
Generate a support bundle
```release-note
A modal will be shown when user clicks on "Generate a support bundle" if they have existing support bundles. 
```
NONE
> Miawong/sc 62536/design feedback on updated troubleshoot page

- e2e/README.md
This PR adds additional details to the e2e README file.
Fixes #
```release-note
NONE
```
> add e2e readme details

- pkg/base/helm_v2.go
- pkg/base/helm_v3.go
- pkg/handlers/config.go
- pkg/kotsadmupstream/upstream.go
- pkg/online/online.go
- pkg/pull/pull.go
- pkg/store/kotsstore/version_store.go
Reverts replicatedhq/kots#3452
> Revert "Allow required values in helm charts"

- pkg/k8sutil/clientset.go
This change is mainly targeted at:
- Make preflights run a lot faster
- Generating support bundles a lot faster
Fixes #
This reduced the amount of time it takes to run preflights in my test app from 45 seconds to < 5 seconds
```release-note
Reduces the time it takes to run preflight checks and generate support bundles at least in half
```
NONE
> Increase client-go k8s config QPS and burst for better performance

- pkg/api/reporting/types/types.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/preflight/preflight.go
- pkg/reporting/app.go
- pkg/reporting/preflight.go
- pkg/reporting/util.go
- pkg/supportbundle/spec.go
- Include preflight checks state and if skipped or not in app data reporting
- Report app info and state when deploying a new version
- Report app info and preflight checks state when preflights complete
Fixes #
```release-note
NONE
```
NONE
> Data reporting improvements

- pkg/kurl/configmap.go
Fixes an issue where the "Cluster Management" tab does not show up in kURL clusters by _not_ caching the decision about whether the cluster is kURL or not.
Fixes [SC-65506](https://app.shortcut.com/replicated/story/65506/cluster-management-tab-does-not-show-up-sometimes)
```release-note
Fixes an issue where the "Cluster Management" tab does not show up in kURL clusters.
```
NONE
> fix: 'Cluster Management' tab does not show up sometimes in kURL clusters

- web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
Noticed that the text when starting a new support bundle generation in the admin console UI has reference to "Sentry Enterprise" which looks to be a test app elsewhere. Suggested some generic alternative text in the pull request.
Fixes #
```release-note
- Fixes an issue where Troubleshoot description used a hard coded application name
```
> Grahamnscp patch 2023

- .github/dependabot.yml
fix a label typo in dependaboy yaml
Fixes #
an issue when dependabot opens a PR and tries to add the label
eg: https://github.com/replicatedhq/kots/pull/3541#issuecomment-1377034361
```release-note
```
NONE
> fix dependabot safe-to-test label

- pkg/filestore/blob_store.go
- pkg/filestore/s3_store.go
- pkg/filestore/store_interface.go
- pkg/handlers/handlers.go
- pkg/handlers/handlers_test.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/handlers/troubleshoot.go
- pkg/store/kotsstore/supportbundle_store.go
- pkg/store/mock/mock.go
- pkg/store/store_interface.go
Adds an API endpoint for deleting support bundles
Fixes #
```release-note
NONE
```
NONE
> Adds an API endpoint for deleting support bundles

- web/src/scss/components/apps/AppVersionHistory.scss
- web/src/scss/index.scss
- web/src/stories/ShowLogsModal.stories.tsx
Run storybook to view the modal 
```release-note
NONE
```
NONE
> Miawong/sc 65991/add show logs modal storybook

- pkg/handlers/handlers.go
- web/src/Root.tsx
- web/src/components/shared/Toast.tsx
- web/src/components/troubleshoot/SupportBundleList.tsx
- web/src/components/troubleshoot/SupportBundleRow.tsx
- web/src/context/ToastContext.tsx
- web/src/scss/components/troubleshoot/SupportBundleList.scss
- web/src/scss/utilities/base.scss
- web/src/stories/Toast.stories.tsx
https://user-images.githubusercontent.com/28071398/212441098-9471fadd-88a4-4be7-bf03-ef4570af72a8.mov
Fixes # [sc-57763] 
Go to troubleshoot and create a support bundle. 
Delete it
```release-note
Adds the ability to delete support bundles. 
```
None
> Miawong/sc 57763/add ability to delete support bundles from admin console

- web/src/components/modals/SnapshotDifferencesModal.tsx
- web/src/stories/SnapshotDifferencesModal.stories.tsx
check storybook :) 
```release-note
NONE
```
NONE
> Miawong/sc 65991/add snapshot differences modal storybook

- web/src/stories/ShowDetailsModal.stories.tsx
> add showdetailsmodal to storybook

- web/.storybook/main.js
- web/src/components/modals/DeleteSnapshotModal.jsx
- web/src/components/modals/DeleteSnapshotModal.tsx
- web/src/stories/DeleteSnapshotModal.stories.tsx
- web/src/types/index.ts
> Miawong/sc 65991/deletesnapshotmodal storybook

- web/.storybook/main.js
- web/src/components/modals/AutomaticUpdatesModal.tsx
- web/src/stories/AutomaticUpdatesModal.stories.tsx
> Miawong/sc 65991/automatic updates modal

- web/src/stories/DeleteRedactorModal.stories.tsx
- adds deleteredactormodal to storybook 
Fixes #
```release-note
none
```
NONE
> add delete redactor modal story

- web/src/stories/ChangePasswordModal.stories.tsx
> Miawong/sc 65991/changepasswordmodal to storybook 

- web/src/features/PreflightChecks/api/getPreflightResult.tsx
- web/src/features/PreflightChecks/types.ts
- web/webpack.config.js
- adds initial refactored hook for preflights component. This will enable us to migrate the preflights components to functional components so we can use modern react features like hooks. 
- Expect some changes in subsequent PRs as I integrate this into the components. Feedback on the naming conventions etc are appreciated. 
Fixes #
https://app.shortcut.com/replicated/story/68110/create-hook-for-preflight-endpoints
```release-note
none
```
none
> add start of preflights hook

- .github/actions/generate-support-bundle/action.yml
- .github/actions/kots-e2e/action.yml
Sometimes debugging failed tests require looking into cluster resources and other namespaces (e.g. velero). This PR expands support bundle collection to include that.
Fixes #
```release-note
NONE
```
NONE
> Don't limit support bundles in e2e tests to a single namespace

- pkg/api/downstream/types/types.go
- pkg/apiserver/server.go
- pkg/operator/operator.go
- pkg/operator/operator_test.go
- pkg/store/kotsstore/downstream_store.go
- pkg/store/kotsstore/version_store.go
- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/shared/NavBar.jsx
- web/src/components/troubleshoot/GenerateSupportBundle.jsx
- web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
- web/src/features/Dashboard/components/Dashboard.tsx
- web/src/features/Dashboard/components/DashboardVersionCard.tsx
- web/src/features/Gitops/utils.js
- web/src/types/index.ts
Uses app's currentVersion icon URI to display app icons
- when a new version is deployed, deployed version's application.yaml is saved in kotsadm-application-metadata configmap
Fixes #
[SC-57832](https://app.shortcut.com/replicated/story/57832).
```release-note
fix a bug where app icon was shown from latest version instead of current version
```
NONE
> use currentVersion iconURI to display app icons

- web/src/components/snapshots/SnapshotStorageDestination.tsx
Fixes # https://app.shortcut.com/replicated/story/68795/snapshot-settings-check-out-our-docs-link-points-to-invalid-url
```release-note
NONE
```
NONE
> Miawong/sc 68795/fix snapshot settings docs link

- web/src/features/Dashboard/api/getUpdateDownloadStatus.ts
- web/src/features/Dashboard/components/Dashboard.tsx
Fixes # https://app.shortcut.com/replicated/story/68585/refactor-dashboard-tsx-to-use-custom-hooks
```release-note
NONE
```
NONE
> Miawong/sc 68585/Refactor Dashboard.tsx to use useUpdateDownloadStatus hook 

- web/src/components/apps/AppVersionHistory.tsx
- sort large state and props in app version history 
Fixes #
https://app.shortcut.com/replicated/story/68569/refactor-version-history-api-calls-to-use-hooks
```release-note
none
```
none
> sort props and state

- pkg/base/replicated.go
- pkg/kotsutil/kots.go
in some cases, KOTS silently ignores errors in decoding and rendering HelmChart custom resources. this PR improves that by surfacing those errors to the customer for better self-troubleshooting.
Fixes #
```release-note
Fixes an issue where errors related to parsing and rendering HelmChart custom resources are silently ignored.
```
NONE
> Surface HelmChart custom resource decoding and rendering errors better

- pkg/snapshot/velero.go
Fixes a few inaccurate error message related to listing/deleting velero/node-agent pods
Fixes #
```release-note
NONE
```
NONE
> Fix a few velero/node-agent related error messages

- web/src/components/config_render/ConfigUtil.js
before
after
Fixes # https://app.shortcut.com/replicated/story/69513/config-item-affix-property-is-not-working-as-expected
you can reproduce by using this config 
https://replicated.slack.com/archives/C02TQTV9G2V/p1676473576402369?thread_ts=1676473560.582609&cid=C02TQTV9G2V
```release-note
Fixes a bug that will display config item correctly when using the affix property. 
```
NONE
> fix config item affix logic

- web/src/components/modals/SnapshotDifferencesModal.tsx
- web/src/components/snapshots/AppSnapshots.jsx
Fixes # https://app.shortcut.com/replicated/story/69743/update-application-metadata-language-from-partial-snapshots-ui
```release-note
NONE
```
NONE
> remove language about app metadata

- pkg/supportbundle/spec.go
- In the [ParseSupportBundleFromDoc](https://github.com/replicatedhq/troubleshoot/blob/a523551da95cf8ba9fda77d344a278087f08f7e9/pkg/supportbundle/load.go#L103) function, it will call [ParseSupportBundle](https://github.com/replicatedhq/troubleshoot/blob/777224f4c3da53e5e88103cca7869a94ea0d06ed/pkg/supportbundle/load.go#L40) to down support bundle spec from URI field if it exists.
- other spec fields e.g URI will be rendered without passing to [addDiscoveredSpecs](https://github.com/replicatedhq/kots/blob/337f77f11bb2b112c7ed18ca9395a7a9ed53dd8d/pkg/supportbundle/spec.go#L267) function
- if there is one or multiple support bundle contains URL as a upstream spec, it will bring duplicated collectors and analyzers.
- add deduplicatedCollectors and deduplicatedAnalyzers to remove those …
> feat(support-bundle): remove duplicated collectors and analyzers

- web/package.json
- web/yarn.lock
- added 4 years ago but i don't see any import or require statements for it 
- I don't think this is used and it's caused an upgrade error here: https://github.com/replicatedhq/kots/security/dependabot/180
Fixes #
```release-note
none
```
none
> remove babel register

- web/package.json
- web/yarn.lock
-remove favicons from this: https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- I don't see this dependency being used. was added a few months ago for an unrelated change 
- causing this alert: https://github.com/replicatedhq/kots/security/dependabot/126
Fixes #
```release-note
none
```
none
> remove favicon utils

- web/package.json
- web/webpack.config.dist.js
- web/yarn.lock
- for https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- this bugsnag plugin was added 4 years ago but looks like it's not actually used 
- this bugsnag plugin hasn't been updated in a couple of years
- has a dependency that's causing a [security warning](https://github.com/replicatedhq/kots/security/dependabot/32)
Fixes #
```release-note
none
```
none
> remove bugsnag

- web/package.json
- web/yarn.lock
- removes jsonwebtoken for this: https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- added 4 years ago but isn't imported or used by any script
- causing this warning: https://github.com/replicatedhq/kots/security/dependabot/181
Fixes #
```release-note
none
```
none
> remove jsonwebtoken

- web/package.json
- web/yarn.lock
- for ticket: https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- attempting to fix this: https://github.com/replicatedhq/kots/security/dependabot/139
Fixes #
```release-note
none
```
none
> force trim-newlines to latest

- .github/dependabot.yml
- for https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- turns on dependabot scanning for all npm ecosystem concerns not just security related ones 
Fixes #
```release-note
none
```
none
> turn on dependabot for npm

- web/src/features/Dashboard/api/getAppDownstream.ts
- web/src/features/Dashboard/components/Dashboard.tsx
useAppDownstream hook
Old PR https://github.com/replicatedhq/kots/pull/3617
There was a PR for this 2 weeks ago, merging it into this branch caused a lot of headaches. so recreated a new PR that includes cleartimeout.
Fixes # https://app.shortcut.com/replicated/story/68585/refactor-dashboard-tsx-to-use-custom-hooks
```release-note
NONE
```
NONE
> refactor fetchappdownstream to use hook

- web/package.json
- web/yarn.lock
- fixes an issue that is blocking dev environment work 
Fixes #
```release-note
none
```
none
> fix missing dependency

- .github/workflows/build-test.yaml
Fixes a shell syntax error in the validate-registry-check test
Fixes #
```release-note
NONE
```
NONE
> Fix shell syntax error in validate-registry-check test

- web/package.json
- web/yarn.lock
- for ticket: https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- attempt to resolve: https://github.com/replicatedhq/kots/security/dependabot/137
Fixes # 
```release-note
none
```
none
> force moment-timezone to latest patch

- .github/workflows/alpha.yaml
Adds a security scan job for the `minio/mc` image shipped with KOTS
Fixes #
```release-note
```
> add scan for minio client

- .github/workflows/release.yaml
Adds the `type::security` label to the automated image dependency PR that runs in the release workflow
Fixes #
```release-note
```
> add security label to automated image deps pr

- .github/workflows/build-test.yaml
- pkg/handlers/app.go
Users shouldn't pass the --force flag when they already specify --undeploy
Fixes #
```release-note
NONE
```
NONE
> force removing app is implied when --undeploy is set

- .github/workflows/update-kubectl.yaml
Fixes #
```release-note
NONE
```
NONE
> add chore label to update-kubectl workflow

- pkg/image/builder.go
Improves the performance of creating application versions by running private image checks concurrently.
Fixes #
```release-note
Improves the performance of creating application versions by running private image checks concurrently.
```
NONE
> Run private image checks concurrently to improve performance

- .github/actions/generate-support-bundle/action.yml
- .github/actions/kots-e2e/action.yml
- .github/actions/kurl-addon-kots-generate/action.yml
- .github/workflows/actionlint.yaml
- .github/workflows/alpha.yaml
- .github/workflows/build-test.yaml
- .github/workflows/e2e-infra-cleanup.yaml
- .github/workflows/e2e-workspace-cleanup.yaml
- .github/workflows/kurl-addon-kots-test.yaml
- .github/workflows/metrics.yml
- .github/workflows/regression.yaml
- .github/workflows/release.yaml
- .github/workflows/tag-helm-chart.yaml
- .github/workflows/update-kubectl.yaml
* Add `actionlint` for static analysis of GitHub Actions workflows
* cleanup linting issues
* update actions to minimum node16 versions
* clean up deprecated usages of certain github commands
Be careful of unintended behavior changes in shell scripts, especially where quotes were added to satisfy shellcheck. I caught one error I had made in the instances where we were populating environment variables from the .image.env, and I'm going to go over it again with a fine-toothed comb, but there may be others.
```release-note
NONE
```
NONE
> add actionlint and clean up deprecations [sc-70302]

- web/src/scss/components/apps/AppVersionHistory.scss
- web/yarn.lock
- checkbox is using hard coded primary default color value. Changed it to use the css variable. 
```release-note
none 
```
none
> switch checkbox to using primary color css variable 

- web/src/scss/components/forms/input.scss
- web/src/scss/components/forms/textarea.scss
- web/src/scss/components/shared/NavBar.scss
- web/src/scss/components/snapshots/AppSnapshots.scss
- web/src/scss/components/watches/WatchDetailPage.scss
- web/src/scss/utilities/colors.scss
- web/src/scss/utilities/forms.scss
- web/src/scss/variables.scss
- accent color is the same as primary color. rather than giving the vendors another override, we're just getting rid of accent color
```release-note
none
```
none
> remove accent color

- web/src/scss/components/troubleshoot/FileTree.scss
- web/src/scss/variables.scss
- makes the file tree background and selected colores theme-able 
Theme with the following style.css:
```
:root {
--card-color: #e9f3ff;
--file-tree-color: #a3bbb6;
--file-tree-highlight-color: #93a9a4;
--icon-color: #000000;
--link-color: #93a9a4;
--primary-color: #a3bbb6;
--primary-disabled-color: #bfc8d5;
--primary-hover-color: #93a9a4;
--secondary-hover-color: #e9f3ff;
--subnav-color: #e9f3ff; 
--tooltip-color: #5b5b5b;
}
```
with and without theming: 
```release-note
none
```
none
> make file tree themeable

- web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
- make the snapshot card use the themeable colors 
```release-note
none
```
none
> fix snapshot card styling

- .github/workflows/build-test.yaml
- web/Makefile
* Breaks out the multi-step `build` jobs in the PR pipeline to maximize caching and parallelization, to improve overall pipeline execution time
* Build web on Node 18 (LTS)
Fixes #
```release-note
NONE
```
NONE
> break out build jobs [sc-70669]

- kurl_proxy/cmd/main.go
- kurl_proxy/cmd/main_test.go
This PR adds Content-Security-Policy and X-Frame-Options HTTP headers to the responses returned by kurl_proxy to mitigate the Clickjacking security vulnerability.
Fixes [SC-70585](https://app.shortcut.com/replicated/story/70585/kots-clickjacking-security-vulnerability)
Before:
```
$ curl -skI https://localhost:8800/
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Headers: content-type, origin, accept, authorization
Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: content-disposition
Content-Length: 373
Content-Type: text/html; charset=utf-8
Date: Wed, 08 Mar 2023 20:01:22 GMT
Etag: W/"175-fQHLMKuqupgvU3/RmUE4/iDMUuQ"
Vary: Accept-Encoding
X-Powered-By: Expres
```
After:
```
$ curl -skI …
```
> add csp headers to kurl_proxy

- web/src/components/shared/Loader.tsx
- current eslint settings don't lint js files 
Fixes # https://app.shortcut.com/replicated/story/60124/investigate-why-eslint-is-not-catching-components-that-are-missing-import-statements
```release-note
none
```
none
> add typechecking to Loader

- web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
- web/src/scss/utilities/buttons.scss
- make rollback button theme-able
```release-note
```
> make rollback button themeable

- web/src/Root.tsx
- web/src/components/Head/KotsPageTitle.tsx
- web/src/components/clusters/GitOps.tsx
- add typechecking to gitopsjsx
Fixes # https://app.shortcut.com/replicated/story/60124/investigate-why-eslint-is-not-catching-components-that-are-missing-import-statements
```release-note
none
```
none
> add typechecking to gitopsjsx

- web/src/components/shared/SideBar/SideBar.tsx
- add typechecking to sidebarjsx
Fixes # https://app.shortcut.com/replicated/story/60124/investigate-why-eslint-is-not-catching-components-that-are-missing-import-statements
```release-note
none
```
none
> add typechecking to sidebarjsx

- web/src/constants/timers.js
- bump slowloading threshold up to 2 minutes
- this is a quick fix. I think we need to reevaluate how we show these loaders for polling behavior i.e. not show a full page loader for these indicators 
Fixes # https://app.shortcut.com/replicated/story/72489/admin-console-keeps-reloading-on-slow-internet-connectivity
```release-note
kots/web: increase time to display slow loading indicator to 2 minutes 
```
none
> bump load loader timeout to 2 minutes

- pkg/base/helm.go
- pkg/base/helm_functions.go
- pkg/handlers/helm.go
- pkg/k8sutil/portforward.go
- web/webcontent.go
run go fmt ./... to fix format linters
Fixes #
```release-note
NONE
```
NONE
> chore: go fmt ./... 

- web/src/components/modals/ShowLogsModal.jsx
Wraps 
Fixes SC-54689
Would appreciate any feedback. Especially about automated testing if possible.
```release-note
Wraps the logs displayed in the deploy logs modal to make it more readable without having to scroll horizontally.
```
NONE
> Wrap log output

- pkg/app/types/app.go
Fixes the json tags for the app type for the `createdAt` and the `updatedAt` fields
Fixes #
```release-note
NONE
```
NONE
> Fix json tags for app type

- web/okteto.yml
- fixes dev environment for kots/web in okteto 
Fixes # https://app.shortcut.com/replicated/story/73162/migrate-kots-to-okteto-v2-manifests
```release-note
none
```
none
> install dependencies before running dev server

- web/src/features/Auth/components/SecureAdminConsole.tsx
Fixes # [sc-72049]
```release-note
Update Log in page wording to include admin console
```
NONE
> change wording to include admin console

- pkg/api/reporting/types/types.go
- pkg/gitops/gitops.go
- pkg/gitops/gitops_test.go
- pkg/handlers/gitops.go
- pkg/reporting/app.go
- pkg/reporting/util.go
- web/src/features/Gitops/components/SetupProvider.jsx
report when gitops is enabled/disabled
Fixes # https://app.shortcut.com/replicated/story/55917/report-when-gitops-is-enabled
```release-note
report when gitops is enabled/disabled
```
NONE
> report when gitops is enabled/disabled

- web/src/components/apps/AppDetailPage.tsx
- web/src/types/index.ts
- sorts multi app installs by `createdAt` date 
Fixes # https://app.shortcut.com/replicated/story/50572/multi-app-in-admin-console-the-order-of-the-applications-in-the-nav-bar-on-left-hand-should-be-persistent-and-not-change
```release-note
kots/web: Multi app installs are now sorted by `createdBy` date with the latest install at the top. 
```
none
> Sort multi app nav by createdBy date 

- pkg/kotsadmconfig/validation/config.go
- pkg/kotsadmconfig/validation/config_test.go
- pkg/kotsadmconfig/validation/validator.go
- pkg/kotsadmconfig/validation/validator_test.go
Fixes #
ignore validation when group.when is false
```release-note
NONE
```
NONE
> ignore validation when group.when is false

- deploy/kurl/kotsadm/template/testgrid/k8s-docker.yaml
Modernize kURL testgrid spec. Remove deprecated add-ons.
> chore: modernize kurl testgrid spec

- pkg/handlers/config.go
- pkg/kotsadmconfig/validation/config.go
- pkg/kotsadmconfig/validation/config_test.go
- pkg/kotsadmconfig/validation/validator.go
- pkg/kotsadmconfig/validation/validator_test.go
- web/src/features/AppConfig/components/AppConfig.tsx
- empty required fields should not block when there is a default value 
Fixes #
https://app.shortcut.com/replicated/story/75137/kots-config-validation-failing-when-the-item-is-required-and-has-default-value-and-or-when-hidden
```release-note
- admin console: fixes an an issue where required fields with default values would not be validated 
```
https://github.com/replicatedhq/replicated-docs/pull/1094
> ignore empty required value if there is a default value

- web/src/components/apps/AppVersionHistory.tsx
- web/src/features/App/PreflightIcon.tsx
- web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
- web/src/features/VersionDiff/VersionDiff.tsx
- web/src/scss/components/apps/AppVersionHistory.scss
- Removed extra preflight icon that was being displayed.
- Improve content layout for sequence number for readability.
- Fixed view diff behavior to improve content layout, and added a back button to prevent user from getting stuck.
- Truncated long version label and added a tooltip for better user experience.
**Before**
**After**
Hover on tooltip to see full name
Loading View Diff, has back button to return to Version history 
Fixes # https://app.shortcut.com/replicated/story/71608/ui-feedback-from-installing-schrodinger-s-app
```release-note
UI Improvements made on version history page such as truncating long version label, removal of unnecessary preflight icon, and improve content layout.
```
NONE
> Miawong/sc 71608/UI feedback from installing schrodinger s

- kotskinds/apis/kots/v1beta1/license_types.go
- kotskinds/config/crds/kots.io_licenses.yaml
- kotskinds/schemas/license-kots-v1beta1.json
- pkg/license/signature.go
Adds the customer email to the license type.
Fixes #
```release-note
NONE
```
NONE
> Add customer email address to the license

- web/src/features/AppConfig/components/AppConfig.tsx
- cleanup debugging and comments 
Fixes # https://app.shortcut.com/replicated/story/75670/errors-when-saving-config-are-not-propagated-to-ui
```release-note
none 
```
> cleanup comment and console logs

- .github/workflows/build-test.yaml
> add validate-remove-app-with-ordered-kind test

- web/src/components/apps/AppLicense.tsx
- web/src/css/icon.css
- web/src/features/Dashboard/components/DashboardLicenseCard.tsx
- web/src/scss/components/apps/AppLicense.scss
- web/src/scss/components/shared/NavBar.scss
- web/src/utilities/utilities.js
- Add padding to the community edition banner.
- Ensure consistency of color across the community edition banner in the Navbar, License page, and DashboardLicenseCard. (Improves contrast of the banner in License page and Dashboard) 
- Fix icon color for each license type 
- Refactor icon type and className 
***********BEFORE***********
Navbar
Dashboard
License Page
************AFTER************
Navbar
Dashboard
License Page
Fixes # https://app.shortcut.com/replicated/story/75508/improve-padding-for-community-edition-banner
```release-note
Improves the Community Edition Banner visual appearance when a user is using a community license. 
```
NONE
> Miawong/sc 75508/improve padding for community edition banner

- web/src/components/apps/AppLicense.tsx
- web/src/components/config_render/ConfigItemTitle.jsx
- web/src/components/troubleshoot/GenerateSupportBundle.jsx
- web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
- web/src/features/AppConfig/components/AppConfig.tsx
- web/src/features/Auth/components/SecureAdminConsole.tsx
- web/src/features/Dashboard/components/Dashboard.tsx
- web/src/features/Dashboard/components/DashboardLicenseCard.tsx
- web/src/scss/components/watches/WatchConfig.scss
- web/src/scss/utilities/utilities.scss
- web/src/utilities/utilities.js
***********BEFORE***********
**********AFTER**********
Fixes # https://app.shortcut.com/replicated/story/75115/improve-layout-for-long-strings
```release-note
Enhances formatting to accommodate lengthy strings.
```
> Miawong/sc 75115/improve layout for long strings

- pkg/kotsutil/kots.go
Adds a runtime check that both the v1beta1 and v1beta2 HelmChart structs implement the HelmChartInterface
Fixes #
```release-note
NONE
```
NONE
> add runtime check for HelmChartInterface

- .github/workflows/build-test.yaml
Adds test coverage for k3s 1.27.1 and removes test coverage for EOL k3s 1.23
Fixes #
```release-note
NONE
```
NONE
> Add k3s 1.27.1 to PR tests

- pkg/operator/client/deploy.go
- pkg/operator/client/deploy_test.go
Fixes an issue where Helm charts deployed using the native Helm installation method were uninstalled then reinstalled when the chart version changes / is updated.
Fixes #
```release-note
Fixes an issue where Helm charts deployed using the native Helm installation method were uninstalled then reinstalled when the chart version changes / is updated.
```
NONE
> don't uninstall and reinstall helm charts when the version changes

- .github/workflows/build-test.yaml
fix test `validate-kots-helm-release-secret-migration`
`validate-kots-helm-release-secret-migration` test fails randomly as the helm upgrade is not completed yet and test checks if the helm release secret exists
Fixes # no-sc
```release-note
NONE
```
NONE
> fix flaky test `validate-kots-helm-release-secret-migration`

- web/src/features/Auth/components/SecureAdminConsole.tsx
- web/src/utilities/utilities.js
When the appName is long: 
Fixes # https://app.shortcut.com/replicated/story/78583/log-in-screen-text-is-too-small-now
```release-note
```
> Miawong/sc 78583/fix log in font size 

- pkg/base/base.go
- pkg/base/replicated.go
- pkg/kotsutil/kots.go
- pkg/kotsutil/kots_test.go
Surfaces errors when failing to parse KOTS kinds.
Fixes #
```release-note
Fixes an issue where parsing invalid KOTS kinds failed silently.
```
NONE
> Surface errors when failing to parse KOTS kinds.

- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
This PR changes the on-PR tests to leverage the compatibility matrix instead of our custom `action-k3s` GH action.
Mostly uses `k3s`, with `kind` where necessary to cover k8s 1.27.  Picked three of our tests use EKS 1.27: `smoke-test`, `minimal-rbac`, and `backup-and-restore`.
https://app.shortcut.com/replicated/story/82931/make-kots-ci-use-compatibility-matrix
```release-note
NONE
```
NONE
> run tests on c11y matrix

- .github/actions/kots-e2e/action.yml
- .github/workflows/build-test.yaml
Always cleans up c11y clusters because we generate support bundles that help with troubleshooting issues.
Fixes #
```release-note
NONE
```
NONE
> Always cleanup c11y clusters because we generate support bundles

- .github/workflows/build-test.yaml
- deploy/Dockerfile
- deploy/okteto/okteto-v2.Dockerfile
- deploy/okteto/okteto.Dockerfile
- hack/dev/skaffold.Dockerfile
Adds support for Kubernetes 1.28
Fixes [SC-86605](https://app.shortcut.com/replicated/story/86605/kots-should-support-k8s-1-28)
```release-note
NONE
```
https://github.com/replicatedhq/replicated-docs/pull/1421
> Support Kubernetes 1.28

- pkg/handlers/handlers.go
- pkg/handlers/helmvm_node_join_command.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
> make a friendly helmvm node join command

- migrations/tables/k0s_tokens.yaml
- pkg/handlers/handlers.go
- pkg/handlers/helmvm_node_join_command.go
- pkg/handlers/interface.go
- pkg/handlers/mock/mock.go
- pkg/helmvm/node_join.go
- pkg/helmvm/util.go
- pkg/store/kotsstore/k0s_store.go
> shorter embedded-cluster join commands

- web/src/Root.tsx
- web/src/components/apps/HelmVMClusterManagement.tsx
- web/src/components/apps/HelmVMViewNode.jsx
> fix routing

- pkg/store/kotsstore/k0s_store.go
> shorter join tokens

- pkg/helmvm/helmvm_node.go
- pkg/helmvm/helmvm_nodes.go
> node usage metrics not being collected is not a fatal error

- pkg/helmvm/helmvm_node.go
- pkg/helmvm/types/types.go
> format pod CPU and memory usage before returning

- web/src/Root.tsx
- web/src/components/apps/AppDetailPage.tsx
- web/src/components/apps/HelmVMClusterManagement.tsx
- web/src/components/apps/HelmVMViewNode.jsx
- web/src/components/shared/CodeSnippet.jsx
> fixes: clipboard, redirect, columns styling/formatting

- pkg/helmvm/helmvm_node.go
> determine node roles based on their labels

- pkg/helmvm/node_join.go
> cleanup the k0s join token creation pod after completion

- web/src/components/apps/AppDetailPage.tsx
- web/src/components/apps/HelmVMClusterManagement.tsx
- web/src/components/apps/HelmVMViewNode.jsx
> fix redirect, add column types

- web/src/components/apps/HelmVMClusterManagement.tsx
> make labels optional

- pkg/helmvm/node_join.go
> remove the --force flag

- pkg/store/types/constants.go
- web/src/Root.tsx
- web/src/components/apps/AppDetailPage.tsx
- web/src/components/apps/HelmVMClusterManagement.tsx
- web/src/components/apps/HelmVMViewNode.jsx
- web/src/components/shared/NavBar.tsx
- web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
- web/src/features/Dashboard/components/DashboardVersionCard.tsx
- web/src/types/index.ts
> update redirect to cluster manage page, comment test data

- pkg/helmvm/helmvm_node.go
- pkg/helmvm/node_join.go
- pkg/helmvm/types/types.go
> node role labels

- pkg/apiserver/server.go
- pkg/handlers/handlers.go
- pkg/handlers/interface.go
- pkg/handlers/metrics.go
- pkg/handlers/middleware.go
- pkg/handlers/mock/mock.go
- pkg/handlers/session.go
> Revert 'Add an endpoint to KOTS where application metrics can be retrieved adhoc'

- pkg/upstream/helm.go
- pkg/upstream/helm_test.go
Don't configure the SDK's user agent as it's not configurable anymore.
Fixes #
```release-note
NONE
```
NONE
> Don't configure the SDK's user agent

- web/src/components/apps/EmbeddedClusterManagement.tsx
> consistently call embedded-cluster controller nodes 'controller'

- .github/dependabot.yml
Reincludes the "dependabot" and PR-type labels on dependabot PRs.
Fixes #
```release-note
```
> Reinclude dependabot PR labels

- .github/workflows/alpha.yaml
- .github/workflows/release.yaml
> release with node 18, which we test with

- .github/workflows/build-test.yaml
Removes reference to old `build-push-kotsadm-image` job
Fixes #
```release-note
```
> remove old build-push-kotsadm-image reference

- .github/workflows/build-test.yaml
Adds `build-kots` to the `needs` for a few workflows that need it.
Fixes #
```release-note
```
> build-kots dependency

- .github/workflows/build-test.yaml
Prevents forks from building/pushing images in the CI workflow.
Fixes #
```release-note
NONE
```
NONE
> Don't allow pushing images on forks

- Makefile
- migrations/tables/instance-report.yaml
- pkg/api/reporting/types/types.go
- pkg/reporting/app.go
- pkg/reporting/app_airgap.go
- pkg/reporting/instance_report.go
- pkg/reporting/report_test.go
- pkg/reporting/util.go
For data analysis purposes, it's helpful to link a particular KOTS and application installation to the embedded cluster that's managing it.
Fixes [SC-95012](https://app.shortcut.com/replicated/story/95012/have-kots-report-the-embedded-cluster-id)
```release-note
NONE
```
NONE
> Report the embedded cluster ID when available

- .github/workflows/build-test.yaml
`gh pr review` accepts either `--approve` or `--comment`, not both. Should use the `--body` flag to specify the body of a review.
Fixes #
```release-note
NONE
```
NONE
> Fix dependabot PR review command

- .github/workflows/image-deps-updater.yaml
This gives the automated PRs manager a chance to review and process it before we're online.
Fixes #
```release-note
NONE
```
NONE
> Run image deps updater at 9am UTC

- pkg/handlers/embedded_cluster_node_join_command.go
When joining a new node to the cluster (embedded-cluster) we need to know what are the configuration overrides in use. This PR makes the endpoint that returns the token to also return the active overrides (both the ones that were embedded in the cluster as the ones that were used at install time).
> feat: provide overrides for embedded cluster join

- .github/dependabot.yml
- .github/workflows/automated-prs-manager.yaml
Creates a single Dependabot PR per project / package manager in order to reduce CI overhead.
Fixes #
```release-note
NONE
```
NONE
> Create a single dependabot PR per package manager / project

- web/Makefile
reverts commit a225628e, which seems to have been inadvertently pushed to main despite branch protection rules
Fixes #
```release-note
```
> revert network-timeout for web deps

- .github/workflows/automated-prs-manager.yaml
- .github/workflows/image-deps-updater.yaml
PRs merged by the `GITHUB_TOKEN` user do not trigger the main workflows on merge. Github suggests using a PAT in order to achieve that: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
Also, use the `REPLICATED_GH_PAT` instead of `NIGHTLY_GH_PAT` or `GH_PAT` as the latter ones belong to the user who creates some of the automated PRs the manager will need to approve and merge, and users cannot approve and merge their own PRs.
Fixes #
```release-note
NONE
```
NONE
> Use REPLICATED_GH_PAT for the Automated PRs Manager workflow

- web/src/utilities/utilities.js
Add new installation statuses for the embedded-cluster operator
Fixes #
```release-note
Add new installation statuses for the embedded-cluster operator
```
> chore: add new ec operator statuses

- cmd/kots/cli/admin-console-upgrade.go
- pkg/handlers/deploy.go
- pkg/handlers/troubleshoot.go
- pkg/kotsadm/push_images.go
- pkg/version/metrics_test.go
unnecessary use of fmt.Sprintf
Fixes #
```release-note
NONE
```
> chore: unnecessary use of fmt.Sprintf

- pkg/version/metrics.go
replace loop with queries = append(queries, graph.Queries...)
Fixes #
```release-note
NONE
```
> chore: replace loop with queries = append(queries, graph.Queries...)

- web/src/utilities/utilities.js
> fix AddonsInstalling constant

- kustomize/overlays/kotsstore/minio/statefulset.yaml
> fix skaffold minio image

- go.mod
- go.sum
Bumps `github.com/replicatedhq/kotskinds` for the removal of `kubectlVersion` and `kustomizeVersion` from the Application custom resource.
https://app.shortcut.com/replicated/story/94079/remove-kubectlversion-and-kustomizeversion
```release-note
```
> bump github.com/replicatedhq/kotskinds

- .github/actions/cmx-versions/dist/index.js
- .github/actions/cmx-versions/index.js
- .github/workflows/build-test.yaml
> ci: use openshift 4.14

- pkg/embeddedcluster/node_join.go
> do not taint controller nodes joining embedded-cluster clusters

- pkg/embeddedcluster/node_join.go
> use non-node join command for embedded-cluster

- web/src/components/apps/AppDetailPage.tsx
- web/src/features/Dashboard/components/Dashboard.tsx
- web/src/features/Dashboard/components/DashboardLicenseCard.tsx
Hides / disables monitoring graphs for embedded clusters.
Fixes [SC-97672](https://app.shortcut.com/replicated/story/97672)
```release-note
NONE
```
NONE
> Hide / disable monitoring graphs for embedded clusters

- .github/workflows/alpha.yaml
Prints the scan reports generated on merge for easier troubleshooting.
Fixes #
```release-note
NONE
```
NONE
> Print scan reports

- cmd/kots/cli/install.go
- pkg/handlers/airgap.go
- pkg/handlers/app.go
- pkg/handlers/license.go
- pkg/kotsadmsnapshot/backup.go
- pkg/kotsutil/embedded.go
- pkg/kotsutil/embedded_test.go
- pkg/registry/images.go
- pkg/registry/registry.go
Automatically detects and uses the registry that comes with embedded clusters (similar to the kURL registry).
Fixes [SC-101172](https://app.shortcut.com/replicated/story/101172)
```release-note
NONE
```
NONE
> Add support for embedded cluster registry

- go.mod
- go.sum
- pkg/embeddedcluster/util.go
To prevent this field from being dropped on upgrades, kots needs to know about it
Fixes #
```release-note
```
> update embedded-cluster-kinds to include a new BinaryName field

- pkg/handlers/embedded_cluster_node_join_command.go
In order for airgap nodes to pull images, they need to list the internal registry as 'yes this is OK to pull from without a valid cert', and in order to do that they need the registry address.
Fixes #
```release-note
```
> include the airgap registry cluster IP in the node join response

- go.mod
- go.sum
Updates troubleshoot to v0.88.0 to resolve CVE-2024-3817
Fixes #
```release-note
Updates images to resolves CVE-2024-3817 with critical severity.
```
NONE
> Update troubleshoot to v0.88.0 to resolve CVE-2024-3817

- deploy/okteto/okteto-v2.Dockerfile
- deploy/okteto/okteto.Dockerfile
- kurl_proxy/okteto.Dockerfile
on-merge CI is failing due to failing image builds, which uses the okteto images: https://github.com/replicatedhq/kots/actions/runs/8909498323/job/24466960102
Fixes #
```release-note
```
> update okteto golang version

- pkg/embeddedcluster/util.go
When we restore, creation timestamps are very nearly random - and so we can't rely on those orders being correct.
Fixes #
```release-note
```
> sort installations by name, not creation timestamp

- pkg/kotsadmsnapshot/backup.go
This includes the App semver and (when relevant) the EC version of the cluster in the snapshot annotations.
This will allow us to ensure we are using the right app and EC version when restoring, and provide better UI to the user.
Fixes #
```release-note
```
> include app and embedded cluster version as backup annotation

- Makefile
- go.mod
- go.sum
Update troubleshoot to a version which reverts a regression
```release-note
NONE
```
> chore: Update troubleshoot to a version with a regression fix

- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/backup_test.go
> add backup annotations for air gap specific embedded cluster infra

- pkg/kotsadmsnapshot/backup.go
> annotate backups with airgap status

- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/types/types.go
- web/src/components/snapshots/SnapshotDetails.jsx
- web/src/stories/ShowAllModal.stories.tsx
Currently, the snapshot page looks like this:
It is very hard to tell what volumes were actually backed up here - those names are of the task that backed them up, not of what was backed up.
So, now we show the pod namespace, pod name, and volume name:
Fixes #
```release-note
```
> display the namespace, podname and volumename of snapshotted volumes

- .github/actions/build-custom-image-with-apko/action.yml
- .github/actions/build-dep-image-with-apko/action.yml
Removes the `apko-image` override from the Chainguard image build process.
Fixes #
```release-note
```
> remove apko-image input for chainguard action

- .github/actions/copy-assets/Dockerfile
- kurl_proxy/skaffold.Dockerfile
Updates remaining base images for the dev env to golang 1.22
Fixes #
```release-note
NONE
```
NONE
> Use golang 1.22 to fix dev env

- web/src/components/snapshots/SnapshotStorageDestination.tsx
https://app.shortcut.com/replicated/story/105248/various-quick-dr-fixes
This PR renames "Path" to "Prefix" for the following object storage snapshot destinations:
* AWS
* GCP
* Azure
* Other-S3
Fixes #
```release-note
```
> rename path to prefix for object store snapshot destinations

- web/src/Root.tsx
- web/src/components/troubleshoot/GenerateSupportBundle.jsx
- web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
- web/src/components/troubleshoot/SupportBundleList.tsx
https://app.shortcut.com/replicated/story/104120/remove-instructions-on-generating-a-bundle-from-the-cli
This PR hides the "click here" to generate a support bundle via CLI command and the upload bundle dropzone for Embedded Cluster. 
Fixes #
```release-note
Hide generate support bundle command for embedded cluster
```
> hide generate support bundle cli command for embedded cluster

- pkg/kotsadm/types/constants.go
- pkg/kotsadm/types/constants_test.go
Includes the disaster recovery chart label for dynamic resources
Fixes #
```release-note
* Various updates to enable high availability support for embedded cluster.
```
NONE
> Include the disaster recovery chart label for dynamic resources

- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/backup_test.go
> backup seaweedfs label and namespace in disaster recovery

- pkg/kotsadmsnapshot/backup.go
Adds an HA annotation to embedded cluster backups.
Fixes #
```release-note
NONE
```
NONE
> Add HA annotation to embedded cluster backups

- pkg/handlers/embedded_cluster_node_join_command.go
- pkg/util/util.go
Fixes [SC 97879](https://app.shortcut.com/replicated/story/97879/support-proxy-installations)
```release-note
```
> expose proxy for embedded cluster

- pkg/upgradeservice/handlers/config.go
- pkg/upgradeservice/handlers/handlers.go
- pkg/upgradeservice/handlers/interface.go
- web/src/components/AppConfigRenderer.jsx
- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/config_render/ConfigFileInput.jsx
- web/src/components/config_render/ConfigGroup.jsx
- web/src/components/config_render/ConfigGroups.jsx
- web/src/components/config_render/ConfigRender.jsx
- web/src/components/upgrade_service/AppConfig.tsx
- web/src/features/AppConfig/components/AppConfig.tsx
This PR implements the `/config/{filename}/download`  endpoint for the upgrade service to support downloading files from the base configuration.
https://app.shortcut.com/replicated/story/105494/upgrade-service-api-side-of-the-config-page-in-the-deployment-wizard
```release-note
```
> download config file

- pkg/upgradeservice/handlers/config.go
- pkg/upgradeservice/handlers/preflight.go
- pkg/upgradeservice/preflight/preflight.go
- pkg/upgradeservice/reporting/reporting.go
This PR addresses a TODO for airgap reporting when preflights are run after saving config or re-running preflights.
Fixes #
```release-note
```
> upgrade service airgap preflight reporting

- .github/workflows/release.yaml
Adds the necessary permissions required to create a release. This seems to be a new requirement by github.
Fixes #
```release-note
NONE
```
NONE
> Fix release permissions

- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/upgrade_service/AppConfig.tsx
- web/src/components/upgrade_service/hooks/getPreflightResult.tsx
do not run preflight when there are results already add loading state to config next button
better ui for available versions errors
https://app.shortcut.com/replicated/story/105489/ui-show-deployment-wizard-when-user-chooses-to-deploy-an-available-version
Fixes # [sc-105489] 
```release-note
```
> EC upgrade: close modal bug, preflight polling issue, error message for available updates 

- web/src/components/apps/AppVersionHistory.tsx
- web/src/types/index.ts
Show "required" tag, release notes, and non deployable cause.
> UI improvements to  available updates

- web/src/components/apps/AppVersionHistory.tsx
> Add released at timestamp

- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/upgrade_service/ConfirmAndDeploy.tsx
- web/src/components/upgrade_service/PreflightChecks.tsx
https://app.shortcut.com/replicated/story/105489/ui-show-deployment-wizard-when-user-chooses-to-deploy-an-available-version
- loading state for start upgrade service 
- minor UI polish 
- test strict preflight check 
- test isEmbeddedCluster check
- refactor rendering of Available updates 
https://www.loom.com/share/8fecf4ecb76740c9a784a956ca66d34c
Fixes # [sc-105489] 
```release-note
```
> EC upgrades UI: loading state for start upgrade service & minor UI polish

- pkg/kotsadmsnapshot/backup.go
This includes the EC network configuration as an annotation on backups, allowing us to ensure it matches when being restored.
Fixes #
```release-note
NONE
```
> include pod and service CIDRs as annotations on embedded cluster snapshots

- pkg/updatechecker/updatechecker.go
> do not run automatic update checks on EC

- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/apps/AvailableUpdatesComponent.tsx
- web/src/components/modals/UpgradeServiceModal.tsx
- web/src/components/upgrade_service/ConfirmAndDeploy.tsx
- web/src/components/upgrade_service/PreflightChecks.tsx
- adds loading state for iframe loading 
- attempt to fix the black screen when iframe is loading 
- disable preparing... and deploying... buttons 
- improve preflight in progress height 
https://www.loom.com/share/8ec46c53c3284c5fbec22b168338d526
https://www.loom.com/share/03ff8d102d984717b541df39abdd8501
Fixes # [sc-105489]
```release-note
```
> EC upgrade UI: Iframe loading state, disable Preparing and Deploying buttons

- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/modals/UpgradeServiceModal.tsx
- web/src/components/shared/modals/SkipPreflightsModal.tsx
- web/src/components/upgrade_service/ConfirmAndDeploy.tsx
- web/src/components/upgrade_service/PreflightChecks.tsx
- web/src/components/upgrade_service/StepIndicator.tsx
- web/src/components/upgrade_service/UpgradeServiceContext.tsx
- add KOTS version to upgrade wizard for testing purposes (hidden) 
- fix ignore preflights workflow - goes to step 3 (confirm and deploy) 
- clean up unnecessary code 
- improve Step indicator style
Fixes # [sc-105489]
```release-note
```
> EC upgrade UI: add KOTS version to upgrade wizard, fix ignore preflights workflow

- web/src/components/UploadLicenseFile.tsx
- web/src/components/snapshots/SnapshotStorageDestination.tsx
> EC upgrade UI: Fix type errors

- Makefile
- README.md
Removes two extra double quotes in the `all-ttl.s` make command that leads to failures.
Fixes #
```
$ make all-ttl.sh
<-- a few moments later -->
=> => naming to ttl.sh/pandemicsyn/kotsadm-migrations:24h                                                                                                                                                                                                                                0.0s
docker push ttl.sh/pandemicsyn/kotsadm-migrations:24h
The push refers to repository [ttl.sh/pandemicsyn/kotsadm-migrations]
3586bccc9897: Layer already exists 
32d2877c3e06: Layer already exists 
ad0b4a0249b4: Layer already exists 
5b339ad5014c: Layer already exists 
15bb10f9bb3a: Layer already exists 
24h: digest: …
```
> fix: Remove extra double quotes in all-ttl.sh make cmd

- deploy/dex/apko.yaml.tmpl
- deploy/minio/apko.yaml.tmpl
- deploy/rqlite/apko.yaml.tmpl
> Remove unnecessary melange packages

- hack/dev/entrypoint.sh
- hack/dev/skaffoldcache.Dockerfile
- kustomize/base/deployment.yaml
- kustomize/base/service.yaml
- pkg/supportbundle/staticspecs/defaultspec.yaml
- update default support bundle spec with [NodeMetrics](https://troubleshoot.sh/docs/analyze/node-metrics/) analyzer for PVC size check with rqlite+minio
- kustomization update for skaffold dev
Fixes https://app.shortcut.com/replicated/story/107874/pvc-filling-up-need-a-collector-analyzer
Demo: https://www.loom.com/share/97f9ae144f06461390bb55f9f9242740?sid=55ecde5b-b58e-40af-b33a-98a6cb42deb6
```release-note
NONE
```
NONE
> feat: update default support bundle spec with PVC check

- web/src/components/apps/AppVersionHistory.tsx
https://app.shortcut.com/replicated/story/109017/new-air-gap-version-doesn-t-show-without-a-page-refresh
https://www.loom.com/share/cef1599d665043f1ba36bfcf8ccc58a9
Fixes #
```release-note
```
> Fetch available updates after uploading a new airgap version

- web/src/components/UploadLicenseFile.tsx
https://app.shortcut.com/replicated/story/107724/if-you-upload-a-license-you-can-visit-the-upload-license-page-and-are-not-redirected
Fixes #
https://www.loom.com/share/80deea7cc78b4c12b4ab0c855c35e832
```release-note
```
> Direct to app if user tries to upload license 

- e2e/README.md
Updates the e2e readme with some basic playwright docs
```release-note
```
> docs: update e2e readme with pw instructions

- web/src/Root.tsx
- web/src/components/UploadLicenseFile.tsx
- web/src/components/apps/AppDetailPage.tsx
- web/src/components/apps/AppLoading.tsx
Add loading page when waiting for license to install
Redirect users when trying to access /upload-license
https://app.shortcut.com/replicated/story/107723/if-i-visit-the-admin-console-with-trailing-slash-i-am-not-guided-through-the-first-time-install-wizard-thingy#activity-109532
This ended up being hard to make a loom for. The flow of this is now
In EC - we will redirect the user if they land on license upload page
they will be redirected to an intermediate screen /cluster/loading which looks like this
from there it will show the loading message and wait for the license to install then it will either
redirect to dashboard if there is an app with current version or if there's multiple pending versions. 
redirect to /cluster/management if there is a pending version
Fixes #
```release-note …
```
> Embedded Cluster: Improve UX for license installation process

- pkg/supportbundle/staticspecs/defaultspec.yaml
> Revert uri field in default support bundle spec

- pkg/supportbundle/spec.go
- pkg/supportbundle/staticspecs/defaultspec.yaml
- pkg/supportbundle/staticspecs/embed.go
> Add uri field to the default support bundle spec

- web/src/components/apps/AppVersionHistory.tsx
- web/src/components/apps/AvailableUpdatesComponent.tsx
https://app.shortcut.com/replicated/story/108917/give-a-way-to-refresh-newly-available-versions-without-refreshing-the-page
Fixes #
```release-note
Add check for updates button for newly available versions
```
> Add check for updates button for newly available versions

- pkg/supportbundle/staticspecs/defaultspec.yaml
- pkg/supportbundle/staticspecs/kurlspec.yaml
> Update default and kurl support bundles specs

- pkg/operator/client/resource.go
```release-note
PriorityClass resources will now be created first and deleted last.
```
> add PriorityClass to resource creation/deletion order

- go.mod
- go.sum
For the EC dev environment
```release-note
```
> chore(ec): add binaryOverrideUrl and metadataOverrideUrl

- pkg/embeddedcluster/upgrade.go
> preserve ec proxy config on cluster upgrade

- pkg/embeddedcluster/upgrade.go
> automatically copy all non-overridden fields in EC installation object

- README.md
NONE
NONE
```release-note
NONE
```
NONE
> Separate command blocks for dev README

- .github/workflows/release.yaml
- Makefile
Record release with pact broker
NONE
```release-note
```
> Run record-release command for pact

- .gitignore
- dev/scripts/common.sh
- dev/scripts/up-ec.sh
- dev/scripts/up.sh
NONE
```release-note
NONE
```
NONE
> Dev env - always patch even if up & cache yarn packages

- e2e/playwright/tests/change-channel/test.spec.ts
NONE
```release-note
NONE
```
NONE
> Fix change-channel e2e test

- .github/actions/cmx-versions/dist/index.js
- .github/actions/cmx-versions/index.js
Enable OKE testing for kots.
NONE
```release-note
NONE
```
NONE
> Adding OKE 1.30.1

- Makefile
> fix(dev): make build-ttl.sh should respect OS and ARCH

- go.mod
- go.sum
> fix(ec): new kinds to fix registry upgrade failure

- go.mod
- go.sum
- pkg/kotsadmsnapshot/backup.go
in support of https://github.com/replicatedhq/embedded-cluster/pull/1238
```release-note
```
> feat(ec): consolidate data directories

- go.mod
- go.sum
- bump the troubleshoot version 
NONE
```release-note
NONE
```
NONE
> feat(support-bundle): bump troubleshoot version

- kurl_proxy/assets/tls-warning.html
- web/src/Root.tsx
https://app.shortcut.com/replicated/story/115483/error-accessing-the-config-page-after-installing
https://app.shortcut.com/replicated/story/115392
[sc-115483]
None
```release-note
Users can now copy the command when validating certificate. Fixes the error message in Config page.
```
None
> Bug: Copy button for validating cert and FE error on Config page 

- kurl_proxy/assets/tls-warning.html
Accidentally removed the IE image in my last PR.
NONE
```release-note
NONE
```
NONE
> Fix: Use IE TLS warn image too

- pkg/ha/ha_test.go
- pkg/kotsadm/objects/rqlite_objects.go
> use .<namespace>.svc for HA-rqlite

- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/backup_test.go
> feat(ec): dr use label for backup name, change terminology

- pkg/supportbundle/spec.go
- pkg/supportbundle/staticspecs/kurlspec.yaml
> add kubernetes system namespaces to generated support bundles

- cmd/kots/cli/install.go
> improve usage strings for additional annotations, labels, and tolerations flags

- web/src/components/config_render/ConfigGroup.jsx
update link for unsupported config types to point to new documentation page.
```release-note
```
> [chore] update config types link

- .github/workflows/release.yaml
Cosign 1.2 isn't working in our CI process: https://github.com/replicatedhq/kots/actions/runs/12748595887/job/35529920507#step:9:260
```release-note
```
> update cosign to the latest v1 release, v1.13.6

- pkg/embeddedcluster/util_test.go
- pkg/image/airgap_test.go
- pkg/tests/pull/cases/airgap/upstream/userdata/installation.yaml
- pkg/tests/pull/cases/airgap/wantResults/kotsKinds/userdata/installation.yaml
- pkg/tests/pull/cases/airgap/wantResults/upstream/userdata/installation.yaml
- pkg/upstream/fetch.go
Push EC manager binary in airgap bundle to registry
[SC-117404](https://app.shortcut.com/replicated/story/117404)
Yes
```release-note
NONE
```
NONE
> Push EC manager binary in airgap bundle to registry

- pkg/apiserver/server.go
- pkg/handlers/debug.go
- pkg/handlers/deploy_ec2.go
- pkg/handlers/handlers.go
- pkg/handlers/websocket.go
- pkg/plan/app.go
- pkg/plan/cluster.go
- pkg/plan/extensions.go
- pkg/plan/manager.go
- pkg/plan/manager_test.go
- pkg/plan/plan.go
- pkg/websocket/upgrade.go
- pkg/websocket/websocket.go
Unnecessary concurrency. Fix flakey test due to race condition with clients global map.
```release-note
```
> chore: remove unnecessary concurrency

- .github/workflows/build-test.yaml
- .github/workflows/release.yaml
- cmd/kots/cli/backup.go
- cmd/kots/cli/download.go
- cmd/kots/cli/install.go
- cmd/kots/cli/restore.go
- cmd/kots/cli/upload.go
- cmd/kots/cli/upstream-download.go
- cmd/kots/cli/upstream-upgrade.go
- cmd/kots/cli/velero.go
- go.mod
- pkg/print/config.go
- pkg/snapshot/backup.go
- pkg/snapshot/restore.go
- pkg/upstream/upgrade.go
This updates kots to build with go 1.24+. There were crypto/tls changes.
```release-note
```
> update go to 1.24+

- .github/actions/copy-assets/Dockerfile
- dev/dockerfiles/kotsadm/Dockerfile.local
- dev/dockerfiles/kurl-proxy/Dockerfile.local
- dev/scripts/common.sh
- kurl_proxy/go.mod
> chore: update go version to 1.24

- e2e/playwright/regression/shared/config.ts
Increases timeout for updating config
```release-note
NONE
```
NONE
> Updating regression tests config can take more than 5 seconds

- e2e/playwright/regression/@existing-online-install-admin/test.spec.ts
- e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
- e2e/playwright/regression/shared/license.ts
- e2e/playwright/regression/shared/version-history.ts
Moving the "check for updates" step earlier in the test shifted the sequence numbers.
```release-note
NONE
```
NONE
> Fix sequences in regression tests

- e2e/playwright/regression/@existing-online-install-admin/test.spec.ts
- e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
- e2e/playwright/regression/shared/version-history.ts
Fixes validating release notes in regression tests
```release-note
NONE
```
NONE
> Fix validating release notes in regression tests

- e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
Fixes expected restore sequence for regression tests
```release-note
NONE
```
NONE
> Fix expected restore sequence for regression tests

- e2e/playwright/regression/shared/version-history.ts
Fix 3rd row index in regression tests
```release-note
NONE
```
NONE
> Fix 3rd row index in regression tests

- e2e/playwright/tests/@smoke-test-airgap/test.spec.ts
- e2e/playwright/tests/@version-history-pagination/test.spec.ts
Fixes flaky smoke airgap test
```release-note
NONE
```
NONE
> fix flaky airgap smoke test

- pkg/replicatedapp/embeddedcluster.go
> info log where we're downloading the kots binary from

- .github/actions/kots-e2e/action.yml
- e2e/inventory/inventory.go
- e2e/playwright/regression/shared/snapshots.ts
- web/src/components/snapshots/SnapshotSchedule.jsx
> Use registry service cluster IP for PR regression tests

- pkg/embeddedcluster/monitor.go
- pkg/embeddedcluster/upgrade.go
- pkg/handlers/troubleshoot.go
- pkg/handlers/update.go
- pkg/metrics/install.go
- pkg/operator/operator.go
- pkg/pull/pull.go
- pkg/replicatedapp/api.go
- pkg/replicatedapp/embeddedcluster.go
- pkg/replicatedapp/upstream.go
- pkg/replicatedapp/upstream_test.go
- pkg/reporting/app_online.go
- pkg/reporting/preflight_online.go
- pkg/template/license_context.go
- pkg/upgradeservice/deploy/deploy.go
- pkg/upstream/replicated.go
- pkg/util/util.go
- pkg/util/util_test.go
Uses the domain provided by EC rather than license endpoint
[SC-121390](https://app.shortcut.com/replicated/story/121390)
```release-note
NONE
```
NONE
> Use domain provided by EC rather than license endpoint

- pkg/docker/registry/registry.go
- pkg/docker/registry/registry_test.go
- pkg/replicatedapp/api_test.go
- pkg/replicatedapp/upstream.go
- pkg/upstream/replicated.go
- pkg/util/util.go
- pkg/util/util_test.go
Fixes updating custom domains in EC installs
test for this is in the EC repo
```release-note
NONE
```
NONE
> Ability to update custom domains in EC installs

- .github/actions/copy-assets/Dockerfile
- dev/dockerfiles/kotsadm/Dockerfile.local
- dev/dockerfiles/kurl-proxy/Dockerfile.local
- dev/scripts/common.sh
- e2e/playwright/tests/@target-kots-version-online/test.spec.ts
- go.mod
- kurl_proxy/go.mod
- pkg/handlers/embedded_cluster_artifacts.go
- pkg/handlers/embedded_cluster_binary.go
- pkg/handlers/handlers.go
[SC-122567](https://app.shortcut.com/replicated/story/122567)
In EC repo.
```release-note
NONE
```
NONE
> Add endpoint that returns the EC binary from the EC data directory

- go.mod
- go.sum
- pkg/kotsadmsnapshot/backup.go
- pkg/kotsadmsnapshot/backup_test.go
moves proxy and network specs into runtime config
```release-note
```
> chore(ec): update kinds

- .github/actions/copy-assets/Dockerfile
- .github/actions/copy-assets/go.mod
- dev/dockerfiles/kotsadm/Dockerfile.local
- dev/dockerfiles/kurl-proxy/Dockerfile.local
- dev/scripts/common.sh
- go.mod
- kurl_proxy/go.mod
> chore(ci): update to go 1.24.4

- e2e/playwright/tests/@no-required-config/test.spec.ts
https://github.com/replicatedhq/kots/actions/runs/16177316076/job/45666969091?pr=5409#step:8:173
```
1) [chromium] › tests/@no-required-config/test.spec.ts:5:1 › no required config ──────────────────
Test timeout of 30000ms exceeded.
Error: expect(locator).toContainText(expected)
Locator: locator('#app')
- Expected string  - 1
+ Received string  + 4
- Ready
+ ApplicationGitOpsChange passwordAdd new applicationLog outConfigure No Required ConfigNo Required SettingsItem 1Item 2No Required SettingsNo setting is required
+ Item 1
+ Item 2
+ Continue v2025.7.9-87b41a-nightly
```
```release-note
```
> chore(ci): fix test flake - slow test

- .github/actions/kurl-addon-kots-publisher/dist/index.js
- .github/actions/kurl-addon-kots-publisher/dist/package.json
- .github/actions/version-tag/dist/package.json
- .github/dependabot.yml
Labels are wrong and label checker workflow fails
Missing built package
```release-note
```
> chore(ci): fix dependabot pr labels and missing built package

- web/jest.config.js
- web/package.json
- web/src/components/upgrade_service/UpgradeService.test.tsx
- web/src/features/App/api/getApps.test.jsx
- web/src/jest-setup.ts
- web/yarn.lock
Bump jest major version. Make dependabot happy
https://github.com/replicatedhq/kots/pull/5459
```release-note
```
> chore(deps): upgrade jest

- e2e/playwright/regression/@embedded-airgapped-install/test.spec.ts
- e2e/playwright/regression/shared/version-history.ts
> fix(e2e): regression test flakiness
