web/src/features/Auth/components/SecureAdminConsole.tsx
Fixes # [sc-47115]
```release-note
NONE
```
NONE
=> add optional chaining

web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/DashboardGitOpsCard.jsx, web/src/components/snapshots/AppSnapshots.jsx, web/src/components/snapshots/SnapshotRow.jsx, web/src/components/snapshots/Snapshots.jsx, web/src/components/troubleshoot/AnalyzerFileTree.jsx, web/src/components/troubleshoot/AnalyzerRedactorReportRow.jsx, web/src/components/troubleshoot/GenerateSupportBundle.jsx, web/src/components/troubleshoot/SupportBundleAnalysis.jsx, web/src/components/troubleshoot/SupportBundleRow.jsx, web/src/components/watches/DownstreamWatchVersionDiff.jsx, web/src/components/watches/WatchSidebarItem/HelmChartSidebarItem.jsx, web/src/features/AppConfig/components/AppConfig.tsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
```<Icon size={12} icon="up-arrow"/>```
Fixes #
```release-note
NONE
```
NONE
=> fix icon sizing for firefox 

pkg/kotsadm/version/kotsadm_version.go, pkg/kotsadm/version/kotsadm_version_test.go
Fixes an issue where in some cases the specified registry namespace is ignored for KOTS images if the specified registry hostname already includes a namespace.
Fixes #
```release-note
Fixes an issue where in some cases the specified registry namespace is ignored for KOTS images if the specified registry hostname already includes a namespace.
```
NONE
=> Fix constructing the path to the configured registry

integration/docker/registry/registry_server.go, integration/docker/registry/temp_registry_test.go
Fixes a flakey integration test related to the temp registry
Fixes #
```release-note
NONE
```
NONE
=> Fix flakey temp registry integration test

.github/workflows/release.yaml
The regression tests are being skipped on all recently merged PRs because of the dependency on validate-kurl-addon job that runs only when changes are made to the deploy/kurl/kotsadm/template directory.
This pull request adds a generate-kurl-addon job as a dependency of the regression tests that is run on all merges to main.
=> Release regression tests not running because of kurl add-on changes

web/src/components/apps/AppVersionHistory.tsx, web/src/components/apps/DashboardVersionCard.tsx
- removes tab filter from kots managed mode 
https://app.shortcut.com/replicated/story/60201/helm-tabs-are-missing-from-output-in-non-helm-mode
```release-note
- fixes issue where log tabs for helm installs would be hidden from kots managed installations 
```
none
=> do not filter tabs in kots managed

pkg/handlers/app.go, pkg/helm/charts.go, pkg/helm/helm.go, pkg/helm/updates.go, pkg/updatechecker/updatechecker.go
On Version History page only new rows should be highlighted when the page is opened.  Preciously existing updates and releases should not be highlighted.
Fixes #
```release-note
* Fixes a bug that causes previously existing rows on the [version history](/enterprise/updating-apps#update-an-application-in-the-admin-console) page to be highlighted when the page is opened in [Helm managed mode (Alpha)](/vendor/helm-install).
```
=> Don't light up version rows every time Version History page is opened

pkg/store/kotsstore/supportbundle_store.go, pkg/store/kotsstore/supportbundle_store_test.go, pkg/supportbundle/execute.go, web/src/components/troubleshoot/GenerateSupportBundle.jsx
If kotsadm pod dies while a support bundle is running, it mains in running state.  This introduces a timeout period that marks bundle as "failed" if it's in running state but is not being updated.
Fixes #
```release-note
* Fixes an issue that causes the [Troubleshoot tab](/enterprise/troubleshooting-an-app) to display support bundle collection progress bar even when support bundle is not actually being collected.
```
NONE
=> Timeout abandoned running bundles

.github/workflows/require-pr-labels.yaml, pkg/handlers/dashboard.go, pkg/version/metrics.go, pkg/version/metrics_test.go
This PR adds support for templating to all properties of the `spec.graphs` field in the kots.io/v1beta1 Application custom resource.
This PR also updates the PR test for label enforcement.
Fixes [SC-59379](https://app.shortcut.com/replicated/story/59379/fmt-sprintf-usage-broken-for-custom-graph-queries) and [SC-51989](https://app.shortcut.com/replicated/story/51989/using-template-functions-in-kots-application-spec-graphs-manifests-fail-to-render-and-display-prometheus-graphs)
Little bit of refactoring for easier unit testing of these changes.
Add custom graphs with template functions to the KOTS application spec:
```
apiVersion: kots.io/v1beta1
kind: Application
metadata:
name: my-application
spec:
graphs:
- title: CPU Usage
query: …
```
=> allow custom graphs to be templated

pkg/kurl/kurl_nodes.go, pkg/kurl/kurl_nodes_test.go
Fixes # https://app.shortcut.com/replicated/story/35952/cluster-page-white-screen-of-death
```release-note
- Fixes an issue where cluster screen became blank when node resources pod capacity were defined with SI units
```
NONE
=> use resource.Value() to compute pod capacity

web/src/components/apps/AppDetailPage.tsx, web/src/components/apps/AppLicense.tsx
Allow user redeploy app version with new values.yaml fail after syncing license.
Fixes #
```release-note
* Adds ability to deploy application with new values after syncing license from admin console in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
=> Allow upgrading chart after license is synced

.image.env, Makefile, pkg/image/constants.go
This PR updates the KOTS image dependencies for local-volume-provider and MinIO.  The LVP update also resolves high severity CVE-2022-27664.
Fixes [SC-58666](https://app.shortcut.com/replicated/story/58666/resolve-high-severity-cve-2022-27664-in-local-volume-provider)
Run `go run ./cmd/imagedeps`
```release-note
Updates the replicated/local-volume-provider image to v0.3.10 to resolve CVE-2022-27664 with high severity.
```
NONE
=> update lvp and minio image deps

pkg/api/downstream/types/types.go, pkg/handlers/app.go, pkg/helm/charts.go, pkg/helm/helm.go, pkg/helm/updates.go, pkg/updatechecker/updatechecker.go, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Uses timestamps from charts info rather than hardcoded time.Now values.
Fixes #
```release-note
* Fixes an issue that causes Released timestamp to be the same for all releases on the [version history](/enterprise/updating-apps#update-an-application-in-the-admin-console) page in [Helm managed mode (Alpha)](/vendor/helm-install).
```
=> Use release timestamps from chart instead of current time

pkg/helm/charts.go
Use actual timestamps from chart when displaying release dates on version history page
Fixes #
```release-note
* Fixes an issue that causes Released timestamp to be the same for all releases on the [version history](/enterprise/updating-apps#update-an-application-in-the-admin-console) page in [Helm managed mode (Alpha)](/vendor/helm-install).
```
=> Match created_at path with where the timestamp actually is

web/src/components/BackupRestore.jsx
- removes `withRouter` from BackupRestore
- `withRouter` is deprecated in react-router 6. This is necessary to upgrade the dependency 
https://app.shortcut.com/replicated/story/59398/update-kots-web-react-router-5-0-5-1
none- refactor 
none
=> remove withRouter from BackupRestore

.github/workflows/build-test.yaml, cmd/kots/cli/admin-console-generate-manifests.go, cmd/kots/cli/admin-console-push-images.go, cmd/kots/cli/admin-console-upgrade.go, cmd/kots/cli/admin-console.go, cmd/kots/cli/app-status.go, cmd/kots/cli/backup.go, cmd/kots/cli/check-version.go, cmd/kots/cli/docker.go, cmd/kots/cli/download.go, cmd/kots/cli/garbage-collect-images.go, cmd/kots/cli/get-apps.go, cmd/kots/cli/get-backups.go, cmd/kots/cli/get-config.go, cmd/kots/cli/get-restores.go, cmd/kots/cli/get-versions.go, cmd/kots/cli/identity.go, cmd/kots/cli/ingress.go, cmd/kots/cli/namespace.go, cmd/kots/cli/pull.go, cmd/kots/cli/remove.go, cmd/kots/cli/reset-password.go, cmd/kots/cli/reset-tls.go, cmd/kots/cli/restore.go, cmd/kots/cli/set-config.go, cmd/kots/cli/upload.go, cmd/kots/cli/upstream-download.go, cmd/kots/cli/upstream-upgrade.go, cmd/kots/cli/velero.go
Fixes kots CLI to use kubeconfig namespace for finding kotsadm when no namespace is passed in via flag.
Fixes # [SC-56078](https://app.shortcut.com/replicated/story/56078/kots-cli-should-respect-the-namespace-from-the-current-context)
May change some backwards compatibility, in that if a user was depending on it not being passed via flags and instead using the default namespace. Now that user may experience a different behaviour if their kubeconfig is set to another namespace.
Another goal of this PR is to align all the `--namespace` functionality, so that the user has a consistent experience. They all get it from flags, kubeconfig context, or set it to `default` in that order, then validate the chosen namespace. 
- Run kubectl config set-context --current --namespace=NAMESPACE and …
=> collect namespace from flag or kubeconfig context

pkg/image/builder.go
Fixes an issue where installing, updating, or configuring applications that have many images defined in KOTS custom resources (e.g. collectors, preflights, analyzers, etc..) hangs or takes a really long time.
Fixes [SC-61040](https://app.shortcut.com/replicated/story/61040/installing-updating-configuring-applications-that-have-many-images-used-in-kots-kinds-collectors-preflights-etc-hangs-or)
Fixes #
```release-note
Fixes an issue where installing, updating, or configuring applications that have many images defined in KOTS custom resources (e.g. collectors, preflights, analyzers, etc..) hangs or takes a really long time.
```
NONE
=> fix: installing/updating/configuring applications that have many kots kinds images hangs or takes a really long time

web/src/Root.tsx, web/src/components/identity/Access.jsx, web/src/components/identity/Access.tsx
- refactors Access component to use react router hook instead of `withRouter`
- `withRouter` is deprecated in react-router 6
https://app.shortcut.com/replicated/story/59398/update-kots-web-react-router-5-0-5-1
none-refactor
none
=> remove withRouter from Access component

.github/workflows/alpha.yaml, .github/workflows/release.yaml
Now that it is an external add-on the kots workflows build the add-on rather than triggering a kurl build.
=> No longer trigger kotsadm kurl package build as it is an external add-on

cmd/kots/cli/install_test.go, pkg/preflight/execute.go, pkg/preflight/preflight.go, pkg/preflight/preflight_test.go, pkg/preflight/types/types.go, pkg/updatechecker/updatechecker.go, web/src/components/PreflightResultErrors.tsx, web/src/components/PreflightResultPage.jsx
If preflights fail to start due to some error, the UI should not be showing the progress bar as if preflights are running.  This change makes this UI progress with the message that preflights did not run.
Fixes #
```release-note
* Fixes an issue that could cause the preflight progress bar to be stuck close to 100% but never complete.
```
=> Don't keep polling preflight status when preflights are not running

pkg/version/metrics.go
This PR changes the prometheus query for disk usage so that it shows the usage per instance and device.
Prior to this change the disk usage graph would should a spike when a new device was mounted and was not as useful. 
Fixes #
[SC-50066](https://app.shortcut.com/replicated/story/50066/kots-disk-usage-reports-a-total-of-all-filesystems-mounted)
The disk usage graph now shows each device and what instance they are in:
1. Use a cluster with Prometheus and KOTS
2. Add and mount a device to the instance
3. Inspect the disk usage graph, it should show the instance-device
Additional nodes can be joined to see metrics from different instances, the picture above is from a 2 node cluster.
```release-note
Updates prometheus query to show disk usage by instance and mount point.
```
NONE
=> change prometheus disk usage query

web/src/utilities/utilities.js, web/src/utilities/utilities.test.js
This PR fixes an issue where customer licenses were not showing as expired in the UI, but when an end user tried to fetch updates, it would fail with a message indicating that the license was expired.  Additionally, it fixes an issue where the UTC expiration time of the license was being compared against the local time, so it made for an inconsistent comparison. This PR changes this so that the UTC time on the license is compared against the current UTC time.
When syncing license in KOTS (before):
Checking for updates:
After this PR, the UI will properly display if the license is expired after syncing:
Fixes [SC-59063](https://app.shortcut.com/replicated/story/59063/can-t-check-for-updates-because-license-is-expired-but-neither-the-admin-console-nor-vendor-portal-says-it-is-expired-yet)
* …
=> fix license expiration check in UI

deploy/kurl/kotsadm/template/base/tmpl-secret-rqlite.yaml, migrations/kustomize/overlays/dev/rqlite.yaml, migrations/kustomize/overlays/okteto/rqlite.yaml, pkg/kotsadm/objects/secrets_objects.go
Fixes an issue where the admin console might restart during the migration from Postgres to rqlite due to a short timeout.
Fixes #
```release-note
Fixes an issue where the admin console might restart during the migration from Postgres to rqlite due to a short timeout.
```
=> Increase rqlite connector/client timeout to 60 seconds

pkg/base/helm.go, pkg/base/helm_test.go, pkg/base/helm_v2.go, pkg/base/helm_v3.go, pkg/base/replicated_test.go, pkg/tests/base/cases/configcontext/base/charts/test-chart-2/values.yaml, pkg/tests/base/render_test.go, pkg/tests/pull/cases/configcontext/wantResults/base/charts/test-chart-2/values.yaml, pkg/tests/pull/cases/configcontext/wantResults/base/charts/test-chart/values.yaml, pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-release-1/values.yaml, pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-release-2/values.yaml, pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-variation-0/values.yaml, pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/values.yaml, pkg/tests/pull/cases/subcharts/wantResults/base/charts/chart/values.yaml, pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/values.yaml
This PR modifies the `RenderHelm` method so that the rendered `values.yaml` file is included in the base files.  This will allow end users to inspect the resulting values for the helm chart(s) that they are installing.  The resulting file is equivalent to what is returned when running `helm get values <release-name> --all`.
Fixes [SC-61242](https://app.shortcut.com/replicated/story/61242/show-the-rendered-values-file-in-the-file-explorer-for-native-helm)
Tested the following changes with a GitOps workflow to ensure no additional data is committed.
* When using replicated helm (v2 and v3), the image pull secrets and application resources (the kustomize output) are committed to the repo.  All other files are not (Chart.yaml, values.yaml, etc).
* When using native helm, only the image pull …
=> include values.yaml in helm base files

pkg/app/types/helm_app.go, pkg/handlers/dashboard.go, pkg/handlers/metadata.go, pkg/helm/cache.go, pkg/helm/charts.go, pkg/helm/informers.go, pkg/kotsutil/kots.go
Run status informers for charts when running in helm managed mode
This PR implements running status informer checks for helm charts when running in helm managed mode
Fixes #
https://app.shortcut.com/replicated/story/59995/support-status-informers-in-helm-managed-mode
```release-note
Added ability to run status informers for helm charts when running in [Helm managed mode (Alpha)](/vendor/helm-install).
```
=> run status informers for charts when in helm managed mode

cmd/kots/cli/enable-ha.go
Fixes #
```release-note
Deprecates the `kots enable-ha` CLI command
```
NONE
=> Deprecate enable-ha cli command

.github/dependabot.yml, .github/workflows/build-test.yaml
- Just allow PRs done from a fork or from a bot when they have the label `@actions/safe-to-test'` 
- Just add the `@actions/safe-to-test'` automatically for bot PRs done from GitHUB
Closes: https://github.com/replicatedhq/kots/pull/3395
More info: https://replicated.slack.com/archives/CM8N4TWR0/p1667859937228889
- Check the PR done to test it out: https://github.com/replicatedhq/kots/pull/3395
- Check the debug output to verify the data in the conditions (see that the github.event_name is 'pull_request' from the fork ): https://github.com/replicatedhq/kots/actions/runs/3417779228/jobs/5689304031
Then, we can review the changes in the conditional. 
NONE
NONE
=> (ci/fix): allow prs done from bots OR from forks be executed ONLY when they have the label @actions/safe-to-test'

README.md
Just add to the README what the platform supported for the CLI and for its operations.
So that users can avoid facing issues like: https://github.com/replicatedhq/kots/issues/3353
Fixes # https://github.com/replicatedhq/kots/issues/3353
Try to use kots to install an app/release on a pre-existent cluster which is not Linux/amd64 
(i.e. against kind running on Apple Silicon)
NONE
NONE
=> :book: add supportability info into README (only linux/amd64)

deploy/Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
This PR updates the kotsadm image to use a Debian Bullseye base image.  Bullseye is the current stable release and is [supported by the security and release teams](https://wiki.debian.org/LTS).  Additionally, this resolves CVE-2022-29458 in the kotsadm image.
Fixes [SC-61309](https://app.shortcut.com/replicated/story/61309/cve-2022-29458)
Removed the separate `s3cmd` install since it is now included in Bullseye: https://packages.debian.org/bullseye/s3cmd
n/a
```release-note
Updates the kotsadm base image to `debian:bullseye-slim` to resolve CVE-2022-29458 with high severity
```
NONE
=> use debian bullseye base image

go.mod, go.sum
Pulls in latest image v5 dependency with a possible fix for https://app.shortcut.com/replicated/story/61570/airgap-install-can-fail-to-push-images-to-private-repo-with-trying-to-reuse-blob-error
Fixes #
```release-note
* Fixes a bug that could result in `invalid status code from registry 400` error when pushing images from airgap bundle into a private registry.
```
NONE
=> Bump github.com/containers/image to v5.23.1

migrations/deploy/Dockerfile
This PR updates the base image for kotsadm-migrations to `debian:bullseye` to keep the base image up-to-date with the latest stable os version and resolves CVE-2022-29458 with high severity.
Fixes [SC-61309](https://app.shortcut.com/replicated/story/61309/cve-2022-29458)
```
trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH ttl.sh/craig/kotsadm-migrations:2h
```
```release-note
Updates the kotsadm-migrations base image to `debian:bullseye` to resolve CVE-2022-29458 with high severity.
```
NONE
=> use debian bullseye base image for kotsadm-migrations

kurl_proxy/deploy/Dockerfile
This PR updates the base image for kurl-proxy to `debian:bullseye-slim` to keep the base image up-to-date with the latest stable os version and resolves CVE-2022-29458 with high severity.
Fixes [SC-61309](https://app.shortcut.com/replicated/story/61309/cve-2022-29458)
```
trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH ttl.sh/craig/kurl-proxy:2h
```
```release-note
Updates the kurl-proxy base image to `debian:bullseye-slim` to resolve CVE-2022-29458 with high severity.
```
NONE
=> use debian bullseye base image for kurl-proxy

Makefile, go.mod, go.sum, integration/replicated/generate.go, integration/replicated/pull_test.go, integration/upload/generate.go, pkg/download/download.go, pkg/handlers/download.go, pkg/kotsadm/push_images.go, pkg/kustomize/helm.go, pkg/kustomize/helm_test.go, pkg/operator/client/client.go, pkg/pull/archive.go, pkg/store/kotsstore/version_store.go, pkg/supportbundle/backup.go, pkg/supportbundle/filetree.go, pkg/supportbundle/supportbundle.go, pkg/upload/archive.go, pkg/version/archive.go
fix medium cve-2019-10743 by update github.com/mholt/archiver mod to v3.5.1
Fixes # https://app.shortcut.com/replicated/story/59087/cve-2019-10743
NONE 
- run `make scan` on kots repo
```release-note
Update github.com/mholt/archiver mod to v3.5.1 to fix medium CVE-2019-10743
```
NONE
=> fix medium cve-2019-10743 by update github.com/mholt/archiver mod to v3.5.1

cmd/kots/cli/install.go, pkg/k8sutil/gke.go, pkg/k8sutil/gke_test.go, pkg/kotsadm/main.go, pkg/kotsadm/objects/rqlite_objects.go, pkg/kotsadm/types/deployoptions.go
PR is to update the rqlite statefulset's cpu request if a gke autopilot cluster is identified. 
This is done to meet autopilot's minimum cpu requirement of 500m. 
Fixes # [SC-61237](https://app.shortcut.com/replicated/story/61237/kotsadm-upgrade-to-1-89-0-fails-on-gke-autopilot)
Installing or Upgrading to kots version 1.89 or newer fails with error:
```
Error: failed to deploy: failed to deploy admin console: failed to ensure rqlite: failed to ensure rqlite statefulset: failed to create rqlite statefulset: admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more policies: {"[denied by autogke-pod-limit-constraints]":["workload 'kotsadm-rqlite' cpu requests '{{250 -3} {\u003cnil\u003e}  DecimalSI}' …
```
=> updates rqlite statefulset's cpu for gke autopilot

.github/workflows/regression.yaml, e2e/hack/deps.sh
k3s and rke2 are no longer supported by kurl
Fixes #
```release-note
NONE
```
NONE
=> pin velero version and remove k3s permutation from regression tests

kotskinds/Makefile, kotskinds/apis/kots/v1beta1/application_types.go, kotskinds/client/kotsclientset/fake/register.go, kotskinds/client/kotsclientset/scheme/register.go, kotskinds/config/crds/kots.io_applications.yaml, kotskinds/schemas/application-kots-v1beta1.json
This PR adds the `replicatedRegistryDomain` and `proxyRegistryDomain` fields to the App spec.
These fields will be used to indicate which CNAME to use for the replicated registry and the proxy registry.
Fixes # [SC-62126](https://app.shortcut.com/replicated/story/62126/add-fields-to-the-app-spec-to-indicate-which-cname-should-be-used-for-the-replicated-registry-and-the-proxy-registry)
- Added the two fields
- Ran: `make -C kotskinds schemas openapischema`
```release-note
NONE
```
=> add replicatedRegistryDomain and proxyRegistryDomain fields to App Spec

pkg/base/helm_v2.go, pkg/base/helm_v3.go, pkg/handlers/config.go, pkg/kotsadmupstream/upstream.go, pkg/online/online.go, pkg/pull/pull.go, pkg/store/kotsstore/version_store.go
- Allows installing applications with Helm charts that have `required` values that are not supplied at install time.
- Show Helm errors when Helm render fails.  Screenshots below show messages before and after this change
- Before:
- After: 
Fixes #
Add a Helm chart with a template like
```
some-key: {{ required "A valid .Values.test is required" .Values.test }}
```
but do not provide a value for `test`
```release-note
* Fixes an issue that causes application license upload to fail for applications that include Helm charts with [`required`](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-required-function) values missing from configuration.
```
NONE
=> Allow required values in helm charts

web/src/features/Dashboard/components/DashboardVersionCard.tsx
- shows release notes 
https://app.shortcut.com/replicated/story/62895/release-notes-cannot-be-opened-on-dashboard
```release-note
- fixes an issue where release notes would not display when the release notes icon is clicked on the dashboard 
```
none
=> add show release notes

web/src/components/apps/AppVersionHistory.tsx, web/src/features/Dashboard/components/DashboardVersionCard.tsx
- adds filter to initial tab selection that filters non-helm tabs in helm managed mode
https://app.shortcut.com/replicated/story/59994/deploy-logs-should-have-the-helmstdout-tab-clicked-when-the-modal-loads
- Gifs show helm managed and non helm managed mode after the fix
- in helm managed mode, the first tab is selected automatically after opening the view logs modal
```release-note
- fixes an issue where no tab was selected when opening the View Logs modal while in helm managed mode 
```
none
=> update initial tab selection

pkg/kotsutil/kots.go
Currently, as described by [replicated-docs](https://docs.replicated.com/enterprise/image-registry-embedded-cluster#enable-and-disable-image-garbage-collection ) enabling/disabling garbage collection is not working.
Fixes #
[SC-62723](https://app.shortcut.com/replicated/story/62723/fix-an-issue-where-enabling-disabling-garbage-collection-is-broken-not-working)
Solution:
if enable-image-deletion key exists and read the value and enable/disable accordingly
else
use system default isKurl() to perform the enable/disable image garbage collection
```release-note
Fix an issue where enabling/disabling image garbage collection is broken
```
NONE
=> Fix an issue where enabling/disabling image garbage collection is broken

kotskinds/apis/kots/v1beta1/application_types.go, kotskinds/client/kotsclientset/fake/clientset_generated.go, pkg/docker/registry/registry.go, pkg/docker/registry/registry_test.go, pkg/preflight/preflight.go, pkg/pull/pull.go, pkg/registry/registry.go, pkg/registry/troubleshoot.go, pkg/registry/troubleshoot_test.go, pkg/render/render.go, pkg/rewrite/rewrite.go, pkg/supportbundle/spec.go, pkg/template/config_context.go
Read `proxyRegistryDomain` fields from KOTS application manifest and if provided use the values to rewrite images instead of default replicated proxy `proxy.replicated.com`
Fixes # [SC-62135](https://app.shortcut.com/replicated/story/62135/kots-reads-proxy-cname-from-app-spec-and-rewrites-proxied-images-with-it)
```release-note
Read `proxyRegistryDomain` fields from KOTS application manifest and if provided use the values to rewrite images instead of default replicated proxy `proxy.replicated.com`
```
Maybe we can improve https://docs.replicated.com/vendor/packaging-private-registry-cname#limitations by adding `app manager supports proxying registries`
=> Read `proxyRegistryDomain` from kots application manifest and rewrite images

pkg/image/builder.go, pkg/pull/pull.go
Fixes an issue where DockerHub credentials provided to the admin console via the 'kots docker ensure-secret' CLI command do not increase the rate limit
Fixes #
this will have a side affect were if the provided credentials have access to the vendor’s private images on dockerhub, they won’t be proxied
```release-note
Fixes an issue where DockerHub credentials provided to the admin console via the [kots docker ensure-secret](/reference/kots-cli-docker-ensure-secret) CLI command do not increase the rate limit.
```
NONE
=> Fix: Dockerhub credentials provided to KOTS via the 'kots docker ensure-secret' CLI command do not increase the rate limit

pkg/kotsadmupstream/upstream.go
Fixes an issue where goroutines were leaked because a routine was left open waiting for data along a pipe even if an error occured causing no data to be sent through the pipe
Fixes # 37571
```release-note
Fixes an issue where goroutines were leaked because a routine was left open waiting for data along a pipe even if an error occured causing no data to be sent through the pipe
```
NONE
=> defer close pipe to fix leaking goroutine issue

web/src/scss/utilities/prism.scss
**before change** 
**after change**
Fixes # [sc-62445] https://app.shortcut.com/replicated/story/62445/admin-console-command-boxes-are-larger-than-they-should-be
```release-note
NONE
```
NONE
=> Fix size of command boxes

deploy/kurl/kotsadm/template/base/rqlite.yaml, migrations/kustomize/overlays/dev/rqlite.yaml, migrations/kustomize/overlays/okteto/rqlite.yaml, pkg/kotsadm/objects/rqlite_objects.go, pkg/kotsadm/rqlite.go
rqlite uses an in-memory DB by default for a better performance, so the memory limit should approximately match the PVC size (1Gi). The PVC is used by rqlite for storing raft logs and compressed db snapshots that are used to rebuild the in-memory DB when rqlite restarts. This PR increases the memory limit to reflect the desired maximum DB size.
rqlite data would rarely be that large, which would usually happen in QA environments with a very large number of versions, so this change would accommodate those environments, but shouldn't affect production environments much since those environments usually have a lot less versions.
This PR does not change the memory request, only the memory limit, so the footprint of KOTS should remain relatively the same.
Fixes #
```release-note
Fixes an issue …
```
=> Increase rqlite memory limit to 1Gi

web/src/components/troubleshoot/SupportBundleList.tsx
Fixes # https://app.shortcut.com/replicated/story/62465/support-bundle-row-shows-unable-to-surface-insights-for-this-bundle-after-completing
```release-note
NONE
```
NONE
=> Update support bundle insight message after completing 

pkg/supportbundle/spec.go, pkg/supportbundle/supportbundle.go
Fixes errors shown when collecting support bundles in existing clusters. Such as:
```
* cannot collect weave-status: action "get" is not allowed on resource "pods" in the "kube-system" namespace
* cannot collect weave-report: action "get" is not allowed on resource "pods" in the "kube-system" namespace
```
This PR moves collectors that are specific to kURL clusters out of the default support bundle spec so that they are only ran in kURL clusters. 
Fixes # [SC-60507](https://app.shortcut.com/replicated/story/60507/don-t-inject-kurl-specific-collectors-to-support-bundle-spec-if-not-running-in-kurl)
```release-note
Fixes errors when generating support bundle in existing clusters via the CLI. 
```
NONE
=> exclude kURL specific collectors from support bundle if not running in kURL

pkg/docker/registry/registry.go, pkg/docker/registry/registry_test.go
Adds support to not proxy all registry images from our default okteto (repldev.com) env (both registry and proxy).
Without this, it's not possible to use a production kots build to tests against our standard okteto setup for registry, proxy, and vendor portal
=> Support registry and proxy from okteto envs

pkg/registry/images.go, pkg/registry/images_test.go
When an external registry is configured, image garbage collection fails
So, disabling the garbage collection
Fixes # [SC-46745](https://app.shortcut.com/replicated/story/46745)
```release-note
Disable image garbage collection when an external registry is enabled
```
NONE
=> Disable image garbage collection when an external registry is enabled

pkg/base/images.go, pkg/base/testdata/replicated-registry/pod.yaml, pkg/base/write_images_test.go, pkg/docker/registry/registry.go, pkg/docker/registry/registry_test.go, pkg/docker/registry/types/types.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go
This PR introduces changes that will read the `replicatedRegistryDomain` field from KOTS application manifest and if provided use the values to rewrite images instead of the default replicated registry `registry.replicated.com`.  Images using the replicated registry domain or custom registry domain _will not_ be re-written to use the proxy since the proper credentials will already be present to pull those images.
KOTS App spec:
```
apiVersion: kots.io/v1beta1
kind: Application
metadata:
name: my-app
spec:
title: My App
replicatedRegistryDomain: craig-registry.testcluster.net
```
Images in Deployment Spec:
Resulting Midstream Kustomization:
Fixes # [SC-62143](https://app.shortcut.com/replicated/story/62143/kots-reads-replicated-registry-cname-from-app-spec-and-rewrites-replicated-registry-i …
=> Read replicatedRegistryDomain from kots application manifest and rewrite images

pkg/template/builder.go, pkg/template/config_context.go, pkg/template/license_context.go, pkg/template/license_context_test.go
This PR modifies the LicenseDockerCfg template function in the [License Context](https://docs.replicated.com/reference/template-functions-license-context#licensedockercfg) to utilize the `replicatedRegistryDomain` and `proxyRegistryDomain` fields from the KOTS Application manifest.  These values, if provided, will override the defaults of `registry.replicated.com` and `proxy.replicated.com` for the replicated registry and proxy, respectively.
Fixes [SC-50068](https://app.shortcut.com/replicated/story/50068/licensedockercfg-template-function-should-respect-the-registry-cnames)
The `licenseCtx` struct now accepts an optional kots application spec that will be used to determine these endpoints, if provided.
Install an application release that includes the `spec.replicatedRegistryDomain` …
=> use registry fields for LicenseDockerCfg template func

pkg/template/static_context.go, pkg/template/static_context_test.go
Exposes k8s version info as a template functions:
- KubernetesVersion
- KubernetesMajorVersion
- KubernetesMinorVersion
Fixes #
```release-note
Adds [KubernetesVersion](/reference/template-functions-static-context#kubernetesversion), [KubernetesMajorVersion](/reference/template-functions-static-context#kubernetesmajorversion), and [KubernetesMinorVersion](/reference/template-functions-static-context#kubernetesminorversion) template functions
```
https://github.com/replicatedhq/replicated-docs/pull/840
=> Expose k8s version info as template functions

pkg/kotsadm/rqlite.go, pkg/kotsadm/rqlite_test.go
Generated manifests for Admin Console contains an empty file for rqlite-headless-service that makes it impossible to deploy Admin Console from manifests.
Fixes #
https://github.com/replicated-collab/swaggerhub-kots/issues/143
```
➜  ~  kubectl kots admin-console generate-manifests --namespace pavansokkenagaraj
Enter a new password for the admin console (6+ characters): ••••••••
Admin Console manifests created in /Users/sokke/admin-console
➜  ~ ls -al /Users/sokke/admin-console
total 136
drwxr--r--  20 sokke  staff   640 16 Dec 10:46 .
drwxr-x---+ 76 sokke  staff  2432 16 Dec 22:07 ..
drwxr-xr-x   2 sokke  staff    64 16 Dec 10:46 coverage
-rw-r--r--   1 sokke  staff   536 16 Dec 10:45 kotsadm-config.yaml
-rw-r--r--   1 sokke  staff  6912 16 Dec 10:45 kotsadm-deployment.yaml
-rw-r--r--   1 …
```
=> fix a bug where rqlite headless service manifest is not generated

web/src/features/AppConfig/components/AppConfig.tsx
- currently showing the labels in the side nav. since labels are not configurations, it doesn't make sense for them to show up in the navigation 
Fixes # https://app.shortcut.com/replicated/story/59046/don-t-show-labels-in-config-nav
```release-note
- Config Page: fixes an issue where field labels were rendered in the config page side nav
```
none
=> filter label type from side nav

web/src/features/AppConfig/components/AppConfig.tsx, web/src/scss/components/watches/WatchConfig.scss
- pins the config nav so it scrolls independently of of the config 
Fixes # https://app.shortcut.com/replicated/story/59042/pin-the-config-navigation-menu-on-the-config-page
```release-note
- Config Page: updated the config nav so that its position is fixed and doesn't scroll with the config form. 
```
=> Make config nav fixed / scroll independently of config form 

cmd/kots/cli/get-config.go, cmd/kots/cli/get-config_test.go, pkg/crypto/aes.go
Plugs in the decrypt flag
Fixes #63231
Create a config with a password, set it to hidden
Currently it's decrypted regardless of if the flag is passed in
```release-note
When using kots get config, now decrypts only if the --decrypt flag has been passed.
```
NONE
=> use decrypt flag

pkg/template/static_context.go
The KOTS linter will throw an error when trying to use SemVer comparison with the KubernetesVersion template function since the linter does not run inside a Kubernetes cluster
Fixes #
```release-note
NONE
```
NONE
=> return valid semver when a k8s version is not detected

.github/actions/kots-e2e/action.yml, .github/workflows/build-test.yaml, e2e/Makefile, e2e/e2e_test.go, e2e/kots/kots.go, e2e/testim/inventory/inventory.go
* Adds an e2e test for a basic airgap installation to add coverage for this workflow
* Changes all e2e tests to run ginkgo with the verbose flag for easier debugging
KOTS test app: https://github.com/replicatedhq/kots-test-apps/pull/64
Fixes #
n/a
To run locally with ttl images:
```
make -C e2e test \
FOCUS="Airgap Smoke Test" \
TESTIM_BRANCH=$TESTIM_BRANCH \
KOTSADM_IMAGE_REGISTRY=ttl.sh \
KOTSADM_IMAGE_NAMESPACE=$USER \
KOTSADM_IMAGE_TAG=24h \
AIRGAP=1
```
```release-note
NONE
```
NONE
=> add airgap smoke test to e2e suite

e2e/testim/client.go
Sets `NODE_OPTIONS=--max-old-space-size=4096` when running the testim cli in our e2e tests.  This resolves the following issue:
```
<--- Last few GCs --->
[59:0x66b6c80]   962194 ms: Scavenge 2025.2 (2078.4) -> 2017.9 (2078.4) MB, 12.8 / 0.1 ms  (average mu = 0.698, current mu = 0.654) allocation failure; 
[59:0x66b6c80]   962683 ms: Scavenge 2027.7 (2080.5) -> 2020.3 (2079.2) MB, 6.6 / 0.0 ms  (average mu = 0.698, current mu = 0.654) allocation failure; 
[59:0x66b6c80]   962714 ms: Scavenge 2026.6 (2079.2) -> 2022.2 (2096.4) MB, 11.9 / 0.0 ms  (average mu = 0.698, current mu = 0.654) allocation failure; 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 0xb6e500 node::Abort() [node]
2: 0xa7e632  [node]
3: 0xd47f20 …
```
=> set max memory for testim cli

.github/workflows/build-test.yaml, e2e/testim/inventory/inventory.go
Our tests utilize ginkgo's `--focus` flag, which [uses a regex](https://onsi.github.io/ginkgo/#description-based-filtering) to filter the specs to run.  As a result, the "Smoke Test" focus was matching both the "Smoke Test" and "Airgap Smoke Test" spec and both were being run as part of `validate-smoke-test` ([example](https://github.com/replicatedhq/kots/actions/runs/3741032193/jobs/6351322465#step:8:109)).
When running:
```
make e2e \
FOCUS="Smoke Test"
```
Outputs:
```
Running Suite: E2E Suite - /
============================
Random Seed: 1671547893
Will run 2 of 15 specs
```
We may want to revisit how we organize the e2e tests to avoid issues like this in the future.  Maybe we can modify the regex so that it only matches what we expect?  Maybe we can leverage [spec …
=> rename airgap smoke test

deploy/Dockerfile
Updates the versions of `kubectl` in the `kotsadm` image to resolve CVE-2022-27664 and CVE-2022-32149
Fixes another part of [SC-60523](https://app.shortcut.com/replicated/story/60523/resolve-high-severity-cve-2022-27664-in-kots)
Before
`trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH kotsadm/kotsadm:v1.92.0`
After
`trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH kotsadm/kotsadm:main`
```release-note
Updates the kubectl binary in the kotsadm image to resolve CVE-2022-27664 and CVE-2022-32149 with high severity.
```
NONE
=> update kubectl version for CVEs

web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx, web/src/features/Dashboard/components/DashboardVersionCard.tsx, web/src/scss/components/apps/AppVersionHistory.scss
Before: 
After fix: 
Fixes # https://app.shortcut.com/replicated/story/45692/preflight-checks-pass-with-warnings-can-sometimes-break-out-of-the-ui
```release-note
Fixed an issue on the App Version History page where the row layout was broken when displaying preflight check warnings.
```
NONE
=> Miawong/sc 45692/preflight checks pass with warnings breaks out of UI 

pkg/kotsadm/types/constants.go, pkg/kotsadm/types/constants_test.go, pkg/supportbundle/spec.go
- it adds a label `troubleshoot.io/kind=support-bundle` when  it stores/updates the Troubleshoot support-bundle spec secret
Shortcut: https://app.shortcut.com/replicated/story/65655/troubleshoot-add-label-to-support-bundle-secret
Fixes #
When you run it under okteto, it will generate a `kotsadm-{app_slug}-supportbundle` secret with following tags
```
labels:
kots.io/backup: velero
kots.io/kotsadm: "true"
troubleshoot.io/kind: support-bundle
```
```release-note
NONE
```
NONE
=> feat(support-bundle): add troubleshoot label for support-bundle spec secret

deploy/Dockerfile
This PR upgrades the helm binary in the kotsadm image to 3.11.0 to resolve CVE-2022-27664 and CVE-2022-32149 with high severity.
Fixes [SC-60523](https://app.shortcut.com/replicated/story/60523/resolve-high-severity-cve-2022-27664-in-kots)
Before:
```
trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH docker.io/kotsadm/kotsadm:v1.92.1 
```
```
usr/local/bin/helm3.9.3 (gobinary)
Total: 2 (HIGH: 2, CRITICAL: 0)
┌───────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│      Library      │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                            Title …
```
=> upgrade helm for CVE-2022-27664 and CVE-2022-32149

web/src/components/snapshots/AppSnapshots.jsx, web/src/components/snapshots/Snapshots.jsx
This I believe bug was mainly because of using ternary operators to render the no snapshots page. 
Fixes # [sc-59660]
```release-note
Fixes a visual bug that renders no snapshots message when snapshot is in progress. 
```
NONE
=> Miawong/sc 59660/Do not show no snapshots if snapshots is in progress 

pkg/api/downstream/types/types.go, pkg/store/kotsstore/downstream_store.go
There is a bug where the config icon in the UI is shown for versions that are not configurable. This helps the UI determine whether to show that icon or not.
Fixes #
```release-note
NONE
```
NONE
=> Return if a version is configurable or not

pkg/gitops/gitops.go, pkg/gitops/gitops_test.go, pkg/handlers/gitops.go
When a gitops integration is disabled, private/public keys are not deleted.
which causes `key already in use` when the public is added to github repo when re-enabling the gitops
Fixes # https://app.shortcut.com/replicated/story/47117
1. Enable and configure gitops for an app
2. Disable the gitops configuration
3. Re-enable the gitops configuration again and when adding public key to the github repo, expect error: `key already in use`
```release-note
delete private/public keys when gitops integration is disabled and keys are not in use by other applications
```
NONE
=> delete private/public keys when gitops integration is disabled and keys are not in use by other applications

deploy/kurl/kotsadm/template/base/install.sh
kots addon prints a kubectl apply warning on a clean install
Description
This shows up in testgrid runs as well.
```
curl  https://staging.kurl.sh/9ba1c1a | sudo bash
```
```
⚙  Addon kotsadm 1.79.0
...
Warning: resource configmaps/kotsadm-confg is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
configmap/kotsadm-confg configured
```
Fixes # [SC-55221: kots addon prints a kubectl apply warning on a clean install](https://app.shortcut.com/replicated/story/55221/kots-addon-prints-a-kubectl-apply-warning-on-a-clean-install)
RUN `curl …
=> add --save-config flag when creating kotsadm-confg configmap(k8s declarative configuration)

.github/workflows/build-test.yaml, pkg/api/downstream/types/types.go, pkg/handlers/app.go, pkg/helm/helm.go, pkg/store/kotsstore/downstream_store.go, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Hides the config icon if a version does not have a config
Fixes #
```release-note
Fixes an issue where the config icon is shown for application versions that do not include a config
```
NONE
=> Do not show the config icon if a version does not have a config

.github/actions/kots-e2e/action.yml, .github/workflows/build-test.yaml
Update the k3s versions used in the end to end tests and add the `--egress-selector-mode disabled` argument input when the version starts with "v1.22". In the current versions, there is a bug in the k3s control plane when using web sockets connections between the pods (default networking option) that results in the kots cli failing to create a port forward.
Fixes [SC-67356](https://app.shortcut.com/replicated/story/67356/kots-cli-port-forwarding-fails-intermittently)
This does not seem to have affected the v1.21 branch, but I updated it to the latest version anyways.
The bug in the k3s control plane was fixed by [this k3s commit](https://github.com/k3s-io/k3s/pull/6216). I'm pretty sure that's the right commit based on the code, but I didn't bisect and test.
Reasoning for why this is the …
=> Update k3s version in e2e tests to avoid the port forward bug

.github/workflows/build-test.yaml
This PR bumps the range of k3s versions used for the `build-test` workflow to 1.23 - 1.26 to align with the [currently supported](https://kubernetes.io/releases/) Kubernetes versions.
Fixes #
```release-note
NONE
```
NONE
=> bump k3s version range to 1.23 - 1.26

web/src/components/shared/EditConfigIcon.tsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx, web/src/features/Dashboard/components/DashboardVersionCard.tsx, web/src/types/index.ts
Fixes # [sc-62358]
Create a release without a `kots-config.yaml`, promote it and deploy it. 
Then create another release and add the config, promote it and check for updates. 
Config icon should render for the new version and not the currently deployed one. 
```release-note
Fixes an issue where the config icon would render when there is no config. 
```
NONE
=> Miawong/sc 62358/admin console config icon is shown for a

web/src/components/apps/AppDetailPage.tsx, web/src/components/apps/AppVersionHistory.tsx, web/src/components/modals/ErrorModal.jsx
- Styling is broken: 
Fixes #
https://app.shortcut.com/replicated/story/45028/ui-is-broken-when-deploying-a-version-in-the-version-history-page-fails-with-a-500-error
- block fetch call to deploy / redeploy and try to deploy or redeploy 
```release-note
kots/web: fixes layout of deploy / redeploy network errors 
```
NONE
=> Rianfowler/sc 45028/UI is broken when deploying a version in 2

web/src/stories/BackupRestoreModal.stories.tsx
Fixes # [sc-65991] 
```release-note
```
=> add BackupRestoreModal to storybook

web/src/stories/RestoreSnapshotModal.stories.tsx
=> add restore snapshot modal to storybook

web/src/components/troubleshoot/SupportBundleList.tsx, web/src/components/troubleshoot/SupportBundleRow.tsx, web/src/context/ToastContext.tsx, web/src/css/icon.css, web/src/scss/utilities/base.scss
Fixes an issue where if a user deletes a support bundle in progress, user can click "generate new support bundle" link. 
Fixes an issue where if a user undo a support bundle in progress, it will continue the progress. 
Fixes # [sc-67312]
```release-note
Fixes an issue where if a user deletes a pending support bundle, user can generate a new support bundle. 
```
NONE
=> Miawong/sc 67312/can t generate new support bundle after deleting

web/src/scss/utilities/base.scss, web/src/scss/utilities/overrides.scss
Fixes # [sc-67714]
```release-note
Fixes the text colors for each state the status informers may be in. 
```
NONE
=> fix colors for status informers

pkg/supportbundle/defaultspec/spec.yaml
Update the default support bundle spec to have troubleshoot collect all logs of pods running in the `rook-ceph` namespace.
Fixes https://github.com/replicatedhq/kots/issues/3318
- This PR preempts a decision of collecting all pod logs in favour of collecting logs based on field selectors
- The process of collecting a support bundle increased by about `30s` in my test cluster
```release-note
NONE
```
NONE
=> chore: collect all pod logs running in the rook-ceph namespace

go.mod, go.sum, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/logparser.go, pkg/kotsadmsnapshot/logparser_test.go
This PR utilizes the v0.6.0 of `github.com/go-logfmt/logfmt`, which [introduced a configurable buffer size](https://github.com/go-logfmt/logfmt/pull/15) for the logfmt Decoder.  These changes increase the max token size to 1MB from the [previous default size of 64KB](https://cs.opensource.google/go/go/+/master:src/bufio/scan.go;l=80).
Fixes [SC-62367](https://app.shortcut.com/replicated/story/62367/bufio-scanner-failure-when-attempting-to-download-backup-logs-which-contain-a-long-log-line)
```release-note
Fixes an issue where backup logs would fail to download if a log line exceeded the default `bufio.Scanner` buffer size of 64KB. This limit has been increased to 1MB in the admin console.
```
NONE
=> update logfmt pkg and increase buffer size

web/src/components/PreflightResultPage.tsx, web/src/features/PreflightChecks/api/getPreflightResult.tsx, web/src/features/PreflightChecks/types.ts
- re-run button is not showing up during failed preflights check in airgapped flow 
Fixes #
https://app.shortcut.com/replicated/story/69593/fix-rerun-button-on-airgapped-preflights-flow
```release-note
- kots/web: fixes and issue where Re-run preflights button would not render during failed preflights in airgapped installation flow 
```
none
=> fix rerun preflight button logic

pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go
If pods are in shutdown state and while backing up the instances, hook backup fails as it tries to exec and tries collecting files. This doesn't happen in pod backup since velero backs up only pods in running state
Fixes # [SC-53284: Velero backups will fail if pods in a Shutdown state are present](https://app.shortcut.com/replicated/story/53284)
It is not possible to create a pod with pod.status.phase as `Failed` + pod.status.reason as `Shutdown`
I have added unit tests + was able to validate the code by changing phase to ImagePullErr and check the pods have the velero exclude labels
```release-note
- Fixes a bug where velero snapshot backup failed due to pods in Shutdown state
```
NONE
=> exclude shutdown pods from backup

web/package.json, web/yarn.lock
- attempting to resolve this issue: https://github.com/replicatedhq/kots/security/dependabot/130
Fixes #
```release-note
none
```
none
=> upgrade terser

web/package.json, web/yarn.lock
- updates grafana/data to latest version for https://app.shortcut.com/replicated/story/69741/update-old-dependencies-in-kots-web
- attempting to resolve this warning: https://github.com/replicatedhq/kots/security/dependabot/128
Fixes #
```release-note
none
```
none
=> update grafana/data to latest minor version

.github/workflows/build-test.yaml, cmd/kots/cli/remove.go, pkg/handlers/app.go, pkg/operator/operator.go
Adds the ability to completely un-deploy an application including its resources from the cluster and not just the reference from the admin console
Fixes #
```release-note
Adds the ability to completely un-deploy an application including its resources from the cluster and not just the reference from the admin console by passing the `--undeploy` flag to the [kots remove](/reference/kots-cli-remove) CLI command.
```
https://github.com/replicatedhq/replicated-docs/pull/972
=> Ability to completely un-deploy an application including its resources and not just the reference

.github/workflows/build-test.yaml, pkg/operator/client/deploy.go
Fixes an issue where specifying the [namespace](/reference/custom-resource-helmchart#namespace) field in the HelmChart custom resource isn't respected when setting the [useHelmInstall](/reference/custom-resource-helmchart#usehelminstall) field to `true`.
Fixes #
```release-note
Fixes an issue where specifying the [namespace](/reference/custom-resource-helmchart#namespace) field in the HelmChart custom resource isn't respected when setting the [useHelmInstall](/reference/custom-resource-helmchart#usehelminstall) field to `true`.
```
NONE
=> fix: namespace field in HelmChart custom resource does not work when useHelmInstall is set to true

.github/workflows/build-test.yaml, cmd/kots/cli/admin-console-push-images.go, cmd/kots/cli/install.go, cmd/kots/cli/upstream-upgrade.go, cmd/kots/cli/util.go, pkg/docker/registry/auth.go, pkg/upstream/upgrade.go
Modifies the `kots install`, `kots upstream upgrade`, and `kots admin-console push-images` commands to validate the provided registry information before processing the airgap bundle.
Fixes #
```release-note
Modifies the [kots install](/reference/kots-cli-install), [kots upstream upgrade](/reference/kots-cli-upstream-upgrade), and [kots admin-console push-images](/reference/kots-cli-admin-console-push-images) commands to validate the provided registry information before processing the airgap bundle.
```
https://github.com/replicatedhq/replicated-docs/pull/975
=> Check whether the registry connection is valid before unpacking the airgap bundle

pkg/docker/registry/auth.go
Adds support for ACR registries by fixing an issue where configuring / validating an ACR (Azure Container Registry) registry from the admin console fails with "service is not specified".
Fixes #
```release-note
Adds support for Azure Container Registry (ACR)
```
https://github.com/replicatedhq/replicated-docs/pull/976
=> Add support for ACR registries

pkg/print/velero.go
Fixes the printed Velero docs link when running `kots velero configure-<>` commands to point to 1.10 instead of 1.9
Fixes #
```release-note
NONE
```
NONE
=> Fix printed Velero docs links to point v1.10 instead of v1.9

.github/workflows/release.yaml
* Removes the unnecessary usage of `github-action-get-latest-release` and replaces it with a short `github-script` to achieve the same effect, using an authenticated token to eliminate rate-limiting errors. The action is unnecessary overhead and security risk for the value it provides. The `repos.getLatestRelease` call implicitly excludes draft and prerelease releases, and the `github` object is a REST client authenticated with the default `GITHUB_TOKEN`.
* Replace deprecated `::set-output::` usage
```release-note
NONE
```
NONE
=> replace usage of github-action-get-latest-release [sc-70357]

.github/workflows/build-test.yaml, pkg/appstate/statefulsets.go
Change the status informer for stateful sets to use a comparison between the controller-revision-hash of the pods in the set to determine the updating status. Similar to how the daemon set is done.
Fixes https://github.com/replicated-collab/h2o-replicated/issues/48
Note there are two edge cases with this method:
* When the last pod is restarting, the status changes from updating to degraded and then ready once the last pod is ready.
* If an update is deployed and pods that should be restarted do not go down and new pods do not come up, then this will always report being ready instead of upgrading or degraded.
Create an app release with the k8s Kind: StatefulSet and in the app manifest make sure there is the following line:
```
StatusInformers:
- statefulset/<statefulset name>
```
Where …
=> Change stateful set status informer updating calculation

deploy/kurl/kotsadm/template/base/rqlite.yaml, migrations/kustomize/overlays/dev/rqlite.yaml, migrations/kustomize/overlays/okteto/rqlite.yaml, pkg/kotsadm/objects/rqlite_objects.go, pkg/supportbundle/defaultspec/spec.yaml
Add a rqlite backup collector 
- Update rqlite statefulsets with RQLITE_PASSWORD which will be used for rqlite db backup
Fixes # https://app.shortcut.com/replicated/story/63348/add-an-rqlite-collector-similar-to-the-pg-dump-one-that-was-used-for-postgres
```release-note
add a support bundle collector for rqlite backup
```
=> add collector for rqlite backup

web/src/components/PreflightResultPage.tsx
Fixes # https://app.shortcut.com/replicated/story/51249/there-should-be-a-rerun-button-on-the-preflights-page-during-initial-install
1. Install a new app
2. you can re-run if some checks have failed
```release-note
Adds re-run button on the preflights page during initial install
```
NONE
=> Bug: add re-run button to preflight check

.github/workflows/release.yaml
Stop using the legacy buildkite builder image for the `release / build-web` job in favor of the bare GitHub runner.
This image is extremely out of date, and this is the only job in this workflow that uses a container image; my suspicion is that the use of the builder image is a leftover artifact from the original and is unnecessary.
```release-note
NONE
```
NONE
=> stop using buildkite builder image for release web build 

.github/workflows/e2e-infra-cleanup.yaml
* Fixes an inadvertent behavior change in e2e-infra-cleanup which captured whitespace in the workspace names, causing terraform to fail.
Fixes #
```release-note
NONE
```
NONE
=> fix cleanup workspace gather to address extra whitespace

web/src/scss/variables.scss
- the underline in the subnav was not showing up. swapped out the component to use a css variable but forgot to set a value to that variable in previous PR. 
```release-note
kots/web: fixes an issue where the selected subnav tab did not render an underline 
```
none
=> fix accent color

.github/workflows/e2e-infra-cleanup.yaml
Fixes scheduled cleanup being too greedy with workspaces.
The terraform wrapper set up by the action is not correctly using environment variables that haven't been exported. This change addresses that by exporting the variable in the loop.
Fixes #
```release-note
NONE
```
NONE
=> Fix cleanup

pkg/k8sutil/portforward.go
when app port-forward port is not available, failure message prints repeatedly
Fixes # https://app.shortcut.com/replicated/story/65158/kots-cli-when-app-port-forward-port-is-not-available-failure-message-prints-repeatedly
1. In replicated application spec, set service/ports which don't exist/defined
2. deploy application
3. run `kubectl kots admin-console` to expose an admin-console on a port
4. and can see the repeatable errors
5. <img width="813" alt="image" src="https://user-images.githubusercontent.com/8703626/225329849-ee960e02-411a-49fa-b4cb-42193aaed252.png">
```release-note
When enabling access to admin-console using command `kubectl kots admin-console`, if application port-forward port is not available, failure message are printed once and retried in silent
```
=> KOTS CLI: when app port-forward port is not available, failure message are printed once and retry in silent

pkg/handlers/troubleshoot.go, pkg/kotsadm/types/constants.go, pkg/supportbundle/spec.go, pkg/supportbundle/spec_test.go, pkg/supportbundle/staticspecs/clusterspec.yaml, pkg/supportbundle/staticspecs/defaultspec.yaml, pkg/supportbundle/staticspecs/embed.go, pkg/supportbundle/staticspecs/kurlspec.yaml, pkg/supportbundle/staticspecs/vendorspec.yaml, pkg/supportbundle/supportbundle.go
- split the current support bundle spec into vender spec, default spec and cluster spec, embed them as code under kots/pkg/supportbundle 
- remove injectDefaults to simplify way of generate specs
- seperate default spec into defaultspec and kurlspec, so we can remove removeKurlCollectors & removeKurlAnalyzers
- deduplicatedCollectors and deduplicatedAnalyzers rewritten
Shortcut: #
[sc-70445](https://app.shortcut.com/replicated/story/70445/simplify-implementation-handling-the-support-bundle-spec)
```release-note
NONE
```
NONE
=> feat(support-bundle): simplify implementation handling the support bundle spec

.github/workflows/build-test.yaml, pkg/helm/update_release.go, pkg/helm/update_release_test.go, pkg/operator/client/deploy.go, pkg/operator/client/deploy_test.go
Helm upgrade fails for charts installed with KOTS versions earlier than 1.95.0
Helm Release Version Secrets were created in kots installed namespace earlier to kots v1.95.0
and in kots v1.95.0 after secrets started to respect kots HelmChart namespace, 
helm upgrade expects these secrets to be their respective namespace
Fixes # https://app.shortcut.com/replicated/story/72389/helm-upgrade-fails-for-charts-installed-with-kots-versions-earlier-than-1-95-0
```release-note
fix a bug where helm release secret was created in kotsadm namespace instead helm release namespace
```
NONE
=> migrate helm release version secrets to helm namespace

.github/actions/kurl-addon-kots-generate/action.yml, deploy/kurl/kotsadm/hack/Makefile
fix kots kurl release
```
LINE asset kots.tar.gz bin/kots.tar.gz
realpath: /home/runner/work/kots/kots/2023.3.24-b20579-nightly/bin/kots.tar.gz: No such file or directory
cp: cannot stat '': No such file or directory
Error: Process completed with exit code 1.
```
=> fix: use absolute path for kots.tar.gz kurl manifest asset

kurl_proxy/cmd/main.go, kurl_proxy/go.mod, kurl_proxy/go.sum
This PR updates the list of accepted cipher suites in kurl_proxy.  The previous package used was outdated and included cipher suites that are now considered weak because they use the CBC encryption algorithm and SHA-1.
This approach aims to replicate the tls configuration provided by the previous package, but with a stronger list of cipher suites: https://github.com/docker/go-connections/blob/master/tlsconfig/config.go#L57-L70
Old List:
```
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA // removed
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA // removed
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA // removed
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA // removed
```
New …
=> update kurl_proxy to use stronger cipher suites

pkg/kotsadm/api.go, pkg/kotsadm/main.go, pkg/kotsadm/objects/configmaps_objects.go
Preserves KOTS install ID on upgrades
Fixes [SC-72983](https://app.shortcut.com/replicated/story/72983/kots-installation-id-gets-removed-on-upgrades)
```release-note
NONE
```
NONE
=> Fix: Preserve KOTS install ID on upgrades

pkg/helm/update_release.go, pkg/helm/update_release_test.go
Fixes a bug where helm release secret creation fails when release secret already exists in release namespace
Fixes # https://app.shortcut.com/replicated/story/73142/helm-deployment-fails-if-the-helm-release-secret-already-exists-in-the-target-namespace
```release-note
Fix the bug that caused the deployment to fail when the migration of Helm release secrets failed because the release secret already existed in the release namespace.
```
=> ignore secret already exists err when creating the helm release secret in release namespace

pkg/helm/charts.go
The `kots-<helm chart name>-config` secret used by the helm managed mode prevents multiple installs of an app's helm charts with different release names. After the first release is installed, any subsequent install using a different release name will fail because the secret already exists. This PR changes the secret name to be `kots-<helm chart name>-<helm release name>` to be unique for each release.
The real fix to this bug is in this vandoor PR: https://github.com/replicatedhq/vandoor/pull/3105
Fixes https://github.com/replicated-collab/cased-kots/issues/31
Once the vandoor PR is merged and released, kots helm managed mode will not function properly on any kots versions without this change.
I used okteto to reproduce to make deploying vandoor easier.
* If needed create a new okteto …
=> store helm release name with chart name secret

web/src/components/UploadAirgapBundle.jsx
before
after
Fixes # [sc-59544]
```release-note
Simplifies wording on airgap bundle upload page
```
NONE
=> simplify airgap bundle upload text

web/src/components/config_render/ConfigCheckbox.tsx, web/src/components/config_render/ConfigFileInput.jsx, web/src/components/config_render/ConfigGroup.jsx, web/src/components/config_render/ConfigInput.jsx, web/src/components/config_render/ConfigSelectOne.jsx, web/src/components/config_render/ConfigTextarea.jsx, web/src/scss/components/config-render/config-base-styles.scss
- improve spacing between items on config page
Fixes # https://app.shortcut.com/replicated/story/70387/improve-spacing-on-config-page-to-make-it-clear-which-lines-are-part-of-which-config-items
```release-note
- admin console: updated spacing and font sizes to improve visual grouping of items on config page 
```
none
=> Rianfowler/sc 70387/improve spacing on config page to make it

migrations/tables/instance-report.yaml, migrations/tables/preflight-report.yaml, pkg/api/reporting/types/types.go, pkg/handlers/deploy.go, pkg/handlers/gitops.go, pkg/handlers/mock/mock.go, pkg/handlers/preflight.go, pkg/online/online.go, pkg/operator/client/client.go, pkg/operator/operator.go, pkg/preflight/preflight.go, pkg/reporting/app.go, pkg/reporting/app_airgap.go, pkg/reporting/app_online.go, pkg/reporting/preflight.go, pkg/reporting/preflight_airgap.go, pkg/reporting/preflight_online.go, pkg/reporting/types.go, pkg/reporting/util.go, pkg/store/kotsstore/reporting_store.go, pkg/store/mock/mock.go, pkg/store/store_interface.go, pkg/updatechecker/updatechecker.go
This change allows collecting instance reporting info in the local database which can be included in support bundles.  It is included by default with rqlite db dump.
Fixes #
The collected data mimics what Admin Console sends to replicated.app service with normal HTTP requests.
```release-note
NONE
```
NONE
=> Store instance reports in db for airgap installs

deploy/Dockerfile, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
This PR bumps the version of the Helm binary included in the kotsadm image to 3.11.3 to resolve CVE-2022-41723 and CVE-2023-25173 with high severity and CVE-2023-25153 with medium severity.
Fixes [SC-71760](https://app.shortcut.com/replicated/story/71760/cve-2022-41723)
Run trivy scan:
```
trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH,MEDIUM kotsadm/kotsadm:main
```
Before:
```
usr/local/bin/helm3.11.0 (gobinary)
Total: 3 (MEDIUM: 1, HIGH: 2, CRITICAL: 0)
┌──────────────────────────────────┬────────────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│             Library              │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                            Title …
```
=> bump helm binary to 3.11.3

pkg/kotsutil/kots.go, pkg/operator/operator.go, pkg/operator/operator_test.go
This PR adds the ability to use template functions in the HelmChart resource `spec.namespace` and `spec.helmUpgradeFlags` fields so that those fields can be set dynamically for the deployment.
This is more of a temporary solution as we work to support template functions in all fields for all kots kinds.
Fixes [SC-71700](https://app.shortcut.com/replicated/story/71700/namespace-and-helmupgradeflags-field-in-helmchart-custom-resource-do-not-support-templating)
Added a new unit test for the operator that will validate that helm chart namespace and upgrade flags are templated before deploying.
Run operator tests:
```
go test -tags='testing netgo containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp' -installsuffix netgo ./pkg/operator …
```
=> template namespace and helmUpgradeFlags

pkg/airgap/airgap.go, pkg/airgap/update.go, pkg/gitops/gitops.go, pkg/handlers/config.go, pkg/handlers/download.go, pkg/handlers/identity.go, pkg/handlers/preflight.go, pkg/handlers/rendered_contents.go, pkg/handlers/upload.go, pkg/kotsadmconfig/config.go, pkg/kotsadmlicense/license.go, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmupstream/upstream.go, pkg/online/online.go, pkg/operator/operator.go, pkg/preflight/preflight.go, pkg/pull/pull.go, pkg/registry/registry.go, pkg/render/render.go, pkg/reporting/app.go, pkg/rewrite/rewrite.go, pkg/store/kotsstore/migrations.go, pkg/store/kotsstore/version_store.go, pkg/supportbundle/supportbundle.go, pkg/tests/base/render_test.go, pkg/version/metrics.go
Change most invocations of `kotsutil.LoadKotsKindsFromPath(archiveDir)` to `LoadKotsKindsFromPath(filepath.Join(archiveDir, "upstream"))` so that the unrendered kots kinds for the upstream directory are loaded. The addition of the 'kotsKinds' directory with rendered kots kinds changes the behavior of `kotsutil.LoadKotsKindsFromPath(archiveDir)` to loading the rendered kots kinds when the pre-rendered kinds were expected. Specifying the 'upstream' sub-directory returns the previous behavior.
Part of issue #73043
The addition of the 'upstream' subdirectory was not done in the `kotsutil.LoadKotsKindsFromPath()` function because it may be used to load the 'kotsKinds' directory in the future, some of the calls already specified the upstream directory, and finally, it's used to specify the …
=> calls to LoadKotsKindsFromPath use the "upstream" dir

pkg/pull/pull.go
Fixes issue reading application metadata from airgap bundle:
```
$ ./bin/kots install craig-helm -n craig-helm-airgap --shared-password password --license-file craig-helm-customer.yaml --airgap-bundle craig-helm-7.13.7.airgap
Error: failed to get metadata from craig-helm-7.13.7.airgap: failed to read kots kinds: failed to walk upstream dir: lstat /var/folders/gc/ttg5vd3178g0kdq_ghkrzjqm0000gn/T/kotsadm2607356351/upstream: no such file or directory
```
Fixes https://replicated.slack.com/archives/C02TQTV9G2V/p1681913858449849
```release-note
NONE
```
NONE
=> fix: loading kots kinds from airgap bundle

web/src/features/AppConfig/components/AppConfig.tsx
- fixes issue with required fields blocking when they're hidden 
https://app.shortcut.com/replicated/story/28650/kotsadm-validation-of-config-options-entered-by-user
```release-note
none
```
none
=> add check for when property at group and item level when determining required error state 

pkg/store/kotsstore/reporting_store.go
The column type is `number` and the value is `string`.  Apparently rqlite handles the cases when string is numeric automatically, but fails if the value is an empty string.
Fixes #
```release-note
```
=> Fix reporting when app is not deployed

cmd/kots/cli/admin-console-push-images.go
Add a warning to `kubectl kots push-images <airgap bundle>` if the airgap bundle specified is both not a valid file and not a valid URL. Without the warning the command appears to have successfully pushed the images.
Fixes #
`kubectl kots admin-console push-images www.google.com ttl.sh` runs successfully with no warning that 'www.google.com' is not a valid airgap bundle and no airgap images were pushed.
```release-note
NONE
```
NONE
=> add warning if push-images airgap file doesn't exist

integration/docker/registry/assets/manifests.yaml, integration/docker/registry/temp_registry_test.go, pkg/docker/registry/temp_registry.go
Fixes an issue where uploading an airgap bundle through the admin console might fail due to issues in getting layers for OCI images.
Fixes #
Reference: https://github.com/containers/image/blob/f5e31f1bcc87fb222786b73a1426bbb5d1507a65/docker/docker_image.go#L143-L145
```release-note
Fixes an issue where uploading an airgap bundle through the admin console might fail due to issues in getting layers for OCI images.
```
NONE
=> fix: process of uploading airgap bundle through the UI sometimes fails to get image layers

.github/workflows/build-test.yaml, cmd/kots/cli/admin-console-copy-public-images.go, cmd/kots/cli/admin-console-push-images.go, cmd/kots/cli/admin-console.go, deploy/assets/kots-upgrade.sh, pkg/kotsadm/copy_images.go
Create the subcommand `copy-public-images` of `admin-console` to copy the public admin console images to a private registry.
Previously the `kots admin-console push-images` command invoked this functionality when passed the argap bundle of "docker.io". Instead of hiding the command behind a secret invocation of another command, this makes copying the public admin console images an explicit command. This also fixes the bug where the `kots admin-console push-images` command would push the public images and exit successfully if the provided airgap bundle didn't exist.
Fixes https://app.shortcut.com/replicated/story/72920/kots-admin-console-push-images-does-not-surface-any-errors-if-airgap-bundle-provided-is-missing
Check out this slack thread for more context on this decision: …
=> Create sub-command 'admin-console copy-public-images'

web/src/components/PreflightResultPage.tsx
version history page
- adds back button for preflight checks page. 
- merge re-run and re-run with limited preflights into one button
Fixes # 
```release-note
Adds back button for preflight checks page 
```
NONE
=> add back button to preflight 

pkg/handlers/login.go, pkg/handlers/session.go
Addresses additional feedback from PR #3810 :
- Removes unused Token from LoginResponse struct
Fixes #
```release-note
NONE
```
NONE
=> updates to auth and session functions

web/src/features/Dashboard/components/Dashboard.tsx
Fixes # https://app.shortcut.com/replicated/story/63472/add-fetch-refetch-disclosures-to-details-modal
```release-note
Display 'last updated' time in the resource status modal to indicate when the data was last automatically fetched.
```
NONE
=> show last updated in details modal

web/src/features/AppConfig/components/AppConfig.tsx
- only show FE validation error message if there's no message provided by the API 
- this includes on change to the helm test. requires merging testim branch after this is merged 
Fixes # https://app.shortcut.com/replicated/story/75670/errors-when-saving-config-are-not-propagated-to-ui
- shows the backend error when there is one. otherwise it falls back to the FE supplied error related to validation 
```release-note
Config page will now show the correct error message for errors not related to validation. 
```
None
=> use configError over validationErrorMessage

web/src/features/AppConfig/components/ConfigInfo.jsx
deployed config"
Fixes # https://app.shortcut.com/replicated/story/75066/when-there-are-no-deployed-app-and-multiple-app-versions-config-screen-shouldn-t-show-edit-the-currently-deployed-config
```release-note
Fixes an issue where it incorrectly displays "edit currently deployed config" when there is no app deployed. 
```
=> check for current version to render "edit currently deployed version"

pkg/handlers/login.go, web/src/features/Auth/components/SecureAdminConsole.tsx
Sets the signedToken as an httpOnly cookie when the user logs in via OIDC. 
The cookie is used to authenticate the user's session.
Fixes #
```release-note
NONE
```
NONE
=> set httpOnly auth cookie when logging in through OIDC

pkg/store/kotsstore/preflight_store.go
This PR fixes an issue with the version history that occurs when an application is being deployed while preflights are running.  If the preflights finished while the app was still deploying, the version status would be reset to `pending` causing a weird UI:
Fixes [SC-76166](https://app.shortcut.com/replicated/story/76166/ui-shows-an-incorrect-state-after-deploying-version-from-version-history-page)
1. Create an application and deploy the initial version.
2. Make a config change
3. Deploy the new version for the version history page before preflights complete
4. Observe the UI state shown above if preflights finish before the deploy finishes
```release-note
Fixes an issue where the version history might incorrectly show a "Deployed" button if an application version was being deployed while …
```
=> fix: version status deploying and preflights running

pkg/kotsadm/objects/rqlite_objects.go, pkg/supportbundle/defaultspec/spec.yaml, pkg/supportbundle/staticspecs/defaultspec.yaml
- use `containerName: rqlite` in all the rqlite statefulset spec
- remove `containerName: rqlite` from sb spec
reason: if the container name for rqlite is changed, the collector will fail.
relying on troubleshoot to select the default container name for collection is better.
https://troubleshoot.sh/docs/collect/exec/#containername-optional
```
The name of the container in which to execute the command. if not specified, the first container in the pod will be used.
```
Fixes # https://app.shortcut.com/replicated/story/76050/rqlite-db-dump-is-no-longer-included-in-support-bundle
```release-note
Fixes a bug where the rqlite collector was unable to collect a data dump if the name of the rqlite container was changed.
```
NONE
=> remove containerName: rqlite from sb spec

pkg/operator/operator.go
Applies application status informers before deploying the application resources as the deployment process can take a long time and it can be useful to check the statuses of different resources while the deployment is happening.
Fixes #
```release-note
Applies application status informers before deploying the actual resources. This can be helpful in cases where deployments can take a long time as the statuses will be available while the deployment is happening.
```
NONE
=> Apply status informers before deploying the app

web/webpack.config.dev.js
https://webpack.js.org/configuration/devtool/
Firefox
Chrome
Fixes # https://app.shortcut.com/replicated/story/75720/remove-source-maps-from-main-bundle-in-dev-build-of-admin-console
1. Run admin console and inspect the network tab for main.[number].js 
```release-note
NONE
```
NONE
=> update sourcemap type to reduce bundle size

web/src/features/Dashboard/components/DashboardLicenseCard.tsx, web/src/scss/utilities/utilities.scss
remove flex-auto from channelTag
This arose from a testim failure: https://app.testim.io/#/project/wpYAooUimFDgQxY73r17/branch/master/test/GP2APVMVJP1moSWn/step/311nJG5ayqwcqEXj/viewer/screenshots?result-id=O3vTga9u1MWwQWg4&path=frCGuJg9nK9aEVM3%3A311nJG5ayqwcqEXj
From testim: 
After fix: 
Fixes # https://app.shortcut.com/replicated/story/75115/improve-layout-for-long-strings
```release-note
NONE
```
NONE
=> fix license customer name when it's long

web/src/components/modals/BackupRestoreModal.jsx
HEATMAP 
BEFORE
AFTER
Fixes # [sc-75727] 
```release-note
Replace the misleading call-to-action button that could mistakenly lead the user to believe it initiates the instance restore process.
```
=> improve ux of backup restore modal - replace call to action 

pkg/apparchive/helm-v1beta2.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go, pkg/tests/pull/cases/v1beta2-charts/upstream/my-excluded-chart.yaml, pkg/tests/pull/cases/v1beta2-charts/wantResults/helm/my-chart-release/values.yaml, pkg/tests/pull/cases/v1beta2-charts/wantResults/kotsKinds/my-chart.yaml, pkg/tests/pull/cases/v1beta2-charts/wantResults/kotsKinds/my-excluded-chart.yaml, pkg/tests/pull/cases/v1beta2-charts/wantResults/upstream/my-chart.yaml, pkg/tests/pull/cases/v1beta2-charts/wantResults/upstream/my-excluded-chart.yaml
This PR fixes an issue where v1beta2 HelmChart `spec.optionalValues[i].when` field did not have template functions rendered before it was parsed as a boolean.  This could lead to errors like the following:
```
{"level":"error","ts":"2023-05-17T19:50:25Z","msg":"rewrite directory: failed to write helm v1beta2 charts: failed to parse when conditional on optional values: strconv.ParseBool: parsing \"repl{{ HasLocalRegistry }}\": invalid syntax"}
```
This PR changes the logic so that the `when` field is rendered prior to parsing.
This PR also fixes an issue where the `exclude` field was not taken into account for v1beta2 charts.
Fixes #
v1beta1 HelmChart resources are templated before this merging of values occurs as part of [this function](https://github.com/replicatedhq/kots/blob/main/pkg/ba …
=> fix: exclude and when for v1beta2 charts

deploy/Dockerfile, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
Bumps Helm to 3.12.0, which resolves a compatibility issue with k8s 1.27: https://github.com/helm/helm/issues/12061
Fixes #
Install an application on a kURL cluster with k8s 1.27 that uses native helm.
```release-note
Bumps the Helm version used by KOTS to 3.12.0 to fix an issue where Native Helm installations were failing on Kubernetes 1.27
```
https://github.com/replicatedhq/replicated-docs/pull/1169
=> fix: bump helm to 3.12.0

web/okteto.Dockerfile, web/skaffold.Dockerfile
This PR updates the base image for the frontend kotsadm-web images used in the development environments (Okteto and Skaffold).  This resolves a [failure](https://github.com/replicatedhq/kots/actions/runs/5072591325/jobs/9110486447) in the release pipeline because an older Debian stretch image was being used.  This isn't a critical fix, but something we should keep probably up-to-date.
Fixes https://github.com/replicatedhq/kots/actions/runs/5072591325/jobs/9110486447
```release-note
NONE
```
NONE
=> update base for web dev images

pkg/handlers/troubleshoot.go, pkg/supportbundle/supportbundle.go, web/src/components/UploadAirgapBundle.jsx
Reverts replicatedhq/kots#3856
There's a troubleshoot bug with --load-cluster-specs.
=> Revert "update CLI support bundle command"

pkg/handlers/troubleshoot.go, pkg/supportbundle/supportbundle.go, web/src/components/UploadAirgapBundle.jsx
https://app.shortcut.com/replicated/story/69757/show-customer-improved-cli-support-bundle-command-for-collecting-support-bundles
Reverting the revert since we can now test embedded clusters with the latest troubleshoot release 0.65.0
Reverts replicatedhq/kots#3909
=> update CLI support bundle command

deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-proxy.yaml, deploy/kurl/kotsadm/template/base/install.sh, deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-proxy.yaml
In order to handle two distinct proxies that may exist in the system separately, it is necessary to treat them individually. The presence of a second environment variable, `PROXY_HTTPS_ADDRESS`, indicates the configured https proxy.
This PR ensures the appropriate utilization of the correct env variable for the https proxy.
Depends on https://github.com/replicatedhq/kURL/pull/4538.
Fixes # [sc-70304]
```release-note
Kots starts to support different proxies for HTTP and HTTPS access.
```
=> bug: setting https proxy to the right value

pkg/base/replicated.go, pkg/base/replicated_test.go, pkg/base/templates.go, pkg/upstream/replicated.go, pkg/upstream/replicated_test.go
Fixes two issues for releases that combined their manifests into a multi-doc yaml file:
- KOTS was failing to create config values.
- Config spec section of the multi-doc yaml was missing from the rendered kotsKinds file.
This was the error logged by kotsadm:
```
• Pulling upstream
• failed to create config values: failed to decode values: Object 'Kind' is missing in ''
• Creating base
• Creating midstreams
• Creating downstream "this-cluster"
```
As a result the `upstream/userdata/config.yaml` was missing when viewing or downloading the files.
Under the `kotsKinds` directory the config spec would be missing from the multi-doc release file:
```
---
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
name: support-bundle
spec:
...
---
<-- config spec should be here
--- …
```
=> fix creation of config values for multi-doc releases

web/src/components/shared/forms/InputField.jsx
Fixes # https://app.shortcut.com/replicated/story/78596/kots-readonly-config-items-appear-editable-in-the-ui
```release-note
Input items can be set to readonly, preventing the users from editing the fields in the UI in the config page. 
```
NONE
=> add disabled and readOnly attr to InputField component

web/src/components/config_render/ConfigRender.jsx
This PR fixes an issue where the config UI would not render repeatable config options ([loom](https://www.loom.com/share/c6f31cbd67d74f53802a3d0a5aec7fb1) of issue).  This was because an `undefined` set of `groups` was being passed to the `triggerChange` function when a repeatable item was added or removed.  This caused a second API call to be made that did not send `configGroups` and would result in the config page being reset to the initial state.
As noted in the code [here](https://github.com/replicatedhq/kots/blob/main/web/src/components/config_render/ConfigRender.jsx#L21-L22), it seems that `this.props.getData(groups)` always returns `undefined`, which looks to have led to this issue since the result was passed to `triggerChange` when adding/removing repeatable items.  This PR …
=> fix: repeatable config options ui

.github/workflows/build-test.yaml, .github/workflows/release.yaml
This PR fixes an issue where unit tests relying on kustomize as a runtime dependency were failing.  It seems that the GH runners no longer shipped with it be default, so this PR adds a setup step to install the appropriate binary.
The PR also includes the changes from https://github.com/replicatedhq/kots/pull/3960 since both are necessary to get all tests passing for the `validate-success` requirement.
Fixes https://github.com/replicatedhq/kots/actions/runs/5468790382/jobs/9972117503#step:4:129
```release-note
NONE
```
=> setup-kustomize in ci-test-kots

.github/workflows/alpha.yaml
Fixes the alpha workflow since Kustomize 5.1, which is now the default on GH runners is not compatible with KOTS, so unit tests will fail.
Fixes https://github.com/replicatedhq/kots/actions/runs/5514478209/jobs/10053836623#step:6:330
```release-note
```
=> fix alpha workflow kustomize

pkg/airgap/update.go
This PR fixes an issue where the `rendered` directory was not being created for airgap updates.  We have [new code](https://github.com/replicatedhq/kots/pull/3964) that searches the rendered manifests for preflights that is resulting in the error:
```
{"level":"error","ts":"2023-07-17T17:10:34Z","msg":"failed to update app from airgap bundle: failed to update app: failed to start preflights: failed to load troubleshoot kinds from path: /tmp/kotsadm2173489735/rendered: failed to walk dir: /tmp/kotsadm2173489735/rendered: failed to walk dir: /tmp/kotsadm2173489735/rendered: lstat /tmp/kotsadm2173489735/rendered: no such file or directory"}
```
Fixes #
```release-note
Fixes an issue where the `rendered` directory was not being created for airgap application updates
```
NONE
=> add downstreams for airgap update

pkg/appstate/ingress.go, pkg/appstate/ingress_test.go, pkg/k8sutil/clientset.go, pkg/k8sutil/clientset_test.go
add default-http-backend ingress service when k8s version is < 1.22
Fixes # https://app.shortcut.com/replicated/story/81855/app-status-not-showing-deployed-application-as-ready-even-if-the-app-is-running
```release-note
NONE
```
NONE
=> add default-http-backend ingress service when k8s version is < 1.22

e2e/velero/cli.go, pkg/template/config_context.go, pkg/upstream/replicated.go, pkg/upstream/replicated_test.go
Fixes an issue where defaults were not used for [repeatable config items](/reference/custom-resource-config#repeatable-items) when doing an automated install via the KOTS CLI.
Fixes #
```release-note
Fixes an issue where defaults were not used for [repeatable config items](/reference/custom-resource-config#repeatable-items) when doing an automated install via the KOTS CLI.
```
NONE
=> Use defaults for repeatable config items if values are not provided

pkg/base/helm.go, pkg/base/helm_test.go
Fixes an issue where processing Helm charts or sub-charts that have `-charts` as a suffix failed.
Fixes #
```release-note
Fixes an issue where processing Helm charts or sub-charts that have `-charts` as a suffix failed.
```
NONE
=> Fix processing charts/subcharts that have '-charts/' as a suffix in the name

deploy/Dockerfile, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
Upgrades the Helm binary in the kotsadm image to 3.12.2 to resolve CVE-2023-2253 with high severity
Fixes https://app.shortcut.com/replicated/story/79329/cve-2023-2253
```release-note
Upgrades the Helm binary in the kotsadm image to 3.12.2 to resolve CVE-2023-2253 with high severity
```
NONE
=> upgrade to helm 3.12.2 to resolve CVE-2023-2253

pkg/k8sutil/clientset.go, pkg/reporting/app.go, pkg/reporting/distribution.go, pkg/reporting/distribution_test.go
This check doesn't work as intended. It checks for the presence of an auto.gke.io resource group, but both standard and autopilot clusters can have this. This PR changes the reporting logic so that all GKE clusters (autopilot and standard), will be reported as `gke`.
The changes mimic those from the SDK: https://github.com/replicatedhq/replicated-sdk/pull/59
Fixes [SC-84648](https://app.shortcut.com/replicated/story/84648/app-manager-instance-insights-show-a-mix-of-gke-and-gke-autopilot-in-the-cluster-type-stream)
Install KOTS to a standard GKE cluster.  Without these changes it will report as `gke-autopilot`, with the changes it will just report as `gke`.
```release-note
Removes the distinction between `gke` and `gke-autopilot` from Kubernetes distribution reporting as this check was not …
```
=> remove gke autopilot distro reporting

.github/actions/kots-gke-create/reserve-capacity.yaml, .github/workflows/build-test.yaml
The `validate-gke-install` test has become increasingly flaky and fails more often than not.  This happens because the `kotsadm` pod is preempted by GKE when the test application pods are deployed and the autopilot cluster has not yet scaled up.  This PR changes the test script to deploy a handful of lower-priority pods that will cause the cluster to begin scaling up before KOTS is deployed.  These pods are also assigned a lower priority class, so they will be the target of preemption, should it occur.  This follows the pattern outlined in GKE documentation: https://cloud.google.com/kubernetes-engine/docs/how-to/capacity-provisioning
More context: https://replicated.slack.com/archives/C02TQTV9G2V/p1692312543883379
Fixes #
```release-note
NONE
```
NONE
=> reserve capacity for gke autopilot test

pkg/apiserver/server.go, pkg/handlers/custom_metrics.go, pkg/handlers/custom_metrics_test.go, pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/middleware.go, pkg/handlers/mock/mock.go, pkg/handlers/session.go, pkg/policy/middleware.go, pkg/replicatedapp/api.go, pkg/reporting/app.go, pkg/session/middleware.go, pkg/store/mock/mock.go
https://app.shortcut.com/replicated/story/85778/endpoint-in-kots-to-receive-dispatch-custom-metrics-to-replicated-app
This add an API endpoint for application to report custom metrics.  The metrics payload is a flat json object where each key is a scalar value.  Data is forwarded to replicated.app synchronously.
replicated.app endpoint does not yet exist and will be updated before this PR is merged.
Fixes #
```release-note
* Adds kotsadm API to send custom application metrics to replicated.app service
```
Yes, TODO.
=> API to accept metrics from application

deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml, deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
Updates the kotsadm deployment/statefulset in kurl to use an EmptyDir volume for the `tmp` directory. This is consistent with the behavior on existing cluster installs. The main reason this is done is to avoid permissions issues on the host that might be caused by the end customer's environment.
Fixes #
```release-note
- Fixes an issue where uploading the application air gap bundle could fail due to a permissions issue when creating files under the `/tmp` directory inside the `kotsadm` pod/container. This is only applicable to embedded cluster installs.
```
NONE
=> Use empty dir for tmp dir in embedded clusters as well

.github/actions/kots-gke-create/reserve-capacity.yaml, pkg/handlers/registry.go
(cherry picked from commit 004d72d53117f79c5796a7fdb3f252a925906b0f)
This PR fixes a race condition where the backend would return a response from the PUT `/api/v1/app/{appSlug}/registry` handler before the image re-writing task started.  This could result in a scenario where the UI polls the `/api/v1/app/{appSlug}/imagerewritestatus` endpoint before there is a task status, so the backend will return a response indicating that image re-writing is complete even though it has not even begun.  This causes the UI to not display the spinner and status messages, as expected.
Example of this in our tests: https://app.testim.io/#/project/wpYAooUimFDgQxY73r17/branch/ricardomaraschini%2Fsc-86964%2Fkots-test-workflow-for-helmvm/test/aPhWnwQiqtBxx2sn/step/wbZJmRizYrvNWuVc/viewer/screenshots?result-id= …
=> fix: race condition when updating registry settings

pkg/apiserver/server.go, pkg/handlers/custom_metrics.go, pkg/handlers/custom_metrics_test.go, pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/middleware.go, pkg/handlers/mock/mock.go, pkg/handlers/session.go
Custom metrics API no longer requires license ID in the authorization header. This also means that custom metrics can no longer be reported in multi-app installs.  The main reason for this change for consistency with Replicated SDK, where license ID is not necessarily known.
Fixes #
```release-note
- Custom metrics API no longer requires authorization header.
```
https://github.com/replicatedhq/replicated-docs/pull/1441
=> Remove authorization header from custom metrics API

pkg/template/static_context.go
Adds support for Lookup function (similar to Helm)
Fixes [SC-85466](https://app.shortcut.com/replicated/story/85466/add-template-function-to-check-if-a-any-version-has-been-deployed)
No tests added for now as this is directly using the Helm lookup functionality.
```release-note
Adds support for `Lookup` template function.
```
TBD
=> Add support for 'Lookup' template function

.github/workflows/build-test.yaml, pkg/apparchive/helm-v1beta2.go
This PR fixes an issue where the charts from the previously deployed version were not being removed if they were no longer part of the current version.  This happened because the `helm` directory for v1beta2 charts was not cleared out before the charts for the current version were written, so even if the chart was not part of the current version, KOTS would still include it as part of the deployment.
https://app.shortcut.com/replicated/story/89845/v1beta2-helm-charts-don-t-get-removed-when-excluded-later-on
Install a chart that has a conditional `exclude` field from a config option.  Toggle the config option to exclude the chart.  Observe that the chart is excluded and uninstalled.
```release-note
Fixes an issue where previously deployed v1beta2 helm charts were not being uninstalled as …
```
=> fix: clear v1beta2 helm directory before writing new charts

.github/workflows/build-test.yaml, web/src/components/modals/AutomaticUpdatesModal.tsx
This PR adds some language to the automatic updates modal in the UI indicating that update checks are configured in local server time.
https://app.shortcut.com/replicated/story/89606/add-local-timezone-clarity-to-the-configure-automatic-updates-ui
```release-note
Adds clarifying language that configured automatic update checks use the local server time.
```
Already a PR in docs https://github.com/replicatedhq/replicated-docs/pull/1462
=> clarify that automatic update checks are in local server time

deploy/Dockerfile, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
Resolves a few CVEs present in the previous Helm version:
3.12.2:
```
usr/local/bin/helm3.12.2 (gobinary)
Total: 4 (MEDIUM: 3, HIGH: 1, CRITICAL: 0)
┌───────────────────────────────────────┬─────────────────────┬──────────┬──────────────────────┬──────────────────┬──────────────────────────────────────────────────────────────┐
│                Library                │    Vulnerability    │ Severity │  Installed Version   │  Fixed Version   │                            Title                             │
├───────────────────────────────────────┼─────────────────────┼──────────┼──────────────────────┼──────────────────┼──────────────────────────────────────────────────────────────┤
│ github.com/cyphar/filepath-securejoin │ GHSA-6xv5-86q9-7xr8 │ MEDIUM   │ v0.2.3               │ 0.2.4 …
```
=> bump helm to 3.13.0

go.mod, go.sum, pkg/base/replicated.go, pkg/kotsutil/kots.go, pkg/operator/client/client.go, pkg/operator/client/deploy.go, pkg/operator/client/deploy_test.go
Moves the HelmChartInterface to the `kotskinds` repo so that other repos (i.e the airgap builder) that utilize this interface don't have to import `kots` just for that interface.
Fixes #
```release-note
NONE
```
NONE
=> Move HelmChartInterface to KotsKinds

pkg/handlers/custom_metrics.go, pkg/handlers/custom_metrics_test.go
This PR fixes in nil pointer panic in custom metrics handler.
Fixes #
```release-note
Fixes n bug that caused no status code to be returned from the custom metrics API requests.
```
NONE
=> Don't panic on nil values

pkg/apiserver/server.go, pkg/handlers/handlers.go, pkg/handlers/interface.go, pkg/handlers/metrics.go, pkg/handlers/metrics_test.go, pkg/handlers/middleware.go, pkg/handlers/mock/mock.go, pkg/handlers/session.go, pkg/policy/middleware.go, pkg/replicatedapp/api.go, pkg/reporting/util.go
Adds an endpoint to KOTS where application metrics can be retrieved adhoc so facilitate the KOTS/SDK integration and telemetry reconciliation.
Fixes [SC-88179](https://app.shortcut.com/replicated/story/88179/add-an-endpoint-to-kots-where-application-metrics-can-be-retrieved-adhoc)
Example responses:
- **Valid license ID**:
```bash
$ curl -s -H 'Authorization: <valid-license-id>' 10.43.247.154:3000/api/v1/app/metrics | jq .
{
"X-Replicated-AppStatus": "ready",
"X-Replicated-ClusterID": "qqtiozrovtsrtgibwfwvydghauchpmhw",
"X-Replicated-DownstreamChannelID": "2TiLbGfE9YRXAPM2JCD9STfS11B",
"X-Replicated-DownstreamChannelSequence": "18",
"X-Replicated-DownstreamSequence": "1",
"X-Replicated-DownstreamSource": "Upstream Update",
"X-Replicated-GitOpsProvider": "",
"X-Replicated-InstallStatus": …
```
=> Add an endpoint to KOTS where application metrics can be retrieved adhoc 

pkg/handlers/helmvm_node_join_command.go, pkg/helmvm/jointoken.go, pkg/helmvm/node_join.go, pkg/helmvm/util.go
=> generate a node join token

migrations/tables/k0s_tokens.yaml, pkg/handlers/handlers.go, pkg/handlers/helmvm_node_join_command.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/helmvm/node_join.go, pkg/helmvm/util.go, pkg/store/kotsstore/k0s_store.go
=> shorter embedded-cluster join commands

pkg/helmvm/helmvm_node.go, pkg/helmvm/types/types.go
include pod usage metrics
add kube-proxy/os/kernel to node metrics
return 'used' not 'available'
Fixes #
```release-note
```
=> better embedded cluster usage metrics

web/src/components/UploadLicenseFile.tsx, web/src/components/apps/HelmVMClusterManagement.tsx, web/src/components/apps/HelmVMViewNode.jsx, web/src/scss/components/apps/HelmVMClusterManagement.scss
=> remove pause and delete columns, update styles

web/src/Root.tsx, web/src/components/apps/HelmVMClusterManagement.tsx, web/src/components/apps/HelmVMViewNode.jsx
=> fix config redirect, remove unnecessary code

pkg/embeddedcluster/node_join.go
=> revert to using ubuntu image to generate node join commands

.image.env, Makefile, migrations/Makefile, pkg/image/constants.go
Upgrades the local-volume-provider, schemahero, minio, and mc dependency images to resolve several CVEs.
Fixes #
```release-note
* Upgrades the replicated/local-volume-provider image to v0.5.5 to resolve CVE-2023-45128 with critical severity, CVE-2023-4911, CVE-2023-29491, CVE-2023-45141, and GHSA-m425-mq94-257g with high severity, and CVE-2023-36054, CVE-2023-3446, CVE-2023-3817, CVE-2023-41338, CVE-2023-39325, CVE-2023-3978, and CVE-2023-44487 with medium severity.
* Upgrades the replicated/schemahero image to 0.16.0 to resolve CVE-2023-4911 with high severity, CVE-2023-2603, CVE-2023-29491, CVE-2023-2650, CVE-2023-31484, and CVE-2023-3978 with medium severity.
* Upgrades the minio/minio image to RELEASE.2023-10-25T06-33-25Z to resolve CVE-2023-4911 and CVE-2023-44487 with high …
```
=> update image dependencies

pkg/kotsadm/types/constants.go, pkg/kotsadm/types/constants_test.go, pkg/supportbundle/spec_test.go, pkg/tests/kotsutil/cases/multiple-preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml, pkg/tests/kotsutil/cases/preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml
Changes the label added to support bundle configmaps and secrets from `troubleshoot.io/kind` to `troubleshoot.sh/kind`, which is the correct label documented here: https://troubleshoot.sh/docs/support-bundle/discover-cluster-specs/
https://app.shortcut.com/replicated/story/92280/support-bundles-generated-from-kots-ui-don-t-include-sdk-airgap-telemetry
```release-note
Fixes an issue where KOTS support bundles were not discovering specs with the `troubleshoot.sh/kind=support-bundle` label
```
NONE
=> change troubleshoot.io to troubleshoot.sh

pkg/reporting/app_airgap.go, pkg/reporting/app_online.go
Fixes an issue where in rare scenarios, telemetry events that closely followed each other were reported out of order.
Fixes [SC-91640](https://app.shortcut.com/replicated/story/91640/race-condition-when-kots-and-the-sdk-report-initial-app-status)
```release-note
Fixes an issue where in rare scenarios, telemetry events that closely followed each other were reported out of order.
```
NONE
=> Handle race condition where events are reported out of order

pkg/handlers/metrics_test.go, pkg/reporting/instance_report.go, pkg/reporting/preflight_report.go, pkg/reporting/report.go, pkg/reporting/report_test.go
Fixes an issue where the reporting data stored in secrets in air gapped installations could exceed the size of the secret (1MB).
Fixes #
```release-note
Fixes an issue where the reporting data stored in secrets in air gapped installations could exceed the size of the secret (1MB).
```
=> Cap report secrets data at 1MB and improve tests

.github/workflows/build-test.yaml
This PR adds a `validate-replicated-sdk` workflow that runs on-PR to test that the following scenarios work:
* KOTS application upgrades that add the SDK
* SDK deployed as a standalone helm chart and as a subchart
* SDK deployed using Replicated and Native Helm v1beta1 and v1beta2
The above is tested on kind and openshift clusters using CMX.
https://app.shortcut.com/replicated/story/92357/e2e-tests-for-installing-the-sdk-with-kots
```release-note
```
=> validate-replicated-sdk test

deploy/Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile, kurl_proxy/deploy/Dockerfile, migrations/deploy/Dockerfile, web/okteto.Dockerfile
This PR upgrades the KOTS base image to Debian Bookworm.
Fixes #
```release-note
* Upgrades the kotsadm base image to `debian:bookworm-slim` to resolve CVE-2023-23914 with critical severity, and CVE-2022-42916 and CVE-2022-43551 with high severity.
```
=> debian bookworm base image

pkg/tests/pull/pull_test.go
The PR modifies the logic so that ordering is not taken into account when validating the resulting pull secret patches for the `pkg/tests/pull` tests. KOTS checks for private images concurrently, so the order of the patches is non-deterministic ([reference](https://github.com/replicatedhq/kots/blob/v1.104.1/pkg/image/builder.go#L157-L169)).
Fixes flaky unit test failing with:
```
--- FAIL: TestKotsPull (13.35s)
--- FAIL: TestKotsPull/test_tag_and_digest_with_rewrite (1.01s)
pull_test.go:177: 
Error Trace:    /home/craig/go/src/github.com/replicatedhq/kots/pkg/tests/pull/pull_test.go:177
/home/craig/.gvm/gos/go1.20/src/path/filepath/path.go:479
/home/craig/.gvm/gos/go1.20/src/path/filepath/path.go:503
/home/craig/.gvm/gos/go1.20/src/path/filepath/path.go:503 …
```
=> fix pull secret check in pull tests

kurl_proxy/okteto.Dockerfile, kurl_proxy/skaffold.Dockerfile
Use Debian 12 golang base image for kurl_proxy dev env as `golang:1.21-buster` doesn't exist
```
retrieving image "golang:1.21-buster": GET https://index.docker.io/v2/library/golang/manifests/1.21-buster: MANIFEST_UNKNOWN: manifest unknown; unknown tag=1.21-buster
```
Fixes #
```release-note
```
=> golang:1.21-bookworm for kurl_proxy dev env

deploy/kurl/kotsadm/template/testgrid/k8s-docker.yaml
=> add 'is kots working' checks to postrelease kurl testing

.github/workflows/alpha.yaml
specifically drop buildkite
The current build fails, because the buildkite image is really, really old.
This is the only place we use the buildkite image - _including the prod release process_, which the updated version is copied from. https://github.com/replicatedhq/kots/blob/8f9da3a4fb1be18ed2f7f05056cb7b58db630703/.github/workflows/release.yaml#L88-L106
Looks a whole lot like https://github.com/actions/checkout/issues/1474.
Fixes #
```release-note
```
=> use the same build step as the actual release

e2e/hack/Dockerfile, e2e/hack/deps.sh
This PR updates the nodejs install method for the e2e dependencies. Previously it was using a deprecated install method that would display a warning for 60 seconds. This PR updates it to use the recommended install method per https://github.com/nodesource/distributions#installation-instructions.
```
repo_deprecation_warning() {
print_bold_deprecation \
"                         ${underline}SCRIPT DEPRECATION WARNING${normal}                    " "\
This script, located at ${bold}https://deb.nodesource.com/setup_X${normal}, used to
install Node.js is deprecated now and will eventually be made inactive.
Please visit the NodeSource ${bold}distributions${normal} Github and follow the
instructions to migrate your repo.
${underline}${green}${bold}https://github.com/nodesource/distributions${norm …
```
=> update e2e nodejs install method

.github/workflows/alpha.yaml, .github/workflows/build-test.yaml, .github/workflows/e2e-infra-cleanup.yaml, .github/workflows/e2e-workspace-cleanup.yaml, .github/workflows/license.yaml, .github/workflows/release.yaml, go.mod, go.sum, web/package.json, web/yarn.lock
This PR merges the following Dependabot PRs:
https://github.com/replicatedhq/kots/pull/3751
https://github.com/replicatedhq/kots/pull/4165
https://github.com/replicatedhq/kots/pull/4159
https://github.com/replicatedhq/kots/pull/4160
https://github.com/replicatedhq/kots/pull/4161
https://github.com/replicatedhq/kots/pull/4162
https://github.com/replicatedhq/kots/pull/4167
https://github.com/replicatedhq/kots/pull/4170
https://github.com/replicatedhq/kots/pull/4171
https://github.com/replicatedhq/kots/pull/4172
~https://github.com/replicatedhq/kots/pull/4175~ skipped to avoid velero update
Fixes #
```release-note
```
=> another mega dependabot

pkg/kurl/configmap.go, web/src/components/apps/KurlClusterManagement.jsx
Fixes an issue in the Cluster Management page in the admin console where a secondary node join command was displayed when the primary node type was selected.
Fixes #
```release-note
- Fixes an issue in the Cluster Management page in the admin console where a secondary node join command was displayed when the primary node type was selected.
```
NONE
=> Generate join command based on selected node type when adding a node

.github/workflows/build-test.yaml, e2e/e2e_test.go, e2e/testim/inventory/inventory.go
This PR adds an on-PR e2e test to cover support bundle generation from the UI and CLI along with some basic validations of the resulting bundle. This test aims to replace the validations done in the regression tests as well as the on-PR smoke-test.
Testim Test: https://app.testim.io/#/project/wpYAooUimFDgQxY73r17/branch/cbo%2Fpair-down-existing-cluster-tests/test/0wypiffGfoX680X4
[SC-93244](https://app.shortcut.com/replicated/story/93244/pair-down-existing-cluster-regression-tests-with-duplicate-coverage)
```release-note
```
=> add support-bundle tests to e2e suite

cmd/kots/cli/admin-console-push-images.go, cmd/kots/cli/install.go, cmd/kots/cli/upstream-upgrade.go, cmd/kots/cli/util.go, cmd/kots/cli/util_test.go
Fixes an issue:
```
kubectl kots install ethan-kots/unstable \
--namespace default \
--airgap-bundle ~/Downloads/ethan-kots-0.1.207.airgap \
--license-file ~/Downloads/ethan-kots-unstable.yaml \
--shared-password admin123 \
--kotsadm-registry 127.0.0.1:6443
• Validating registry information ✗  
Error: Failed to test access to "127.0.0.1" with user "": failed to ping registry: Get "http://127.0.0.1/v2/": dial tcp 127.0.0.1:80: connect: connection refused
```
After fix:
```
./bin/kots install ethan-kots/unstable \
--namespace default \
--airgap-bundle ~/Downloads/ethan-kots-0.1.207.airgap \
--license-file ~/Downloads/ethan-kots-unstable.yaml \
--shared-password admin123 \
--kotsadm-registry 127.0.0.1:6443
• Validating registry information ✗  
• Extracting airgap bundle
Extracting …
```
=> fix: registry check strips port

.github/workflows/build-test.yaml, e2e/e2e_test.go, e2e/testim/inventory/inventory.go
This PR adds a `validate-gitops` job to the on-PR test suite. This aims to replace the gitops tests in the regression and smoke-test suites.
Testim test: https://app.testim.io/#/project/wpYAooUimFDgQxY73r17/branch/cbo%2Fsc-93244%2Fmove-gitops-on-pr/test/oSR5CoilEqKs0I4E
https://app.shortcut.com/replicated/story/93244/pair-down-existing-cluster-regression-tests-with-duplicate-coverage
```release-note
```
=> add gitops test to e2e suite

cmd/kots/cli/install.go, pkg/base/helm.go, pkg/base/helm_v2.go, pkg/base/helm_v3.go, pkg/base/render.go
This PR removes code associated with the `--set` flag for `kots install`. Values passed to this flag were not being used.
For reference, this flag was added in: https://github.com/replicatedhq/kots/pull/63
https://app.shortcut.com/replicated/story/93670/remove-old-code-related-to-set-flag-for-kots-install
Previously these values were parsed into `renderOptions.HelmOptions`, but this is no longer the case and that field is also unused.
```release-note
```
https://github.com/replicatedhq/replicated-docs/pull/1682
=> remove code associated with unused --set flag

.github/actions/build-push-kurl-proxy-image/action.yml, .github/workflows/alpha.yaml, .github/workflows/build-test.yaml, .github/workflows/release.yaml, kurl_proxy/deploy/apko.yaml.tmpl, kurl_proxy/deploy/melange.yaml.tmpl
Uses Chainguard to build the kurl-proxy image for the PR, on merge, and release workflows.
Fixes [SC-94246](https://app.shortcut.com/replicated/story/94246/build-kurl-proxy-image-with-chainguard)
```release-note
- Uses Chainguard to build the kurl-proxy image to resolve CVE-2023-45853 with critical severity; CVE-2023-25652, CVE-2023-29007, CVE-2023-25652, CVE-2023-29007, CVE-2023-5981, CVE-2023-2953, CVE-2023-44487, CVE-2023-31484, CVE-2023-47038, CVE-2023-31484, CVE-2023-47038, CVE-2023-31484, CVE-2023-47038, CVE-2023-31484, CVE-2023-47038 with high severity; CVE-2023-4039, CVE-2023-4039, CVE-2023-5678, CVE-2023-4039, CVE-2023-4641, CVE-2023-5678, CVE-2023-4641 with medium severity; CVE-2011-3374, TEMP-0841856-B18BAF, CVE-2022-0563, CVE-2016-2781, CVE-2017-18018, CVE-2022-27943, …
```
=> Build kurl-proxy image with Chainguard

pkg/identity/deploy/deploy.go
The `dex` binary in Chainguard's image exists at `/usr/bin/dex` and not at `/usr/local/bin/dex`. Either way, simply running the binary via `dex` should suffice.
Fixes #
```release-note
NONE
```
NONE
=> Fix deploying dex for the identity service

kustomize/base/deployment.yaml, migrations/kustomize/overlays/dev/rqlite.yaml, migrations/kustomize/overlays/okteto/rqlite.yaml
Adds a pod security context to the rqlite dev env statefulset definition to specify the user. This is needed after the switch to the chainguard image, which runs as a different user by default.
Fixes #
```release-note
```
=> runAsUser 1001 for dev env

pkg/kotsutil/troubleshoot.go, pkg/preflight/preflight.go, pkg/tests/kotsutil/troubleshoot_test.go
This PR modifies the `LoadTSKindsFromPath` function so that it will not fail if the path does not exist, but will instead return an empty `TroubleshootKinds`. This fixes an issue where re-running preflights for a sequence created on a KOTS version prior to 1.96.0 would hang indefinitely and log the error:
```
{"level":"error","ts":"2023-12-12T14:30:15Z","msg":"failed to run preflights: failed to load troubleshoot kinds from path: /tmp/kotsadm3762812014/rendered: failed to walk dir: /tmp/kotsadm3762812014/rendered: failed to walk dir: /tmp/kotsadm3762812014/rendered: lstat /tmp/kotsadm3762812014/rendered: no such file or directory"}
```
https://app.shortcut.com/replicated/story/94221/re-running-preflights-for-versions-created-by-older-versions-of-kots-fails
```release-note
Fixes an issue …
```
=> don't fail loading troubleshoot kinds if directory doesn't exist

.github/workflows/image-deps-updater.yaml
Uses the NIGHTLY PAT to create the image deps update PR in order for the PR workflows to run.
Fixes #
```release-note
NONE
```
NONE
=> Use NIGHTLY PAT to trigger image dep update

integration/database/rqlite_migration_test.go
- run tests against the actual rqlite image that will be used in production.
- `rqlite/rqlite` will not have the same tags that we generate for our `kotsadm/rqlite` image
Fixes [SC-94750](https://app.shortcut.com/replicated/story/94750/improve-the-workflow-for-updating-3rd-party-image-tags-like-minio-rqlite-and-dex)
```release-note
NONE
```
NONE
=> Use kotsadm/rqlite image in migrations test

integration/replicated/pull_test.go, pkg/persistence/persistence.go, pkg/replicatedapp/api.go, pkg/reporting/app.go, pkg/store/store.go
Injects relevant header metadata when KOTS reaches out to Replicated.
Fixes #
```release-note
NONE
```
=> KOTS reporting to replicated-app

.github/actions/build-push-image-with-apko/action.yml, .github/workflows/image-deps-updater.yaml
Action inputs seem to be set to null if the action is triggered by a `schedule` event rather than a `workflow_dispatch` event. Which is causing the `overwrite` input for the `build-push-image-with-apko` action to be set to `''` instead of `'false'`, thus skipping the action entirely.
Reference to the upstream issue: https://github.com/actions/runner/issues/924
Fixes #
```release-note
NONE
```
NONE
=> Fix image deps updater overwrite input

.github/dependabot.yml, .github/workflows/build-test.yaml
Workflows triggered by Dependabot do not have access to regular Actions secrets, but do have access to dedicated Dependabot secrets. Reference: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets
The necessary secrets to run PR workflows have been copied over to Dependabot secrets for the repo.
Added a new "dependabot" job to the "build-test" workflow to auto approve and merge successful Dependabot PRs.
Fixes #
```release-note
NONE
```
NONE
=> Abiltiy to run tests in Dependabot PRs and auto approve/merge

.github/workflows/build-test.yaml
Even if someone re-runs the workflows in Dependabot PRs, we still want to automatically approve/merge it.
`github.actor` -> Who triggered the workflow.
`github.event.pull_request.user.login` -> The PR author.
Fixes #
```release-note
NONE
```
NONE
=> Use PR author instead of actor for dependabot PRs

.github/workflows/build-test.yaml
If the `validate-kurl-addon` job is skipped, the `dependabot` job will also be skipped even if it only `needs` the `validate-success` job. This seems to be an upstream issue in Github actions: https://github.com/actions/runner/issues/2205
Fixes #
```release-note
NONE
```
NONE
=> Fix dependabot job conditional

.github/workflows/automated-prs-manager.yaml, .github/workflows/build-test.yaml
Automates the processing of automated PRs (e.g. dependabot PRs).
Fixes #
```release-note
NONE
```
NONE
=> Automated PRs manager workflow

.github/workflows/automated-prs-manager.yaml
The nightly token cannot approve and merge its own PRs, our GITHUB_ACTION token already has write access and can approve and merge PRs, so use it instead. This Github action doesn't create events that require triggering subsequent workflows, so using the GITHUB_ACTION token here should be sufficient.
Fixes #
```release-note
NONE
```
NONE
=> Use GITHUB_TOKEN for  Automated PRs Manager github action

deploy/Dockerfile, deploy/apko.yaml.tmpl, deploy/melange.yaml.tmpl, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
This PR adds kubectl 1.29 to the kotsadm image as part of adding support for kubernetes 1.29.
https://app.shortcut.com/replicated/story/95653/add-kots-support-for-k8s-1-29
```release-note
NONE
```
NONE
=> add kubectl 1.29

pkg/kotsadm/objects/minio_objects.go, pkg/kotsadm/objects/rqlite_objects.go
Adds default node affinity rules to the rqlite and minio StatefulSets.
Fixes #
```release-note
* Fixes an issue where the `kotsadm-rqlite` and `kotsadm-minio` pods could be scheduled on arm nodes.
```
NONE
=> Add default node affinity rules to rqlite and minio

cmd/kots/cli/admin-console-upgrade.go
=> Fix kots build

kurl_proxy/cmd/main.go, kurl_proxy/cmd/main_test.go, kurl_proxy/go.mod, kurl_proxy/go.sum
Have `kurl-proxy` service set `acceptAnonymousUploads=1` in the `kotsadm-tls` cert by default when we generate the default self signed certificate. This allows prompting Admin Console users to upload BYO certs on first for first time installs. When KOTS is installed as a kURL addon, the [installer script sets this flag to 1](https://github.com/replicatedhq/kots/blob/650c91516e2dd6cf7668c71da42f6cb5ba16333d/deploy/kurl/kotsadm/template/base/install.sh#L424). Doing so in this service aligns with what's expected.
Fixes # [sc-94724](https://app.shortcut.com/replicated/story/94724)
```release-note
```
-  I added some TODOs of some changes to consider. They are out of scope in this PR but would like your thoughts on them since the code was written a while back.
=> improvement: set acceptAnonymousUploads=1 for initial kotsadm-tls cert

pkg/image/minio.go, pkg/image/minio_test.go, pkg/kurl/configmap.go, pkg/kurl/configmap_test.go
Fixes an issue where configuring snapshots to use internal storage in kURL clusters with HA MinIO and OpenEBS configuration failed.
Fixes #
```release-note
* Fixes an issue where configuring snapshots to use internal storage in kURL clusters with HA MinIO and OpenEBS configuration failed.
```
NONE
=> Detect MinIO image from the 'ha-minio' StatefulSet if exists

pkg/embeddedcluster/monitor.go, pkg/embeddedcluster/util.go
if no embedded cluster installation object has been found in the cluster we can't start an upgrade. on this case (where the installation does not exists) we shouldn't be failing but moving on instead.
during the initial cluster bootstrap the installation object may take a while to be created therefore a scenario where the kots app is installed but no installation object exists is valid.
=> bug: do not fail to install if no embedded cluster installation

pkg/embeddedcluster/node_join.go
=> use kurl-proxy-kotsadm nodeport in embedded-cluster installations

web/src/features/Dashboard/components/AppStatus.tsx
The current state: 
The updated state: 
'details' relates to the application state, not the cluster state, and so should be next to the application state.
Fixes #
```release-note
```
=> embedded cluster state display should not split up application state

pkg/handlers/login.go
Adds the namespace to the password reset command displayed to the user.
Fixes #
```release-note
Adds the namespace to the password reset command displayed when the admin console is locked after hitting the limit of unsuccessful login attempts.
```
=> add namespace to locked password command

.github/workflows/regression.yaml
This PR passes a date value to the `expires_on` variable for the regression tests. This will add a default AWS tag of `expires-on: YYYY-MM-DD` so that it can be cleaned up by cloud custodian. These resources are already cleaned up automatically by a separate workflow after 24h, but this will serve as a fallback in cases where the automated cleanup fails.
https://app.shortcut.com/replicated/story/94097/remove-expires-on-never-labels-from-kots-regression-test-resources
```release-note
```
=> pass expires-on date for regression tests

.github/workflows/regression.yaml
Fixes the `date` command used to generate the `expires-on` date. The previous command worked on on a test linux VM, but seems to not work on the GH runner image. This PR modifies it to use `+2 days` instead.
Fixes https://github.com/replicatedhq/kots/actions/runs/7588411529/job/20671159631
```release-note
```
=> fix expires-on date command

.github/workflows/regression.yaml
Gets the workspace expiration for regression test resources in a separate job running on ubuntu as the test jobs run on the `hashicorp/terraform:1.0.11` image
Fixes #
Tested the `date` function in `build-test` here: https://github.com/replicatedhq/kots/actions/runs/7590240251/job/20676412203
```release-note
```
=> get expiration in separate job

.github/actions/cmx-versions/action.yaml, .github/actions/cmx-versions/dist/index.js, .github/actions/cmx-versions/index.js, .github/dependabot.yml, .github/workflows/build-test.yaml
Reduces the number of testIM tests we run by:
- Running tests against k3s and openshift only.
- Groups Dependabot PRs for kurl-proxy
- Limits number of open PRs for Dependabot to 2 PRs per project.
Fixes [SC-97507](https://app.shortcut.com/replicated/story/97507)
```release-note
NONE
```
NONE
=> Only run tests against k3s and openshift

Makefile, pkg/api/handlers/types/types.go, pkg/handlers/app.go, pkg/store/kotsstore/version_store.go, pkg/store/mock/mock.go, pkg/store/store_interface.go, web/src/Root.tsx, web/src/components/apps/AppDetailPage.tsx, web/src/components/clusters/EmbeddedClusterUpgrading.tsx, web/src/types/index.ts, web/src/utilities/utilities.js, web/src/utilities/utilities.test.js
This PR improves the KOTS UI so that when it loses connection to the API during a cluster upgrade, a separate dialog is shown indicating to the user that the cluster is being updated and that connectivity will be restored once it completes.
https://www.loom.com/share/29a2622f3cec4276aac30b5670dfc35a?sid=b0460ba2-26c5-4cf1-8ed5-dce842a7563f
https://app.shortcut.com/replicated/story/97393/detect-cluster-update-and-show-a-better-message-when-the-admin-console-goes-down
1. Install a KOTS app
2. Upgrade to a newer version that includes an embedded cluster upgrade (k0s version bump)
```release-note
```
=> embedded cluster upgrade modal

pkg/handlers/app.go
This PR fixes an issue where the embedded cluster check was using the old function as https://github.com/replicatedhq/kots/pull/4398 was merged without containing the latest changes from https://github.com/replicatedhq/kots/pull/4397.
Fixes #
```release-note
```
=> update embedded cluster check in apps handler

.github/workflows/release.yaml, pkg/image/airgap.go, pkg/imageutil/image.go, pkg/imageutil/image_test.go
Fixes an issue in the process of building the kotsadm bundle in our CI. Also refactors the code the changes the kotsadm/kotsadm-migrations image tag when the kotsadm tag is specified.
Fixes #
```release-note
NONE
```
NONE
=> Fix building kotsadm bundle

pkg/api/handlers/types/types.go, pkg/embeddedcluster/monitor.go, pkg/handlers/app.go, pkg/operator/operator.go, web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx, web/src/features/Dashboard/components/Dashboard.tsx, web/src/features/Dashboard/components/DashboardVersionCard.tsx, web/src/types/index.ts, web/src/utilities/utilities.js
This PR makes a few changes to create a smoother cluster upgrade experience:
* The embedded cluster will now only be upgraded once the application is deployed and ready. Previously the cluster upgrade would happen whether or not the deployment was successful or app was ready.
* The intermediate status of the cluster upgrade will be displayed in the UI ("waiting for app to be ready" and "updating cluster" messages).
* Logic was added to the frontend to suppress error messages that might show during a cluster upgrade. This is because the UI will lose connectivity to the API during the upgrade, which is expected.
Loom: https://www.loom.com/share/bed22e2cfce34f3aa32ce3b915f44bec?sid=70f622dc-f7c9-4860-a781-70c5718ec6ce
https://app.shortcut.com/replicated/story/97396/integrate-cluster-status-in …
=> show intermediate cluster upgrade status

web/src/components/apps/EmbeddedClusterManagement.tsx, web/src/components/apps/EmbeddedClusterViewNode.jsx, web/src/components/shared/NavBar.tsx
This PR includes a bunch of smaller UI changes for embedded cluster management:
* Cluster management tab in navbar stays underlined when navigating to node details
* Change "Cluster Nodes" title to just "Nodes"
* Remove the "This page lists..." subtitle from the nodes page
* Grid search fixed for node name and roles
* Adds dividers for the grid headers
* Updates copy on add node modal and removes "Command expires:"
* On the add node modal, i there's only one role defined, conditionally remove the sentence "Select one or more roles to assign to the new node.", don't show the role, and show the join command automatically
* Remove kubelet/kube-proxy/kernel version information from node details page
**Loom** detailing changes: https://www.loom.com/share/2563b05afeb34d70811088b54da11e7a?sid=3f3 …
=> embedded cluster management UI cleanup

pkg/handlers/embedded_cluster_node_join_command.go
The application license is not embedded into the embedded cluster binary anymore, which means that the `join` command cannot use it to determine the metrics base URL. This PR updates the embedded cluster join command response to include the metrics base URL of the currently active installation object.
Fixes part of [SC-98173](https://app.shortcut.com/replicated/story/98173)
```release-note
NONE
```
NONE
=> Return metrics base URL with the embedded cluster join command response

kurl_proxy/assets/tls.html
Replaces `HTTPS for MyApp the admin console` with `HTTPS for the MyApp admin console`
Fixes #
```release-note
```
=> fix the wording of the kurl-proxy tls page

migrations/tables/instance-report.yaml, pkg/api/reporting/types/types.go, pkg/reporting/app.go, pkg/reporting/app_airgap.go, pkg/reporting/instance_report.go, pkg/reporting/report_test.go, pkg/reporting/util.go
Includes the embedded cluster version in the reporting information.
Fixes #
```release-note
NONE
```
NONE
=> Report embedded cluster version

pkg/airgap/airgap.go, pkg/airgap/update.go, pkg/apparchive/helm-v1beta2.go, pkg/image/airgap.go, pkg/midstream/write.go, pkg/pull/pull.go, pkg/tests/pull/cases/configcontext/testcase.yaml, pkg/tests/pull/cases/customhostnames/testcase.yaml, pkg/tests/pull/cases/kotskinds/testcase.yaml, pkg/tests/pull/cases/multidoc/testcase.yaml, pkg/tests/pull/cases/needsconfig/testcase.yaml, pkg/tests/pull/cases/replicatedhelm/testcase.yaml, pkg/tests/pull/cases/samechartvariations/testcase.yaml, pkg/tests/pull/cases/simple/testcase.yaml, pkg/tests/pull/cases/subchart-alias/testcase.yaml, pkg/tests/pull/cases/subchart-crds/testcase.yaml, pkg/tests/pull/cases/subcharts/testcase.yaml, pkg/tests/pull/cases/taganddigest-norewrite/testcase.yaml, pkg/tests/pull/cases/taganddigest-rewrite/testcase.yaml, pkg/tests/pull/cases/v1beta2-charts/testcase.yaml
=> Do not process online images in airgap mode for v1beta2 Helm charts

pkg/handlers/license.go
This PR updates the KOTS license install flow so that the airgap upload page is not shown in embedded clusters. Currently, this only happens if the license is not airgap enabled, but we also want this behavior for embedded clusters because we do not yet support airgap installs.
https://app.shortcut.com/replicated/story/99470/don-t-show-air-gap-upload-page-in-kots
```release-note
```
=> don't show airgap upload page if embedded cluster

pkg/handlers/embedded_cluster_confirm_cluster_management.go, pkg/handlers/embedded_cluster_delete_node.go, pkg/handlers/embedded_cluster_drain_node.go, pkg/handlers/embedded_cluster_get.go, pkg/handlers/embedded_cluster_node_join_command.go, pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/online/online.go, pkg/store/kotsstore/version_store.go, pkg/store/types/constants.go, web/src/components/apps/AppDetailPage.tsx, web/src/components/apps/EmbeddedClusterManagement.tsx, web/src/types/index.ts
This PR adds a new version status `pending_cluster_management` for embedded clusters to represent the state during an initial install when the user must confirm their cluster management settings. All embedded cluster installs will have the initial version set to this state prior to completing the cluster management step. Once that step is completed, the version status will either be set to `pending_config`, `pending_preflight`, or `pending`, depending on whether or not there is any app configuration or preflights defined.
This fixes an issue where an application without required configuration would automatically deploy in embedded clusters, which was not the desired behavior.
https://app.shortcut.com/replicated/story/99681/disable-autodeploy
```release-note
```
=> add pending_cluster_management status for embedded clusters

web/src/components/PreflightResultPage.tsx
This PR fixes an issue where the "Ignore Preflights" option was not displayed on the preflights page when preflights were running.
Fixes and would now be covered by this currently failing test https://app.testim.io/#/project/wpYAooUimFDgQxY73r17/branch/master/test/Ecw4Nb9QY7E0tlH0/step/xRHXDdEr5gRnFZqH/viewer/screenshots?result-id=fCnAxLtz2T3at7go&path=EINjRokMifGuEcuL%3AuAlu2UmjAzgrxA3n%3AxRHXDdEr5gRnFZqH
Before:
After:
Fixes #
```release-note
Fixes an issue where the "Ignore Preflights" option was not displayed on the preflights page when preflights were running.
```
NONE
=> fix hidden ignore preflights option

pkg/handlers/embedded_cluster_node_join_command.go
Joining a cluster with the wrong k0s version fails. Returning the version along with the node join command allows the CLI to check this in the future.
Fixes #
```release-note
```
=> return the embedded cluster version with the node join response

.github/workflows/automated-prs-manager.yaml
Merging PRs occasionally fails due to some race condition. I believe this might fix the issue.
Fixes #
```release-note
NONE
```
NONE
=> Add delay between approving and merging PR in the automated PRs manager

web/src/components/apps/AppDetailPage.tsx
This PR modifies the front-end redirect logic so that the user is not routed to the `/upload-license` page if they are not logged in and instead is routed to the login page.
https://app.shortcut.com/replicated/story/97047/license-upload-page-flashes-briefly-on-startup
```release-note
Fixes an issue where the license upload page flashes briefly before being redirected to the login page
```
=> fix license upload page flash when logged out

pkg/api/handlers/types/types.go, pkg/embeddedcluster/util.go, pkg/handlers/app.go, web/src/utilities/utilities.js, web/src/utilities/utilities.test.js
This PR fixes a race condition issue in embedded clusters where the cluster upgrade modal would fail to show intermittently. This issue would arise if the new installation had been applied to the cluster, but had not yet had a `state` reported back to the UI before downtime occurred. In this scenario, the UI was not able to determine whether a cluster upgrade was pending.
This PR changes the app details response to also include the number of installation objects in the cluster. In this case, we can infer that if the latest installation does not yet have a state, but is not the only installation, then it has just recently been applied and a cluster upgrade may be pending. If there is not actually an upgrade pending, downtime will not occur and the UI will receive another update with the …
=> fix cluster upgrade modal not showing intermittently

.github/workflows/build-test.yaml, cmd/kots/cli/get-config.go, cmd/kots/cli/set-config.go, pkg/handlers/config.go, web/src/features/AppConfig/components/AppConfig.tsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
Adds the ability to:
1- Get the config values for the currently deployed app version using the KOTS CLI by passing the `--current` flag.
2- Update the config values for the currently deployed app version using the KOTS CLI by passing the `--current` flag.
3- Update the config values for any app version using the KOTS CLI by providing the corresponding sequence via the `--sequence` flag.
4- Update the config values for any version using the UI.
Fixes:
- [SC-98393](https://app.shortcut.com/replicated/story/98393)
- [SC-99170](https://app.shortcut.com/replicated/story/99170)
- [SC-100008](https://app.shortcut.com/replicated/story/100008)
```release-note
- Adds the ability to get the config values of the currently deployed app version via the CLI by passing the `--current` flag to the …
```
=> Improvements to get/set config CLI commands

pkg/store/kotsstore/version_store.go
Fixes #
```release-note
Prevents app rollback on embedded-cluster installations.
```
=> disable rolling back the app on embedded cluster

pkg/embeddedcluster/roles.go, pkg/embeddedcluster/roles_test.go
This PR modifies the embedded cluster node label sanitization so that node labels with DNS prefixes are supported.
Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
Fixes #
```release-note
Fixes an issue in embedded clusters where forward slashes were replaced with dashes in custom role labels
```
=> allow embedded cluster node labels with dns prefix

go.mod, go.sum, pkg/image/airgap.go, pkg/image/airgap_test.go, pkg/image/types/types.go, pkg/imageutil/image.go, pkg/imageutil/image_test.go
The PR updates the `admin-console push-images` CLI command to support pushing embedded cluster artifacts from airgap bundles. These artifacts will be present in an `embedded-cluster` directory. If the directory is not present, this is a no-op.
Sample output:
```
$ ./bin/kots admin-console push-images embedded-all.airgap ttl.sh/my-app
...
Pushing artifact ttl.sh/my-app/embedded-cluster/charts.tar.gz:2TiLbGfE9YRXAPM2JCD9STfS11B-76-0.1.66
Pushing artifact ttl.sh/my-app/embedded-cluster/embedded-cluster:2TiLbGfE9YRXAPM2JCD9STfS11B-76-0.1.66
Pushing artifact ttl.sh/my-app/embedded-cluster/images-amd64.tar:2TiLbGfE9YRXAPM2JCD9STfS11B-76-0.1.66
```
https://app.shortcut.com/replicated/story/100535/expand-kubectl-kots-push-images-command-to-include-embedded-cluster-additional-files
```release-note …
```
=> push embedded-cluster oci artifacts

cmd/kots/cli/install.go
Adds `--exclude-admin-console` flag to the install command so that it can be used by the embedded cluster. This is because KOTS would be managed by Helm there, not the KOTS CLI.
Fixes #
```release-note
NONE
```
NONE
=> Add exclude-admin-console flag to KOTS install command to support EC installs

cmd/kots/cli/install.go, pkg/airgap/airgap.go, pkg/automation/automation.go, pkg/handlers/airgap.go, pkg/image/airgap.go, pkg/image/types/types.go, pkg/kotsadm/configmaps.go, pkg/kotsadm/main.go, pkg/kotsadm/types/deployoptions.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go, pkg/upstream/upgrade.go
The primary change is removing the need for `TagAndPushImagesFromPath` so that `TagAndPushImagesFromBundle` is used in all cases, which handles processing embedded-cluster artifacts. There was a bit of refactoring necessary to leverage the compressed instead of extracted airgap bundle.
https://app.shortcut.com/replicated/story/101172/embed-the-kots-cli-and-use-it-to-install-the-app-not-kots-in-online-and-airgap-mode
```release-note
```
=> process embedded-cluster airgap artifacts during install and upgrade

pkg/airgap/airgap.go
Prevents the application from being automatically deployed if cluster management is pending in Embedded Cluster. The `pending_cluster_management` status was added in https://github.com/replicatedhq/kots/pull/4461, but never taken into account for airgap installs.
Fixes #
```release-note
```
=> fix: don't deploy app if pending_cluster_management in airgap

pkg/image/airgap.go, pkg/image/airgap_test.go
Uses http instead of https when pushing embedded cluster artifacts
Fixes https://github.com/replicatedhq/embedded-cluster/actions/runs/8435730730/job/23101878462#step:4:17031
```release-note
```
=> use plain http for embedded artifact push

pkg/image/airgap.go, pkg/image/airgap_test.go
This PR modifies the code that pushes images from the older docker-archive bundle format so that only files within the `images` directory get pushed. This fixes an issue where docker-archive bundles that contain embedded cluster artifacts would fail to get pushed to the registry with errors such as:
```
Error: failed to push images: failed to push images from docker archive bundle: failed to get images info from bundle: not enough parts in image path: "embedded-cluster/charts.tar.gz"
```
Fixes #
```release-note
```
=> only push from images directory for docker archive bundles

web/src/utilities/utilities.js
This PR fixes an issue in the KOTS UI during embedded cluster upgrades where the new `CopyingArtifacts` installation state was unknown to the UI and resulted in some inconsistent statuses during a cluster upgrade.
Fixes #
```release-note
```
=> add mapping for CopyingArtifacts installation state

web/src/utilities/utilities.js, web/src/utilities/utilities.test.js
This PR updates the logic for detecting a cluster upgrade on the front-end to account for the `PendingChartCreation` installation state. Now that we have switched over to a StatefulSet for `kotsadm`, a simple upgrade of the KOTS helm chart can cause downtime in a single node cluster, so we want to account for that here.
*Note: Smoke tested with an airgap install/upgrade and behaved as expected*
Fixes #
```release-note
```
=> consider PendingChartCreation state during upgrade ui

pkg/image/airgap.go
print a counter to show progress while pushing images and embedded cluster artifacts to the registry. we want this output so we can show a better feedback to the user when installing a kots application on an embedded cluster instance.
output sample:
```
root@ec:~#  /var/lib/embedded-cluster/bin/kubectl-kots \
install \
embedded-cluster-smoke-test-staging-app/ci-airgap \
--license-file ./license.yaml \
--namespace kotsadm \
--app-version-label appver-dev-7976976 \
--exclude-admin-console \
--airgap-bundle ./embedded-cluster-smoke-test-staging-app.airgap
• Validating registry information ✓
• Deploying application
Pushing image 1/1
Pushing image 10.103.35.61:5000/embedded-cluster-smoke-test-staging-app/nginx:latest
Copying blob 035788421403 skipped: already exists
Copying blob c5cdd1ce752d …
```
=> feat: print x/y progress to the stdout

cmd/kots/cli/admin-console-push-images.go, go.mod, go.sum, pkg/embeddedcluster/util.go, pkg/embeddedcluster/util_test.go, pkg/image/airgap.go, pkg/image/airgap_test.go, pkg/image/online.go, pkg/image/types/types.go, pkg/imageutil/image.go, pkg/imageutil/image_test.go, pkg/kotsadm/main.go, pkg/midstream/write.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go, pkg/tests/pull/cases/airgap/upstream/userdata/installation.yaml, pkg/tests/pull/cases/airgap/wantResults/kotsKinds/userdata/installation.yaml, pkg/tests/pull/cases/airgap/wantResults/upstream/userdata/installation.yaml, pkg/tests/pull/pull_test.go, pkg/upstream/fetch.go, pkg/upstream/replicated.go, pkg/upstream/types/types.go, pkg/upstream/upgrade.go, pkg/upstream/write.go
This PR modifies code paths associated with the `upstream upgrade` CLI command to to ensure that embedded cluster artifacts from the airgap metadata are persisted in the installation file. This helps enable airgap upgrades from the CLI in embedded clusters.
Enables automated airgap upgrade testing of: https://app.shortcut.com/replicated/story/101432/trigger-airgap-upgrade-from-kots
Fixes #
```release-note
```
=> pass embedded cluster artifacts in upstream upgrade

pkg/embeddedcluster/node_join.go, pkg/embeddedcluster/node_join_test.go, pkg/handlers/embedded_cluster_node_join_command.go
Includes the `--airgap-bundle` flag in the node join command in airgap mode
Fixes [SC-102751](https://app.shortcut.com/replicated/story/102751)
```release-note
NONE
```
NONE
=> Include airgap-bundle flag to node join command in airgap mode

web/src/features/Dashboard/components/AppStatus.tsx, web/src/features/Dashboard/components/Dashboard.tsx
This PR fixes an issue where the url for the "Edit Config" link on the dashboard was invalid and contained an `undefined` reference.
Fixes [SC-102656](https://app.shortcut.com/replicated/story/102656/edit-config-button-doesn-t-work)
```release-note
Fixes an issue where the **Edit config* link on the dashboard was not functioning as expected.
```
NONE
=> fix edit config link on dashboard

pkg/handlers/app.go, pkg/kotsutil/kots.go, pkg/kotsutil/kots_test.go
This PR treats every embedded cluster installation as if it had the default backup config object provided, if one was not provided. This allows Embedded Cluster installs with 'snapshots' turned on in the license to perform snapshots regardless of whether it is present in the app.
Fixes #
```release-note
```
=> treat every embedded cluster app as if it has a backup object

hack/dev/skaffoldcache.Dockerfile, pkg/handlers/app.go, pkg/handlers/backup.go, pkg/snapshot/store.go, pkg/snapshot/velero.go, web/src/Root.tsx, web/src/components/apps/AppDetailPage.tsx, web/src/components/modals/DeleteSnapshotModal.tsx, web/src/components/shared/NavBar.tsx, web/src/components/shared/NavBarDropdown.jsx, web/src/components/shared/SubNavBar/SubNavBar.jsx, web/src/components/snapshots/AppSnapshots.jsx, web/src/components/snapshots/GettingStartedSnapshots.jsx, web/src/components/snapshots/SnapshotDetails.jsx, web/src/components/snapshots/SnapshotRow.jsx, web/src/components/snapshots/SnapshotSchedule.jsx, web/src/components/snapshots/SnapshotSettings.tsx, web/src/components/snapshots/SnapshotStorageDestination.data.jsx, web/src/components/snapshots/SnapshotStorageDestination.tsx, web/src/components/snapshots/Snapshots.jsx, web/src/components/snapshots/SnapshotsWrapper.jsx, web/src/config-ui/subNavConfig.js, web/src/features/Dashboard/components/Dashboard.tsx, web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx, web/src/stories/DeleteSnapshotModal.stories.tsx, web/src/utilities/utilities.js
This PR updates the admin console UI for embedded cluster disaster recovery.
Summary of changes for Embedded Clusters:
* Rename overall tab to "Disaster Recovery"
* Rename mentions of "snapshots" to "backups" and get rid of the full vs partial distinction
* Limit the settings to only one storage destination
* Other small edits based on some early feedback (typos, re-wording, removing some things)
Fixes [SC-103322](https://app.shortcut.com/replicated/story/103322/remove-unused-dr-settings-for-ec)
```release-note
```
=> disaster recovery UI for embedded cluster

go.mod, go.sum
- Updates troubleshoot to v0.91.0 to resolve a panic seen when analysing ReplicaSetStatus information. The PR in troubleshoot is https://github.com/replicatedhq/troubleshoot/pull/1538
Fixes #
```release-note
Updates troubleshoot to resolve troubleshoot ReplicaSetStatus analyzer bug
```
NONE
=> Update troubleshoot to v0.91.0 to resolve ReplicaSetStatus analyzer nil result issue

pkg/handlers/metadata.go, pkg/handlers/metadata_test.go, web/src/Root.tsx, web/src/features/Auth/components/SecureAdminConsole.tsx
This PR adds an `isEmbeddedClusterRestoreInProgress` field to the `/metadata` endpoint. The UI will use this field to determine whether it should redirect the user to the Cluster Management page after logging in.
Fixes https://app.shortcut.com/replicated/story/104122/improve-kots-ui-during-embedded-cluster-restore
```release-note
```
=> redirect to cluster mgmt if EC restore in progress

web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx, web/src/utilities/utilities.js, web/src/utilities/utilities.test.js
This PR addresses an issue where the dashboard snapshot card would show an extra slash if the user entered a bucket prefix with a leading slash in the snapshot settings. This changes the logic to handle cases with and without a leading slash in the bucket path.
Before:
After:
Fixes https://app.shortcut.com/replicated/story/104151/remove-extra-slash-from-the-bucket-on-the-dr-card-on-the-dashboard
```release-note
Fixes an issue where the snapshot settings card on the admin console dashboard contained an extra slash in the object store bucket path
```
=> remove extra slash in snapshot bucket path

pkg/kotsadm/types/constants.go, pkg/kotsadm/types/constants_test.go
This PR conditionally adds the `replicated.com/disaster-recovery=infra` label to all KOTS resources when running in an embedded cluster.
Fixes https://app.shortcut.com/replicated/story/104230/ensure-that-necessary-kots-configmaps-secrets-are-restored-as-part-of-embedded-cluster-dr
```release-note
```
=> add replicated.com/disaster-recovery=infra label to kotsadm resources

pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/handlers/snapshots.go, web/src/components/snapshots/SnapshotSchedule.jsx
Currently, the snapshot schedule/retention configuration looks like this:
This makes it conceptually appear as if retention only impacts scheduled backups, and not manual ones.
After update:
Fixes #
```release-note
Updates the snapshot settings page to clarify that retention settings apply to both scheduled and manual snapshots.
```
=> Split boxes for snapshot schedule and retention

e2e/scripts/deps.sh
playwright install command should be run from within the project/playwright directory. This was a already bug, but older versions of Playwright didn't hard fail on it.
Fixes #
```release-note
NONE
```
NONE
=> Fix installing playwright

pkg/reporting/distribution.go, pkg/reporting/distribution_test.go, pkg/reporting/types.go
- add missing distribution embedded-cluster for template function
Fixes #
[sc-104283](https://app.shortcut.com/replicated/story/104283/add-embedded-cluster-and-k0s-to-distribution-template-function)
repl{{ Distribution }} can only return k0s, which should be `embedded-cluster`
```release-note
support repl{{ Distribution }} return embedded-cluster 
```
NONE
=> feat(kots): add embedded cluster distribution

.github/actions/build-custom-image-with-apko/action.yml, .github/actions/build-dep-image-with-apko/action.yml, .github/actions/kurl-addon-kots-generate/action.yml, .github/actions/kurl-addon-kots-publish/action.yml, .github/actions/kurl-addon-kots-test/action.yml, web/src/components/apps/AppDetailPage.tsx, web/src/utilities/utilities.js, web/src/utilities/utilities.test.js
This PR fixes an issue where the KOTS UI subnav would not show the selected tab for the "Config", "Troubleshoot", and "View Files" tabs. This is because previously we were only considering the last element in the path, so any routes with subpaths like `/config/<sequence>` or `/troubleshoot/analyze/<bundle-id>` would cause the tabs to show as not active.
Before `/app/craig-helm/tree/0`:
After `/app/craig-helm/tree/0`:
Fixes https://app.shortcut.com/replicated/story/102653/config-and-view-files-tab-lack-blue-underline-when-clicked-on
```release-note
Fixes an issue where the "Config" and "View Files" tabs would not display as active when clicked.
```
=> fix config and view files tab underlines

pkg/handlers/metadata.go, pkg/handlers/metadata_test.go
Uses the new embedded cluster restore state ConfigMap to detect if an embedded cluster restore is in progress and is waiting for nodes to be added.
[SC-104152](https://app.shortcut.com/replicated/story/104152)
```release-note
NONE
```
NONE
=> Use new EC restore state ConfigMap name

pkg/docker/registry/registry.go, pkg/docker/registry/registry_test.go, pkg/kotsadm/types/constants.go
This PR adds the `replicated.com/disaster-recovery: app` label to the pull secrets that KOTS adds to the deployable resources for k8s manifests and v1beta1 Helm charts.
Fixes #
```release-note
```
=> add application disaster recovery labels for injected pull secrets

pkg/k8sutil/portforward.go
When there is high network latency, port forward may not succeed in under 1 second. This change increases the exponential backoff client timeout to up to 6+ seconds.
Fixes #
[sc-92888]
```release-note
Fix `kubectl kots port-forward` for high latency network connections.
```
=> fix: cli port-forward fails with high network latency

pkg/image/airgap.go, pkg/image/airgap_test.go
start using tls when pushing embedded cluster artifacts to the internal registry
=> feat: oras using tls registry

go.mod, go.sum, pkg/embeddedcluster/util.go, pkg/handlers/app.go, pkg/handlers/license.go, pkg/license/signature.go, pkg/template/license_context.go, pkg/template/license_context_test.go, web/src/Root.tsx, web/src/components/apps/AppLicense.tsx, web/src/types/index.ts
Uses the new `IsDisasterRecoverySupported` license field instead of `IsSnapshotSupported` for enabling disaster recovery in embedded clusters.
Fixes #
```release-note
NONE
```
NONE
=> Use DR license field to enable DR

go.mod, go.sum, pkg/embeddedcluster/util.go
This PR updates the `github.com/replicatedhq/embedded-cluster-kinds` import to v1.3.0 and updates logic so that the `isHighAvailability` field is preserved when upgrading the cluster.
Fixes #
```release-note
```
=> preserve isHighAvailability field in ec installation object

go.mod, pkg/embeddedcluster/monitor.go, pkg/embeddedcluster/node_join.go, pkg/embeddedcluster/node_join_test.go, pkg/embeddedcluster/roles.go, pkg/embeddedcluster/util.go, pkg/handlers/app.go, pkg/handlers/embedded_cluster_get.go, pkg/handlers/embedded_cluster_node_join_command.go, pkg/k8sutil/clientset.go, pkg/k8sutil/cluster.go, pkg/kotsadmsnapshot/backup.go, pkg/reporting/app.go, pkg/util/util.go
Removes usage of embedded-cluster-config configmap to remove the requirement of restoring the embedded cluster operator before the admin console.
Fixes #
```release-note
NONE
```
NONE
=> Remove usage of embedded-cluster-config configmap

.github/workflows/build-test.yaml, cmd/kots/cli/install.go, cmd/kots/cli/install_test.go, pkg/airgap/airgap.go, pkg/airgap/update.go, pkg/handlers/config.go, pkg/handlers/embedded_cluster_confirm_cluster_management.go, pkg/handlers/identity.go, pkg/handlers/preflight.go, pkg/handlers/registry.go, pkg/handlers/upload.go, pkg/kotsadmlicense/license.go, pkg/kotsadmupstream/upstream.go, pkg/online/online.go, pkg/preflight/preflight.go, pkg/preflight/preflight_test.go, pkg/store/kotsstore/preflight_store.go, pkg/store/kotsstore/preflight_store_test.go, pkg/updatechecker/updatechecker.go
This PR fixes an issue where the user could not skip/ignore failing non-strict preflights and deploy from the CLI even if all strict preflights were passing. This impacted both the `install` and `upstream upgrade` commands when using the `--skip-preflights` flag.
https://app.shortcut.com/replicated/story/95957/cannot-skip-ignore-failing-non-strict-preflights-and-deploy-from-the-cli-even-if-all-strict-preflights-pass
```release-note
Fixes an issue where users could not skip or ignore failing non-strict preflights and deploy from the CLI even if all strict preflights were passing when using the `--skip-preflights` flag.
```
=> ignore failing non strict preflights if skipped

pkg/airgap/update.go, pkg/airgap/update_test.go
This PR fixes an issue where users were unable to upload airgap bundle if the version label was the same as the base version for non-semver channels. This check is intentional for semver-enabled channels, but has been changed for non-semver channels so that only the channel and sequence is considered.
https://app.shortcut.com/replicated/story/106450/unable-to-upload-airgap-bundle-if-the-version-label-is-the-same-as-the-base-version
```release-note
Fixes an issue where airgap uploads would fail with an error indicating that is was already the current version in cases where the version labels matched. This version label check is intentional for semver-enabled channels, but was not for non-semver enabled channels.
```
=> fix airgap version check when semver is not enabled

pkg/embeddedcluster/util.go, pkg/kotsadmsnapshot/backup.go
Adds SeaweedFS S3 service IP to backup annotations to preserve it on restores.
Fixes part of [SC-105712](https://app.shortcut.com/replicated/story/105712)
```release-note
* Various updates to enable high availability support for embedded cluster.
```
NONE
=> Add SeaweedFS S3 service IP to backup annotations

pkg/handlers/handlers.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/handlers/update.go, pkg/updatechecker/updatechecker.go, pkg/updatechecker/updatechecker_test.go, pkg/upstream/replicated.go, pkg/upstream/types/types.go
This PR adds an `/api/v1/app/{appSlug}/updates` endpoint to the KOTS api that will serve the available upstream updates from replicated-app. This supports work done to facilitate the upgrader service and will be used to present a list of available versions in the UI.
https://app.shortcut.com/replicated/story/105487/kots-api-endpoint-that-returns-available-updates-from-replicated-app
Sample response:
```
{
"success": true,
"updates": [
{
"versionLabel": "1.12.3",
"updateCursor": "56",
"channelId": "2eXvHnzz4j3rQAkEueeqLCZs5xU",
"isRequired": false,
"status": "pending_download",
"parentSequence": 0,
"sequence": 0,
"source": "",
"preflightSkipped": false,
"upstreamReleasedAt": "2024-06-11T14:49:26Z",
"downloadStatus": {}
},
{
"versionLabel": "1.12.2",
"updateCursor": "55",
"channelId": …
```
=> add available updates api endpoint

kurl_proxy/cmd/main.go, kurl_proxy/cmd/main_test.go
Updates the CSP headers for kurl proxy to permit same origin iframing to support the upgrade service. With the previous configuration, the upgrade service modal would fail to load when accessed through kurl-proxy with errors like:
```
Refused to frame 'https://127.0.0.1:30880/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```
This is a modification to changes made as part of: https://app.shortcut.com/replicated/story/70585/kots-clickjacking-security-vulnerability
Fixes #
```release-note
```
=> allow kurl proxy iframe from same origin

pkg/handlers/config.go, pkg/handlers/identity.go, pkg/handlers/upload.go, pkg/kotsadmconfig/config.go, pkg/kotsadmlicense/license.go, pkg/preflight/execute.go, pkg/preflight/preflight.go, pkg/render/render.go, pkg/render/types/interface.go, pkg/reporting/app_online.go, pkg/rewrite/rewrite.go, pkg/store/kotsstore/license_store.go, pkg/store/kotsstore/version_store.go, pkg/store/mock/mock.go, pkg/store/store_interface.go, pkg/tests/renderdir/renderdir_test.go, pkg/upgradeservice/handlers/config.go, pkg/upgradeservice/handlers/handlers.go, pkg/upgradeservice/handlers/interface.go, pkg/upgradeservice/preflight/preflight.go
This PR adds an API endpoint to the upgrade service for saving config. The handler will trigger preflights to run in the background after successfully saving the config and rendering the base archive.
https://app.shortcut.com/replicated/story/105494/upgrade-service-api-side-of-the-config-page-in-the-deployment-wizard
```release-note
```
=> save config api for upgrade service

pkg/k8sutil/clientset.go
kots is segfaulting upon airgap bundle upload (through ui), the error returned is (redacted):
```
fatal error: concurrent map read and map write
...
github.com/replicatedhq/kots/pkg/k8sutil.GetKubeClient({0x3e08e14?, 0xc000e5f980?})
/home/build/pkg/k8sutil/clientset.go:157 +0xb4
...
```
this commit moves the `AddToScheme()` call to  the `init()` function.
=> bug: fix concurrent map read and map write

go.mod, go.sum, pkg/image/airgap.go
instead of showing lam image push in a different section of the kots output we should count it as part of the embedded cluster artifacts.
output:
```
root@bold-sky:/home/dev# ./kots install embedded-cluster-smoke-test-staging-app/ci-airgap --license-file ./license.yaml --namespace kotsadm --app-version-label appver-dev-c51b55a --exclude-admin-console --airgap-bundle ./embedded-cluster-smoke-test-staging-app.airgap
• Validating registry information ✓
• Deploying application
Pushing application images (1/1)
Pushing image 10.96.0.11:5000/embedded-cluster-smoke-test-staging-app/nginx:1.24-alpine
Copying blob da33b1ad0ac4 skipped: already exists
Copying blob 16eaaaf5f1c0 skipped: already exists
Copying blob b407bcc80638 skipped: already exists
Copying blob a0fbd691d7c1 skipped: already exists …
```
=> feat(user feedback): count lam as an embedded cluster artifact

.github/actions/cmx-versions/dist/index.js, .github/actions/cmx-versions/index.js, .github/workflows/arm64-arc-runner-set.yaml
This PR temporarily disables CMX testing with EKS 1.30 as KOTS will fail to install due to lack of a default storage class. The goal is to unblock the KOTS pipeline while we work to add compatibility.
Fixes #
```release-note
```
=> temporarily disable EKS 1.30 testing

.github/workflows/arm64-arc-runner-set.yaml
Increases the disk size of the Arm Github runner to 100GB to allow multiple concurrent builds to run
Fixes # n/a
```release-note
NONE
```
NONE
=> Update arm64-arc-runner-set.yaml to 100G disk

pkg/embeddedcluster/util.go, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go
Adds support for Velero 1.14
Fixes [SC-109426](https://app.shortcut.com/replicated/story/109426)
Velero 1.14 does not allow backup `includedNamespaces` to have a namespace that doesn't exist.
```release-note
* Adds support for Velero 1.14
```
NONE
=> Add support for Velero 1.14

pkg/upgradeservice/bootstrap.go, pkg/upgradeservice/server.go
Fixes an issue in embedded cluster upgrades where rendering Helm charts that use Helm capabilities could fail since they are not initialized in the upgrade service.
Fixes [SC-109394](https://app.shortcut.com/replicated/story/109394)
```release-note
* Fixes an issue in embedded cluster upgrades where rendering Helm charts that utilize Helm capabilities could fail.
```
NONE
=> Init Helm capabilities in upgrade service

pkg/k8sutil/clientset.go, pkg/k8sutil/clientset_test.go
Story details: https://app.shortcut.com/replicated/story/98355
=> fix: [sc-98355] KubernetesMinorVersion | ParseInt cannot handle eks minor version with no integer string

web/src/components/upgrade_service/AppConfig.tsx, web/src/components/upgrade_service/PreflightChecks.tsx, web/src/components/upgrade_service/UpgradeServiceContext.tsx
https://www.loom.com/share/712881200a9e4047946e7dd3b0919d33?sid=304dcb04-2459-4d0c-a62f-84b476dddae0
Fixes #
```release-note
Reruns preflight checks when user updates config in Embedded Cluster upgrade
```
=> Embedded Cluster upgrade: Rerun preflights when config has changed

cmd/kots/cli/admin-console-upgrade.go
The current help message for the `kots admin-console upgrade` command is inaccurate as it would upgrade to the version of the CLI, not latest.
Fixes #
```release-note
NONE
```
NONE
=> Fix the admin-console upgrade CLI command help text

pkg/handlers/embedded_cluster_confirm_cluster_management.go, web/src/components/PreflightResultPage.tsx, web/src/components/apps/EmbeddedClusterManagement.tsx, web/src/components/upgrade_service/ConfirmAndDeploy.tsx, web/src/components/upgrade_service/PreflightChecks.tsx, web/src/features/AppConfig/components/AppConfig.tsx, web/src/features/PreflightChecks/api/getPreflightResult.tsx
https://app.shortcut.com/replicated/story/107731/uncaught-in-promise-error-unable-to-confirm-cluster-managementuncaught-in-promise-error-unable-to-confirm-cluster-management
https://app.shortcut.com/replicated/story/108918/preflights-box-is-too-big-during-initial-install
https://www.loom.com/share/1efd8f1e2c094a919e05829c8e41c026
Fixes # [sc-108918] [sc-107731]
This PR 
- remove the check for pending versions in pending_cluster_management status, so now it will not fail.
- make preflight box smaller and remove decimal.
- Fix going back on preflight page will now go to config page, not cluster management.  
```release-note
Improve UI of Preflight Results page 
Fix error when clicking continue in Cluster Management 
```
=> Fix error in Cluster Management page when clicking continue 

pkg/supportbundle/staticspecs/defaultspec.yaml
This PR adds a URI field to the default support bundle specs so that end user installations can more quickly receive upstream updates.
https://troubleshoot.sh/docs/support-bundle/supportbundle/#uri
https://app.shortcut.com/replicated/story/109412/kots-the-kots-support-bundle-spec-does-not-have-a-uri
Fixes #
```release-note
```
=> Add uri field to the default support bundle spec

web/src/components/apps/EmbeddedClusterManagement.tsx
Adds id to the role management buttons for testing
UI improvements made from this story is missing classname. Making it hard to test in playwright.  https://app.shortcut.com/replicated/story/108379/guide-the-user-through-the-nodes-page-during-initial-install
Fixes #
```release-note
```
=> Add class for role management buttons

web/src/components/modals/UpgradeServiceModal.tsx, web/src/components/upgrade_service/AppConfig.tsx
https://app.shortcut.com/replicated/story/108898/spinner-lags-and-changes-position-when-the-upgrade-service-is-starting
https://www.loom.com/share/1ea5e3c827b84a72b42a741c4bf04b4e
Fixes #
```release-note
Improve styles for the loader in the upgrade service
```
=> Align loader spinner when the upgrade service is starting

web/src/Root.tsx, web/src/components/tree/KotsApplicationTree.tsx
Hide commands to download application archive from View Files page in embedded cluster
https://app.shortcut.com/replicated/story/110539/hide-commands-to-download-application-archive-from-view-files-page-in-embedded-cluster#activity-110952
Fixes #
```release-note
Hide commands to download application archive in Embedded Cluster View files page
```
=> Hide commands to download application archive in embedded cluster

web/src/components/apps/AvailableUpdatesComponent.tsx, web/src/features/Dashboard/components/AvailableUpdateCard.tsx, web/src/features/Dashboard/components/DashboardVersionCard.tsx
https://app.shortcut.com/replicated/story/108146/show-on-the-dashboard-that-there-are-newly-available-versions#activity-110729
Fixes #
```release-note
Show available updates in Dashboard for Embedded Cluster
```
=> Show available updates in Dashboard 

pkg/supportbundle/staticspecs/kurlspec.yaml
Requirement to include the collector name print in the error logs. See story #[109476](https://app.shortcut.com/replicated/story/109476/troubleshoot-print-collector-name-when-a-collector-fails)
Fixes #
NONE
```release-note
```
NONE
=> feat: Print runPod collector name in failed error logs

web/src/Root.tsx, web/src/components/apps/EmbeddedClusterManagement.tsx, web/src/components/shared/NavBar.tsx
https://app.shortcut.com/replicated/story/106757/show-a-dedicated-node-join-page-during-restores
- show join command in embedded cluster restore
- hide top navbar items during resotre
Fixes #
```release-note
Show join command during restore in Embedded Cluster 
```
=> Show join command during restore in Embedded Cluster

pkg/rewrite/rewrite.go, pkg/upstream/helm.go, pkg/upstream/helm_test.go
When kotsadm is configured to use proxy at install time, Replicated SDK chart must also be configured with the same proxy settings.
https://app.shortcut.com/replicated/story/111175/support-for-installing-behind-a-proxy
Unit tests updates. The change manually tested with a real proxy:
```
$ kubectl -n dmitriykots2 describe deployment replicated | grep Environment -A 10
Environment:
HTTP_PROXY:                    http://10.128.0.23:3128
HTTPS_PROXY:                   http://10.128.0.23:3128
NO_PROXY:                      10.96.0.1,35.225.92.50,kotsadm-rqlite,kotsadm-postgres,kotsadm-minio,kotsadm-api-node
REPLICATED_NAMESPACE:           (v1:metadata.namespace)
REPLICATED_POD_NAME:            (v1:metadata.name)
DISABLE_OUTBOUND_CONNECTIONS:  false
IS_HELM_MANAGED:               true …
```
=> Pass-through PROXY environment to Replicated SDK deployment

pkg/kotsutil/kots.go, pkg/kotsutil/kots_test.go, pkg/snapshot/filesystem_minio.go, pkg/snapshot/filesystem_minio_test.go
=> supply additional labels and annotations to fs-minio pods

.github/workflows/regression.yaml
The helmvm regression test is failing with a 'curl doesn't know this flag' error: https://github.com/replicatedhq/kots/actions/runs/10755567932/job/29827721257#step:8:2071
comes from Embedded Cluster, here: https://github.com/replicatedhq/embedded-cluster/blob/39eb313c03eeb27089f4cf3982a5353e39e46961/scripts/cache-files.sh#L61
which runs with ubuntu-latest while kots uses ubuntu-20.04
https://github.com/replicatedhq/embedded-cluster/blob/fd4ed73cfe2cafb818450393c23143d5fcdd327d/.github/workflows/ci.yaml#L169
So this bumps kots to use the same runner as Embedded Cluster here.
```release-note
```
=> run integration tests with ubuntu-latest to match embedded-cluster

deploy/kurl/kotsadm/template/base/tmpl-secret-rqlite.yaml, pkg/kotsadm/objects/kotsadm_objects.go, pkg/kotsadm/objects/secrets_objects.go, pkg/supportbundle/staticspecs/kurlspec.yaml
When setting NO_PROXY env var to include .cluster.local this will not work with the shorthand dns.
```release-note
KOTS will now use the fully qualified .svc.cluster.local address when making requests to kotsadm-rqlite and kotsadm-minio services for simplified HTTP proxy configuration using `NO_PROXY=.cluster.local`.
```
=> fix(proxy): use fqdn for kotsadm-rqlite and kotsadm-minio addresses

.github/workflows/release.yaml, .gitignore, Makefile, contracts/replicated-app/init_test.go, contracts/replicated-app/root_test.go, go.mod, go.sum
This bootstraps Pact consumer for replicated.app.
https://app.shortcut.com/replicated/story/110520/add-test-for-unauthenticated-200-response-from-https-replicated-app
NONE
```release-note
```
=> Bootstrapping pact tests for replicated.app

web/src/components/config_render/ConfigDropdown.tsx
This will hide the dropdown if there is `when` field is configured.
https://replicated.slack.com/archives/C01CE41DDUM/p1726129358501859
https://app.shortcut.com/replicated/story/112048/config-dropdowns-always-show-even-with-when-field-set-to-false
[sc-112048]
```release-note
Fix dropdown logic for when condition in Config
```
=> Fix Dropdown logic for when field

pkg/template/static_context.go
```release-note
Add a new template function 'PrivateCACert' that returns the name of a configmap containing additional CA certificates provided by the end user.
```
https://github.com/replicatedhq/replicated-docs/pull/2633
=> add PrivateCACert template function

pkg/embeddedcluster/upgrade.go, pkg/replicatedapp/embeddedcluster.go
Fixes an issue where upgrading the application in Embedded Cluster failed if the version label contained special characters like `+`.
[SC-110955](https://app.shortcut.com/replicated/story/110955)
NONE
```release-note
Fixes an issue where upgrading the application in Embedded Cluster failed if the version label contained special characters like `+`.
```
NONE
=> fix: EC - unable to upgrade if version label has special characters

cmd/kots/cli/pull.go, pkg/kotsadmupstream/upstream.go, pkg/online/online.go, pkg/pull/pull.go, pkg/registry/registry.go, pkg/render/render.go, pkg/rewrite/rewrite.go, pkg/upstream/admin-console.go, pkg/upstream/helm.go, pkg/upstream/helm_test.go
Replicated SDK now supports adding custom CA from a ConfigMap. This uses the same CA that kotsadm is deployed with for Replicated SDK pod. The config map is assumed to to have been created out of band.
```release-note
Adds support for configuring Replicated SDK with additional [Certificate Authority](https://docs.replicated.com/reference/template-functions-static-context#privatecacert) value as the one specified using the `--private-ca-configmap` command line parameter.
```
=> Add custom CA when deploying replicated-sdk

README.md, dev/patches/kotsadm-web-up.yaml, dev/scripts/common.sh, dev/scripts/down-ec.sh, dev/scripts/down.sh, dev/scripts/up-ec.sh, dev/scripts/up.sh
Adds the ability to manage npm packages in the dev env
[SC-112746](https://app.shortcut.com/replicated/story/112746)
NONE
```release-note
NONE
```
NONE
=> Ability to manage npm packages in dev env

kurl_proxy/cmd/main.go
Ability to recognize Embedded Clusters in kurl proxy
NONE
```release-note
NONE
```
NONE
=> Ability to recognize Embedded Clusters in kurl proxy

pkg/supportbundle/defaultspec/spec.yaml, pkg/supportbundle/staticspecs/defaultspec.yaml, pkg/supportbundle/staticspecs/kurlspec.yaml
Collect information of whether connection to replicated.app succeeded or not, and analyse the results. The check already existed [here](https://github.com/replicatedhq/kots/blob/a38c002e6e59954e1f671c3f1070789a00a267cf/pkg/supportbundle/staticspecs/kurlspec.yaml#L8) but was missing in other specs
[sc-113418](https://app.shortcut.com/replicated/story/113418/check-that-kots-is-able-to-connect-to-replicated-app-license-server)
NONE
```release-note
Test connection to replicate.app and analyse results when collection support bundles in non-kURL clusters
```
NONE
=> chore: Add check for replicated.app to support bundle specs missing the check

pkg/supportbundle/spec.go, pkg/supportbundle/staticspecs/defaultspec.yaml
This PR removes `clusterResources: {}` from the default spec. Today, this will take precedent over a more specific instantiation of the `clusterResources` collector leading to a confusing experience for users.
By default if no `clusterResources` collector is specified in a `SupportBundle` spec, `troubleshoot` will add one https://github.com/replicatedhq/troubleshoot/blob/main/pkg/supportbundle/collect.go#L116-L117
[SC-112609](https://app.shortcut.com/replicated/story/112609)
```release-note
```
=> remove clusterResources from the default SupportBundle Spec

dev/scripts/common.sh, dev/scripts/down-ec.sh, dev/scripts/up-ec.sh
- add `--kubeconfig=/var/lib/embedded-cluster/k0s/pki/admin.conf`, since kos kubectl didn't pick up the KUBECONFIG
NONE
```release-note
NONE
```
NONE
=> fix(ec): solve make kotsadm-up-ec fail

pkg/operator/client/client.go, pkg/operator/client/deploy.go, pkg/operator/client/namespaces.go
When deployed to an embedded cluster, custom CA configmap is created automatically in the kotsadm namespace by EC installer. The same config map is used in Replicated SDK and also by application via template functions. The config map needs to be copied to any additional namespace where SDK or the application may be deployed.
https://app.shortcut.com/replicated/story/114248/sdk-pod-is-unable-to-start-when-using-custom-ca-and-deploying-into-one-of-the-additional-namespaces
```release-note
Fixes an issue that could prevent Replicated SDK from being deployed into an additional namespace when using Embedded Cluster.
```
NONE
=> Copy custom CA config map to additional namespaces

pkg/upstream/helm.go
In EC installs, Replicated SDK is not being granted cluster level access, which limits its functionality resulting in bad data being reported.
Relevant Replicated SDK PR: https://github.com/replicatedhq/replicated-sdk/pull/218
https://app.shortcut.com/replicated/story/114128/replicated-sdk-reports-k0s-when-installed-in-embedded-cluster-causing-distribution-to-flip-flop-in-events-view
```release-note
When included, Replicated SDK will be deployed with the same ClusterRole as the Admin Console.
```
=> Use cluster role for the SDK deployment when running in EC

cmd/kots/cli/admin-console-upgrade.go, pkg/kotsadm/api.go, pkg/kotsadm/api_test.go, pkg/kotsadm/main.go, pkg/kotsadm/secrets.go, pkg/kotsadm/types/upgradeoptions.go
```release-note
- Fixes an issue that causes proxy settings to be removed on `kotsadm admin-console upgrade`.
- Fixes an issue that causes `--strict-security-context` to be removed on `kotsadm admin-console upgrade`.
```
=> fix: persist http proxy settings and security context on upgrades

cmd/kotsadm/cli/root.go, pkg/apparchive/helm-v1beta1.go, pkg/store/kotsstore/downstream_store.go, pkg/store/kotsstore/downstream_store_test.go, pkg/store/kotsstore/kots_store.go, pkg/store/kotsstore/version_store.go, pkg/store/store.go, pkg/supportbundle/spec.go, pkg/updatechecker/updatechecker.go, pkg/util/util.go
Allows rollbacks for a given version if allowRollback is true for the latest downloaded version, and this is embedded cluster, and the embedded cluster config has changed between the version and current.
https://www.loom.com/share/fca871a6b1ca4031bcfde3ee966ce421?sid=334fa25b-40f3-4a83-affb-6257b53b2940
```release-note
Adds support for rollbacks in Embedded Cluster installations for versions where the embeddedcluster.replicated.com/v1beta1.Config has not changed between versions.
```
https://github.com/replicatedhq/replicated-docs/pull/2794
=> feat(ec): allow rollbacks for embedded cluster

pkg/docker/registry/temp_registry.go
Fixes an issue where the config of the local registry that KOTS uses to process air gap bundles can be overridden by the host's environment variables.
[SC-105931](https://app.shortcut.com/replicated/story/105931)
NONE
```release-note
NONE
```
NONE
=> Ignore host env vars as they may override the registry config

pkg/supportbundle/defaultspec/spec.yaml, pkg/supportbundle/staticspecs/defaultspec.yaml
Reverts replicatedhq/kots#4934
Reverting as this broke generating support bundles for air gapped installations
```release-note
* Fixes an issue where generating support bundles failed in air gapped installations
```
NONE
=> Revert "chore: Add check for replicated.app to support bundle specs missing the check"

Makefile, pkg/upgradeservice/bootstrap.go
Fixes an issue where updating the app in Embedded Cluster failed if the new app version contained a required config item without a default or value.
[SC-111215](https://app.shortcut.com/replicated/story/111215)
Yes, will be implemented in the EC repo
```release-note
* Fixes an issue where updating the app in Embedded Cluster failed if the new app version contained a required config item without a default or value.
```
NONE
=> fix: unable to upgrade EC when introducing a required config item w/o default or value

pkg/supportbundle/staticspecs/kurlspec.yaml
Fixes an issue where the replicated.app health check collector hangs in air gap kURL environments.
```release-note
* Fixes an issue where generating a support bundle could hang in air gap kURL environments.
```
NONE
=> Add timeout to replicated.app health check collector

e2e/playwright/tests/@change-license/test.spec.ts, e2e/playwright/tests/@multi-app-backup-and-restore/test.spec.ts, e2e/playwright/tests/@multi-app-install/test.spec.ts, e2e/playwright/tests/@no-required-config/test.spec.ts, pkg/airgap/airgap.go, pkg/airgap/update.go, pkg/handlers/config.go, pkg/handlers/identity.go, pkg/handlers/registry.go, pkg/handlers/upload.go, pkg/kotsadmupstream/upstream.go, pkg/kotsutil/kots.go, pkg/kotsutil/kots_test.go, pkg/online/online.go, pkg/operator/operator.go, pkg/preflight/preflight.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go, pkg/store/kotsstore/license_store.go, pkg/store/kotsstore/version_store.go, pkg/store/kotsstore/version_store_test.go, pkg/store/mock/mock.go, pkg/store/store_interface.go, pkg/upgradeservice/preflight/preflight.go
Consolidate the logic for determining downstream version status so it's easier to unit test and more readable.
[SC-106273](https://app.shortcut.com/replicated/story/106273)
Yes
```release-note
NONE
```
NONE
=> Consolidate the logic for determining downstream version status

kurl_proxy/assets/tls-warning.html
I noticed that on Safari the instructions were for Chrome, and I noticed that the wording for the instructions were out of date for several browsers.
In addition to fixing those things, I added support for Edge (I think many enterprises use Windows) and Opera because they were easy. But I didn't have images for those, so I don't show an image for those.
We also showed Chrome instructions if we didn't recognize the browser, so I added some default text that would show in unhandled browsers
Unhandled:
Edge with no image:
Firefox with image:
NONE
```release-note
Updates the instructions that inform users how to proceed with a self-signed certificate using different browsers when installing with the Admin Console.
```
NONE
=> Update TLS warning steps for different browsers

.github/actions/cmx-versions/action.yaml, .github/actions/kurl-addon-kots-publisher/action.yml, .github/actions/version-tag/action.yml, .github/workflows/build-test.yaml, cmd/kots/cli/download.go, pkg/download/download.go, pkg/handlers/download.go
Adds the ability to download the application archive of any version including the currently deployed one.
[SC-115707](https://app.shortcut.com/replicated/story/115707)
Yes
```release-note
Adds the ability to download the application archive of any version including the currently deployed one.
```
TBD
=> Ability to download the application archive of any version including the currently deployed one

.github/actions/cmx-versions/dist/index.js, .github/actions/cmx-versions/index.js, .github/workflows/build-test.yaml
Uses OpenShift 4.15.0-okd because it has more warm clusters.
[SC-115719](https://app.shortcut.com/replicated/story/115719)
Yes
```release-note
NONE
```
NONE
=> Use OpenShift 4.15.0-okd

pkg/apiserver/server.go, pkg/embeddedcluster/node_join.go, pkg/embeddedcluster/node_join_test.go, pkg/handlers/app.go, pkg/handlers/dashboard.go, pkg/handlers/embedded_cluster_get.go, pkg/handlers/embedded_cluster_node_join_command.go, pkg/handlers/embedded_cluster_node_join_command_test.go, pkg/handlers/handlers.go, pkg/handlers/kubeclient/kubeclient.go
On join, return all the TCP endpoints the joining node needs to preflight for to ensure a successful connection to the cluster
https://app.shortcut.com/replicated/story/113015/preflight-remote-access-on-join
Yes, added tests to the handler and to the newly added method
Also run some manual tests on an EC local dev deployment:
```
root@node1:/replicatedhq/embedded-cluster# curl -k -v "https://172.17.0.2:30000/api/v1/embedded-cluster/join?token=FGjr0qVT2dRHrMialHJk7zd8" | jq .
(...)
{
"clusterID": "19750e22-03ff-44ae-8fcb-c41e70ca4db5",
"k0sJoinCommand": "/usr/local/bin/k0s install controller --enable-worker --no-taints --labels kots.io/embedded-cluster-role=total-1,kots.io/embedded-cluster-role-0=controller-test,controller-label=controller-label-value",
"k0sToken": "...", …
```
=> feat(ec_join): update handler to return tcp connections required

e2e/playwright/tests/@smoke-test/test.spec.ts, pkg/embeddedcluster/metrics.go, pkg/embeddedcluster/upgrade.go, pkg/embeddedcluster/util.go, pkg/operator/operator.go, pkg/upgradeservice/deploy/deploy.go
Sends upgrade events instead of operator
Related https://github.com/replicatedhq/embedded-cluster/pull/1527
```release-note
```
=> chore(ec): send upgrade events instead of the operator

pkg/apiserver/server.go, pkg/handlers/debug.go, pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/handlers/websocket.go, pkg/websocket/types/types.go, pkg/websocket/websocket.go, web/src/Root.tsx, web/src/components/DebugInfo.jsx, web/src/scss/components/DebugInfo.scss
Implements a WebSocket server for the EC manager to connect to.
[SC-116574](https://app.shortcut.com/replicated/story/116574)
```release-note
NONE
```
NONE
=> feat: embedded cluster manager websocket

pkg/handlers/backup.go, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go, pkg/kotsadmsnapshot/k8sclient/k8sclient.go, pkg/kotsadmsnapshot/types/types.go, pkg/kotsadmsnapshot/veleroclient/veleroclient.go, web/src/components/snapshots/Snapshots.jsx
This PR adds support for the new instance backups format. Current functionality remains unaffected, and we keep listing backups as usual, but we've introduced a new contract change paired with the necessary UI change to read the new data format.
https://app.shortcut.com/replicated/story/116335/modify-listinstancebackups-handler-to-support-new-dr
Added a whole series of test to the overall list functionality.
```release-note
NONE
```
☝️ this PR makes no functional changes to the backup experience.
I've also run manual tests on both EC and existing cluster and everything looks good.
NONE
=> feat(ec): change `ListInstanceBackups` handler to return `ReplicatedBackups`

Makefile, dev/dockerfiles/kotsadm/Dockerfile.local, dev/manifests/kotsadm/minio.yaml, pkg/operator/client/delete.go, pkg/operator/client/gvkn.go
Story details: https://app.shortcut.com/replicated/story/117029
Demo: https://www.loom.com/share/3a33f7af9a4b4df39c2ff309aaa99f48?sid=a032f5d3-16e0-4e8a-aac9-655bacc3bfff
* implement new annotation `kots.io/keep: "true"` for KOTS to skip deleting the manifest if the annotation present in non-Helm install
* misc update in KOTS debug setup. I run `DEBUG_KOTSADM=1 make debug` to debug the code changes.
=> feat: [sc-117029] Add keep annotation to KOTS

pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go
Adds support for orLabelSelectors to the velero.io/v1 Backup resource so vendors can selectively choose what resources to back up from their application.
```release-note
Adds support for adding orLabelSelectors to the velero.io/v1 Backup resource for [Full Snapshots](https://docs.replicated.com/vendor/snapshots-overview).
```
https://github.com/replicatedhq/replicated-docs/pull/2893
=> feat(snapshots): support for orLabelSelectors

migrations/Makefile, pkg/docker/registry/registry.go, pkg/docker/registry/registry_test.go, pkg/k8sutil/clientset.go, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go, pkg/kotsadmsnapshot/download.go, pkg/snapshot/velero.go
Some cleanup and moving the dr annotation to infra from app.
```release-note
```
=> feat(ec): fixes for restore in new improved dr

pkg/handlers/app.go, pkg/store/kotsstore/version_store.go
We no longer save the default backup spec in the database so IsSnapshotsSupportedForVersion() returns false. There is no need to check this for EC as it is always supported.
```release-note
```
=> fix(ec): always enable snapshots

pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go, pkg/kotsadmsnapshot/types/types.go
In order to restore the backup we need to be able to associate a restore spec with a backup.
```release-note
```
=> feat(snapshots): encode restore spec in backup cr for restore

pkg/kotsadm/objects/minio_objects.go, pkg/snapshot/filesystem_minio.go, pkg/supportbundle/staticspecs/defaultspec.yaml
Currently MinIO component of kotsadm runs in quiet mode and does not provide any logging output. Removing the quiet flag improves visibility into MinIO operations and helps with troubleshooting storage related issues.
Before changes in MinIO logs
```
```
After changes in MinIO logs
```
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.2023-12-20T01-00-02Z (go1.21.6 linux/arm64)
Status:         1 Online, 0 Offline.
S3-API: …
```
=> feat: remove quiet flag in Minio

pkg/handlers/restore.go, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go, pkg/kotsadmsnapshot/restore.go, pkg/kotsadmsnapshot/types/types.go, pkg/operator/operator.go, pkg/snapshot/backup.go, pkg/snapshot/restore.go
Prevents previous versions of kots from listing new dr backups in the instance backups list.
```release-note
```
=> feat(snapshots): add new replicated.com/disaster-recovery-version annotation

pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go
Update the `DeleteBackup` handler to handle replicated backups with Replicated Backups consisting of multiple Velero Backups.
https://app.shortcut.com/replicated/story/116347/modify-deletebackup-handler-to-support-new-dr
Yes, I've run manual tests to validate current functionality remains unchanged and added a series of automated tests
```release-note
NONE
```
NONE
=> feat(ec): `DeleteBackup` supports deleting new Replicated Backups

deploy/melange.yaml.tmpl, kurl_proxy/deploy/melange.yaml.tmpl, migrations/deploy/melange.yaml.tmpl
Fixes CI build
```
Error: failed to build image components: building "amd64" layer: installing apk packages: error getting package dependencies: constraining initial packages: parsing constraint "kotsadm-migrations-head=v2024.12.16-d644f5-nightly-r0": invalid version v2024.12.16-d644f5-nightly-r0, could not parse
```
```release-note
```
=> fix(ci): chainguard build is broken

pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go, pkg/kotsadmsnapshot/types/types.go
This PR cleans up a series of volume backup annotations that we don't really use (and probably never used?). These annotations were supposed to be set on the `Backup` Velero resource based on the `PodVolumeBackups` Velero resource. However this code was never in place for `InstanceBackups` and was commented early on for the `AppBackups`:
- https://github.com/replicatedhq/kots/commit/7e020868255e9dc56416fd1f7606e3c021b08771
Part of https://app.shortcut.com/replicated/story/117470/change-the-listinstancebackups-endpoint-to-return-a-flat-array-structure-of-replicated-backups
Added a series of tests to the `ListBackupsForApp` and updated the Instance backup ones.
```release-note
NONE
```
NONE
=> chore(backup): cleanup volume annotations

.github/actions/build-custom-image-with-apko/action.yml, .github/actions/build-dep-image-with-apko/action.yml, pkg/handlers/backup.go, pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go, pkg/kotsadmsnapshot/types/types.go, web/src/components/RestoreSnapshotRow.jsx, web/src/components/snapshots/SnapshotDetails.jsx
Adds support to backup details endpoint for new DR.
```release-note
```
=> feat(snapshots): GetBackup details endpoint should support new dr

pkg/kotsadm/objects/kotsadm_objects.go
The required value of the 'pre.hook.backup.velero.io/command' annotation on the kotsadm pod has changed. This updates the upgrade command to change the value.
```release-note
```
=> update the velero backup annotation when updating kotsadm

pkg/kotsadm/objects/kotsadm_objects.go, pkg/kotsadm/objects/kotsadm_objects_test.go
=> fix: update spec with new scripts dir when updating kotsadm

pkg/embeddedcluster/upgrade.go, pkg/embeddedcluster/util.go, pkg/reporting/distribution.go, pkg/upgradeservice/deploy/deploy.go
Support for migration from Embedded Cluster v1 to v2
Related https://github.com/replicatedhq/embedded-cluster/pull/1718
```release-note
```
=> feat(ec): migration from v1 to v2

go.mod, go.sum, pkg/embeddedcluster/upgrade.go, pkg/operator/operator.go, web/src/components/modals/UpgradeStatusModal.tsx, web/src/utilities/utilities.js
- Runs cluster upgrade if v2Enabled is set to true
- Shows feedback in ui of v2 migration in progress
```release-note
```
=> feat(ec): migration from v1 to v2 - fixes

web/src/components/snapshots/SnapshotDetails.jsx
Button is missing. Tests are failing
```release-note
```
=> fix(ui): missing pre snapshot scripts show more button

pkg/supportbundle/staticspecs/kurlspec.yaml
Collecting all k8s API server audit logs tend to generate large support bundles where audit logs account for `1GB` in size. Not the entire audit history is always needed. This leads to UX issues such as
- Slowness when generating support bundles in Admin Console caused by long times taken when redacting
- Sending large bundles which need to be sent by customers to vendors, and then to Replicated.
Limits collecting all k8s-audit logs to the latest one only
NONE
```release-note
Only collect the latest kURL k8s-audit API server log
```
NONE
=> chore: Only collect the latest kURL k8s-audit API server log

pkg/image/online.go
```
Error: failed to validate installation: failed to create online app: failed to pull: failed to write common midstream: failed to update installation images: failed to wait for image checks: failed to check if image  is private: failed to parse docker ref "": invalid reference format
```
is unclear
```
Error: failed to validate installation: failed to create online app: failed to pull: failed to write common midstream: failed to update installation images: failed to wait for image checks: failed to check if image "" is private: failed to parse docker ref "": invalid reference format
```
is a little more clear
```release-note
```
=> quote the image name in image check failure errors to make it clear it is empty

.github/workflows/image-deps-updater.yaml
Fixes the image deps automated workflow slack notification after it's been updated to use 2.0 of `slackapi/slack-github-action`
NONE
```release-note
NONE
```
NONE
=> Fix image deps slack notification

pkg/embeddedcluster/upgrade.go, pkg/upgradeservice/process.go, web/src/components/apps/AvailableUpdatesComponent.tsx
Surfaces upgrade service errors to the UI.
NONE
```release-note
Improves error visibility by displaying the actual error message in the UI instead of a generic one when an upgrade fails to start.
```
NONE
=> Surface upgrade service errors to the UI

e2e/playwright/regression/@existing-online-install-admin/test.spec.ts, e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts, e2e/playwright/regression/shared/registry-settings.ts, e2e/playwright/regression/shared/version-history.ts, e2e/playwright/regression/shared/view-files.ts, e2e/playwright/tests/@min-kots-version-online/test.spec.ts, e2e/playwright/tests/@range-kots-version-online/test.spec.ts
Fixes an issue where the new sequence of an upstream update version is difficult to determine causing flakiness in the tests.
Attempts a fix for an issue in loading the file tree in the view files page by not having to resize the window for validating registry changes.
```release-note
NONE
```
NONE
=> Fix flakiness in playwright regression tests

e2e/playwright/regression/@existing-online-install-admin/test.spec.ts, e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts, e2e/playwright/regression/shared/registry-settings.ts, e2e/playwright/regression/shared/version-history.ts
Moves checking for updates earlier in the regression test to reduce conflicts with other running instances of the test.
[SC-120663](https://app.shortcut.com/replicated/story/120663)
```release-note
NONE
```
NONE
=> Move checking for updates earlier in the regression test

e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
Add snapshots RBAC before validating dashboard so the snapshots card show up in the dashboard.
```release-note
NONE
```
NONE
=> Add snapshots RBAC before validating dashboard

e2e/playwright/regression/shared/version-history.ts
Fixes validating deploy logs for regression tests
```release-note
NONE
```
NONE
=> Fix validating deploy logs for regression tests

.github/actions/cmx-versions/dist/index.js, .github/actions/cmx-versions/index.js
Disables OKE CMX tests due to DockerHub rate limits issue until [SC-120817](https://app.shortcut.com/replicated/story/120817) is resolved.
```release-note
NONE
```
NONE
=> Disable OKE CMX tests due to DockerHub rate limits issue

.github/workflows/build-test.yaml
Most of our e2e run in Kind. We current use kind with k8s 1.28. This PR upgrades the tests to run against k8s 1.30
With CMX, specifiying kind v1.30.0 currently results in kind v1.30.10
The test requiring the rancher image with k3s running locally has been updated from `v1.27.1-k3s1`to `v1.30.10-k3s1`. The image is [here](https://hub.docker.com/layers/rancher/k3s/v1.30.10-k3s1/images/sha256-30ec626f4550223da4c0696b50a4886469deccfad6211861dee7bdd90e41e9dd)
=> Running e2e in more current and relevant kind versions

e2e/playwright/regression/@embedded-airgapped-install/test.spec.ts
Wait for Velero in kurl-airgap-install regression test before validating snapshots functionality as joining a worker node can cause Velero to become unavailable for a bit.
```release-note
NONE
```
NONE
=> Wait for Velero in kurl-airgap-install regression test

.github/workflows/daily-container-scans.yml, .github/workflows/scan-container-image.yml
- Adds new image scanning process 
- Scan the actual public image on dockerhub
- Use Grype as the scanner
- Use Sarif format as attachment to the repo so it gets added to the code scan results
- Enrich the Sarif with properties we use for reporting purposes
- To determine the image tag we use the release version from this repo
We scan the public image to ensure we are scanning what people are using. If we were to build the image and scan, we would actually be scanning a new image instead of the current release.
None
NONE
```release-note
NONE
```
NONE
=> adds new image scanning process 

Makefile
Ability to push kots binary to ttl.sh for testing with EC.
```bash
make kots-ttl.sh 
...
Uploading ab639dc1d1ea kots.tar.gz
Uploaded  ab639dc1d1ea kots.tar.gz
Pushed [registry] ttl.sh/salah/kots.tar.gz:24h
Digest: sha256:a91eb649b339c329a329b2c2cbd21772899010df2d1b9077d9cada69b85fe9ab
```
NONE
```release-note
NONE
```
NONE
=> Ability to push kots binary to ttl.sh

.github/workflows/build-test.yaml, e2e/playwright/regression/@embedded-airgapped-install/test.spec.ts, e2e/playwright/regression/@embedded-online-install/test.spec.ts, e2e/playwright/regression/shared/cluster-management.ts, pkg/replicatedapp/api_test.go
- Mix between OpenShift versions to maximize the chances of using the CMX warm pool.
- Disable `validate-existing-online-install-minimal` (check comment in the changes as to why).
- Wait for worker node to join before validating snapshots in regression tests.
- Add missing case to `getRequest` unit test.
```release-note
NONE
```
NONE
=> Various tests improvements

integration/replicated/generate.go, integration/replicated/pull_test.go, integration/upload/generate.go, pkg/apparchive/app.go, pkg/apparchive/helm-v1beta1_test.go, pkg/download/download.go, pkg/embeddedcluster/upgrade.go, pkg/handlers/download.go, pkg/image/airgap.go, pkg/operator/client/client.go, pkg/operator/client/deploy.go, pkg/operator/client/deploy_test.go, pkg/pull/archive.go, pkg/store/kotsstore/version_store.go, pkg/supportbundle/backup.go, pkg/supportbundle/filetree.go, pkg/supportbundle/supportbundle.go, pkg/upload/archive.go, pkg/util/tar.go
Overwrites existing files when untarring. This mimics the default behavior of `tar xvf`.
```release-note
* Fixes an issue where extracting Helm charts failed on deploy if duplicate files were found in the chart.
```
NONE
=> Overwrite existing files when untarring

e2e/playwright/shared-core/support-bundle.ts
Files in the redaction list are randomly sorted, and one of the files in the IP addresses redactions doesn't exist in the support bundle and can end up the one being selected in the test. This PR is a bandaid to address the flakiness in the meantime by selecting the second row in the redaction list where the files always exist until we figure out the underlying cause.
```release-note
NONE
```
NONE
=> Fix support-bundle test flakiness

.github/workflows/alpha.yaml, .github/workflows/scan-image-grype.yml
St0rmz1/chore/move to grype and clean up
Migrates image scans from Trivy to Grype.
Same functionality, but uses our reusable workflow
- reports in sarif
- won't fail on build, but will still report
None
NONE
```release-note
NONE
```
NONE
=> Migrate scans to reusable workflow using Grype

e2e/playwright/regression/shared/license.ts, e2e/playwright/tests/shared/upload-license.ts, web/src/components/UploadLicenseFile.tsx
Uploading rli files no stopped working a while ago, and there is no migration path any more. RLI files can still be selected, but result in an error.
NONE
```release-note
NONE
```
=> Remove .rli file filter for licenses

e2e/playwright/regression/shared/license.ts, e2e/playwright/tests/shared/upload-license.ts
A recent change removed the `.rli` file filter for the license upload dropzone component, but older kots versions that our upgrade tests use still look for that. This PR removes the `accept` locator from our tests entirely as it's not really necessary.
```release-note
NONE
```
NONE
=> Fix uploading license file in regression tests

.github/workflows/alpha.yaml, .github/workflows/image-deps-updater.yaml, .github/workflows/kurl-addon-kots-publish.yaml, .github/workflows/kurl-addon-kots-test.yaml, .github/workflows/regression.yaml, .github/workflows/release.yaml, .github/workflows/tag-helm-chart.yaml, .github/workflows/update-kubectl.yaml
ubuntu-20.04 is removed and cannot be used anymore.
```release-note
NONE
```
NONE
=> use ubuntu-latest instead of ubuntu-20.04

pkg/airgap/airgap.go, pkg/automation/automation.go, pkg/online/online.go
Fixes processing config values in EC automated installs. The config values secret gets deleted after it's read, this PR makes it so that it's only read once and the value gets passed down.
```release-note
* Improvements for multi-node Embedded Cluster.
```
NONE
=> Fix processing config values in EC automated installs

.github/workflows/release-for-ec.yaml, .github/workflows/tag-helm-chart.yaml
This PR makes it possible to release for EC without an official release of vanilla KOTS by introducing a new GitHub dispatch workflow `release-for-ec.yaml` that handles building and tagging KOTS images and the kots helm chart using a special EC tag.
The workflow validates tag formats, builds necessary packages and images for `kotsadm-migrations`, `kurl-proxy`, and `kotsadm` components, then tags the KOTS Helm chart with a commit SHA suffix that is only used to link the tag to a specific commit in this repo as there is no real tag / release.
```release-note
NONE
```
NONE
=> Add support for EC release tags

cmd/kots/cli/get-joincommand.go, cmd/kots/cli/get-joincommand_test.go, cmd/kots/cli/get.go, pkg/api/handlers/types/types.go, pkg/embeddedcluster/roles.go, pkg/handlers/embedded_cluster_get.go, pkg/handlers/embedded_cluster_node_join_command.go
=> add hidden 'get join-command' command for embedded-cluster

pkg/handlers/embedded_cluster_artifacts.go, pkg/handlers/handlers.go, pkg/util/util.go, web/src/features/AppConfig/components/AppConfig.tsx
Adds endpoint that returns the EC infra images from the k0s directory.
[SC-122568](https://app.shortcut.com/replicated/story/122568)
In EC repo.
```release-note
NONE
```
NONE
=> Add endpoint that returns the EC infra images from the k0s directory

.github/actions/scan-image/action.yml
- Add safe_image_name which will eval to something like docker.io-replicated-local-volume-provider, to make it easier for github code scan to track issues. We need to remove the image version from the name.
- Then when we upload the sarif we set the category to include the new safe image name, which will ensure code scan results are properly tracked by github and will get automatically closed.
- After this gets merged, I will need to manually kick off the job and then clean out any potential dups or old data from the code scan issues.
NONE
NONE
```release-note
NONE
```
NONE
=> Add safe_image_name to help github better track scan findings over time

pkg/embeddedcluster/node_join.go, pkg/embeddedcluster/node_join_test.go, pkg/handlers/embedded_cluster_artifacts.go, pkg/handlers/handlers.go
Removes airgap bundle flag from join command as it's deprecated and not needed anymore.
[SC-122569](https://app.shortcut.com/replicated/story/122569)
Yes, in EC repo.
```release-note
NONE
```
NONE
=> Remove airgap bundle flag from join command

cmd/kots/cli/get-joincommand.go, cmd/kots/cli/get-joincommand_test.go, cmd/kots/cli/get.go, pkg/api/handlers/types/types.go, pkg/embeddedcluster/node_join.go, pkg/embeddedcluster/node_join_test.go, pkg/handlers/embedded_cluster_node_join_command.go, web/src/components/apps/EmbeddedClusterManagement.tsx, web/src/components/modals/AddANodeModal.tsx
Returns a list of commands from the API for the new join experience.
Updates the UI to reflect the new join experience.
```
$ /replicatedhq/kots/bin/kots get join-command -n kotsadm 
curl -k https://172.17.0.2:30000/api/v1/embedded-cluster/binary -o embedded-cluster.tar.gz && \
tar -xvf embedded-cluster.tar.gz && \
sudo ./embedded-cluster join 172.17.0.2:30000 mKjXc3FTBddmX3y4zkSMAKFB
```
```
$ /replicatedhq/kots/bin/kots get join-command -n kotsadm -ojson
{
"commands": [
"curl -k https://172.17.0.2:30000/api/v1/embedded-cluster/binary -o embedded-cluster.tar.gz",
"tar -xvf embedded-cluster.tar.gz",
"sudo ./embedded-cluster join 172.17.0.2:30000 GMYTL8RfkaTVBHylpslZy9yc"
]
}
```
```release-note
```
=> feat(ec): update node join instructions for improved join experience

pkg/tasks/tasks.go, pkg/upgradeservice/deploy/deploy.go
The stack trace does not include the caller.
```
goroutine 637 [running]:
github.com/rqlite/gorqlite.(*Connection).WriteOneParameterized(0xc0005b54c0?, {{0x4b99b78, 0x36}, {0xc0012f0160, 0x2, 0x2}})
/var/cache/melange/gomodcache/github.com/rqlite/gorqlite@v0.0.0-20221028154453-256f31831ff3/write.go:80 +0x13c
github.com/replicatedhq/kots/pkg/tasks.UpdateTaskStatusTimestamp({0xc0005b54c0, 0x37})
/home/build/pkg/tasks/tasks.go:94 +0x16a
github.com/replicatedhq/kots/pkg/tasks.StartTicker.func1()
/home/build/pkg/tasks/tasks.go:58 +0x87
created by github.com/replicatedhq/kots/pkg/tasks.StartTicker in goroutine 653
/home/build/pkg/tasks/tasks.go:54 +0x74
```
https://go.dev/play/p/ycLN77GiMAk
https://go.dev/play/p/XO5k7xEfVtP
```release-note
```
=> chore: fix stack trace

cmd/kots/cli/get-joincommand_test.go, pkg/embeddedcluster/node_join.go, pkg/embeddedcluster/node_join_test.go
Uses .tgz instead of .tar.gz for join instructions for consistency with the vendor portal and enterprise portal.
Yes
```release-note
NONE
```
NONE
=> Use .tgz instead of .tar.gz for join instructions

pkg/tasks/tasks.go
Updates upgrade task status timestamp safely in case of panics so they don't halt the upgrade progress in the UI if rqlite temporarily lost quorum.
[SC-123136](https://app.shortcut.com/replicated/story/123136)
```release-note
NONE
```
NONE
=> update upgrade task status timestamp safely

pkg/upgradeservice/deploy/deploy.go
Surfaces embedded cluster upgrade failures on panics
[SC-123136](https://app.shortcut.com/replicated/story/123136)
```release-note
NONE
```
NONE
=> Surface embedded cluster upgrade failures on panics

go.mod, go.sum
New property HostCABundlePath in RuntimeConfigSpec for improved CA support in Embedded Cluster
```release-note
```
=> feat(ec): HostCABundlePath in RuntimeConfigSpec for improved CA support

.github/workflows/build-test.yaml
push-dex is missing as a dep. rather than add it everywhere im consolidating into a dependent step
https://github.com/replicatedhq/kots/actions/runs/16177316076/attempts/1?pr=5409
```release-note
```
=> chore(ci): consolidate deps for e2e validate tests

go.mod, go.sum, pkg/airgap/update.go, pkg/handlers/app.go, pkg/handlers/upgrade_service.go, pkg/update/required.go, pkg/update/required_test.go, pkg/update/update.go
Doesn't allow updates of >1 minor kube versions for airgap EC installs
[SC-127829](https://app.shortcut.com/replicated/story/127829)
Yes
```release-note
NONE
```
NONE
=> feat(ec-updates): don't allow updates of >1 minor kube versions for airgap

e2e/playwright/regression/shared/version-history.ts
Addresses flakiness in playwright e2e tests, where we're checking for deployment status in the version history screen (for `Deploying`) however the version might have already been deployed before the UI check.
- https://github.com/replicatedhq/kots/actions/runs/17344549437/job/49318661802
NA
It's a test fix
```release-note
NONE
```
NONE
=> chore(e2e): address flakiness in deployment check

.github/workflows/release.yaml, e2e/playwright/regression/shared/version-history.ts, pkg/operator/operator.go, pkg/version/version.go
The current version card says "Currently deployed version" even when deploying. Logs are not yet available.
And
The frontend can stop polling for version status because the deploy api call sets the status to deploying in a go routine. This makes it synchronous.
```release-note
```
=> chore(ci): fix regression test flake

cmd/kots/cli/get-versions.go, pkg/print/versions.go
This is necessary to support the new EC V3 + KOTS upgrade workflow.
Example:
```bash
./bin/kots get versions default-kots-app-4 -ojson  
[
{
"versionLabel": "0.0.331+notrequired",
"sequence": 1,
"createdOn": "2025-08-14T18:47:09Z",
"status": "pending",
"deployedAt": null,
"source": "Upstream Update",
"channelId": "1YHCrcggWF7LeCjG1twkOdv6Oh6",
"channelSequence": 958
},
{
"versionLabel": "0.0.330",
"sequence": 0,
"createdOn": "2025-08-14T18:46:34Z",
"status": "deployed",
"deployedAt": "2025-08-14T18:46:36Z",
"source": "Online Install",
"channelId": "1YHCrcggWF7LeCjG1twkOdv6Oh6",
"channelSequence": 957
}
]
```
And:
```bash
./bin/kots get versions default-kots-app-4
VERSION                SEQUENCE    STATUS      SOURCE             CHANNEL ID                     CHANNEL SEQUENCE …
```
=> Include channel ID and sequence in get versions command

.github/workflows/build-test.yaml, cmd/kots/cli/deploy.go, cmd/kots/cli/root.go, e2e/scripts/deps.sh, go.mod, pkg/airgap/update.go, pkg/airgap/update_test.go, pkg/handlers/download.go, pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/handlers/update.go, pkg/kotsadmupstream/upstream.go, pkg/store/mock/mock.go, pkg/update/required.go, pkg/update/required_test.go, pkg/upstream/upgrade.go
Adds a new hidden KOTS command for V3 EC to be able to sync license, download update, update config and deploy in a single operation without having to know or track KOTS's version history.
[SC-129122](https://app.shortcut.com/replicated/story/129122)
```release-note
NONE
```
NONE
=> New hidden KOTS command for V3 EC to sync license, download update, update config and deploy in a single operation

.github/workflows/build-test.yaml, deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml, deploy/kurl/kotsadm/template/base/kurl-proxy/tmpl-deployment.yaml, deploy/kurl/kotsadm/template/base/rqlite.yaml, deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml, deploy/kurl/kotsadm/template/base/statefulset/patches/s3-migration.yaml, dev/manifests/kotsadm/deployment.yaml, dev/manifests/kotsadm/rqlite.yaml, pkg/identity/deploy/deploy.go, pkg/kotsadm/objects/kotsadm_objects.go, pkg/kotsadm/objects/minio_objects.go, pkg/kotsadm/objects/minio_objects_test.go, pkg/kotsadm/objects/rqlite_objects.go, pkg/kotsutil/kots_test.go, pkg/s3/s3.go, pkg/snapshot/filesystem_minio.go
Removes limits for all pods
```release-note
Removes CPU resource limits for all KOTS Admin Console pods.
```
=> chore: remove cpu resource limits from k8s objects
