replicatedhq/kots

deploy/.goreleaser.yml
the v0.6.0 release contained 'kots.so_linux_amd64_so.tar.gz'
=> remove '_so' suffix from kots.so release binaries as it is already present in the name

pkg/kotsadm/api_objects.go
as suggested by @marccampbell 
This fixes a recently introduced kots-operator sync permissions issue.
=> update rolebinding from kotsadm-operator to kotsadm-api

cmd/kots/cli/admin-console.go, cmd/kots/cli/download.go, cmd/kots/cli/install.go, cmd/kots/cli/pull.go, cmd/kots/cli/upload.go
Adds short and long help strings for the following commands:
admin-console
download
install
pull
upload
=> Add help strings for kots commands

Makefile
`v0.9.7-2-g358842a-dirty` vs `v0.9.7-2-g358842a`
=> if the git state is dirty, include that in the binary's version output

cmd/kots/cli/download.go, cmd/kots/cli/pull.go, cmd/kots/cli/upload.go
* Add `-n` shortcut for all instances of `namespace` option
* Make 'kots download' a "usage fail" if no app-slug is provided (because otherwise it fails confusingly)
* Fix `kots upload` usage message and default to the same user home dir for source that `kots download` uses for dest
Addresses https://github.com/replicatedhq/kots/issues/86 & https://github.com/replicatedhq/kots/issues/56
=> Fix inconsistencies in CLI flags and usage strings

pkg/midstream/lists.go, pkg/midstream/write.go
When there is a mix of proxied and public images, this will remove proxied images from the rewrite rules in favor of rewritten with the local private registry
=> remove existing images from kustomize instead of from the newly discovered list

go.mod, go.sum
see https://github.com/manifoldco/promptui/issues/117
a version override is added for go-i18n to avoid go mod issues
=> use promptui 0.3.2 until issue with persistent cursors is resolved

cmd/kots/cli/root.go, cmd/kots/cli/upstream-upgrade.go, cmd/kots/cli/upstream.go, ffi/updateslist.go, go.mod, pkg/download/download.go
This PR adds a new command:
```
kubectl kots upstream upgrade --namespace <namespace> <app-slug>
```
This command will do the same thing as clicking "Check for updates" in the admin console. If GitOps is enabled, it will result in a commit. If not, it will result in pending versions.
=> Upstream update

ffi/templates.go, pkg/config/config.go
Given an app archive, this will find the config, values and license and render a single file via an FFI function.
Open questions: what should we do about password values? Will the cluster encryption key be processed because it runs in as an ffi in the api sandbox?
=> Add FFI function to render any template

pkg/base/base.go, pkg/base/replicated.go, pkg/base/write.go, pkg/base/write_test.go
Some helm charts have duplicate resource definitions. This is fine in helm and kubectl, but kustomize doesn't like it. We can't pick one of these, because there is no guarantee that they are identical. So let's create a merge patch.
=> Prevent duplicates in the base

pkg/base/helm.go, pkg/base/write.go
We had an option already present "SplitMultidocYAML" but it wasn't used.
This uses the same splitting technique implemented by ksplit, but in memory. Only affects files with multidocs in them, and them -1, -2 indexes them, instead of trying to come up with deterministically generated names
=> Split multi-doc yaml renders

go.mod, kotskinds/apis/kots/v1beta1/config_types.go, kotskinds/multitype/boolstring.go, pkg/config/config.go, pkg/template/config_context.go, pkg/upstream/replicated.go, pkg/upstream/replicated_test.go
'true' is translated to the string '"1"', 'false' into '""'
Those were the values that we previously suggested for the defaults of boolean config options, so this works with existing kotsadm config rendering code.
=> accept bools or strings in config yaml

go.mod, pkg/kotsadm/kotsadm.go, pkg/kotsadm/limitrange.go, pkg/kotsadm/minio.go, pkg/kotsadm/minio_objects.go, pkg/kotsadm/postgres.go, pkg/kotsadm/postgres_objects.go, pkg/kotsadm/postgres_test.go
This makes kots attempt to find a postgres and minio pvc size that's within acceptable limit ranges, if there are limit ranges defined.
For example, given a limit range of:
```yaml
% kubectl get limitrange resource-limits -o yaml
apiVersion: v1
kind: LimitRange
metadata:
name: resource-limits
namespace: kots-tester
spec:
limits:
- max:
cpu: "2"
memory: 1Gi
min:
cpu: 7m
memory: 100Mi
type: Pod
- default:
cpu: "1"
memory: 512Mi
defaultRequest:
cpu: 20m
memory: 256Mi
max:
cpu: "2"
memory: 1Gi
min:
cpu: 7m
memory: 100Mi
type: Container
- max:
storage: 1Gi
min:
storage: 1Gi
type: PersistentVolumeClaim
```
When attempting to deploy, KOTS will prompt with:
```
Enter the namespace to deploy to: kots-tester
• Deploying Admin Console
• Creating namespace ✓  
✗ The storage request for minio is not …
```
=> Limit ranges

pkg/kotsadm/postgres_objects.go
previously it said 'The storage request for minio...' for both postgres and minio
=> fix postgres invalid size prompt

cmd/kots/cli/install.go
it doesn't actually do what it says it does, and so is a footgun
=> hide the 'exclude-admin-console' flag from 'kots install --help'

pkg/k8sutil/config.go, pkg/kotsadm/operator.go
instead of parsing the kubeconfig and trying to get a namespace from there, which won't always exist and won't always be accurate even if it does exist
=> use target namespace in subject-access-review request

kotskinds/apis/kots/v1beta1/helmchart_types.go, kotskinds/apis/kots/v1beta1/helmchart_types_test.go
This PR updates the helm render utility to handle values with a `.`.
We pass these in to the render function the same way that the `--set` CLI flag does in `helm render`.  The problem this addresses is when there's a values.yaml that contains something like this:
```yaml
ingress:
annotations:
kubernetes.io/ingress.class: nginx
```
Before this PR, this would be rendered as:
```yaml
annotations:
kubernetes: "map[io/ingress:map[class:nginx]]"
kubernetes.io/ingress.class: "nginx"
```
This is because helm splits on the `.` character. By adding escaping in, this now renders as:
```yaml
annotations:
kubernetes.io/ingress.class: "nginx"
```
=> Handle helm values with a dot

support-bundle.yaml
Initial support-bundle spec that we'll return (via Cloudflare rules on useragent) for troubleshoot requests made to https://kots.io.
=> default support-bundle spec for kots

pkg/image/builder.go
With this change, setting `KOTSADM_INSECURE_SRCREGISTRY` to `true` within the `kotsadm-api` container will allow kotsadm to pull images from insecure registries
=> allow disabling image pull security for development environments

cmd/kots/cli/upstream-upgrade.go
Otherwise the current `cmd.Help(); os.Exit(1)` behavior (for not providing an appSlug) is completely unhelpful
=> include requirement for appSlug in 'kots upstream upgrade' help text

pkg/kotsadm/kotsadm_objects.go
the role migration is handled in https://github.com/replicatedhq/kots/pull/284, which is not yet merged (but will be for 1.12)
=> add 'kotsadm-password' to the set of secrets the kotsadm deployment can access

go.mod, go.sum, kotskinds/multitype/boolstring.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/main_test.go, pkg/util/marshal_indent.go, pkg/util/marshal_indent_test.go
use laverya/yaml.v3 to marshal yaml with unlimited line length
also add MarshalYAML interface for the BoolOrString type (so that it renders the same as it did previously)
=> fix config yaml rendering with long template functions

ffi/config.go, go.mod, go.sum, pkg/config/config.go, pkg/config/config_test.go, pkg/util/marshal_indent.go
The new code has improved testing for differences with the previous json marshaller based code, and uses replicatedhq/yaml instead of laverya/yaml
=> update configmarshal code

cmd/kots/cli/admin-console-upgrade.go, cmd/kots/cli/admin-console.go, cmd/kots/cli/download.go, cmd/kots/cli/install.go, cmd/kots/cli/reset-password.go, cmd/kots/cli/root.go, cmd/kots/cli/upload.go, cmd/kots/cli/upstream-upgrade.go, cmd/kots/cli/util.go, go.mod, go.sum, pkg/auth/auth.go, pkg/download/download.go, pkg/k8sutil/clientset.go, pkg/k8sutil/kotsadm.go, pkg/k8sutil/portforward.go, pkg/k8sutil/proxy.go, pkg/kotsadm/main.go, pkg/kotsadm/types/deployoptions.go, pkg/kotsadm/types/upgradeoptions.go, pkg/upload/port-forward.go, pkg/upload/upload.go, pkg/upload/upload_license.go
This changes everywhere we create a generic clientset to use all supported kubeconfig flags. After this, all kots cli options will support the exported genericclioptions. 
This allows for behavior like 
```
kubectl --kubeconfig ~/path/to/alternate/config install app-name
```
And kots will respect the alternate kubeconfig.
=> Use genericlioptions KubernetesFlags when building clientsets

go.sum, integration/upload/server.go
On some envs, the test execution continued before listenandserve was ready. this will now poll that the server is ready before continuing execution of the tests
=> Make mockserver wait for start

pkg/docker/registry/auth.go
This allows kots to push images to http registries, but doesn't solve the problem of pulling images _from_ those registries
That's something that (afaict) needs to be done on the host side
=> allow use of insecure (http) docker registries

cmd/kots/cli/reset-password.go, go.mod
basically, `kubectl kots reset-password mynamespace`, `kubectl kots reset-password -n mynamespace` and `kubectl kots reset-password --namespace mynamespace` should all work.
=> allow using the namespace flag with the reset-password command

.gitignore, go.mod, go.sum, pkg/template/config_context.go, pkg/template/config_context_test.go, pkg/template/depgraph_test.go, pkg/template/license_context.go, pkg/template/license_context_test.go
without this, you can't put a license template function in a config value/default and have it work
this PR also includes a fix to allow building on windows without GCC - updating to github.com/Microsoft/hcsshim@master (specifically updating to include https://github.com/microsoft/hcsshim/pull/749/commits/0981fba75cc27b842950636eb469e940b4d3ebe3) removes the last thing requiring cgo and thus gcc.
=> include license in config value resolution

Makefile
Prior to this fix, you'd see numerous `scope-go-{timestamp-guid}.log` files generated next to source files with each build.
Setting SCOPE_LOG_ROOT_PATH to /dev/null within the makefile supresses their creation.
Run `find . -name *.log` after a `make` to verify.
This is a workaround for https://github.com/undefinedlabs/scope-go-agent/issues/174
=> set SCOPE_LOG_ROOT_PATH to /dev/null to avoid creating lots of logfiles

pkg/template/depgraph.go, pkg/template/depgraph_test.go
Now error messages include the offending configitem, and why:
```
no config options exist with 0 dependencies - "alpha" depends on "bravo"; "bravo" depends on "alpha", "charlie"
```
or
```
no config options exist with 0 dependencies - "bravo" depends on "doesnotexist"
```
Previously, the error was always the same:
```
No nodes exist with 0 dependencies
```
=> improve configitem resolution failure messaging

pkg/k8sutil/portforward.go
Resolving this issue:
```
W0304 18:24:28.286858    3266 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1396 clients constructed calling "..."
```
We were storing the cfg that we read from the flags, and creating new client instances from it. That's not ideal. Instead, let's get new config each time we want to create a new client.
Why don't we just cache the clientset? That sounds appealing, but then are caching auth tokens, which could have worse effects.
=> Read config each time we construct a client

cmd/kots/cli/download.go
'kots upload' only allows using the `--slug` flag, so this allows us to make the suggested usage consistent
=> allow 'kots download <slug>' or 'kots download --slug <slug>'

kotskinds/apis/kots/v1beta1/application_types.go
This fixes a broken JSON tag in `ApplicationSpec{}`.
=> kotskinds/apis/kots/v1beta1: fix JSON tag

integration/upload/server.go, pkg/upload/upload.go
The response on this was URI but never used. Changing this to app slug because that's the value that is needed in other requests.
This is potentially a breaking change (but the API route changes here also).
The TS API (existing API) is being deprecated, not removed. Any functionality that depends on the full URI being returned here can continue to use the TS API for 1.14 and 1.15 release cycles.
=> Call the Go API for upload

pkg/download/download.go, pkg/k8sutil/portforward.go
Switch the default CLI to use the Go API for downloading. The TS API is deprecated and will be removed in 1.16.0 but retains full functionality until then..
Also, this was using a static local port (3000). This PR makes use of existing code to have the local port be dynamically allocated.
=> Download in the Go api

pkg/upstream/replicated_test.go
Fixed up yaml was returning empty documents because we were passing `---`
Also fixed up yaml adds a new line
=> Tests supporting fixup

.github/workflows/build-test-deploy.yaml
Was removed in 6ed7eaa3e36847e5ad24093a94340e5ef2ff604b.
Requires to have `SCOPE_DSN` added to the repository's secrets.
=> Add Scope DSN to testing step

pkg/kotsadm/kotsadm_objects.go
this duplicates SHIP_API_ADVERTISE_ENDPOINT in the nodejs api pod
https://github.com/replicatedhq/kots/blob/bbb7ed29573b5ccb481615b46266247320d826fe/pkg/kotsadm/api_objects.go#L308-L311
=> add API_ADVERTISE_ENDPOINT env var to golang api pod

pkg/kotsadm/minio_objects.go
closes https://github.com/replicatedhq/kots/issues/177
=> remove 'upgrade from 1.4.0' chown migration

cmd/kots/cli/install.go, ffi/online.go, pkg/kotsadm/license.go, pkg/kotsadm/license_objects.go, pkg/kotsadm/main.go, pkg/kotsadm/types/deployoptions.go, pkg/pull/peek.go, pkg/pull/pull.go
This fixes #450 by changing this functionality completely. Before this PR, `kots install .. --license-file` used the license file and pulled locally.
With this PR, the behavior of kots install works the same, with or without a license file. If a license file is passed, it's written to a secret with a label and kotsadm will pick it up during start (replicatedhq/kotsadm#1376)
=> Change `kots install --license-file` to be the same as `kots install`, but automate license installation

pkg/base/base.go, pkg/base/write.go, pkg/base/write_test.go
if resources have different namespaces, they aren't the same namespace
fixes https://github.com/replicatedhq/kots/issues/476
=> fix detection of independent resources in different namespaces

kotsadm/pkg/snapshot/velero.go, kotsadm/pkg/supportbundle/backup.go
Fixes #539 
The helm chart uses different label selectors.
There's still a chance this won't work in some cases. There are no static label selector or annotations in this deployment. But KOTS supports "standard" installations of velero, and this extends support for the velero helm chart installation method.
=> Support detecting velero from helm chart

kotsadm/operator/pkg/client/deploy.go, kotsadm/operator/pkg/client/doc.go, kotsadm/operator/pkg/client/gvkn.go
This makes it possible for a KOTS application include a namespace definition and manifest that will be deployed into that namespace, while supporting a single "apply" release.
The operator, which handles the application phase, will extract namespaces from the manifest, apply them before applying the rest of the documents.
There's a 5 second hard coded sleep after CRD and namespace that already exists. The Kubernetes API server will have this much time to actually apply the namespace or the deploy will still fail.
A better solution could be to use an informer to allow for the namespace creation to happen in > 5 seconds. This has not been a problem yet, but this is something to watch for.
=> Early apply namespaces in addition to CRDs

kotsadm/api/src/controllers/kots/KotsAPI.ts, kotsadm/api/src/kots_app/graphql/kots_app_types.ts, kotsadm/api/src/kots_app/kots_app.ts, kotsadm/api/src/kots_app/kots_app_store.ts, kotsadm/api/src/kots_app/kots_ffi.ts, kotsadm/api/src/kots_app/kots_installation_spec.ts, kotsadm/api/src/util/tar.ts, kotsadm/migrations/fixtures/src/schema/schema.ts, kotsadm/migrations/tables/app_version.yaml, kotsadm/pkg/version/version.go, kotsadm/web/src/queries/AppsQueries.js, kotskinds/apis/kots/v1beta1/installation_types.go, pkg/base/base.go, pkg/base/base_test.go, pkg/base/replicated.go, pkg/base/write.go, pkg/base/write_test.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go
This pr will render yaml parse errors as part of the kots.io/v1beta1 Installation yaml document
Including the following yaml file in a release would render no files. There would be no messaging to the user and the installation would proceed.
```yaml
not: kubernetes
---
{{
```
With the addition of this commit the user will see errors in the Installation yaml document.
bad.yaml
=> Fail on invalid yaml

cmd/kots/cli/install.go, cmd/kots/cli/pull.go
Adds the `--config-values` option - recentry introduced in `kots install` - to `kots pull` to facilitate a similar workflow for validating rendered manifests.
Fixes #514.
=> Add '--config-values' option for 'kots pull'

kotsadm/api/src/controllers/kots/KotsAPI.ts
```
no match found for link http://applink in app ports http://notapplink, http://anothernotapplink
```
=> log when no match found for app link

Makefile, go.mod, kotsadm/api/src/snapshots/resolvers/veleroClient.ts, kotsadm/go.mod, kotsadm/go.sum, pkg/docker/registry/auth.go, pkg/template/static_context.go
Includes template functions for proxy and no_proxy.
There was a docker library that that didn't have an option to configure the http client so the original plan of using `PROXY_ADDRESS` env var and opting-in for non-cluster requests didn't work. Instead https://github.com/replicatedhq/kURL/pull/486 expands the NO_PROXY var to include all in-cluster hostnames.
=> Kotsadm works with HTTP_PROXY

kotsadm/api/src/kots_app/kots_app_store.ts, kotsadm/pkg/airgap/airgap.go, kotsadm/pkg/airgap/update.go, kotsadm/pkg/online/online.go, kotsadm/pkg/registry/registry.go, kotsadm/pkg/upstream/upstream.go
A missing `finalError = err` in here was causing applications that should have a `install_err` install status to have a `installed` install status: https://github.com/replicatedhq/kots/pull/619/files#diff-0b2ffb5eb00a02a319abad5e1e622644R146
=> better handling for app installation errors

kotsadm/pkg/handlers/backup.go
this fixes a bug that was causing the api log to show stack traces when velero is not installed
=> Velero is still optional

kotsadm/pkg/automation/automation.go, kotsadm/pkg/handlers/license.go, kotsadm/web/src/components/UploadLicenseFile.jsx, pkg/pull/pull.go
Addresses #629 
The license will not be synced before checking for expiration date, and uploading the license will fail with `License is expired` if the uploaded license is expired.
The license WILL be synced before checking for expiration date, and if the upstream license is not expired, installation will not be interrupted.
=> check license expiration on license upload

kotsadm/kurl_proxy/assets/tls-custom.css
=> fix kurl-proxy: button styles looking very off

pkg/template/random.go, pkg/template/random_test.go, pkg/template/static_context.go
Adds the randBytes function to cryptographically generate a base64-encoded string of random bytes of a given length.
Resolves #716.
=> Add RandomBytes template function

kotsadm/pkg/automation/automation.go, kotsadm/pkg/handlers/license.go, kotsadm/pkg/online/online.go
Should always show the config screen (if a config is provided) and not run preflights or deploy until the user saves the values, even if no config items are required.
Should bypass the config screen if configuration is not required (e.g. there aren't any required items or any unset required items).
=> skip config screen on automated installs if not required

kotsadm/web/src/components/PreflightResultPage.jsx
=> preflight result page design updates

kotsadm/pkg/downstream/diff.go, kotsadm/web/package.json, kotsadm/web/src/components/shared/DiffEditor.jsx, kotsadm/web/src/utilities/utilities.js, kotsadm/web/yarn.lock
=> fix diff summary in both UI and API

kotsadm/pkg/apiserver/server.go, kotsadm/pkg/handlers/redact.go, kotsadm/pkg/redact/redact.go, kotsadm/pkg/redact/redact_test.go
the existing route requires you to update the description, redactor yaml, etc at the same time
Usage is to post `{"enabled":true}` or `{"enabled":false}` to `/api/v1/redact/enabled/{slug}` to enable/disable a redactor. It returns the full redactor yaml+metadata struct
=> add a route to only update a redactor's enabled status

cmd/kots/cli/upstream-upgrade.go, kotsadm/pkg/updatechecker/updatechecker.go
=> Fix: upstream update should deploy

kotsadm/web/src/components/gitops/GitOpsDeploymentManager.jsx
GitOps wording incorrectly conveys that "automatic deploys" are not possible anymore. It should say that click-to-deploy is not possible from the UI.
=> Click-to-deploy is disabled, not automatic deploys.

kotsadm/pkg/handlers/redact.go, kotsadm/pkg/redact/redact.go, kotsadm/pkg/redact/redact_test.go, kotsadm/web/src/components/redactors/EditRedactor.jsx, kotsadm/web/src/components/redactors/RedactorRow.jsx, kotsadm/web/src/components/redactors/Redactors.jsx, kotsadm/web/src/components/troubleshoot/AnalyzerFileTree.jsx, kotsadm/web/src/components/troubleshoot/SupportBundleList.jsx, kotsadm/web/src/components/troubleshoot/TroubleshootContainer.jsx, kotsadm/web/src/scss/components/redactors/EditRedactor.scss
=> Managing redactors updates

.github/workflows/build-test.yaml, kotsadm/Makefile, kotsadm/api/Makefile, kotsadm/api/deploy/Dockerfile, kotsadm/build-ttl-ci.sh, kotsadm/kurl_proxy/Makefile, kotsadm/migrations/Makefile, kotsadm/migrations/fixtures/Makefile, kotsadm/minio/Makefile, kotsadm/operator/Makefile, kotsadm/pkg/apiserver/depends.go
Significant change to the kots test process.
This PR removes the shared DigitalOcean cluster and used a local k3s install as a test matrix. Tests are executed against the supported versions of Kubernetes, all in cluster.
=> Test on multiple K3s versions

pkg/template/static_context.go, pkg/template/static_context_test.go
Adds `TLSCACert`, `TLSCertFromCA`, and `TLSKeyFromCA` to generate a named CA cert/key pair and access the cert, as well as generate cert/key pairs from that CA as needed (based on the combination of CA name, cert name, and common name).
Useful when you need a separate CA certificate, such as working around https://github.com/openssl/openssl/issues/1418.
Fixes #844.
=> Generate CA and certificates from CA

kotsadm/api/deploy/Dockerfile, kotsadm/deploy/Dockerfile, kotsadm/kurl_proxy/deploy/Dockerfile, kotsadm/operator/deploy/Dockerfile
This will reduce the image size by about 549.2M if it does break anything :)
=> Reduce image size, copy with chown flag

pkg/pull/pull.go, pkg/upstream/replicated.go, pkg/upstream/types/types.go, pkg/upstream/write.go
=> encrypt plain text passwords on initial install

pkg/base/images.go, pkg/image/builder.go, pkg/k8sdoc/types.go, pkg/midstream/midstream.go, pkg/midstream/write.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go
Closes https://github.com/replicatedhq/kots/issues/631
=> Add pull secrets and re-write image in Pod objects

kotsadm/web/package.json, kotsadm/web/yarn.lock
last piece of the puzzle to resolve #897 
upgrade to replicatedhq/ship-init version 1.6.23 to support conditional `when` field on config groups.
=> upgrade replicatedhq/ship-init to version 1.6.23

ffi/updatedownload.go, kotsadm/pkg/airgap/update.go
instead of saying that version 157 is newer than version 157
=> add a special message for failing to install the current version

kotsadm/go.mod, kotsadm/go.sum, kotsadm/pkg/secrets/sealed_secrets.go, kotsadm/pkg/secrets/secrets.go, kotsadm/pkg/version/version.go
This adds an experimental feature to integrated the bitnami sealedsecrets controller into kots.
With this change, if a secret is deployed to the same namespace as kots, and the secret looks like
```
apiVersion: v1
data:
cert.pem: <base64 encoded certificate?
kind: Secret
metadata:
labels:
kots.io/buildphase: secret
kots.io/secrettype: sealedsecrets
name: kots-sealed-secret
namespace: default
type: Opaque
```
All secrets in the base will be replaced with encrypted sealed secrets.
=> Convert secrets to sealed secrets

.github/workflows/build-test.yaml, kotsadm/operator/pkg/applier/kubectl.go, kotsadm/operator/pkg/client/client.go, pkg/kotsadm/api_objects.go, pkg/kotsadm/kotsadm_objects.go
=> Fixing minimal rbac install

pkg/image/builder.go
inspired by an error message:
```
failed to pull: failed to find private images: failed to list upstream images: failed to walk upstream dir: failed to check if image is private: failed to parse image ref:: invalid reference format
```
where the offending image is `:`, which is nearly impossible to search for. A file path would make this easier.
=> return a better error message when unable to find images

kotsadm/pkg/kurl/kurl_nodes.go
this fixes the following error:
```
2020-09-08T22:46:07.285Z	ERROR	handlers/kurl_get.go:21	parse 'ha' entry in kurl config "": strconv.ParseBool: parsing "": invalid syntax
```
=> don't parse empty strings as bool in kurl config

kotsadm/cmd/kotsadm/cli/api.go, kotsadm/cmd/kotsadm/cli/restore.go, kotsadm/cmd/kotsadm/cli/root.go, kotsadm/kustomize/overlays/dev/deployment.yaml, kotsadm/pkg/logger/logger.go
This changes the default log level in kotsadm from DEBUG to INFO and also updates the output format to JSON.
Before this change, on a live install (and also on dev):
```
2020/09/11 15:35:06 kotsadm version v1.19.0
2020-09-11T15:35:06.448Z	DEBUG	s3pg/s3pg_store.go:144	waiting for object store to be ready[]
2020-09-11T15:35:06.449Z	DEBUG	s3pg/s3pg_store.go:103	waiting for database to be ready[]
2020-09-11T15:35:06.461Z	DEBUG	s3pg/s3pg_store.go:155	object store is ready[]
2020-09-11T15:35:06.463Z	DEBUG	s3pg/s3pg_store.go:116	database is ready[]
2020-09-11T15:35:06.473Z	DEBUG	updatechecker/updatechecker.go:30	starting update checker[]
2020-09-11T15:35:06.528Z	DEBUG	updatechecker/updatechecker.go:64	configure update checker for app[{slug 15 0 admin <nil>}]
2020-09-11T15:35:06.528Z	DEBUG …
```
=> Updates to logger and levels

pkg/template/license_context.go
I've added documentation for allowed values, so figured it should remain updated by adding this comment requesting a docs update whenever the function adds/changes allowed values.
https://github.com/replicatedhq/kots.io/pull/272
=> Tiny PR: Add note to update docs when updating LicenseFieldValue

kotskinds/apis/kots/v1beta1/airgap_types.go, pkg/pull/pull.go
this way we don't get 'failed to verify bundle signature' when the apps don't match
=> include AppSlug in airgap spec, check against license

kotsadm/pkg/kurl/configmap.go
doing so cancels the 'delete kurl-join-cert pod' task
=> don't cancel context after finishing createCertAndKey

pkg/base/add_bundle_part.go, pkg/base/write.go, pkg/downstream/write.go, pkg/k8sutil/kustomization.go, pkg/midstream/write.go
This PR updates KOTS to allow different tags from the same image to be used. The current KOTS implementation generates a Kustomize patch to replace images after specifying the local registry. This doesn't work when there are two different tags in use by the same image (see kubernetes-sigs/kustomize#2701). In addition, the type that we use from Kustomize plainly states that the tag should not be set, and does not have a field for `tag` to be set (https://github.com/kubernetes-sigs/kustomize/blob/1c24fe7d16ec0031b68b946afbb2f9d70b7b0937/api/types/image.go#L9)
There are several options available here, but we want KOTS to stick closely to the upstream tools. Currently KOTS always uses the same tag, so removing the `newTag` field from this Kustomization before writing the file results in the …
=> Prevent setting newTag in kustomization file

kotsadm/pkg/supportbundle/analyze.go
also, the default case of '1 replica' should be a pass, not a warn
=> analyze 'kotsadm', not 'kotsadm-api', deployment

kotsadm/pkg/store/s3pg/version_store.go, pkg/kotsutil/kots.go
This won't actually allow things to work when they did not previously work (because we expect installation spec to be valid) but it at least makes the error not a 'failed to scan row' error and instead something searchable
=> kots_installation_spec can be null, so scan into sql.NullString

kotsadm/kurl_proxy/Dockerfile.skaffold, kotsadm/kurl_proxy/Makefile, kotsadm/kurl_proxy/cmd/main.go
The environment variable `NODE_PORT` is already defined and configured, but it was never used. Instead the port `8800` was hard-coded. Uses `NODE_PORT` to set the listening port, defaulting to `8800`.
Uses multi-stage build to only ship the `kurl_proxy` binary. Omits the symbol table, debug information, and DWARF table with linker flags.
=> Slim kurl-proxy and use NODE_PORT

kotsadm/pkg/apiserver/server.go, kotsadm/pkg/handlers/airgap.go, kotsadm/web/src/ConnectionTerminated.jsx, kotsadm/web/src/Root.jsx, kotsadm/web/src/components/AirgapUploadProgress.jsx, kotsadm/web/src/components/UploadAirgapBundle.jsx, kotsadm/web/src/utilities/airgapUploader.js, kotsadm/web/src/utilities/fetchWithTimeout.js
The behavior will be as follows:
1- The Admin Console will try reconnecting to the api and will timeout after 10 seconds if it couldn't (intervals of 1 second). During the "reconnecting" phase, the progress bar will be left as is and a message indicating connectivity issues will be shown to the user.
2- If reconnected successfully and there was no data loss in the api, uploading will resume normally and the progress bar will continue from where it left off.
3- If reconnected successfully but there was some data loss in the api, uploading will be automatically restarted and the progress bar will be reset to 0.
When resuming uploads, the progress bar will instantly be set to where it left off instead of showing small incremental changes.
=> Handle intermittent internet failure during airgap bundle upload

Makefile, Makefile.build, kotsadm/Makefile, kotsadm/kurl_proxy/Dockerfile.skaffold, kotsadm/kurl_proxy/Makefile, kotsadm/operator/Makefile, kotskinds/Makefile
Reverts Dockerfile changes from https://github.com/replicatedhq/kots/pull/1110 because they didn't apply to the production Dockerfile.
Adds Makefile.build to set common build variables such as SHELL, GOPROXY, and LDFLAGS. Updates Makefiles to include it. Adds `-s -w` to all `go build` invocations for smaller binaries by omitting the symbol table, debug information, and DWARF table.
=> Update 'go build' link flags

kotsadm/go.mod, kotsadm/pkg/handlers/troubleshoot.go
Unresolved issues:
1. redactors make tar or tar.gz invalid
2. tar is dropped in a directory deep within the bundle `/default/kotsadm-6b588f457c-jzx4k/kotsadm/tmp/app-version-archive545366197/ethan-kots.tar`
=> Include app version archive in support bundle

kotsadm/pkg/store/s3pg/version_store.go, kotsadm/pkg/version/version.go, pkg/k8sutil/portforward.go, pkg/kotsutil/kots.go
Port forward used to require that the k8s.io and kots.io app specs service names matched exactly, but the docs state that the kots.io spec doesn't need to specify the port if it's the only port on the service. This PR changes the requirements and no longer uses the k8s.io spec, but now just the kots.io spec. 
Additionally, the kots CLI was not logging anything discoverable, so i changed that to log to stdout/stderr. This could be noisy when creating a service and it's not yet ready. So the api pod will now check that the service has at least 1 ready pod before sending it to the client to begin a port forward on it. In the event that this doesn't complete, the logs will be in the kotsadm logs, not flooding the client logs. But for port conflicts and RBAC issues port-forwarding the …
=> Make port forward work

kotsadm/pkg/handlers/registry.go, kotsadm/pkg/preflight/preflight.go, kotsadm/pkg/preflight/preflight_test.go, kotsadm/pkg/registry/registry.go, kotsadm/pkg/registry/troubleshoot.go, kotsadm/pkg/registry/troubleshoot_test.go, kotsadm/pkg/supportbundle/supportbundle.go, pkg/docker/registry/registry.go, pkg/k8sdoc/types.go, pkg/kotsutil/kots.go, pkg/midstream/write.go
Currently, troubleshoot supports private images with imagePullSecrets. This is way too manual though and requires knowledge of the end customers environment or use of template functions.
This PR changes KOTS to automatically rewrite `image` tags in any `run` collector from image name to the private image name. 
If the image is public and the instance is online, no change.  
If the image is private and the instance is online, will rewrite to the Replicated proxy registry and use the license as an imagePullSecret.
If the image is in the replicated private registry and the instance is online, will add the license as an imagePullSecret.
If the instance has a local registry available, this will always use that and write an imagePullSecret with the pull credentials to the local registry.
=> Automatically rewrite private and local images in preflight and support bundle

kotsadm/pkg/handlers/cors.go, kotsadm/pkg/handlers/troubleshoot.go, kotsadm/web/src/components/troubleshoot/SupportBundleAnalysis.jsx, kotsadm/web/src/components/troubleshoot/SupportBundleRow.jsx
Currently, when you download a support bundle, each download is the same filename, so you can't tell them apart. This PR adds the support bundle creation/collection datetime as a suffix to the bundle name.
=> unique support bundle names

pkg/base/images.go, pkg/image/builder.go
mention how many images are in the document, and which one failed
quote image refs with '%q' to make them clearer
=> further improve image parse ref failure messaging

cmd/kots/cli/install.go, pkg/kotsadm/kotsadm_objects.go, pkg/kotsadm/types/deployoptions.go
Sets `DISABLE_OUTBOUND_CONNECTIONS` on `--airgap` flag and `--kotsadm-registry` instead of just `--kotsadm-registry`
=> Set DISABLE_OUTBOUND_CONNECTIONS on --airgap flag

kotsadm/pkg/apiserver/server.go, kotsadm/pkg/socketservice/socketservice.go
Restoring application backups in the old format will cause the disaster recovery labels to be removed. This will redeploy the restored version upon restore which will make sure the labels are present.
=> Redeploy on restore

pkg/template/kurl_context.go
recent installs of kurl do not use 'base' as the installer name
fixes https://github.com/replicatedhq/kots/issues/1192
=> fallback to any kurl installer if one named 'base' is not found

cmd/kots/cli/remove.go, kotsadm/pkg/handlers/app.go
```
$ kubectl kots remove myapp-1 -n default
• Removing application myapp-1
Error: failed to remove app, command may be retried with --force flag: application myapp-1 is deployed and cannot be removed
```
=> Update messaging when app cannot be removed

cmd/kots/cli/install.go, cmd/kots/cli/upstream-upgrade.go, kotsadm/pkg/airgap/airgap.go, kotsadm/pkg/airgap/update.go, kotsadm/pkg/automation/automation.go, kotsadm/pkg/handlers/airgap.go, kotsadm/pkg/handlers/config.go, kotsadm/pkg/handlers/license.go, kotsadm/pkg/handlers/registry.go, kotsadm/pkg/handlers/update.go, kotsadm/pkg/handlers/upload.go, kotsadm/pkg/license/license.go, kotsadm/pkg/online/online.go, kotsadm/pkg/store/ocistore/version_store.go, kotsadm/pkg/store/s3pg/version_store.go, kotsadm/pkg/store/store_interface.go, kotsadm/pkg/updatechecker/updatechecker.go, kotsadm/pkg/upstream/upstream.go, kotsadm/pkg/version/version.go, pkg/kotsadm/configmaps_objects.go, pkg/kotsadm/types/deployoptions.go, pkg/kotsutil/kots.go
On initial install, if a license and a config files are provided, skip-preflights will bypass preflight checks and deploy the app.
```
kots install myapp --config-values ./config.yaml --license-file ./license.yaml --shared-password password --skip-preflights
```
On updates, skip-preflights will bypass prefligths.  To deploy the latest version, the `--deploy` flag should be specified.
```
kots upstream upgrade myapp -n myapp --skip-preflights
```
=> Allow skipping preflights

kotsadm/pkg/handlers/app.go, pkg/docker/registry/auth.go, pkg/image/builder.go, pkg/kotsadm/push_images.go
this leads to the https://github.com/containers/image/blob/1a0dda734e3bed323a9674e274b379cf841fe8b1/docker/docker_client.go#L752 codepath instead of https://github.com/containers/image/blob/1a0dda734e3bed323a9674e274b379cf841fe8b1/docker/docker_client.go#L774
=> don't check for v1 docker registries - this obscures the actual error

kotsadm/deploy/install-krew.sh, kotsadm/operator/deploy/install-krew.sh
The krew installation instructions no longer point to google storage, and this results in a 404 on a new, clean environment.
Updating with the latest crew.dev installation instructions
=> Fix krew install

cmd/kots/cli/app-status.go, cmd/kots/cli/root.go, kotsadm/pkg/apiserver/server.go, kotsadm/pkg/handlers/app.go, kotsadm/pkg/policy/policies.go
This is hidden for now, needed in the test grid to validate that an app is ready.
```
$ kubectl kots app-status -n default appslug
{"appstatus":{"appId":"1lo5gQWBoCuU2rRUCNq2xFyPdBS","updatedAt":"2020-12-18T00:49:45.417477Z","resourceStates":[{"kind":"EMPTY","name":"EMPTY","namespace":"EMPTY","state":"ready"}],"state":"ready"}}
```
=> Add a (hidden) CLI command to return the app status

pkg/kotsadm/main.go
if someone runs `kubectl kots install --airgap-bundle ./bundle.airgap --license-file ./mylicense.yaml --namespace mynamespace` or similar _without_ `--kotsadm-registry`, `--registry-username` etc, we should make it clear that the app images will not be pushed.
(I'm not sure if there's any valid scenarios in which you would want to do this, and I figure the "I'm missing args" log line is better than making it an error until we figure that out)
=> log when not pushing images in airgap cli install

cmd/kots/cli/install.go
These flags have been in the product for 6 months, but they are still incomplete. Let's hide them to avoid confusion until they are ready to be tried.
=> Hide incomplete experimental flags from CLI

kotsadm/pkg/store/s3pg/supportbundle_store.go, kotsadm/pkg/store/s3pg/version_store.go
it should be unambiguous what code returned the error
=> improve 'failed to download file' errors

pkg/handlers/handlers_test.go, pkg/handlers/troubleshoot.go, pkg/policy/getters.go, pkg/store/kotsstore/migrations.go, pkg/store/kotsstore/supportbundle_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/supportbundle_store.go, pkg/store/store_interface.go, pkg/supportbundle/supportbundle.go, pkg/supportbundle/types/types.go
In the pg version of KOTS, there are three tables, three types:
- Pending Support BUndle
- Support Bundle 
- Support Bundle Analysis
This PR keeps the types the same, but moves the storage. Now there will be 1 secret per bundle/analysis. If theres no analysis, the spec will have an empty analysis.
The secrets for bundles and analysis are named `supportbundle-<id>`
In addition to the common KOTS labels, these objects have some additional labels:
```
kots.io/kind: supportbundle
kots.io/appId: <value>
```
Pending support bundles are secrets, with common labels, the labels above, but `kots.io/kind` is set to `pendingsupportbundle`.
Additionally, there's some cleanup. We had GetSupportBundle and GetSupportBundleForSlug. But Slugs and IDs were the same, so this was two code paths that was …
=> Migrate support bundles to native k8s objects

migrations/tables/api_task_status.yaml, pkg/store/kotsstore/kots_store.go, pkg/store/kotsstore/migrations.go, pkg/store/kotsstore/task_store.go
I am migrating any rows from Postgres into the ConfigMap. It's unlikely that this will be needed, but there is possibly an edge case where an application upgrade is in progress and the Admin Console is upgrades before it completes. In this case, the migration isn't going to add a new resumable functionality, but it will keep the user experience consistent.
=> Move tasks to a configmap, out of postgres

kotsadm/operator/go.mod
**github.com/gorilla/websocket is already on version v1.4.2** ( https://github.com/replicatedhq/kots/pull/1478)
**github.com/mitchellh/hashstructure to v1.1.0** (https://github.com/replicatedhq/kots/pull/1476)
=> api dependencies updates

cmd/kots/cli/upload.go, cmd/kots/cli/upstream-upgrade.go, pkg/handlers/upload.go, pkg/upload/upload.go
Adds `--deploy` and `--skip-preflights` flags to `kots upload`. This enables uploading local changes and immediately deploying them, which is useful for a CLI-only workflow.
Resolves #1201.
=> add 'kots upload --deploy --skip-preflights'

kotsadm/operator/go.mod
github.com/spf13/cobra from 0.0.5 to 0.0.7  (https://github.com/replicatedhq/kots/pull/1613)
github.com/pact-foundation/pact-go from 1.0.0-beta.5 to 1.5.1 (https://github.com/replicatedhq/kots/pull/1623)
=> Bump go dependencies

pkg/kotsadm/objects/affinity_objects.go
`NodeSelectorTerms` are OR'ed, but `MatchExpressions` are AND'ed
=> Fix node affinity for Admin Console objects

.github/workflows/build-test.yaml, deploy/postgres/Dockerfile, migrations/deploy/Dockerfile, migrations/kustomize/overlays/dev/postgres.yaml, pkg/kotsadm/objects/postgres_objects.go
Moving postgres to alpine since postgres 10 is not available on buster.
Bumping schemahero to 0.12.1 because is used buster as base.
=> Move postgres to alpine and bump schemahero to 0.12.1

pkg/k8sutil/kotsadm.go
Not waiting for the pods to delete is creating a race condition where new pods are being created before the restic wait container can finish, causing the CLI to hang.
=> fix(cli): wait for deleted registry pods on restore

pkg/kotsadmsnapshot/download.go
Previous response object was empty for Velero errors, which occur when a post-restore hook fails. This adds in errors+warnings from cluster resources and velero.
=> fix(cli): report velero and cluster errors in restore status

web/src/components/snapshots/SnapshotStorageDestination.jsx
Fix for the Azure Velero plugin name. I opted to modify the existing entry instead of adding a new one since I think we are recommending >1.5.
Also changed the ordering to alphabetical per @AmberAlston (also works because cloud providers end up first).
=> fix(kotsadm): missing azure snapshot option in settings UI

pkg/airgap/airgap.go, pkg/kotsadmconfig/config.go, pkg/online/online.go, pkg/store/kotsstore/version_store.go, pkg/store/ocistore/version_store.go, web/src/components/apps/AppConfig.jsx
this pr will add (put back) the ability to block the deployment of new versions if they have non-set required config items until these items are configured. this pr will preserve the functionality of showing the config screen by default during the installation process, even if all required config items are set and have values (except for automated installs, which might still override/bypass this behavior later if no required items are unset).
=> require configuration before deployment when there are non-set required config items

pkg/airgap/airgap.go, pkg/airgap/update.go
in airgapped mode, both the installation and the update event have the same message in the version history page. this pr will help distinguish between the two.
=> distinguish between airgap install and airgap update for each version

kotsadm/operator/pkg/client/client.go
This attempts to fix an issue when running with `requireMinimalRBACPrivileges` set to true and no additional namespaces. Kots fills the logs with:
```
E0326 10:40:36.461431       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:stoplight-platform:kotsadm-operator" cannot list resource "namespaces" in API group "" at the cluster scope
```
=> Dont run namespaces informer if there are no additional namespaces in app spec

.github/workflows/build-test.yaml
This will no longer cancel in-progress jobs in test matrix.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
=> github actions build-test strategy fail-fast false

.github/dependabot.yml
I see that github is automatically making security patch prs. I'm worried about this change introducing too many PRs so im going to roll it back for now.
=> Dependabot disable npm

.gitignore, cmd/kots/cli/velero.go, pkg/snapshot/providers/azure.go, pkg/snapshot/store.go, pkg/snapshot/velero.go
Mostly @salahalsaleh's work, but had some git, err, "issues" with my rebase and it was easier for me to cherrypick on a new branch.
Added CLI support for configuring backup before app is installed for AWS, GCP and Azure providers. I broke Azure out into subcommands because I anticipate having to add other auth methods from the docs that require different fields. I'd like to do this for AWS and GCP too depending on input.
=> feat(cli): commands for configuring snapshots storage destination

go.mod, go.sum, kotsadm/operator/Dockerfile.skaffold, kotsadm/operator/deploy/Dockerfile, pkg/app/types/types.go, pkg/handlers/preflight.go, pkg/handlers/registry.go, pkg/preflight/preflight.go, pkg/registry/troubleshoot.go, pkg/store/ocistore/app_store.go
Adding Private Image check that will show up when read-only private registry is used.
This uses similar pattern to injected support bundle collectors.  When there is a private registry read-only configured, we add a new collector (`Registry`) and analyzer (`RegistryAnalyze`).   The images are populated from the `knownImages` field in the Installation spec, which includes all images found in release spec and was created for a similar purpose in support bundle.  Image pull secret is also generated from registry settings.
=> registry image preflights

.github/workflows/build-test.yaml, cmd/kots/cli/velero.go, go.mod, go.sum, kotsadm/operator/go.sum, pkg/print/fs-minio-velero-config.go, web/src/components/snapshots/AppSnapshots.jsx, web/src/components/snapshots/ConfigureSnapshots.jsx, web/src/components/snapshots/GettingStartedSnapshots.jsx, web/src/components/snapshots/SnapshotSettings.jsx, web/src/components/snapshots/SnapshotStorageDestination.jsx, web/src/components/snapshots/Snapshots.jsx, web/src/utilities/utilities.js
Adding support for Velero 1.6.0 and making it the default in Kots. Main changes:
1. Allow compatibility in the UI with any minor version >= 1.5.1
2. Adjust [plugin names for 1.6.0](https://github.com/vmware-tanzu/velero/pull/3183)
3. Various doc updates.
=> feat: velero 1.6.0 support

kotskinds/apis/kots/v1beta1/license_types.go
Fixes marshaling EntitlementValue so that values are correctly marshaled. Without this change values were always an empty object (`{}`). This change fixed it, and seems to be consistent with all examples in https://golang.org/pkg/encoding/json/.
=> Fix Marshaling EntitlementValue

cmd/kots/cli/velero.go
It's hard to parse the output based on the provided format when the progress is part of the output. This pr will make it easier to automate the snapshot filesystem commands and parse their output without having to filter out other logs.
=> filesystem snapshots - don't print progress if output format is specified

pkg/handlers/config.go, web/src/components/apps/AppConfig.jsx, web/src/components/apps/AppVersionHistoryRow.jsx
Allow editing currently deployed and latest version.  Editing in this context means config can be edited and when saved, it will result in a new version being created.  Only version 0 can be modified directly during the initial install.
=> Allow editing deployed version config

pkg/docker/registry/registry.go, pkg/handlers/config.go, pkg/handlers/registry.go, pkg/kotsadm/main.go, pkg/kotsadmlicense/license.go, pkg/midstream/registry.go
After an old deployed version is edited, this enables license sync to get the license up to date and saving registry to point old version at the right registry.
=> Ability to update registry and license after a deployed version is edited

pkg/handlers/license.go, pkg/kotsadmlicense/license.go, pkg/updatechecker/updatechecker.go, web/src/components/apps/AppLicense.jsx, web/src/components/apps/Dashboard.jsx
After an old version is edited, syncing license will create a new version, but the user will be told that the license is up to date instead of showing the modal that redirects to version history
=> Show new version message after license sync

web/src/scss/utilities/forms.scss
=> when box checkbox is active, use lightened version of the accent color

pkg/handlers/deploy.go, pkg/handlers/update.go, pkg/online/online.go, pkg/preflight/preflight.go, pkg/reporting/preflight.go, pkg/updatechecker/updatechecker.go, web/src/components/apps/AppDetailPage.jsx
**Problems:** 
- Go routine was running after new version was deployed, and it was reporting “missing” status for older versions. 
- Sending preflight reporting data was called before version is deployed.
**Fixes:**
- Added check to see is deployed sequence changed.
- Send preflight reporting data after version is deployed.
=> Check for deployed sequence before reporting preflights

web/src/components/troubleshoot/GenerateSupportBundle.jsx
When a support bundle is collected via the cli, the UI is supposed to automatically redirect and view that support bundle after it's been uploaded. This stopped working after the recent code refactoring for the support bundle work.
=> fix support bundle redirect for the cli

pkg/supportbundle/execute.go
This is scoping the cluster-resources namespace to default in kurl installations. The was a regression in 1.40.0
=> Support bundle does not include resources for namespaces other than default

pkg/kotsadm/main.go, pkg/kotsadm/operator.go
When running `kots admin-console upgrade` command, ClusterRole is always created for Admin Console because the command does not check metadata for installed application.
=> Check application metadata on admin console upgrades

cmd/kots/cli/install.go, pkg/upload/upload.go
Setting the `AllowEdit` flag moves the cursor to the end of the string, which matches pre-1.33.0 behavior, the release where prompt got broken.  The flag has no (material) effect when no default text is specified.
=> Fix cursor on promptui inputs

pkg/airgap/update.go, pkg/api/downstream/types/types.go, pkg/handlers/config.go, pkg/handlers/deploy.go, pkg/handlers/update.go, pkg/handlers/upload.go, pkg/preflight/preflight.go, pkg/reporting/preflight.go, pkg/store/kotsstore/downstream_store.go, pkg/store/kotsstore/version_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/downstream_store.go, pkg/store/ocistore/version_store.go, pkg/store/store_interface.go, pkg/store/types/constants.go, pkg/updatechecker/updatechecker.go
When new updates are available, we download them asynchronously and they show up as "Pending config" on dashboard
When there are no updates, we attempt to deploy the latest known version, which now produces this message
=> Don't deploy versions that are missing required configurations

pkg/template/builder.go
do not fail on being unable to get dockerhub credentials, since they're just used to increase the rate limit
=> don't fail if not able to get dockerhub credentials

pkg/config/config.go, pkg/template/config_context.go, pkg/template/config_context_test.go
We already render the default values when creating a new config context (new builder), we should apply those rendered values to the config instead of/before having them be rendered later when all of the config is rendered in one shot.
=> fix: preserve defaults for editable config items during live rendering

web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/AppVersionHistoryRow.jsx, web/src/scss/components/troubleshoot/FileTree.scss, web/src/scss/utilities/base.scss
Icon and "Github" text are dynamic and will display whichever git provider the customer is using. The "Github" text will also just show the full url if the application is airgapped so that users can copy/past the link rather than rely on the external link.
=> always show view button for gitops and have a tooltip if there is no commit url for version

.github/workflows/kotsadm.yaml, migrations/Dockerfile.skaffold, migrations/deploy/Dockerfile, migrations/fixtures/Makefile
```
┌─────────┬───────────────┬───────────────────┬───────────────────┬──────────────────┬──────────┐
│ (index) │     NAME      │     INSTALLED     │     FIXED-IN      │  VULNERABILITY   │ SEVERITY │
├─────────┼───────────────┼───────────────────┼───────────────────┼──────────────────┼──────────┤
│    0    │ 'libgcrypt20' │     '1.8.4-5'     │ '1.8.4-5+deb10u1' │ 'CVE-2021-33560' │ 'Medium' │
│    1    │ 'libgnutls30' │ '3.6.7-4+deb10u6' │ '3.6.7-4+deb10u7' │ 'CVE-2020-24659' │ 'Medium' │
│    2    │ 'libgnutls30' │ '3.6.7-4+deb10u6' │ '3.6.7-4+deb10u7' │ 'CVE-2021-20231' │  'High'  │
Discovered vulnerabilities with fix versions at or above the severity threshold
```
Fixes  'CVE-2021-20231'
=> chore(migrations): update schemahero version for CVE patches

cmd/kots/cli/admin-console.go, pkg/k8sutil/kotsadm.go, pkg/k8sutil/pod.go, pkg/kotsadm/main.go
kotsadm pods from different owners (deployment, statefulset) may co-exist for a brief period of time during the upgrade process from versions pre 1.46.0 to 1.46+. we can't just check that the owner is a statefulset because full snapshots taken before 1.46.0 will have kotsadm as a deployment and the restore will hang waiting for a statefulset.
=> fix restoring old snapshots taken when kotsadm was a deployment

cmd/kots/cli/admin-console-upgrade.go, pkg/kotsadm/main.go
since customers might forgot to pass the opt-in flag on subsequent upgrades, KOTS should handle that gracefully. in this case, KOTS will check if the opt-in occurred and default to that for subsequent upgrades even if the customer tries to opt out or forgets to pass the opt-in flag.
=> opt-out of removing minio is unsupported after opt-in

deploy/backup.sh
"The -n test requires that the string be quoted within the test brackets. Using an unquoted string with ! -z, or even just the unquoted string alone within test brackets normally works, however, this is an unsafe practice. Always quote a tested string."
reference: https://tldp.org/LDP/abs/html/comparison-ops.html
=> small improvement to the backup bash script

kotsadm/operator/pkg/applier/process.go, kotsadm/operator/pkg/client/client.go, kotsadm/operator/pkg/client/deploy.go, pkg/pull/pull.go
Remove files from "charts" sub-directories in overlays if corresponding files are missing from base.  Based on file system layout, which is less than ideal, but it works well.
=> Allow removing charts from app

cmd/kots/cli/reset-tls.go, kurl_proxy/kustomize/base/deployment.yaml
skaffold sets the kurl-proxy label as "kurl-proxy", but production labels this as "kurl-proxy-kotsadm".  All references should match 'kurl-proxy-kotsadm'.
=> target app should be "kurl-proxy-kotsadm"

pkg/base/helm.go, pkg/base/helm_test.go, pkg/base/helm_v2.go, pkg/base/helm_v3.go, pkg/base/replicated.go
Fixes this [issue](https://app.clubhouse.io/replicated/story/33490/helmchart-namespace-field-overrides-custom-values-specified-in-the-chart). Kustomize was previously overwriting all namespaces. This PR adds the spec namespace (if it's defined) to all the helm resources. If a helm resource already has a defined namespace (e.g. from the values), the namespace is left as is. If no custom namespaces are defined, the resources are installed in the same namespace as the app.
=> fix: allow separate namespaces for helm chart resources

kustomize/overlays/dev/deployment.yaml
This is needed to do hostpath backups on when running this on a development server. Otherwise it will throw an error looking for that statefulset.
=> Add in POD_OWNER_KIND

pkg/base/write.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go
Chart directories still have the original layout, with all files intact.  Deduplication happens in the top level kustomization file, so its layout reverted to the original one.
=> Deduplicated app resources

support-bundle.yaml
```
$ kubectl support-bundle -n default https://kots.io
...
* failed to run collector "collectd/collectd": create daemonset: create daemonset: DaemonSet.apps "troubleshoot-copyfromhost-8dr8b" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "PullIfNotPresent": supported values: "Always", "IfNotPresent", "Never"
```
=> imagePullPolicy: IfNotPresent not PullIfNotPresent

support-bundle.yaml
Fixed a typo in the collector name
=> Support bundle copyFromHost not collectFromHost for kurl host-preflights collector

kotsadm/operator/pkg/client/deploy.go
When decoding an unregistered kind, operator failed to extract namespace from the spec, which caused `kubectl delete` command to fail with 
```
error: the namespace from the provided object "monitoring" does not match the namespace "kots". You must pass '--namespace=monitoring' to perform this operation.
```
fixes #1691
=> Use the correct namespace when deleting app components

cmd/kots/cli/admin-console.go, cmd/kots/cli/admin-generate-manifests.go, pkg/upstream/admin-console.go, pkg/upstream/write.go
Adds a new CLI command for generating admin console manifests ([CH36021](https://app.clubhouse.io/replicated/story/36021/a-cli-command-or-a-flag-for-the-kots-pull-command-to-generate-only-the-admin-console-components-as-kustomizable-yaml-manifests)).
=> feat: add cli command for generating admin console manifests

pkg/kotsadm/configmaps.go, pkg/kotsadm/main.go, pkg/kotsadm/objects/configmaps_objects.go, pkg/kotsadm/types/deployoptions.go, pkg/kotsutil/kots.go
This addresses the following issues:
1- rewriting application images in airgapped embedded clusters correctly
2- not including kotsadm configmaps in the generated yaml manifests for the pull/generate command
3- not respecting updated kotsadm configuration when running kots install after the initial run
=> fix kotsadm installation params for embedded clusters

Makefile, cmd/kots/cli/run.go, go.mod, go.sum, pkg/apiserver/server.go, pkg/handlers/mock/mock.go, pkg/persistence/persistence.go, pkg/store/kotsstore/user_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/user_store.go, pkg/store/store_interface.go, pkg/user/user.go
This is a refactor to move the login logic out of the user.go and into a store function. We don't touch the database for in-cluster (normal) installations, so this wasn't obvious to be in the store.
Note: there's now a `make kots_experimental` to make this workflow easier to debug.  I've been running:
```
make kots-experimental  && ./bin/kots run test --shared-password=password
```
---
For kots run (experimental) support, we don't expect to have a k8s api available to write the shared password and invalid counts to. So I moved this to the sqlite database that we are creating on the host filesystem. There's a table called "kotsadm_params" which is just (key/value) and it felt like a good place to stash this data.
There are a few quirks here that were difficult to place this morning. Open …
=> Refactor login to support additional backends

pkg/persistence/stringtime.go, pkg/store/kotsstore/app_store.go
When using SQLite, the there is not a time type. These are stored as strings. So I've created two new types to handle the conversion between pg's native type and sqlite's non-type. As we continue integrating, these types will have to be use more.
=> Fix embedded license install

.github/workflows/build-test.yaml, .github/workflows/deploy.yaml, .github/workflows/kotsadm.yaml
Uses the cache-action to store the go.mod cache and improve future build speeds
=> Add cache for CI

cmd/kots/cli/admin-console-push-images.go, pkg/docker/registry/ecr.go, pkg/s3/s3.go
Currently kots determines if the Docker repo being used is an ECR repo. If it is, it expects to be provided with an access key and secret to authenticate with the ECR repo. However in some cases, kots will be run with an assumed role or on an EC2 instance with an instance role that doesn't have an access key. The go SDK will use a default credential provider chain if no credentials are specified that will use the instance role or other credentials.
This change allows kots to be installed without an access key when using ECR
I didn't see a contributor guide so happy to take any feedback
Related to feature 31678, although this isn't likely sufficient to truly solve that case
=> Support non-access key based AWS credentials

.gitignore, pkg/store/kotsstore/app_store.go, pkg/store/kotsstore/appstatus_store.go, pkg/store/kotsstore/downstream_store.go, pkg/store/kotsstore/kotsadm_params_store.go, pkg/store/kotsstore/prometheus_store.go, pkg/store/kotsstore/version_store.go
SQLite does not recognize argument numbering and requires them to be in the correct order.
=> Make postgres queries work with sqlite

cmd/kots/cli/run.go, pkg/apiserver/server.go, pkg/cluster/apiserver.go, pkg/cluster/authnz.go, pkg/cluster/cluster.go, pkg/cluster/controller.go, pkg/cluster/scheduler.go, pkg/persistence/sqlite.go, pkg/store/kotsstore/embedded_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/embedded_store.go, pkg/store/store_interface.go, pkg/supportbundle/server.go
This will wait for the api server to start by polling it's readyz endpoint.
This is necessary to start controlling the startup and verifying that the cluster is ready before the app can be deployed.
Now, when starting the app with `kots run` the output is:
```
• Starting cluster ✓  
The cluster is running. Press ctrl+c to terminate
```
=> Wait for the K8s api server to start

pkg/cluster/antrea.go, pkg/cluster/antrea.yaml, pkg/cluster/cluster.go, pkg/cluster/controller.go, pkg/cluster/scheduler.go
This PR embeds a small amount of YAML for Antrea and then applies it after the cluster is running. This uses the dynamic client so that we don't need kubectl installed to make it work.
=> Add CNI (Antrea) to embedded cluster

cmd/kots/cli/install.go, pkg/automation/automation.go
update warning message about failing to pull app metadata to include that it might also cause the admin console to not run with minimal rbac privileges if the application requires that.
=> update warning message about failing to pull app metadata

.gitignore, cmd/kots/cli/run.go, pkg/cluster/antrea.go, pkg/cluster/cluster.go, pkg/cluster/containerd.go, pkg/cluster/cri.go, pkg/cluster/kubelet.go, pkg/cluster/runc.go, pkg/cluster/util.go
This is where the `kots run` experiment starts to have a narrower target! 
We need containerd to be installed in order to start, and containerd needs runc to be present. This PR will attempt to start containerd and the kubelet in process. This will not install anything as a service. Runc is a dependency, so we should see if it's possible to install it locally and point the containerd configuration file at it.
=> Kubelet and containerd (with runc)

pkg/cluster/controller.go
For reference, the value for `--controllers` flag comes from [this code](https://github.com/kubernetes/kubernetes/blob/1bd00776b5d78828a065b5c21e7003accc308a06/cmd/kube-controller-manager/app/controllermanager.go#L435-L440).
=> Controller manager starts

go.mod, pkg/docker/registry/token.go, pkg/session/session.go
inspired by https://github.com/auth0/go-jwt-middleware/pull/69, although their PR title is misleading.
=> switch from dgrijalva/jwt-go to form3tech-oss/jwt-go to fix CVE-2020-26160

cmd/kots/cli/version.go
[CH33701](https://app.clubhouse.io/replicated/story/33701/kots-cli-add-output-formatting-option-for-json-and-status-field-if-possible)
=> feat: add json output for version cmd

pkg/operator/client/client.go
this was implicitly base64 encoded when the operator send the data to kotsadm in the request. the data was of type `[]byte` and the api receives it as `string` in the request type, which implicitly base64 encodes the data.
=> fix showing deploy logs

web/src/components/apps/AppLicense.jsx
Confirmed spacing is fixed in chrome, safari and firefox
=> fix spacing on license page

pkg/k8sutil/openshift.go
this is to prevent a false positive that broke installs in non-openshift clusters that have rook 1.6.7 installed which contains a crd with group `replication.storage.openshift.io`. ch36790
=> fix openshift cluster detection

cmd/kots/cli/run.go, cmd/kots/cli/util.go, pkg/apiserver/server.go, pkg/cluster/antrea.go, pkg/cluster/antrea.yaml, pkg/cluster/cluster.go, pkg/cluster/containerd.go, pkg/cluster/controller.go, pkg/cluster/init.go, pkg/gitops/gitops.go, pkg/handlers/rendered_contents.go, pkg/handlers/session.go, pkg/k8sutil/clientset.go, pkg/k8sutil/kotsadm.go, pkg/k8sutil/portforward.go, pkg/kustomize/diff.go, pkg/kustomize/util.go, pkg/operator/client/client.go, pkg/operator/client/deploy.go, pkg/operator/client/hooks.go, pkg/operator/client/namespaces.go, pkg/operator/helm.go, pkg/operator/operator.go, pkg/persistence/sqlite_schema.go, pkg/preflight/execute.go, pkg/supportbundle/backup.go, pkg/util/kubectl_version.go
outstanding issues:
1- containerd doesn’t run because it can’t find runc in PATH
2- antrea falls back to using the in-cluster config. we need to point to the right kubeconfig file to use instead.
=> deploy app using kots run (first pass)

.github/workflows/build-test.yaml
https://app.shortcut.com/replicated/story/37194/ci-failures-should-notify-the-team-in-slack
=> chore: enable slack notifications for nightly builds

.github/workflows/release.yaml
kind/chore
Adds slack notifications to nightly regression tests.
Fixes [SH37194](https://app.shortcut.com/replicated/story/37194/ci-failures-should-notify-the-team-in-slack)
```release-note
NONE
```
NONE
=> chore: add slack notifications for nightly regression tests

.github/workflows/release.yaml
kind/chore
Automatically creates a release notes draft in the kots.io repository with the version filled out based on the release tag.
None
None
=> chore(ci): add action to kick off release notes

pkg/supportbundle/spec.go, pkg/supportbundle/spec_test.go
kind/bug
Support bundle namespaces are set in a separate step for backwards compatibility.  This step also calls a template builder, but only with static context, which makes most template functions unavailable.  This is not necessary since the entire spec is passed through a complete template builder at a later point.
```release-note
Fixes a bug that caused support bundle collectors to ignore the template in the namespace field and to use the Admin Console namespace.
```
=> Use builder with all contexts to for templating out namespaces in support bundle spec

pkg/docker/registry/auth.go, pkg/image/builder.go
kind/bug
fixes a bug in the workflow of transferring images between registries which prevented the ability to use instance roles to push/pull to/from ECR registries.
Fixes #sc-37780
no
no
=> fix: ability to use instance roles to push/pull to/from ECR registries when transferring images between registries

pkg/supportbundle/analyze.go
kind/bug
fixes an issue where support bundle generation would hang if the analyzer spec includes a k8s version analyzer
no
no
=> fix: check for existing k8s version analyzer

.github/workflows/alpha.yaml, .github/workflows/build-test.yaml, .github/workflows/release.yaml, migrations/fixtures/Makefile, migrations/fixtures/deploy/Dockerfile
kind/bug
The nightly build generates a dot env file containing the latest tags for images used in KOTS. Previously this file was sourced
before make was called, but, because the environment variables aren't exported, the Makefile doesn't detect the environment variables and uses defaults.  This is because the environment variables must be _exported_ or explicitly set on the same line 
as the make command `SOMEVAR=bar make` before the Makefile can see them.  This PR replaces the source with the export command and a little bash foo to export all the variables declared in the dot env file, ignoring comment lines. Also replaced a hard coded tag in a docker file which is now set by a generated version tag. 
Fixes #37728
```release-note
NONE
```
NONE
=> Export .image.env file so the environment vars are picked up by Makefile

pkg/docker/registry/registry.go, pkg/operator/client/client.go
kind/bug
ImagePullSecrets are generated automatically by default.  If these are created for a helm chart, it's possible the helm resources have Helm Hooks defined that would be processed before the pull secret is generated.  This causes the pull to fail.
This PR attaches a helm hook and weight to image pull secrets.  This ensures the secret is created before any other helm resources with a weight above -99.  A vendor setting a resource weight below -99 will still run into this problem.
```release-note
Fixed a Helm hooks bug where pre-install and pre-upgrade hooks were processed before the image pull secret was deployed.
```
NONE
=> Jeffgolden/sc 37499/pullsecrets need lowest helmhook weight

cmd/kots/cli/garbage-collect-images.go, pkg/handlers/garbage_collect_images.go, pkg/kotsutil/kots.go, pkg/operator/client/client.go, pkg/registry/images.go
kind/enhancement + kind/bug
1- image garbage collection stopped working after kots 1.48.0, this pr fixes that regression.
2- adds the ability to force image garbage collection via the cli command even if rollback is enabled.
```release-note
* fixed a bug that caused image garbage collection to not work on embedded clusters.
* added the ability to force image garbage collection via the cli even if rollback is enabled for the application.
```
https://github.com/replicatedhq/kots.io/pull/577
=> fix image garbage collection and add the ability to ignore enforcing rollbacks

pkg/filestore/s3_store.go
Include actual error in error logs when object store is not available.
Better error logging to help troubleshooting.
Fixes #
```release-note
NONE
```
NONE
=> Include S3 error when waiting for object store fails

.github/workflows/build-test.yaml, cmd/kots/cli/pull.go, pkg/docker/registry/registry.go, pkg/kotsadm/version/kotsadm_version.go, pkg/midstream/midstream.go, pkg/midstream/write.go, pkg/operator/client/client.go, pkg/operator/client/namespaces.go, pkg/operator/operator.go, pkg/operator/types/types.go, pkg/pull/pull.go, pkg/registry/troubleshoot.go, pkg/rewrite/rewrite.go, pkg/template/config_context.go, pkg/template/config_context_test.go
kind/bug
Release 1.50.2 replaced the generically named secret `kotsadm-replicated-registry` with app specific secrets.  With online installs, the generic secret is no longer created.  However some apps have this name hardcoded in their specs.  This change ensures that both secrets are available for backwards compatibility.
Fixes #
Both secrets are in the same overlay file, `sercet.yaml` which is now a multi-doc:
```
apiVersion: v1
data:
.dockerconfigjson: <base64>
kind: Secret
metadata:
name: myapp-registry
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
.dockerconfigjson: <base64>
kind: Secret
metadata:
name: kotsadm-replicated-registry
type: kubernetes.io/dockerconfigjson
```
Admin Console now creates both secrets in additional namespaces:
```
$ kubectl get secrets  -A | …
```
=> Ensure kotsadm-replicated-registry secret for backwards compatibility

pkg/kotsadm/objects/kotsadm_objects.go, pkg/kotsadm/objects/minio_objects.go, pkg/kotsadm/objects/postgres_objects.go, pkg/snapshot/filesystem.go
This allows KOTS to run when `readOnlyRootFilesystem` is specified in a PodSecurityPolicy, which could be set on secure clusters.
Fixes #
Yes
```release-note
* KOTS will successfully install/upgrade when `readOnlyRootFilesystem` is specified in an existing cluster.
```
None
=> feat: allow readonlyRootFilesystem for existing installs

pkg/base/helm.go
kind/bug
This fixes an issue that was causing Chart.yaml and Chart.lock to be ignored for Helm sub-charts. With this fix, any level of sub-chart nesting should work now.
It still handles the special case where `base.Path == ""` for the top-level Chart.yaml and Chart.lock. For sub-charts, it does a slightly different check to find the correct additional files. Previously those additional files were being ignored which led to a Helm error when deploying.
Fixes [SH37929](https://app.shortcut.com/replicated/story/37929/helm-sub-sub-charts-are-not-copied-into-base-correctly)
```release-note
Fixed a Helm issue where Chart.yaml and Chart.lock files were being ignored and lost for sub-charts of sub-charts.
```
NONE
=> fix: append additional files correctly for sub charts

go.mod, go.sum
Update troubleshoot to v0.13.17
kind/bug
This fixes preflight collectors that specify absolute file paths, which may be in locations where non-root user may not have write permissions.
Fixes #
```release-note
NONE
```
NONE
=> Troubleshoot v0.13.17

pkg/airgap/airgap.go, pkg/online/online.go
kind/bug
fixes an issue in automated installs where a non-configurable application is not automatically deployed when preflights are skipped.
SC-37368
```release-note
Fixed an issue in automated installs where a non-configurable application is not automatically deployed when preflights are skipped.
```
NONE
=> fix: auto-deploy app when there's no config and preflights are skipped

go.mod, go.sum, pkg/supportbundle/defaultspec/spec.yaml
Do not show missing weave and goldpinger error when files are missing.  These are kurl specific files and only present in kurl clusters.
Fixes #
```release-note
Fixed a bug that showed Weave and Inter-pod Networking errors when no corresponding data is collected because it is not applicable.
```
NONE
=> Don't fail weave report if no files collected

web/src/components/apps/AppLicense.jsx, web/src/scss/components/apps/AppLicense.scss
kind/bug
fixes a misalignment for the license sync button under the License page
```release-note
* Fixed a bug in the Admin Console license page where the ["Sync License"](/kotsadm/updating/license-updates/#syncing-the-license) button was misaligned.
```
NONE
=> fix license sync button misalignment

web/src/components/troubleshoot/AnalyzerInsights.jsx
Fix frontend filtering logic to match the text displayed to the user.
```release-note
Filter checkbox for troubleshoot was defaulting to the opposite of what the display text said and it wasn't filtering analysis without a completion type out from errors and warnings.
```
NONE
=> 38977: Fix analysis filtering

pkg/api/reporting/types/types.go, pkg/kotsutil/kots.go, pkg/reporting/app.go, pkg/reporting/util.go
Product and Engineering wants to track the number of Native Helm installs as the feature goes to GA.  This will inform priority for future Helm updates.
As KOTS collects downstream data, it will now search for HelmChart KOTS kinds.  If found, the HelmChart's install method (Replicated Helm vs Native Helm) will be recorded.  This data is sent back to Replicated.
```release-note
KOTS telemetry will now include whether installed helm charts leverage our Native Helm feature.
```
NONE
=> Adding helm data to downstream report

pkg/kotsadm/objects/postgres_objects.go
this timeout is only enforced in k8s 1.20+, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/\#configure-probes
kind/bug
Increases the timeout for the postgres readiness probe to match that of the liveness probe. On some systems 1s is too small, and this is only enforced in k8s 1.20+.
Fixes #
```release-note
Increased the timeout for the kotsadm-postgres readiness probe
```
=> increase readiness probe timeout to 5s to match liveness probe

pkg/template/builder.go
kind/bug
template.NewBuilder calls ApplicationInfo.Slug, though ApplicationInfo is not required by the function. This was causing panics in kots-lint.
NONE
NONE
=> Provide slug string if ApplicationInfo is nil

pkg/template/config_context.go, pkg/template/depgraph.go, pkg/template/depgraph_test.go
kind/bug
Previously if a nonexistent config item is specified in ConfigOption template, it would evaluate to an empty string.  This behavior has changed since the previous release, which makes it incompatible with some apps.
Fixes #
```release-note
NONE
```
NONE
=> Allow ConfigOption functions accept config names that don't exist

pkg/pull/pull.go, pkg/rewrite/rewrite.go
kind/bug
If helm charts have a common prefix such as a company name, the name gets stripped from the resulting chart directory name in /base.  This no longer matches the original chart name.
When writing kustomize files for these subcharts on the Native Helm feature, the subchart directories are not properly excluded when searching for private images.  This causes kustomization that targets subchart resources, resulting in Kustomize errors on deploy.
This PR uses the chart's Base name, after modification, and not the original chart name.
```release-note
Fixed a Native Helm bug that caused Kustomize "resource not found" errors when supplying multiple Helm charts with the same name prefix.
```
NONE
=> handling renamed (removed prefix) chart directory

cmd/kots/cli/admin-console-upgrade.go, cmd/kots/cli/install.go, pkg/kotsadm/main.go, pkg/kotsadm/objects/distribution_objects.go, pkg/kotsadm/objects/kotsadm_objects.go, pkg/kotsadm/objects/minio_objects.go, pkg/kotsadm/objects/postgres_objects.go, pkg/kotsadm/objects/shared_object_config.go, pkg/kotsadm/types/deployoptions.go, pkg/kotsadm/types/upgradeoptions.go
kind/bug
Fixes SC-39345,  issues reported around the new 1.56.0 security contexts
```release-note
Fixes stuck postgres pod in KOTS 1.56.0 caused by additional security contexts. The strict security contexts are now enabled during admin console install and upgrade by the `strict-pod-security` flag.
```
Yes, kots.io incoming.
=> fix: make strict security contexts optional

pkg/base/helm.go
kind/bug
Fixes an issue that prevented charts with empty sub-charts from deploying. If a chart lists as a sub-chart as a dependency in `Chart.yaml`, it expects to find a corresponding `Chart.yaml` for the dependency. For sub-charts that don't render into any manifests, the `Chart.yaml` is lost and causes Helm to complain about a missing dependency.
Fixes [SH39460](https://app.shortcut.com/replicated/story/39460/bitnami-postgres-chart-does-not-work-with-native-helm).
App `vera-postgres-native` can be used to easily verify it.
```release-note
Fixed a Helm issue that prevented charts with empty sub-charts/dependencies from deploying.
```
NONE
=> add chart yaml for empty sub charts

pkg/operator/client/client.go, pkg/operator/client/deploy.go, pkg/operator/client/gvkn.go
kind/bug
Instead of searching through the saved manifests to determine what resources exist in the cluster, and then inspecting each pod to see if they match those resources, and then deleting the PVCs associated with those pods during a restore, we should just rely on the `kots.io/app-slug=%s` annotation on pods.
This will prevent missing PVCs from pods in helm charts.
Fixes #
```release-note
NONE
```
=> cleanup all app pvcs during restore process

cmd/kots/cli/admin-console-generate-manifests.go, pkg/kotsadm/kotsadm.go, pkg/kotsadm/types/deployoptions.go, pkg/upstream/admin-console.go, pkg/upstream/types/types.go
Adds flags to the `kots generate-manifests` command to let vendors/customers enable minimal rbac without manually editing the files.
Fixes SC-39602
```release-note
Added flags `--minimal-rbac` and `--additional-namespaces` to the `kots generate-manifests` command to enable minimal-rbac deployments through YAML.
```
Yes, TBD.
=> feat(cli): generate-manifests now supports minimal rbac

.github/workflows/regression.yaml, .github/workflows/release.yaml
Ability to run regression tests without everything else.
```release-note
NONE
```
=> Adding standalone trigger for regression testing

pkg/base/replicated.go
Fixing recursive merge for optional values
kind/bug
No issue reported
It depends. Anyone using `optionalValues` might experience behavior that previously didn't work.
```release-note
```
No. As it fixes behavior that is supposed to work from the existing documentation
=> Fixing recursive merge

pkg/pull/pull.go
kind/bug
KOTS Pull does not copy base before writing midstream.  This causes odd behavior when processing through midstreams later, including downstream files not being written for some Native Helm charts.  KOTS Rewrite copies base, which works.  This PR copies the working code from KOTS Rewrite over to KOTS Pull.
```release-note
Fixed a bug with `kots install` on Native Helm causing some resources to be skipped during deployment
```
NONE
=> Copy original base before writing midstream

cmd/kots/cli/velero.go, pkg/snapshot/store.go, web/src/components/snapshots/SnapshotStorageDestination.jsx
This PR chooses PVC over objectstore based on disableS3 flag.
The Pre-requisite for this PR: https://github.com/replicatedhq/kURL/pull/2366
How to test this:
1. Create a KURL cluster by setting disableS3 flag in the kotsadm addon (curl https://kurl.sh/e0fe387 | sudo bash)
2. Build the kotsadm image in codeserver and copy to ttl.sh (./hack/build-ttl.sh from kots repo)
3. In the kurl cluster, edit the statefulset to point the image to image: ttl.sh/jalaja/kotsadm:12h
4. velero plugin add ttl.sh/jalaja/local-volume-provider:12h
5. Go to kotsadm ui, choose snapshot settings, choose **Internal Storage**  from the Pull down, Choose it, Save it.
6. Take snapshots.
```
spec:
contour:
version: 1.18.0
docker:
version: 20.10.5
ekco:
version: 0.12.0
kotsadm:
disableS3: true
version: 1.57.0 …
```
=> Migrate snapshots from objectstore to PVC

cmd/kots/cli/upstream-upgrade.go, pkg/handlers/update.go, pkg/updatechecker/updatechecker.go, pkg/upstream/upgrade.go
This PR adds the current and latest versions to the output of `kots upstream upgrade`. This includes the sequence numbers and semver labels. For the latest versions, all new available versions are listed. Customers are expected to store those available versions if needed because they won't be returned again after they're pulled.
[36671](https://app.shortcut.com/replicated/story/36671/kots-cli-add-current-and-latest-version-details-and-ensure-this-information-is-available-as-json-output)
Feel free to suggest any name changes on the JSON output.
```release-note
Added version output for both current and new available releases to the upstream upgrade CLI command.
```
NONE
=> add current and available release version to upstream upgrade cmd

pkg/base/replicated.go, pkg/base/templates.go, pkg/config/config.go, pkg/config/config_test.go, pkg/crypto/aes_test.go, pkg/handlers/config.go, pkg/kotsadmconfig/config.go, pkg/render/render.go, pkg/template/builder.go, pkg/template/config_context.go, pkg/template/config_context_test.go, pkg/upstream/replicated.go
followup to kind/chore in https://github.com/replicatedhq/kots/pull/2386
The config page should not show decrypted passwords if they were not freshly entered
Fixes #
```release-note
NONE
```
(this is how things work in the currently released kotsadm version)
=> explicitly do not decrypt passwords shown on the config page

Makefile.build, hack/CONTRIBUTING.md, hack/dev/Dockerfile.skaffold, hack/dev/entrypoint.sh, skaffold.yaml
kind/chore
Builds are really slow with delve enabled. Opt in
Fixes NONE
```release-note
NONE
```
NONE
=> Skaffold profile to enable delve

deploy/Dockerfile, hack/dev/Dockerfile.skaffold, pkg/cluster/init.go
kind/bug
reverts to kustomize 3.5.4 from 3.8.10 which is causing slowness
we reverted from 3.10.0 to 3.8.10 in the past, where we should've reverted to 3.5.4
```release-note
To fix some general slowness related to using Kustomize, the version of Kustomize was reverted to 3.5.4 from 3.8.10.
```
NONE
=> revert to kustomize 3.5.4 not 3.8.10

pkg/base/base.go, pkg/base/base_test.go, pkg/base/helm.go, pkg/base/helm_test.go, pkg/base/replicated.go, pkg/pull/pull.go, pkg/rewrite/rewrite.go, pkg/tests/pull/cases/configcontext/testcase.yaml, pkg/tests/pull/cases/configcontext/wantResults/overlays/midstream/charts/test-chart/secret.yaml, pkg/tests/pull/cases/configcontext/wantResults/overlays/midstream/secret.yaml, pkg/tests/pull/cases/simple/testcase.yaml, pkg/tests/pull/cases/subcharts/testcase.yaml, pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-1/secret.yaml, pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-2/charts/subsubchart/secret.yaml, pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-2/secret.yaml, pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/secret.yaml, pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/secret.yaml, pkg/tests/pull/pull_test.go
kind/bug
When using useHelmInstall with namespace in kots.io/v1beta1.HelmChart, image pull secrets are rendered in the kotsadm console namespace. This will render in the overridden namespace.
Fixes NONE
```release-note
Fixed an issue that would cause image pull secrets to be rendered in the Admin Console namespace rather than the `namespace` specified in the kots.io/v1beta1.HelmChart when using `useHelmInstall`.
```
NONE
=> Write helm midstream with HelmChart namespace

.devcontainer/devcontainer.json, .github/workflows/alpha.yaml, .github/workflows/build-test.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yaml, actions/copy-assets/Dockerfile, actions/copy-assets/go.mod, go.mod, hack/dev/Dockerfile.skaffoldcache, kurl_proxy/Dockerfile.skaffold, kurl_proxy/go.mod
kind/chore
Update to go 1.17, which is already used in the kURL repo.
NONE
NONE
=> chore: update go to 1.17

pkg/base/write_images.go, pkg/pull/pull.go, pkg/registry/images.go, pkg/rewrite/rewrite.go, pkg/upstream/installation.go, pkg/upstream/push_images.go
kind/bug
When running garbage collection in private registry, Admin Console uses the `KnownImages` list to determine what images can be deleted.  Under some conditions, that list was not being populated, which would cause garbage collection to ignore corresponding images in the registry.
Fixes #
```release-note
Fixes a bug that causes application images to not be [deleted from private registry](https://kots.io/kotsadm/registries/kurl-registry/).
Fixes a bug that causes images included in support bundle's [`run` collector](https://troubleshoot.sh/docs/collect/run/#image-required) to not be deleted from private registry.
```
NONE
=> Populated KnownImages value in the installation file

pkg/handlers/update.go, pkg/updatechecker/updatechecker.go
kind/bug
Checking for updates before a version is deployed results in a nil pointer panic
```
2021/12/23 18:47:58 http: panic serving 127.0.0.1:56814: runtime error: invalid memory address or nil pointer dereference
goroutine 1560 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x2c3d260, 0xcc6f1b0})
/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/replicatedhq/kots/pkg/updatechecker.CheckForUpdates({{0xc000cf3d40, 0x1b}, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0})
/go/src/github.com/replicatedhq/kots/pkg/updatechecker/updatechecker.go:265 +0xe97
```
Fixes #
```release-note
NONE
```
NONE
=> Don't nil panic when checking for updates

.github/workflows/release.yaml
kind/chore
Prevents automated PRs that just sit in the Kurl and Kots.io repos for nightly jobs
NONE
NONE
=> chore(ci): block auto prs for nightlies

pkg/upstream/upgrade.go
kind/bug
This fixes a nil pointer panic during upstream upgrade no upgrades are available.
Fixes #
```release-note
Fixes a panic that happens when [kots upstream upgrade](/kots-cli/upstream/) command.
```
NONE
=> nil pointer panic during upstream upgrade

pkg/snapshot/store.go
type::bug
Fixes an issue where "Internal" is not correctly displayed when Velero is configured to use the LVP PVC storage.
Fixes [SC-40756](https://app.shortcut.com/replicated/story/40756/kots-does-not-show-correct-snapshot-storage-location-for-internal-storage-when-using-lvp-plugin)
```release-note
Fixes a problem with the "Internal Storage" option not being selected by default in kURL clusters with the `disableS3` option set. 
```
NONE
=> fix(snapshots): display internal for disableS3 in kURL

.github/workflows/release.yaml, Makefile, deploy/.goreleaser.yaml
type::feature
M1 support for Mac clients. Bash script to install still needs to be updated accordingly because `/usr/local/bin` doesn't exist by default.
I checked the deprecation notices between the version we were using and the new version.
```release-note
Support universal binary for KOTS CLI MacOS M1.
```
NONE
=> feat(cli): build universal M1 binary

web/src/components/AirgapUploadProgress.jsx, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/AppVersionHistoryRowClassic.jsx, web/src/components/apps/DashboardCard.jsx, web/src/components/apps/DashboardClassic.jsx, web/src/components/apps/DashboardVersionCard.jsx, web/src/scss/components/AirgapUploadProgress.scss, web/src/scss/components/apps/AppVersionHistory.scss
type::chore
Cleaning up some style issues and UI 
borders back on rows
progress bar contained to box
borders back on graphs
version history doesn't show status label
```release-note
Cleanup to CSS and resolving style issues
```
NONE
=> Dashboard style cleanup

web/src/components/troubleshoot/SupportBundleList.jsx, web/src/components/troubleshoot/SupportBundleRow.jsx
type::bug
Hide the "Send bundle to vendor" link if this feature is not enabled.
Fixes #
```release-note
Fixes a bug that caused the `Send bundle to vendor` link to be shown when this feature is not enabled.
```
NONE
=> Don't show send support bundle link if not enabled

pkg/handlers/snapshots.go, pkg/snapshot/filesystem.go
type::feature
Shows a more descriptive error message when a user chooses a host path that does not exist.  It is needed so our users/vendors can easily understand what they are doing wrong.
Fixes #
Attached screenshots show the two separate views a user might see this.  One is updating  storage and one creating storage.
```release-note
Display descriptive error when provided host path does not exist.
```
NONE
=> descriptive errmsg when hostpath dne

.github/workflows/regression.yaml
type::chore
Regression tests randomly fail with "connection refused" error because it takes some time for hosts to fully start
Fixes #
```release-note
NONE
```
NONE
=> Wait for regression hosts to come up before running tests

web/src/scss/utilities/base.scss
type::bug
Prevent deployment status labels from breaking into multiple lines on small displays
Yes
```release-note
Prevent deployment status labels from breaking into multiple lines on small displays
```
NONE
=> no wrap whitespace on status tags

pkg/pull/pull.go, pkg/rewrite/rewrite.go, pkg/upstream/push_images.go
type::bug
When `useHelmInstall` is set, kots will render a midstream for each Helm chart, which is also when images are pushed to private registry. However all images are pushed when the top level midstream is rendered.
Fixes #
```release-note
Fixes a bug that caused images to be pushed to private registry multiple times during airgap install.
```
NONE
=> Don't push airgap images multiple times when installing

web/src/components/apps/AppConfig.jsx
type::bug
Don't show edit current config message when doing a new install
Yes
```release-note
Fixes a bug that displayed a message to "edit the current config when performing a new install
```
NONE
=> don't show edit current config message on initial install

pkg/airgap/update.go, pkg/handlers/deploy.go, pkg/kotsadmupstream/upstream.go, pkg/kotsutil/kots.go
type::feature
Adds the ability to block upgrading the application if the current KOTS version is incompatible with the KOTS version required by the release.
```release-note
Adds the ability to block upgrading the application if the current KOTS version is incompatible with the KOTS version required by the release.
```
NONE
=> Enforce KOTS version compatibility check on version creation instead of deployment

cmd/kots/cli/upstream-upgrade.go, pkg/airgap/update.go, pkg/handlers/airgap.go, pkg/handlers/update.go, pkg/kotsadmupstream/upstream.go, pkg/updatechecker/updatechecker.go
type::feature
Adds the ability to skip KOTS version compatibility check when updating the app via the CLI
```release-note
NONE
```
Coming soon
=> Ability to skip KOTS version compatibility check when updating the app via the CLI

web/src/components/apps/AppConfig.jsx, web/src/components/apps/AppDetailPage.jsx, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/AppVersionHistoryClassic.jsx, web/src/components/apps/Dashboard.jsx, web/src/components/apps/DashboardCard.jsx, web/src/components/apps/DashboardClassic.jsx, web/src/components/apps/DashboardVersionCard.jsx
type::feature
If a new version is trying to be deployed but the vendor has specified a KOTS version that is different than what is currently installed the user should see a message that they need to upgrade KOTS before proceeding with the new version.
Classic UI will an error "Incompatible KOTS version" and a 'Show details' link which will open this modal.
The new UI has more space and can handle this error better without the need of a modal. Here is what the error looks like on the dashboard as well as on the app version history page
Yes
```release-note
Adds functionality to display a modal with commands for upgrading KOTS if there the version attempting to be deployed has a different KOTS version specified than the one the user has installed.
```
NONE
=> add modal when specified KOTS version does not match current version

web/src/components/apps/AppStatus.jsx, web/src/components/apps/Dashboard.jsx
type::bug
Fixes a bug where the link to view unavailable resources was missing on the new dashboard UI
```release-note
Fixes a bug that caused the "Details" link to view unavailable resources to not be visible on the new dashboard UI
```
NONE
=> details link for app resource modal

web/src/utilities/airgapUploader.js, web/src/utilities/utilities.js
type::bug
Don't block airgap upload if compatibility couldn't be determined and handle invalid yaml files
```release-note
NONE
```
NONE
=> Don't block airgap upload if compatibility couldn't be determined in the UI and handle invalid yaml files

pkg/handlers/snapshots.go
type::bug
Need it to eliminate bug until it is implemented properly.  Check should happen outside of kots container.
Fixes #
```release-note
Disable host path does not exist error messaging
```
NONE
=> do not return error until bug is fixed

web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/AppVersionHistoryClassic.jsx
type::bug
'Diff versions' button changes to 'Diff releases' after you click it the first time
```release-note
NONE
```
NONE
=> fix: 'Diff versions' button changes to 'Diff releases' after you click it the first time

web/src/components/shared/Footer.jsx
type::bug
When a new version comes in that doesn't have a target kots version set, the target kots version message in the footer does not go away.
```release-note
NONE
```
NONE
=> hide target kots version footer message when latest pulled version doesn't have it

cmd/kots/cli/upstream-upgrade.go, pkg/handlers/update.go, pkg/updatechecker/updatechecker.go, pkg/upstream/upgrade.go
type::feature
make updates check process synchronous by default and expose error messages for it
```release-note
Changes the [`kots upstream upgrade`](/kots-cli/upstream/) command to be synchronous by default and exposes error messages for it.
```
TBD
=> make updates check process synchronous by default and expose error messages for it

pkg/operator/client/deploy.go
type::bug but also type::feature ? more of an improvement really
Helm defaults to a 5 minute timeout. For larger deployments this is blocking Helm installs.
Default timeout should be set to 60 minutes until we can provide a better method to pass custom flags to Helm.
Fixes #
```release-note
Sets the Native Helm timeout to 60 minutes instead of the default 5 minutes
```
NONE
=> add default timeout to helm command

pkg/image/minio.go, pkg/snapshot/filesystem.go
type::bug
We cannot really run Node() API unless the kotsadm has cluster wide privileges
Hence added the given below logic to detect the instance type first and accordingly detect the MinIO image
In existing install with limited RBAC, kotsadm does not have previliges to run Nodes() API.
If it is a kurl instance, then use search logic to find the best minio image.
If it is not a kurl instance, return the static image name present in the bundle.
SC-39403
Fixes #
```release-note
```
=> detect minio image based on the kurl or existing instance

pkg/operator/applier/kubectl.go
type::bug
Dry runs of PVCs with OpenEBS and K8s 1.19-1.21 fail because the OpenEBS operator doesn't support server-side dry runs (at least the versions of OpenEBS we support).
Fixes [SC-42122](https://app.shortcut.com/replicated/story/42122/dry-run-failure-when-deploying-on-kurl-with-openebs).
```release-note
- Fixes deploy log errors for PVCs when using OpenEBS with Kubernetes 1.19-1.21.
```
NONE
=> fix: client-side dry run to support legacy operators

cmd/kots/cli/admin-console.go, cmd/kots/cli/app-status.go, cmd/kots/cli/garbage-collect-images.go, cmd/kots/cli/get-apps.go, cmd/kots/cli/get-config.go, cmd/kots/cli/get-versions.go, cmd/kots/cli/install.go, cmd/kots/cli/remove.go, cmd/kots/cli/set-config.go, pkg/download/download.go, pkg/k8sutil/portforward.go, pkg/snapshot/backup.go, pkg/snapshot/restore.go, pkg/upload/port-forward.go, pkg/upload/upload_license.go
type::feature
The port-forward to the kotsadm pod will be disconnected if the pod is destroyed. This PR will make the CLI automatically attempt to re-establish port-forwarding.
Fixes [SC-43634](https://app.shortcut.com/replicated/story/43634/the-port-forward-to-access-the-admin-console-should-remain-active-and-switch-to-the-new-kotsadm-pod-after-upgrading-kots)
```release-note
NONE
```
NONE
=> feat: cli will attempt to reconnect port-forward if disconnected

.github/workflows/build-test.yaml, .github/workflows/release.yaml, deploy/Dockerfile
type::feature
Including `kots` binary in the Admin Console image will allow automatically upgrading Admin Console in-cluster.
Fixes #
```release-note
NONE
```
NONE
=> Add kots binary to kotsadm image

cmd/kots/cli/check-version.go, cmd/kots/cli/root.go, pkg/handlers/healthz.go
type::feature
The KOTS CLI version may not match the API version after an upgrade of KOTS.  This PR introduces a check that is run after all KOTS CLI commands and will warn the user of a version mismatch.
Fixes [SC-43774](https://app.shortcut.com/replicated/story/43774/cli-to-message-user-when-it-does-not-match-api-version)
Related to [SC-43597](https://app.shortcut.com/replicated/story/43597/poc-auto-upgrading-kots)
```release-note
NONE
```
NONE
=> feat: cli will warn user if version does not match api

.github/workflows/build-test.yaml, .github/workflows/release.yaml, cmd/kots/cli/install.go
type::bug
The existing flag --port-forward defaults to true and was inconsistent with the rest of the boolean flags, which default to false.  This occasionally led to support requests where `--port-forward false` was not leading to the expected behavior.  This PR introduces a new flag `--no-port-forward` that defaults to false and deprecates the old `--port-forward` flag.
Fixes [SC-38396](https://app.shortcut.com/replicated/story/38396/kots-install-port-forward-flag-doesn-t-work-without-the)
Also modified the Github actions to use this new flag in place of `--port-forward=false`.
```release-note
Adds a new flag `--no-port-forward` to the CLI install command to disable automatic port-forwarding. The old flag `--port-forward` has been deprecated.
```
Yes: [Docs …
=> bug: added --no-port-forward flag for install command

.github/workflows/nightly.yaml, actions/version-tag/index.js
type::tests
This PR adds a second nightly build so that tests can be re-run.  The goal is for all tests to pass on at least one of the two runs since some tests fail intermittently.  This should improve the odds that a nightly build can be released.
n/a
n/a
```release-note
NONE
```
NONE
=> added second nightly build

go.mod, go.sum
type::bug
Updates troubleshoot to v0.30.0 to fix viewing pod details in the troubleshoot analysis page.
```release-note
Fixes a bug where the "See details" button in the support bundle analysis page wouldn't show any information about the unhealthy pod.
```
NONE
=> Update troubleshoot to v0.30.0 to fix viewing pod details

cmd/kots/cli/restore.go, pkg/snapshot/restore.go
type::feature
Adds the ability to exclude the applications or the admin console from full snapshot restores using the CLI
```release-note
Adds the ability to exclude the applications or the KOTS admin console from full snapshot restores using the [kots restore](/kots-cli/restore/) CLI command.
```
Pending
=> Ability to exclude the applications or the admin console from full snapshot restores using the CLI

cmd/kots/cli/install.go, pkg/kotsadm/objects/configmaps_objects.go, pkg/kotsadm/types/deployoptions.go
type::feature
This PR stores the necessary CLI flags in a ConfigMap so that they can be later utilized during the automatic upgrade.
Fixes [SC-44027](https://app.shortcut.com/replicated/story/44027/write-kots-cli-install-options-to-config-map-to-support-autoupdating)
```release-note
NONE
```
NONE
=> feat: store cli flags in configmap for autoupgrade

Makefile, okteto-pipeline.yml, okteto.Dockerfile, pkg/image/image.go, pkg/kotsadm/api.go, pkg/operator/client/client.go, pkg/supportbundle/defaultspec/spec.yaml, web/src/components/apps/AppGitops.jsx
type::bug
Allows gitops to be disabled when it's enabled but has an invalid config. Before this change, you were required to fix the configuration and then disable.
no
=> Allow gitops to be disabled when there is not a valid config

cmd/kots/cli/admin-console-push-images.go, pkg/image/builder.go, pkg/kotsadm/copy_images.go, pkg/kotsadm/objects/images.go, pkg/kotsadm/push_images.go
type::feature
This is required in order to do auto-upgrades when Admin Console images are used with a private registry.
Fixes #
This CLI is hidden and will not be documented yet.  Usage looks like this:
```
$ ./bin/kots admin-console push-images docker.io ttl.sh/divolgin
Copying minio/minio:RELEASE.2022-01-08T03-11-54Z to ttl.sh/divolgin/minio:RELEASE.2022-01-08T03-11-54Z
Copying blob 0e3d9ac748ab skipped: already exists  
...
Copying config c0092c1ed2 done  
Writing manifest to image destination
Storing signatures
Copying kotsadm/kotsadm-migrations:v1.59.2 to ttl.sh/divolgin/kotsadm-migrations:v1.59.2
...
Copying config 0ed0ea7b7c done  
Writing manifest to image destination
Storing signatures
...
```
```release-note
* Added experimental CLI for copying Admin Console images to a private …
```
=> CLI to copy Admin Console images to private registry

pkg/kotsutil/kots.go
type::chore
Remove a noisy log line.  Kots version is always a valid semver except in a dev build.
Fixes #
```release-note
NONE
```
NONE
=> Remove noisy log

cmd/kots/cli/admin-console-push-images.go, deploy/Dockerfile, deploy/kots-upgrade.sh, pkg/kotsadm/updates.go, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/DashboardVersionCard.jsx
Self-updates will copy images to private registries automatically.  This is part of the self-updating feature, so no separate release notes are needed.
type::feature
Fixes #
```release-note
NONE
```
NONE
=> Copy kots images to private registry if one is configured during self-updates

pkg/automation/automation.go, pkg/handlers/license.go, pkg/handlers/mock/mock.go, pkg/license/license.go, pkg/store/kotsstore/app_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/app_store.go, pkg/store/store_interface.go
type::bug
This PR allows a user to reupload a license if the license has not been used for a successful installation.  Makes UX much smoother so the user does not have to manually run a command to remove the app.
Fixes [SC-36475](https://app.shortcut.com/replicated/story/36475/unable-to-re-attempt-uploading-the-license-if-it-fails-to-install-the-first-time)
Tested in Okteto, Okteto endpoint for kots web: https://kotsadm-web-stefanrepl.replicated.okteto.dev/. 
```release-note
Allow user to re-upload license if application is not installed.
```
=> allow reupload of license if app is not installed

kurl_proxy/assets/insecure.html, kurl_proxy/assets/tls.html
type::bug
Fixes a bug where the app icon in the metadata would not show as the favicon on the TLS pages.
yes
```release-note
Fixes a bug where the app icon in the metadata would not show as the favicon on the TLS pages.
```
None
=> favicon on TLS pages

pkg/store/kotsstore/version_store.go
type::bug
Fixes an issue where trying to re-download a pending app version after upgrading from KOTS 1.65 would fail due to an invalid license for that version.
```release-note
Fixes an issue where trying to re-download a pending app version after upgrading from KOTS 1.65 would fail due to an invalid license for that version.
```
NONE
=> Only load the license for an app version if it's valid

pkg/handlers/metadata.go, web/src/Root.jsx
This PR fixes a bug where the "Cluster Mangement" tab would not appear when first installing an app (refresh would fix it) if it was installed via kurl.
N/A
N/A
```release-note
- Fixes bug where the Cluster Management tab would not be initially present if the application is installed via kURL
```
NONE
=> Kiraboyle/sc 43176/when installed with kurl the cluster management

.github/workflows/release.yaml
type::chore
Removes the automatic PR generation for the legacy docs site.
N/A
NONE
NONE
=> chore(ci): remove kots.io PR generation

.github/workflows/build-test.yaml, .gitignore, Makefile.build, deploy/build-test-pipeline/selenium-standalone.yaml, deploy/smoke-test/selenium-standalone.yaml, kustomize/overlays/okteto/deployment.yaml, migrations/deploy/Dockerfile, web/.gitignore, web/dist/README.md, web/okteto.Dockerfile, web/okteto.yml
Remove the need for tunneling with testim and improve performance for pull request testing
Fixes #NONE
NONE
```release-note
NONE
```
NONE
=> Fix ngrok failures

pkg/airgap/airgap.go, pkg/online/online.go
type::bug
Fixes an issue where preflights weren't triggered and admin console redirected to config page instead of the dashboard page for automated installs.
```release-note
NONE
```
NONE
=> Trigger preflights after configuring the version

go.mod, go.sum
See https://github.com/golang/go/issues/37278
This resolves the bug created when GitHub removed ssh-1 support, but we should really switch keys to ed25519. This code will remain compatible with keypairs generated previously. Switching to ed25519 likely involves a migration.
=> Use fork of x/crypto

pkg/api/downstream/types/types.go, pkg/registry/images.go, pkg/store/kotsstore/downstream_store.go, pkg/store/kotsstore/version_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/version_store.go, pkg/store/store_interface.go
type::bug
Garbage collection is removing images for previously deployed version using sequence sorting, which is incorrect for semver based channels.
Fixes #
```release-note
* Fixes an issue that can cause images that are still used by the application to be deleted from the private kURL registry during image garbage collection.
```
NONE
=> Respect semver ordering when garbage collecting images

README.md
Fixes #
```release-note
NONE
```
NONE
=> Updated the Readme links from kots.io to docs.replicated.com

pkg/handlers/snapshots.go
type::bug
Fixes an issue where NFS snapshots could not be configured when Minio is enabled.
Fixes [SC-45386](https://app.shortcut.com/replicated/story/45386/unable-to-configure-nfs-snapshots-when-using-minio)
Commented out a piece of code that was not implemented, but was causing a nil pointer panic when configuring an NFS storage location
```release-note
Fixes an issue where NFS snapshots could not be configured when Minio is enabled in the cluster.
```
NONE
=> fix nil pointer panic for NFS snapshots

web/src/components/snapshots/SnapshotSettings.jsx
type::bug
This PR fixes an issue where the UI was checking the snapshot settings every 2 seconds regardless of how long the request took to complete.  This introduced a race condition where later requests to check the settings sometimes returned earlier, causing some weird behavior with the UI.  This would sometimes cause the banner/modal to display indicating that velero was not configured, when it actually was.  This was confusing for customers and led to support issues as a result.
Fixes [SC-37857](https://app.shortcut.com/replicated/story/37857/snapshot-settings-shows-error-while-restic-and-velero-are-restarting)
Without this change, the promise would resolve immediately after the fetch request was initiated.  With this change, it will return the promise generated by the fetch api and …
=> make fetchSnapshotSettings wait for response

.github/workflows/build-test.yaml
type::tests
use correct tag for e2e tests
```release-note
NONE
```
NONE
=> --kotsadm 2h instead of 12h for e2e tests

pkg/handlers/snapshots.go, web/src/components/snapshots/SnapshotSchedule.jsx, web/src/components/snapshots/SnapshotStorageDestination.jsx
type::bug
There is some flakiness in the snapshots UI where it will indicate to the user that velero is not installed after they update the snapshot settings.  This PR addresses two of these issues.
First, the proper values are now being returned from the api so that once settings are updated, the UI can evaluate whether velero is installed and the settings have been updated (dialog below would sometimes show after updating settings indicating velero was not installed).
Second, the UI will now wait for the settings update to complete before showing any warnings indicating that velero is not ready.  Before this, the UI would flash a warning for a few seconds during the settings update, potentially causing some confusion (see screenshot of issue below).
Additional fixes for …
=> fix: addresses snapshot UI bugs indicating velero is not installed

web/src/components/apps/DashboardGraphsCard.jsx, web/src/scss/components/watches/DashboardCard.scss
type::bug
Fixes a style bug that causes the grid of metric graphs to be broken when there are more than three graphs.
```release-note
Fixes a style bug that causes the grid of metric graphs to be broken when there are more than three graphs.
```
NONE
=> handle css in grid of graphs better when scaling beyond three graphs

go.mod, go.sum, pkg/supportbundle/defaultspec/spec.yaml
This PR adds a contour-specific pod health check.
This largely duplicates the 'every namespace' pod health check, but has a better message.
This commit also includes an update to troubleshoot that makes the pod health analyzer detect '0/1 Running' '1/2 Running' etc as 'unhealthy' to match the docs [here](https://troubleshoot.sh/docs/analyze/cluster-pod-statuses/).
Fixes #
```release-note
The default troubleshoot analyzers will now specifically call out issues with envoy/contour if detected.
```
NONE
=> add a contour-specific pod health check

web/src/components/apps/DashboardLicenseCard.jsx, web/src/scss/components/apps/AppLicense.scss, web/src/scss/components/watches/DashboardCard.scss
type::bug
This PR adds the correct className to the dashboard card if the customer license is a community license. This PR also updates the `CommunityLicense` class styles and removes additional unused community card styles.
Fixes #45184 in Shortcut (https://app.shortcut.com/replicated/story/45184)
```release-note
NONE
```
Yes, we will need to update the screenshots on this page: https://docs.replicated.com/vendor/licenses-about-types#about-community-licenses.
Here are updated screenshots:
=> fix: update community license className and remove unused classes

pkg/kotsutil/kots.go
This adds troubleshoot/v1beta2, HostPreflight to the kotsutil LoadKotsKinds function.
KOTS doesn't require this type be loaded because it's generally removed before the manifests are passed to kots. kURL should be the handler for these kinds. But this function (LoadKotsKinds) is exported and used elsewhere, including some other replicatedhq projects that lint and extract custom resources for other purposes. 
This PR will not affect KOTS, but allows a single, unified location for kots kinds to be loaded for maintainability of other projects.
=> Add hostpreflight to kotsutil

pkg/supportbundle/spec.go
All of the YAML collectors collect to admin_console, see https://github.com/replicatedhq/kots/blob/6710b2dd0c0e8ffddf85bbdca230c7c66975b709/pkg/supportbundle/defaultspec/spec.yaml#L19
Fixes #
```release-note
```
=> put all support bundle files in kots/admin_console not kots/admin-console

pkg/handlers/login.go, pkg/handlers/session.go
fixes KOTS JWT session timeout to 12 hours and validates expired sessions and logout automatically
**type::bug**
Current JWT timeout are set to 14 dats which is too long and expired sessions are not validated
Fixes # [SC-34580](https://app.shortcut.com/replicated/story/34580/kots-jwt-timeouts-are-too-long-non-oidc-login)
YES
```release-note
fixes KOTS JWT session timeout to 12 hours and validates expired sessions and logout automatically
```
YES
TODO
=> set KOTS JWT session timeout to 12 hours and validate expired sessions

web/src/components/config_render/FileInput.jsx
type::bug
This PR fixes a bug where the "Select a different file" link to change the uploaded file for was not working.  This PR adds the appropriate label element so that the file input gets triggered properly on click.
Fixes [SC-45124](https://app.shortcut.com/replicated/story/45124/select-a-different-file-link-for-fileuploading-does-not-work)
n/a
```release-note
Fixes an issue where the "Select a different file" link was not allowing the user to change the selected file.
```
NONE
=> fix: "Select a different file" link for file uploads

web/src/components/snapshots/SnapshotSettings.jsx
type::tests
only poll snapshot settings after the update request succeeds to fix tests
```release-note
NONE
```
NONE
=> only poll snapshot settings after the update request succeeds

pkg/handlers/handlers_test.go, pkg/handlers/login.go, pkg/handlers/session.go, pkg/handlers/session_test.go, pkg/store/kotsstore/session_store.go, pkg/store/mock/mock.go, pkg/store/ocistore/session_store.go, pkg/store/store_interface.go
type::bug
Currently kots UI session timeout is 12 hours.
If a user is logged in and is using the UI, he would be automatically logged out.
For user's convenience, extend the session expiry by an hour when current session is less than 11 hours (sessionTimeout: 12 hours - 1 hour) 
Fixes #
```release-note
fixes session timeout by extending the session by an hour if session expiry is at least less than one hour of session timeout
```
NO
=>  fix: extend active user session by an hour if session expiryAt is less than one hour of session timeout

web/src/components/PreflightResultPage.jsx, web/src/components/apps/AppDetailPage.jsx, web/src/components/apps/Dashboard.jsx, web/src/components/shared/modals/SkipPreflightsModal.jsx
type::feature
This PR allows for an application to be deployed when a user selects to ignore preflights during installation.  Previously app was not being deployed when ignoring preflights and this was causing confusion for some customers.
Fixes #
https://app.shortcut.com/replicated/story/36852/skip-preflight-checks-on-initial-install-does-not-install-app
https://github.com/replicated-collab/swaggerhub-kots/issues/19
This PR also includes some clean up and reordering of code.  Code that was no longer relevant was removed, and other code was moved as @sgalsaleh and I found bugs.
```release-note
Automate deployment of application when preflights are ignored.
```
=> when user ignores preflights during installation, deploy the application

pkg/app/app.go, pkg/updatechecker/updatechecker.go
Fixes #
```release-note
Update the 'last checked for updates at' time even when no updates are available
```
=> set the 'last checked for updates at' time even when no updates are available

deploy/Dockerfile, hack/dev/skaffold.Dockerfile, pkg/version/metrics.go
type::feature
I thought graphs were not working. Turns out graphs do not show up before first version is deployed. I don't really know if this intentional.
Fixes NONE
```release-note
Default monitoring graphs will now show up prior to the first app version deployment.
```
NONE
=> Show default monitoring graphs before first version is deployed

pkg/registry/images.go
type::bug
Limits images garbage collection to the application's registry namespace
Fixes [SC-46748](https://app.shortcut.com/replicated/story/46748/images-garbage-collection-should-be-limited-to-the-application-s-registry-namespace)
```release-note
Fixes an issue that causes images garbage collection in embedded clusters to remove images outside of the application's dedicated registry namespace.
```
NONE
=> Images garbage collection should be limited to the application's registry namespace

web/src/components/apps/DashboardGraphsCard.jsx, web/webpack.config.js
type::bug
- Fixes an issue where the legend on the dashboard graphs were blank
- Fixes an issue when hovering on a graph the tooltip showed "LLL" instead of a formatted date
Fixes https://github.com/replicated-collab/mandiant-replicated/issues/64, Fixes https://github.com/replicated-collab/julia-kots/issues/48
```release-note
- Fixes an issue where the legend on the dashboard graphs were blank
- Fixes an issue when hovering on a graph the tooltip showed "LLL" instead of a formatted date
```
NONE
=> fix broken monitoring graph legend, fix broken date templating to show localized date instead of LLL

pkg/store/kotsstore/version_store.go
type::bug
This ensures that application upgrades are re-downloaded and new configuration is applied when an older version is updated with new configuration.
Fixes #
To create this dataset, 45 was deployed, 46 was downloaded, then 45 was updated.
```
sequence | update_cursor | version_label | is_required 
----------+---------------+---------------+-------------
0 | 45            | 0.3.1         | f
1 | 46            | 0.4.2         | f
2 | 45            | 0.3.1         | f
3 | 45            | 0.3.1         | f
(4 rows)
```
Before the change in the PR, the function would return the _latest known_ cursor, which is 46, which would cause replicated.app API to return no updates.
With this change, the function now returns the _currently deployed_ cursor, which is 45, which allows replicated.app …
=> Re-download newer versions if an older one was updated

.github/workflows/codespaces.yaml
this job is broken due to the deletion of a github repo
Fixes #
```release-note
```
=> disable 'prebuild codespace' job on merge to main

pkg/appstate/ingress.go, pkg/identity/deploy/deploy.go, pkg/identity/deploy/undeploy.go, pkg/ingress/deploy.go, pkg/ingress/ingress_config.go, pkg/kotsadm/ingress.go, pkg/kotsadm/objects/kotsadm_objects.go
type::bug
Fixes status informers to use networking.k8s.io/v1 api version for ingress instead of extensions/v1beta1
`networking.k8s.io/v1` will detect both `networking.k8s.io/v1` and `extensions/v1beta1` ingress types
```release-note
Fixes an issue where ingress status informers would always report "missing" in kubernetes 1.22+
```
NONE
=> Fix: use networking.k8s.io/v1 api version for ingress instead of extensions/v1beta1

pkg/handlers/handlers_test.go, pkg/handlers/session.go, pkg/handlers/session_test.go, pkg/store/kotsstore/user_store.go
type::bug
return nil instead of default time when kotsadm password updated is nil
during snapshot restore, if a backup is old and doesn't contain passwordUpdatedAt
when user restores the old snapshot, user will be logged out automatically.
instead of using passwordSecret.CreateTimeStamp, use nil when there is no valid updated timestamp
Fixes #
```release-note
NONE
```
NONE
=> return nil instead of default time when kotsadm password updated is nil

cmd/kots/cli/install.go, cmd/kots/cli/install_test.go, pkg/apiserver/server.go, pkg/automation/automation.go, pkg/handlers/airgap.go, pkg/logger/clilogger.go
type::bug
This PR fixes an issue where automated airgapped installs were not working.  Automated airgapped installs used different logic to install the license, so the status was not being reported using a task and the `kots install` command was unable to verify the installation.  This PR refactors the automated airgap install to use the same logic as the online install.
Additional messaging to the user was also added to better indicate the automated installation progress.
Fixes [SC-45886](https://app.shortcut.com/replicated/story/45886/when-installing-from-the-cli-if-preflights-fail-or-have-a-warning-the-application-isn-t-deployed-but-there-is-no-message) for automated airgapped installations
Screenshots of various outcomes below...
Successful install:
Additional app configuration …
=> refactor AutomateAirgapInstall to use task logic

.github/workflows/release.yaml
the package was removed in ubuntu 20.04
Fixes #
```release-note
```
=> no longer install btrfs-tools for goreleaser

web/src/components/apps/AppConfig.jsx, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/AppVersionHistoryRow.jsx, web/src/components/apps/DashboardGitOpsCard.jsx, web/src/components/apps/DashboardVersionCard.jsx, web/src/components/modals/AutomaticUpdatesModal.jsx, web/src/components/shared/SubNavBar/SubNavBar.jsx, web/src/scss/components/apps/AppVersionHistory.scss, web/src/scss/components/watches/DashboardCard.scss, web/src/scss/variables.scss, web/src/utilities/utilities.js
type::feature
Cleans up the UI and gets rid of confusion around deployed and new available versions when GitOps is enabled.
Fixes #
Demo showing changes: https://www.loom.com/share/1e19ac639f8f43168b136e5ef8698239
```release-note
UI improvements to the Application Dashboard and Version History page when GitOps is enabled
```
NONE (that I know of, potentially some new screenshots but thats TBD)
=> updated GitOps UI for dashboard and version history

kurl_proxy/deploy/Dockerfile, migrations/deploy/Dockerfile
type::chore
Updates gzip and liblzma5 packages to patch CVEs in kurl-proxy and kotsadm-migrations images.
Fixes #
[SC-46660](https://app.shortcut.com/replicated/story/46660/update-kurl-proxy-image-to-address-cve-2018-25032-and-cve-2022-1271)
```release-note
NONE
```
NONE
=> Update gzip and liblzma5 packages to patch CVEs

.github/workflows/nightly.yaml
type::chore
We don't need a second nightly anymore since tests are no longer 'flakey'
n/a
```release-note
NONE
```
NONE
=> remove second nightly

pkg/operator/client/gvkn.go, pkg/operator/client/gvkn_test.go
type::bug
Excludes the api version when identify manifests to be deleted on deploy. kubernetes does not consider the api version when identifying manifests to be deleted or updated, just the kind, name, and namespace.
1- add an ingress object with api version `networking.k8s.io/v1` to your app
2- install and deploy the app
3- replace with an ingress object with api version `extensions/v1beta1` in your app
4- deploy that version => ingress object is recreated when it should've been updated (since kubernetes supports that)
```release-note
* Fixes an issue where changing the api version for a native Kubernetes object caused that object to be deleted and recreated instead of just being updated.
```
NONE
=> Exclude the api version when identifying native k8s manifests to be deleted on deploy

pkg/handlers/config.go, pkg/secrets/sealed_secrets.go, pkg/secrets/secrets.go, pkg/secrets/secrets_suite_test.go, pkg/secrets/secrets_test.go, pkg/store/kotsstore/version_store.go
- adds missing unit tests for secrets logic
- adds support for multidoc secrets that would improperly ignore multiple secrets and drop non secrets if there was a valid secret in that file
Fixes (shortcut)
https://app.shortcut.com/replicated/story/46647/initial-gitops-commit-does-not-use-sealed-secrets
In a clean environment:
- install a kubernetes cluster (ie kurl)
- create a namespace
- create a secret (example attached) and apply to the cluster
- must have the labels:
- `kots.io/buildphase: secret`
- `kots.io/secrettype: sealedsecrets`
- install the app as normal (the app/config should not matter) 
- create a repo for enabling gitops
- In your app, go to the gitops tab and setup gitops as normal ([docs](https://docs.replicated.com/enterprise/gitops-single-app-workflow))
- In the repo, …
=> Kiraboyle/sc 46647/initial gitops commit does not translate all labeled secrets to sealed secrets

web/src/components/troubleshoot/GenerateSupportBundle.jsx
type::feature
Currently, users can generate multiple support bundles at once, and if you navigate away from the `/generate` page, you will lose the ability to track the progress of your support bundle.
This PR adds a check when visiting the `/generate` page, so that if there is an existing bundle in progress, the user will not be shown the button to generate another support bundles. If there is a support bundle in progress, this page will show the progress for the latest bundle.
Fixes [#47061](https://app.shortcut.com/replicated/story/47061/support-bundle-generation-from-kots-ui-can-t-be-done-in-the-background)
There is some follow up work that will need to be done, such as:
- Add the ability to cancel the generation of a support bundle (in the event that it gets "stuck" and never …
=> Prevent multiple support bundles being generated, show in progress support bundle

pkg/operator/operator.go
type::bug
only marks the version as deployed upon restore instead of actually redeploying it
1- install an app and take a partial snapshot
2- restore the snapshot => version should not be stuck on deploying
```release-note
NONE
```
NONE
=> only mark the version as deployed upon restore instead of actually redeploying it

web/src/components/snapshots/SnapshotSchedule.jsx
type::feature
Makes the ability to do a custom snapshot schedule more discoverable.
Here is a video of the change: https://www.loom.com/share/a66a2cca6ffa45bcb76858ef9cfb214e
```release-note
When automatic snapshots are enabled an input showing the CRON schedule is always visible and editable to allow for more granular. 
```
NONE
=> always show cron input. auto switch to custom when typing in the box

kurl_proxy/assets/insecure.html, kurl_proxy/cmd/main.go
type::bug
This PR makes it so that the custom favicon a vendor sets will show on the initial kots cert and tls pages on Chrome and Safari.
Fixes [#47714](https://app.shortcut.com/replicated/story/47714/vendors-branded-icon-does-not-show-in-browser-tab-favicon-on-tls-cert-key-page-in-admin-console-in-chrome)
None
1. Install an app with custom icon.
2. Open admin console in Chrome or Safari.
3. You should see your custom icon in the tab bar at the top (see images below).
```release-note
Fixes custom icons on the TLS/cert page on Safari and Chrome.
```
No
=> Fix broken favicon on TLS pages in Chrome and Safari

pkg/handlers/snapshots.go, pkg/k8sutil/pod.go, pkg/s3/s3.go, pkg/snapshot/filesystem.go, pkg/supportbundle/spec.go
type::bug
When NFS backend configuration for snapshots fails, the user is presented with a generic error message. The specific error is also no surfaced by support bundle analyzers.
This will also clean up orphaned `kotsadm-fs-minio-check` pods once configuration is successful.
Fixes #
- This probably doesn't cover every possible failure mode.
- UI could use some work for cases where error messages are excessively long.
- Screenshots in comments.
1. Navigate to Snapshots settings page
2. Trigger error in one or more of the following ways:
- enter invalid IP address/host name (invalid will cause error to surface sooner; i/o timeout takes longer and may not happen fast enough)
- remove/rename `mount.nfs` binary on the host
- remove write permissions from the NFS directory
3. Click "Update" …
=> Surface Minio FS errors better in UI and support bundles

pkg/handlers/app.go
any airgap version should be installable initially. this wasn't affecting anything, just an error in the logs.
```release-note
NONE
```
NONE
=> any airgap version can be installed initially

README.md, pkg/handlers/app.go, pkg/handlers/dashboard.go, pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/helm_managed.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/policy/policies.go, web/src/components/apps/AppDetailPage.jsx, web/src/components/apps/Dashboard.jsx, web/src/components/apps/DashboardGraphsCard.jsx, web/src/components/apps/DashboardVersionCard.jsx
type::feature
This PR implements viewing helm installations
Fixes #
Link to my okteto environment where I have installed 2 helm charts: https://kotsadm-web-stefanrepl.replicated.okteto.dev
```release-note
Show Helm installations when running in Helm managed mode (beta)
```
=> show installed helm charts in web when running in helm managed mode

pkg/kurl/join_cert.go, pkg/kurl/kurl_nodes.go
On k8s 1.24.0 node labels are changed to `control-plane ` and `master` label is removed. In order to support existing kots installs on 1.24.0, added logic to accommodate  this new label `control-plane`
Fixes # SC-48706
None
No
```release-note
TODO
```
yes
=> Add support to do existing install on k8s 1.24.0

web/src/components/apps/DashboardVersionCard.jsx
Fixes a bug that would cause the confirmation modal to always show "Redeploy" even if the version was not already deployed.
Demo loom: https://www.loom.com/share/361557298c964a57a720beebd3ffd69b
On the dashboard make sure you have a new available version. Click on the deploy button for the new version. you shuold be presented with a dialog to confirm the deployment and the text should read "Deploy version..." and the button should be "Deploy"
```release-note
Fixes a bug that would cause the confirmation modal to always show "Redeploy" even if the version was not already deployed.
```
NONE
=> graysonnull/sc-48421 fix redeploy/deploy logic on dashboard card

web/src/components/apps/AppDetailPage.jsx, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/DashboardVersionCard.jsx, web/src/components/shared/SubNavBar/SubNavBar.jsx, web/src/components/tree/KotsApplicationTree.jsx, web/src/config-ui/subNavConfig.js, web/src/scss/utilities/base.scss
- Hides elements that are not necessary for helm managed installs 
https://app.shortcut.com/replicated/story/48106/remove-parts-of-the-admin-console-that-don-t-make-sense-when-using-the-direct-helm-install
You will need to have a helm managed app install. 
- Add a helm managed application
- View Kots 
```release-note
For helm managed installs: 
- Removes registry settings tab 
- Removes **View Diff** links from application dashboard and history 
- Removes edit file instructions on **View file tab**
```
=> hide more stuff for helm managed charts

go.mod, pkg/handlers/app.go, pkg/handlers/status.go
feature, we need it so we can add value to the kots console when running in helm mode.  This PR adds both the chart version and also uses the chart icon if set for each chart in the UI.
Fixes #
https://app.shortcut.com/replicated/story/48837/show-the-currently-deployed-version-in-the-admin-console
See screenshot attachments
Link to okteto env: https://kotsadm-web-stefanrepl.replicated.okteto.dev/
```release-note
```
=> show deployed chart version and icon for helm charts in UI

pkg/buildversion/buildversion.go, pkg/docker/registry/auth.go, pkg/download/download.go, pkg/handlers/redact.go, pkg/handlers/troubleshoot.go, pkg/handlers/update.go, pkg/kotsadmlicense/platform_license.go, pkg/license/license.go, pkg/metrics/install.go, pkg/reporting/app.go, pkg/reporting/preflight.go, pkg/upstream/replicated.go, pkg/upstream/upgrade.go, pkg/util/request.go, pkg/version/metrics.go
Consistently sets the user-agent to the kots version string in outgoing http requests.
Tracked in SC: https://app.shortcut.com/replicated/story/48588/kots-instances-reporting-kots-version-go-http-client-2-0
None
None
=> Set user agent on outbound http requests

.github/workflows/build-test.yaml, e2e/README.md, e2e/cluster/k3d.go, e2e/e2e_test.go, e2e/helm/cli.go, e2e/kots/kots.go, e2e/kubectl/command.go, e2e/testim/client.go, e2e/util/util.go, e2e/velero/cli.go
testim nightly test is failing cause testim does not have the proper kubeconfig in its env
Fixes NONE
```release-note
NONE
```
NONE
=> Add kubeconfig to testim env

pkg/version/metrics.go
When using prom with scrape annotations our disk usage graph does not work.
Fixes NONE
```release-note
Dashboard "Disk Usage" graph will now report metrics for prometheus deployments using the `kubernetes-service-endpoints` job.
```
NONE
=> Disk usage graph missing for prometheus with kubernetes-service-endpoints job enabled

cmd/imagedeps/main_test.go, cmd/imagedeps/testdata/basic/.image.env, cmd/imagedeps/testdata/basic/constants.go, cmd/imagedeps/testdata/with-overrides/.image.env, cmd/imagedeps/testdata/with-overrides/constants.go
Updates minio image to latest upstream tag to resolve CVEs
Fixes #
`trivy image minio/minio:RELEASE.2022-06-11T19-55-32Z`
```release-note
Updates the MinIO image to address the following critical and high severity CVEs: CVE-2021-42836, CVE-2021-41266, CVE-2020-26160, CVE-2018-25032, CVE-2022-0778, CVE-2022-25235, CVE-2022-25236, CVE-2022-25315, CVE-2022-24407
```
NONE
=> Update minio image to latest upstream tag to resolve CVEs

e2e/Makefile, e2e/testim/client.go
Branch ignore-snapshots-bytes in testim must be merged with fix.
=> Do not check snapshots datasize for nightly e2e test

pkg/base/base.go
This PR excludes installers from the base application manifests.  Currently, installer manifests will be applied along with the rest of the base application manifests and could overwrite resources created by kURL, if applied in the default namespace.
Also fixes [SC-49951](https://app.shortcut.com/replicated/story/49951/don-t-include-the-k8s-installer-in-the-diff)
Not as big of a deal since we are going to be requiring pinned versions for this feature.
1. Include an installer in a release
2. Deploy the release using the admin console
3. Installer will be present in the admin console namespace
```release-note
NONE
```
NONE
=> exclude kurl kinds from base

pkg/handlers/app.go
This fixes a bug that would cause duplicate Helm installations to be shown when running in helm managed mode in clusters with open permissions.
Fixes #
```release-note
Fixed a bug that would cause duplicate Helm installations to be shown when running in helm managed mode in clusters with open permissions.
```
=> fix multiple apps in helm response when running in gke/eks

e2e/e2e_test.go, e2e/kubectl/command.go, e2e/nightly_test.go
Fixes e2e failure when command to produce debug output takes too long to run
https://github.com/replicatedhq/kots/runs/6993028918?check_suite_focus=true#step:8:378
Fixes NONE
```release-note
NONE
```
NONE
=> Don't fail e2e suite on debug output

pkg/installers/installers.go, pkg/preflight/preflight.go, pkg/preflight/preflight_test.go
This PR adds a built-in preflight check for kubernetes installers that are included as part of an application release.  This allows a vendor to include this preflight check so that the end customer is alerted if the kubernetes installer included in the release does not match what is deployed to the cluster.  Since it is a preflight check, the vendor is able to customize the messaging and link out to relevant docs, if desired.
In order to invoke this built-in preflight check, the user must include the `kots.io/installer: "true"` annotation in a `yamlCompare` analyzer:
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
name: installer-preflight
spec:
analyzers:
- yamlCompare:
annotations:
kots.io/installer: "true"
checkName: Kubernetes Installer
outcomes:
- fail:
message: The …
```
=> feat: kubernetes installer preflight

pkg/base/replicated.go
Fixed an issue where KOTS would crash if a Helm Chart is included with optional values and no values.
```
Starting Admin Console API on port 3000...
• Listing releases
• Pulling upstream
• Creating base
panic: assignment to entry in nil map
goroutine 10595 [running]:
github.com/replicatedhq/kots/pkg/base.renderReplicatedHelmChart(0xc000f10000, {0xc001358a00?, 0xc000e2f000?, 0xc00039ef00?}, 0xc0011eeff0, 0x0?)
/home/runner/work/kots/kots/pkg/base/replicated.go:218 +0xfac
github.com/replicatedhq/kots/pkg/base.renderReplicated(0xc000b460c0, 0xc0011eeff0)
/home/runner/work/kots/kots/pkg/base/replicated.go:136 +0x631
github.com/replicatedhq/kots/pkg/base.RenderUpstream(0x53e4860?, 0xc00035a720?)
/home/runner/work/kots/kots/pkg/base/render.go:37 +0x6c …
```
=> Prevent panic nil map

.github/workflows/build-test.yaml, cmd/kots/cli/admin-console-push-images.go
`kots admin-console push-images` command should work with anonymous (or role bases) registries, which means users should be able to omit registry credentials.  Right now the command fails with:
```
Error: failed get registry login from secret: failed to get secret: secrets "kotsadm-private-registry" not found
```
Fixes #
Run `kots admin-console push-images kotsadm.tar.gz ttl.sh/somens` 
```release-note
* Fixes a bug that caused the [push-images](/reference/kots-cli-admin-console-push-images) command to fail when`--registry-password` and `--registry-username` are not specified for use with anonymous registries.
```
NONE
=> push-images command should not require username and password

.github/workflows/build-test.yaml, cmd/kots/cli/admin-console-push-images.go
This is an update for PR https://github.com/replicatedhq/kots/pull/2937.  We should not fail pushing images for any reason, not just if the secret isn't found.
Fixes #
```release-note
NONE
```
NONE
=> Never fail if registry credentials cannot be loaded for any reason

web/src/components/apps/AppStatus.jsx, web/src/scss/components/shared/InlineDropdown.scss
Fixes a regression that caused application spec service links to NOT be rewritten to the hostname used in the browser
Fixes #
```release-note
Fixes a bug that causes links defined in the [SIG Application custom resource](/reference/custom-resource-sig-application) to not be rewritten to the hostname used in the browser
```
NONE
=> Rewrite application spec service links to the hostname used in the browser

pkg/handlers/helm.go, pkg/handlers/license.go, web/src/components/apps/Dashboard.jsx, web/src/components/apps/DashboardLicenseCard.jsx
Get license from replicated app endpoint for helm installations.  Then display the license data in kots UI (refer to screenshot below)
Fixes #
https://app.shortcut.com/replicated/story/51369/show-updated-license-information-in-the-admin-console
```release-note
Display license information in UI for Helm application installs
```
=> display license info for helm app installations

go.mod, go.sum, integration/replicated/pull_test.go, pkg/base/images.go, pkg/base/testdata/base-specs/pod.yaml, pkg/base/write_images.go, pkg/base/write_images_test.go, pkg/image/builder.go, pkg/k8sdoc/types.go, pkg/kotsutil/kots.go, pkg/pull/pull.go, pkg/registry/troubleshoot.go, pkg/registry/troubleshoot_test.go, pkg/rewrite/rewrite.go
Troubleshoot has added some new collectors that need to pull images.  Kots needs to rewrite these images and add pull secrets if they are hosted in private registries.
Fixes #
```release-note
* Fixes a bug that caused private images in some collectors to not be rewritten during preflight checks.
```
NONE
=> Rewrite images in all collectors that use images

.github/workflows/e2e-workspace-cleanup.yaml
Adds a reusable workflow for cleaning up a single e2e test workspace. This will eventually be called by a workflow which finds the workspaces ready to be cleaned up (and can also be called as one-off where needed).
=> Add workflow for cleaning up a single workspace [sc-51778]

pkg/helm/cache.go
Config secret is now always present, so the IsConfigurable flag needs to be set differently.
Fixes #
```release-note
NONE
```
NONE
=> The config secret should always be there, so check if key exists in the map

.github/workflows/release.yaml
This PR automates tagging of the kots-helm repo upon tag of the KOTS repo.  This tagging triggers ci in kots-helm that tags and pushes a versioned chart.
Fixes #
https://app.shortcut.com/replicated/story/53400/automatically-release-kots-helm-chart-when-a-kots-release-is-created
```release-note
```
=> tag helm chart on release

web/src/components/apps/NodeRow.jsx, web/src/components/apps/NodeRow.test.js
This PR updates the label in cluster manage to include the prefix. This allow ease of use for users to copy the labels. 
A common way user will use these labels is `kubectl get nodes -l kubernetes.io/hostname=kurl-demo-2`
Fixes # https://app.shortcut.com/replicated/story/51241/labels-on-the-cluster-management-tab-are-incorrect
1. Enable isKurlEnabled in Root.jsx (navbar component) 
2. In ClusterNodes.jsx, set the response in `/api/v1/kurl/nodes` endpoint
`const response = {
nodes: [
{
name: "ip-172-31-55-169",
isConnected: true,
isPrimaryNode: true,
canDelete: false,
kubeletVersion: "v1.23.9",
cpu: { capacity: 4, available: 0 },
memory: { capacity: 15.625690460205078, available: 0 },
pods: { capacity: 110, available: 0 },
labels: [
"beta.kubernetes.io/arch:amd64", …
=> Miawong/sc 51241/labels on the cluster management tab are incorrect

integration/replicated/pull_test.go, pkg/binaries/kubectl_test.go, pkg/binaries/kustomize_test.go, pkg/operator/client/deploy_test.go, pkg/pull/pull_test.go, pkg/upstream/fetch_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
```release-note
NONE
```
NONE
=> test: use `T.TempDir` to create temporary test directory

pkg/helm/cache.go, pkg/helm/updates.go
Fixes duplicated versions (8.1.8 in the screenshot) on the Version History page when a cached update is installed with Helm.
Fixes #
```release-note
NONE
```
NONE
=> Update cache of available updates when chart versions are installed/removed

web/src/components/apps/AppStatus.jsx
This PR addresses an issue where users are unable to specify a different hostname in the url for the deployed application.  For example, the below spec would create a link with the url: `https://<admin-console-hostname>/some/path` instead of `https://www.example.com/some/path`:
```
descriptor:
links:
- description: "Open the Application"
url: https://www.example.com/some/path
```
In some cases, the user might have a different hostname for the deployed application, so the hostname in the url should reflect what was provided in the spec.
Additionally, if the user provided an invalid url, it could cause an uncaught error on the client-side and render the admin console unusable.
Fixes [SC-48585](https://app.shortcut.com/replicated/story/48585/open-msv-dashboard-button-appears-and-it-redirects- …
=> fix: use parsed url for dashboard link href

web/package.json, web/src/components/apps/AppStatus.jsx, web/src/components/apps/Dashboard.jsx, web/src/components/apps/Dashboard.test.js, web/src/components/apps/styles/paragraphs.js, web/src/components/apps/styles/theme.js, web/yarn.lock
Removes the ability to click on `Details` modal if a user does not have statusInformers defined in the config.
Fixes # https://app.shortcut.com/replicated/story/51243/resource-status-empty-empty-empty-by-default
1. Create a release and remove statusInformers 
2. Promote release, create customer, download license 
3. View that there are no `Details` link 
```release-note
NONE
```
NONE
=> Miawong/sc 51243/resource status empty empty empty by default

pkg/supportbundle/defaultspec/spec.yaml
Added an additional node condition check ("Unknown")
This PR adds a secondary outcome to the node Ready/NotReady check for the default `spec.yaml`. This is needed as we've made an internal Troubleshoot change over at https://github.com/replicatedhq/troubleshoot/pull/622
Main reason for this is that the originating Troubleshoot function to check node availability was not functioning properly.
Adding this secondary outcome will support both Troubleshoot and KOTS
Fixes # Internal Shortcut 49103
This PR does not introduce any 'breaking' changes
NONE
```release-note
NONE
```
NONE
=> Update spec.yaml - Additional node condition check

pkg/kotsadmsnapshot/backup.go, pkg/kotsadmsnapshot/backup_test.go
This PR addresses an issue where backups would fail to validate if a wildcard was present in the KOTS Application `additionalNamespaces` array.  Velero does not allow both a wildcard and specific namespaces to be present in the `includedNamespaces` array for a backup.  We document support for dynamic namespaces in our [docs](https://docs.replicated.com/vendor/operator-defining-additional-namespaces#dynamic-namespaces), but doing this would result in an invalid backup resource.  This PR adds a method that will prepare the list of `includedNamespaces` by removing specific namespaces if a wildcard is present.  Additionally, this method will also remove empty and duplicate namespaces from the `includedNamespaces` array.
Fixes [SC-53815](https://app.shortcut.com/replicated/story/53815/snapshots …
=> fix: remove specific namespaces from backup if wildcard is specified

pkg/handlers/rendered_contents.go, pkg/kustomize/diff.go, pkg/kustomize/helm.go, pkg/kustomize/helm_test.go, pkg/operator/helm.go, pkg/operator/operator.go
Fixes an issue where generating the diff fails when excluding a Helm chart that was previously included
Fixes #
```release-note
Fixes an issue where generating the diff fails when excluding a Helm chart that was previously included
```
=> Fix: Unable to generate diff when excluding a helm chart that was previously included

pkg/template/static_context.go, pkg/template/static_context_test.go
Implements the HTTPS_PROXY template function
Fixes #
```release-note
Adds a [HTTPSProxy](/reference/template-functions-static-context#httpsproxy) template function which returns the address of the proxy that the Replicated admin console is configured to use.
```
https://github.com/replicatedhq/replicated-docs/pull/497
=> Implement HTTPS_PROXY template function

web/src/components/config_render/ConfigFileInput.jsx, web/src/scss/components/config-render/config-base-styles.scss
This adds help text for items of type file in config. 
Fixes # https://app.shortcut.com/replicated/story/45364/kots-config-help-text-field-does-not-work-for-items-of-type-file
1. Create a release 
2. Edit the kots-config.yaml 
3. add 
```
- name: example_settings
title: My Example Config
description: Configuration to serve as an example for creating your own. See [https://kots.io/reference/v1beta1/config/](https://kots.io/reference/v1beta1/config/) for configuration docs. In this case, we provide example fields for configuring an Ingress object.
items:
- name: tls_privkey_pem
title: "SSL/TLS Private Key"
help_text: |
TLS private key.  **Must be in PEM format.**
required: false
type: file
```
4. add app to Admin Console 
5. view Config tab 
6. verify that help text is visible …
=> render help text if it exists for ConfigFileInput

pkg/kurl/kurl_nodes.go
this was improperly removed in https://github.com/replicatedhq/kots/commit/4dd47ac5d28212c6e1e043821533ba23a8329ce0\#diff-b667666f36ab8bad01757412856508e1207d897523d75c9fc50db9143bf5c29bL160
Fixes #
```release-note
Fix the display of node statistics in the "Cluster Management" tab
```
=> use port 10250 when a certificate is available for mTLS

deploy/Dockerfile, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
Updating Kustomize version to 4.5.7 would resolve a lot of CVEs and also unblock us from implementing other features like supporting using both a tag and/or a digest for identifying images.
Fixes #
```release-note
Updates Kustomize version from 3.5.4 to 4.5.7. Note: Kustomize version 4.5.7 does not allow duplicate YAML keys.
```
https://github.com/replicatedhq/replicated-docs/pull/503
=> Update kustomize version from 3.5.4 to 4.5.7

kotskinds/apis/kots/v1beta1/helmchart_types.go, kotskinds/apis/kots/v1beta1/helmchart_types_test.go, pkg/handlers/config.go, web/src/components/shared/modals/HelmDeployModal.jsx
This PR implements only merging repl tmpl values on config changes.  Previously any value present in the Helm Chart CRD would be merged.  This code implements a check against rendered values and templated values to ensure we only merge in templated values that are rendered.
Fixes #
Loom demoing the work: https://www.loom.com/share/5781fe81c5504229a936d2850d688741
```release-note
Fixes a bug that would cause values that did not use repl templating to be rendered into values.yaml on a config update in [Helm managed mode (Alpha)](/vendor/helm-install).
```
=> only merge repl tmpl values on config change in helm managed mode

pkg/supportbundle/supportbundle.go
For applications that ship without support bundle spec, support bundle is now collected using the default collectors and analyzers.
Fixes #
```release-note
* Fixes an issue that caused an error when clicking the Analyze application button on the [Troubleshoot page](/enterprise/troubleshooting-an-app#create-a-support-bundle-using-the-admin-console) when application does not include a support bundle spec in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
=> Use defaul collectors and analyzers, if support bundle spec cannot be downloaded

web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/AppVersionHistoryRow.jsx, web/src/components/shared/modals/HelmDeployModal.jsx
- adds rollback label and command to helm modal on version history page 
https://app.shortcut.com/replicated/story/49673/show-when-there-s-an-update-to-the-helm-chart-available
- you will need to be in helm managed mode to test this 
```release-note
- (alpha) for helm managed installations, add rollback label to deployment button and rollback command to helm modal on version history page 
```
NOne
=> Rianfowler/sc 49673/show when there s an update to the helm chart 5

web/src/config-ui/subNavConfig.js
- Always show license tab when `isHelmManaged`
https://app.shortcut.com/replicated/story/54609/show-the-license-tab
Fixes #54609
- You will need to set your dev environment to helm managed to view 
- open kots in helm managed mode 
```release-note
- (alpha) Fix bug where license tab would not show for helm managed applications 
```
NONE
=> show license tab when isHelmManaged

pkg/base/helm.go
Fixes the bug when HelmChart does not have `namespace` key specified, all `kind: Namespace` manifests in the chart will be excluded from deployment.
Fixes #
```release-note
* Fixes an issue that can cause `Namespace` manifests packaged in Helm charts to be excluded from deployment, causing namespaces to not be created when [useHelmInstall](/reference/custom-resource-helmchart#usehelminstall) is set to `true` and [namespace](/reference/custom-resource-helmchart#usehelminstall) is an empty string.
```
NONE
=> Ignore namespace manifests when adding namespaces with kustomize

web/src/components/apps/AppVersionHistory.jsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx, web/src/features/AppVersionHistory/YamlErrors.jsx, web/src/features/AppVersionHistory/YamlErrors.test.jsx, web/src/features/AppVersionHistory/index.js
- move AppVersionHistoryRow into bulletproof proper directory 
- extract YamlErrors component 
- refactor AppVersionHistoryRow to use new YamlErrors component 
n/a
n/a 
- You'll need to promote a release with yaml errors. I just stuck some random characters at the end of the app deployment yaml 
NONE- this is just a refactor 
NONE
=> extra yaml errors into component

.github/workflows/e2e-workspace-cleanup.yaml, .github/workflows/regression.yaml
This PR adds a step to immediately tear down the test infrastructure on a successful run.
```release-note
NONE
```
=> Add job to tear down infra on a successful test run [sc-55434]

pkg/kurl/node_join.go
There is a discrepancy between what is printed on `kotsadm admin console` with what is printed on the console. I verified the rest of the IP addresses do match (probably got fixed later)
Verified on Dev envt.
Fixes #
SC-24607
```release-note
```
=> Node join commands should fail on network issues early to match console output

pkg/base/images.go, pkg/docker/registry/images.go, pkg/docker/registry/images_test.go, pkg/image/builder.go
This PR adds support for images that include both a tag and digest for online installations.  Previously including these images in a release would result in the following error:
```
failed to parse image ref \"docker.io/library/nginx:1.22@sha256:0b5075a59503dd31d1903f6bcebc834a775277dcbd378b1c100f921b77ca6bec\": Docker references with both a tag and digest are currently not supported
```
This PR adds additional logic that normalizes the ambiguous image reference so that it can be parsed.  If an image has both a tag and a digest, the normalized image will contain the digest only.
Example using private and public images with a tag and digest from various registries:
```
Normal  Pulled     36m   kubelet            Successfully pulled image …
```
=> feat: add support for images with tag and digest

.github/workflows/e2e-workspace-cleanup.yaml
Need to get more reliable cleanup of testing environments. This will force the jumpbox cleanup step to run even if the environment cleanup fails. The jumpbox cleanup will fail if there are still environment resources.
```release-note
NONE
```
=> always try to clean up jumpbox

pkg/version/version.go, web/src/components/apps/AppLicense.jsx, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/Dashboard.jsx, web/src/components/apps/DashboardLicenseCard.jsx, web/src/components/apps/DashboardVersionCard.jsx, web/src/components/modals/AutomaticUpdatesModal.jsx, web/src/components/shared/SubNavBar/SubNavBar.jsx, web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx, web/src/features/AppConfig/components/AppConfig.jsx, web/src/features/AppConfig/components/ConfigInfo.jsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Currently, there is an issue where when the user configures GitOps, it is enabled in the admin console before the deploy key is added to the git provider. This puts you in a state where nothing works—you can't deploy with KOTS, but KOTS also can't yet push updates to the repo.  This PR fixes that issue by not changing the admin console UI until it has successfully connected to the git repo.
Fixes [SC-55411](https://app.shortcut.com/replicated/story/55411/don-t-enable-gitops-until-the-deploy-key-has-been-tested-and-works)
The property `isConnected` reflects whether or not the admin console has successfully connected to the repo, but most of the UI was going off of the `enabled` property, which only indicates whether gitops has been "enabled" which happens when clicking enable. …
=> fix: don't enable gitops until the deploy key is added

web/src/components/shared/CodeSnippet.jsx
https://app.shortcut.com/replicated/story/54423/copy-buttons-on-the-deploy-modals-don-t-work
- AFAIK there isn't a way to test this in okteto directly since there's no way to force it to show the admin console from http 
- I forced the component to render this state by passing in false into the prop as a test (not shown in this code) 
- load kots without TLS 
```release-note
- (alpha) hide copy command in UI when clipboard is not available 
```
NONE
=> add clipboard check to copy command rendering check

web/src/components/watches/DownstreamWatchVersionDiff.jsx
- prerequisite to upgrading to react 18. this component has a logic error that react no longer ignores 
NONE- this is just a refactor 
NONE
=> refactor fetchRenderedApplicationTree to use promise.all

pkg/base/helm.go, pkg/base/helm_test.go
This PR changes the default value for `helmVersion` from `v2` to `v3` for the HelmChart custom resource.  Previously, there was an automatic check of the helm chart `apiVersion` to try and determine the `helmVersion` to use.  If the newer `apiVersion` was present, KOTS would default to `helmVersion: v3`, otherwise KOTS would default to `helmVersion: v2`.  This check has been removed so that we will always default to `helmVersion: v3` unless `helmVersion: v2` is explicitly specified in the HelmChart custom resource.
Fixes [SC-55352](https://app.shortcut.com/replicated/story/55352/change-helm-default-to-v3)
n/a
Create a release with a helm chart resource and do not specify the `helmVersion` in the spec.  It should always default to using helm v3.
```release-note
Changes the default value …
```
=> Default to Helm v3

web/src/components/snapshots/AppSnapshots.jsx, web/src/components/snapshots/Snapshots.jsx
This PR fixes an issue where the fake snapshot row that is created when starting a manual snapshot has a `startedAt` date that results in an uncaught error when being parsed [here](https://github.com/replicatedhq/kots/blob/main/web/src/utilities/utilities.js#L609).  This occurs in the Firefox and Safari web browsers, but does not in Chrome.  This PR changes the date for this temporary row to reflect the format that is eventually returned from the backend.
When starting a snapshot the uncaught error results in:
And results in the following console output:
```
RangeError: date value is not finite in DateTimeFormat.formatToParts()
a http://localhost:8800/main.086962ee69422e5fee8a.js:2
offsetName http://localhost:8800/main.086962ee69422e5fee8a.js:2
o …
```
=> fix: fixes date parsing issue when starting snapshots in firefox

deploy/Dockerfile, deploy/okteto/okteto-v2.Dockerfile, deploy/okteto/okteto.Dockerfile, hack/dev/skaffold.Dockerfile
This PR updates the version of the Helm binary that is included in the KOTS image to resolve CVE-2022-21698 and CVE-2022-27191.
```
usr/local/bin/helm3.8.2 (gobinary)
Total: 2 (HIGH: 2, CRITICAL: 0)
┌─────────────────────────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬───────────────────────────────────────────────────┐
│               Library               │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                       Title                       │
├─────────────────────────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────────────────────────┼───────────────────────────────────────────────────┤
│ …
```
=> fix: update helm to resolve CVE-2022-21698 and CVE-2022-27191

pkg/template/license_context.go, pkg/template/license_context_test.go
This PR fixes the `'{{repl LicenseFieldValue "isSnapshotSupported" }}'` template function.  Currently, this template function will return an empty string since it does not appear in the switch statement.
Fixes [SC-56285](https://app.shortcut.com/replicated/story/56285/issnapshotsupported-value-for-licensefieldvalue-template-function-returns-an-empty-string)
Upstream:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: example-configmap
data:
isSnapshotSupported: '{{repl LicenseFieldValue "isSnapshotSupported" }}'
```
Base:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: example-configmap
data:
isSnapshotSupported: ''
```
```release-note
Fixes an issue where the [LicenseFieldValue](https://docs.replicated.com/reference/template-functions-license-context#licensefieldvalue) template …
```
=> fix: add isSnapshotSupported to LicenseFieldValue template function

pkg/helm/charts.go, pkg/license/license.go
When no kots app config values are provided for helm at install or upgrade time, don't error out.  Just show empty config.
Fixes #
```release-note
NONE
```
NONE
=> Fix error when no config values provided for helm

web/src/components/snapshots/SnapshotStorageDestination.jsx
Fixes being able to type in the 'path' field for other s3-compatible storage destination
Fixes #
```release-note
- Fixes an issue in the UI where typing in the `path` field for other S3-compatible storage snapshot destination did not work.
```
NONE
=> Fix being able to type in the 'path' field for other s3-compatible storage destination

web/src/components/apps/AppGitops.jsx, web/src/components/gitops/SetupProvider.jsx, web/src/scss/components/apps/AppVersionHistory.scss, web/src/scss/components/shared/NavBar.scss, web/src/scss/components/shared/SideBar.scss, web/src/scss/components/watches/Dashboard.scss
This change allows vendor to use square or circular logos without cutting off the logo. 
Previously: 
Current change - square logo 
Current change - circle logo 
Current change - with community logo 
Fixes # https://app.shortcut.com/replicated/story/37566/vendor-has-more-styling-control-for-vendor-logo
```release-note
Allows vendors to use square or circular logos. 
```
NONE
=> Allow square and circular app logos 

pkg/handlers/app.go, pkg/handlers/config.go, pkg/helm/charts.go, web/src/components/shared/modals/HelmDeployModal.jsx, web/src/features/AppConfig/components/AppConfig.jsx
When a Helm release is redeployed or when a release config changes, the `helm upgrade` command must be pinned to the correct release version, otherwise the latest release (if available) will be pulled down and installed.
Fixes #
1. Install a chart version
2. Ship a new chart release, but don't "Check for updates"
3. Try redeploying the installed version or updating the config
```release-note
* Fixes an issue that caused inadvertent application upgrades while redeploying or updating the config of the currently installed release in [Helm managed mode (Alpha)](/vendor/helm-install)
```
NONE
=> When redeploying or updating config, pin helm command to the correct chart version

pkg/api/handlers/types/types.go, pkg/handlers/app.go, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/DashboardVersionCard.jsx, web/src/components/shared/modals/HelmDeployModal.jsx, web/src/features/AppConfig/components/AppConfig.jsx
When running helm upgrade upgrade commands, `-n <namespace>` parameter will be included on command line.
Fixes #
```release-note
* Fixes an issue that caused namespace to be omitted from the `helm upgrade` command in [Helm managed mode (Alpha)](/vendor/helm-install)
```
NONE
=> Include namespace in helm upgrade commands

pkg/app/types/app.go, pkg/app/types/helm_app.go, pkg/app/types/types.go, pkg/handlers/config.go
Live config render functionality in Helm managed mode
Fixes #
```release-note
* Fixed an issue that could cause templates to be shown on the [config page](/vendor/config-screen-about#admin-console-config-tab) instead of actual rendered values in [Helm managed mode (Alpha)](/vendor/helm-install)
```
NONE
=> Live-render config in Helm mode

.github/workflows/release.yaml
These tests currently don't run, neither on merge, nor on actual release tag. This PR fixes that so that they run on merge similar to other tests.
=> fix: trigger target/min/range/kgrid tests on merge

web/src/components/apps/AppRegistrySettings.jsx, web/src/components/shared/AirgapRegistrySettings.jsx, web/src/scss/components/watches/WatchDetailPage.scss
As part of the custom branding, updating the registry settings page UI with a background color is needed to ensure elements are still visible if app's background color is changed. 
**Before:** 
**Current Change:** 
Fixes # https://app.shortcut.com/replicated/story/56997/update-registry-settings-ui
```release-note
NONE
```
NONE
=> Update Registry Settings UI

kotskinds/apis/kots/v1beta1/application_types.go, kotskinds/config/crds/kots.io_applications.yaml, kotskinds/schemas/application-kots-v1beta1.json, pkg/handlers/metadata.go, web/src/Root.jsx
This PR adds a `branding` field to the KOTS application custom resource.  This field will allow a vendor to include a css string that will be applied to the admin console UI.
Example usage:
```
apiVersion: kots.io/v1beta1
kind: Application
metadata:
name: my-app
spec:
title: My Application
branding: |
.btn.primary {
background-color: red;
}
```
Fixes [SC-56511](https://app.shortcut.com/replicated/story/56511/use-custom-css-to-modify-the-look-of-the-admin-console-using-a-field-in-the-kots-application-kind)
Not exactly sure how testim tests for css, but we should have some basic testing for this feature once we document all of the class names.
Add some css to the application resourse `branding` field.  *Note, this field requires the `is_branding_enabled` entitlement in Vendor Portal in …
=> feat: allow custom branding of the admin console

pkg/password/password.go, pkg/store/kotsstore/session_store.go
The missing label is needed to clean up dynamically created secrets when uninstalling Helm managed installs
Fixes #
```release-note
* Fixes an issue that caused secrets and config maps created outside of Helm to be left over in the namespace after Helm chart is uninstalled in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
=> Add kotsadm label to sessions sectret; there is one on all other secrets

pkg/handlers/config.go, pkg/handlers/helm.go, pkg/helm/charts.go, pkg/helm/updates.go, pkg/util/tar.go, web/src/components/apps/DashboardVersionCard.jsx, web/src/components/shared/modals/HelmDeployModal.tsx, web/src/features/AppConfig/components/AppConfig.jsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
In Helm managed mode, releases don't have sequences/revisions and there is no `kind: Config` files available for these.  This makes config screen not work for pending updates.
This PR adds `isPending` and `semver` parameter to URLs.  When specified, the API fetches the matching chart version from registry and uses the `kind: Config` file extracted from the chart itself, not from the cluster.
Fixes #
```release-note
* Adds ability to configure and deploy pending updates when Admin Console is running in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
=> Ability to edit config for pending upgrades

pkg/apiserver/server.go, pkg/operator/operator.go, pkg/operator/operator_test.go
This PR fixes an issue where status informers were not being re-applied when the kotsadm pod restarted.  This is because status informers were only applied after an application deployment, so when the pod restarted, the application status would remain as it was prior to the restart and would only update once a version was deployed/redeployed.  This PR changes this so that status informers for the currently deployed release (if there is one) will be applied when the operator starts up.
Fixes [SC-55879](https://app.shortcut.com/replicated/story/55879/status-informers-do-not-get-re-applied-after-kotsadm-pod-restarts)
Refactored the `Start(...)` method for the operator to accept the client and store interfaces as arguments so we can more easily unit test it.
1. Deploy an application with …
=> start status informers when operator starts

pkg/apiserver/server.go, pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/version/version.go
This PR refactors the operator so that it can be unit tested more easily.  It creates an `Init(...)` method that initializes the operator with a client and store interface.  This will allow for mocks to be used when unit testing.
n/a
Added a global reference to the initialized operator within the package that is accessed using the `MustGetOperator()` method.  This method will panic if the operator has not yet been initialized.  This was necessary because the deploy method is used elsewhere in the code and we need a way to access the currently initialized operator.
```release-note
NONE
```
NONE
=> refactor operator to improve unit testing

kurl_proxy/go.mod, kurl_proxy/go.sum
This PR updates the `github.com/gin-gonic/gin` module in the kurl_proxy image to resolve CVE-2020-28483.
n/a
n/a
Build kurl_proxy alpha image.  Run trivy scan:
```
trivy image --format table --ignore-unfixed --severity CRITICAL,HIGH kotsadm/kurl-proxy:alpha
```
```release-note
Updates the github.com/gin-gonic/gin module in the kurl-proxy image used for embedded cluster installations, to resolve CVE-2020-28483 with high severity.
```
NONE
=> resolve CVE-2020-28483 in kurl_proxy image

web/src/components/SecureAdminConsole.jsx
Fixes # https://app.shortcut.com/replicated/story/47115/add-redirect-if-user-visits-kots-login-when-already-authenticated
```release-note
Redirects user to /apps if they are already logged in. 
```
NONE
=> Redirect to apps when user already authenticated

pkg/base/helm.go, pkg/base/helm_test.go
Fixes an issue where kots fails to render helm charts that have subcharts referenced as local file repositories
Fixes #
```release-note
Fixes an issue where KOTS fails to render Helm charts that have subcharts referenced as local file repositories
```
NONE
=> Fix: kots fails to render helm charts that have subcharts referenced as local file repositories

web/src/scss/components/Login.scss
Fixes # https://app.shortcut.com/replicated/story/57825/license-upload-page-should-also-remove-border-radius-from-app-icon
```release-note
NONE
```
NONE
=> remove border radius and box shadow from app logo

web/src/Root.jsx, web/src/components/SecureAdminConsole.jsx, web/src/features/AddNewApp/components/InstallWithHelm.jsx
- adds new route and component for showing helm install instructions 
https://app.shortcut.com/replicated/story/53446/in-helm-managed-mode-user-is-prompted-to-upload-license
- Need to navigate directly to `/install-with-helm` to view 
- I expect the redirect changes to be complicated so I'm isolating this change 
NONE- will add release notes in PR with redirect updates 
NONE
=> Rianfowler/sc 53446/in helm managed mode user is prompted to

pkg/image/image.go, pkg/image/image_test.go, pkg/upstream/push_images.go, pkg/upstream/push_images_test.go, web/src/components/modals/AutomaticUpdatesModal.jsx
Fixes an issue where KOTS image garbage collection deletes images that are still in use by application.
Fixes #
```release-note
Fixes an issue in embedded clusters where image garbage collection deletes images that are still in use by application.
```
NONE
=> fix: kots image garbage collection deletes images that are still in use by application

pkg/kotsadm/objects/minio_objects.go
This PR bumps the memory limit for the kotsadm-minio statefulset from 200Mi to 512Mi per recommendations [here](https://github.com/minio/minio/issues/7962#issuecomment-516442231).  Also stated [here](https://github.com/minio/minio/issues/15664#issuecomment-1239439157) that 200Mi is low for Minio.
Fixes [SC-33669](https://app.shortcut.com/replicated/story/33669/minio-pod-crashes-due-to-oom)
```release-note
Increases the memory limit for the `kotsadm-minio` statefulset from 200Mi to 512Mi.
```
NONE
=> fix: bump minio memory limit to 512Mi

web/src/components/apps/AppLicense.jsx, web/src/components/apps/DashboardLicenseCard.jsx, web/src/components/apps/LicenseFields.jsx, web/src/components/apps/LicenseFields.tsx
Loom: https://www.loom.com/share/dbccca64fa364c96904b5308ea0803a7
Fixes # 
```release-note
Updates the UI for customer license entitlements to provide better visibility.
```
NONE
=> Miawong/sc 55710/redesign how we display custom license fields

pkg/k8sutil/portforward.go, pkg/k8sutil/portforward_test.go
Fixes an issue where headless/unattended installs hang in embedded clusters with recent Kubernetes versions.
Fixes [SC-55766](https://app.shortcut.com/replicated/story/55766/headless-unattended-install-does-not-work-in-kurl-clusters)
```release-note
Fixes an issue where headless/unattended installs hang in embedded clusters with recent Kubernetes versions.
```
NONE
=> fix: Headless/unattended install hangs in embedded clusters with recent kubernetes versions

pkg/handlers/config.go, pkg/helm/updates.go
When viewing config for a pending update, all previously configured values are missing and have to be re-entered manually.  With this change we use values for the currently deployed version to pre-populate the config screen.
This also adds caching for pending Helm releases to make Config page and live config faster.
Fixes #
```release-note
* Fixes an issue that caused values to be missing on the [config page](/vendor/config-screen-about#admin-console-config-tab) for pending updates in [Helm managed mode (Alpha)](/vendor/helm-install)
```
NONE
=> Use values from currently deployed version to display on config for pending version

web/src/components/snapshots/SnapshotStorageDestination.tsx
This PR fixes an issue where the proper data was not being sent to the `/api/v1/snapshots/settings` endpoint when updating snapshot settings (for AWS and GCP storage locations).
Fixes a failing regression test where instance role snapshots could not be configured.
Create embedded cluster.  It will be automatically configured with internal snapshots.  Try changing the settings to AWS instance role snapshots.
```release-note
NONE
```
NONE
=> fix check for snapshot settings changed

pkg/airgap/update.go, pkg/handlers/app.go, pkg/handlers/config.go, pkg/handlers/status.go, pkg/handlers/update.go, pkg/helm/helm.go, pkg/helm/updates.go, pkg/kotsadmupstream/upstream.go, pkg/tasks/tasks.go, pkg/updatechecker/updatechecker.go, web/src/components/apps/DashboardVersionCard.jsx, web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
When checking for updates in Helm managed mode, pull charts from upstream and check if config is needed so the user can be taken to config screen before deploying new releases.  Update status is now shown as `Pending config` if config is needed.
Updates are downloaded as soon as they are received
The Update button has correct state on the Version history page
The Configure button is shown on the Dashboard
Fixes #
```release-note
* Fixes an issue that allowed new Helm releases to be deploying without configuring them first when there is a missing required configuration value in [Helm managed mode (Alpha)](/vendor/helm-install)
```
NONE
=> Propagate pending_config status to UI when config is needed

pkg/operator/operator.go, pkg/operator/operator_test.go
This PR modifies the operator `Start(...)` method to run the resume status informers task in a goroutine.  It also incorporates the `golang.org/x/sync/errgroup` module so that the method can properly wait for the goroutines for each task to finish before returning.  This makes the `Start(...)` method of the operator easier to unit test.
Fixes #
```release-note
NONE
```
NONE
=> chore: resume status informers in goroutine

web/src/components/PreflightRenderer.jsx
before
with current change
Fixes # https://app.shortcut.com/replicated/story/57456/when-a-strict-preflight-fails-the-message-is-misaligned
```release-note
Fixes message alignment when a strict preflight check fails. 
```
=> fix message alignment when strict preflight check fails

pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/helm.go, pkg/helm/charts.go, pkg/helm/updates.go, web/src/components/hooks/useDownloadValues.js, web/src/components/hooks/useDownloadValues.test.jsx, web/src/features/AppConfig/components/AppConfig.jsx
Downloaded values.yaml file always uses values spec from the currently deployed version.  Instead it should use the values spec for the version that is being configured and deployed.
Fixes #
```release-note
* Fixes an issue that caused config templates to be applied to the wrong values.yaml file in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
=> Use correct sequence/semver when downloading values.yaml file

pkg/updatechecker/updatechecker.go
Use currently deployed values to check if a pending update requires a config in Helm managed mode.
Fixes #
```release-note
* Fixes a bug that caused the config screen to be displayed for a new version with required config items even if all config values had been set in a previously deployed version in [Helm managed mode (Alpha)](/vendor/helm-install).
```
NONE
=> Use values from currently deployed version to check if pending_config

e2e/hack/deps.sh, pkg/helm/cache.go, web/src/components/apps/AppVersionHistory.jsx, web/src/components/apps/DashboardVersionCard.jsx, web/src/components/hooks/useDownloadValues.js, web/src/components/hooks/useDownloadValues.test.jsx, web/src/components/hooks/useIsHelmManaged.test.jsx, web/src/components/hooks/useSaveConfig.test.jsx, web/src/features/App/api/getApps.test.jsx, web/src/features/AppConfig/components/AppConfig.tsx, web/src/features/AppVersionHistory/api/getVersions.test.jsx
- When new version is configured with all required config items, all other pending versions should have the same values applied by default, making configuration step before deployment optional.
- Fixes the download values.yaml button on the Version History and Dashboard for pending Helm releases.
Fixes #
```release-note
NONE
```
NONE
=> Recalculate config_pending when new version is deployed

.github/workflows/alpha.yaml, .github/workflows/build-test.yaml, .github/workflows/release.yaml, Makefile, e2e/e2e_test.go, e2e/kots/kots.go, e2e/testim/inventory/inventory.go, e2e/testim/inventory/test.go, pkg/handlers/app.go, pkg/handlers/download.go, pkg/k8sutil/portforward.go, pkg/kotsadmupstream/upstream.go, pkg/pull/peek.go, pkg/pull/pull.go, pkg/updatechecker/updatechecker.go, web/Makefile, web/src/components/shared/SubNavBar/SubNavBar.jsx
1. Binaries made on branches now have valid semvers
2. Bumped tests to k8s v1.24
3. Three fixed tests now use the built versioned artifact instead of the kots.io/install script for their setup because nightly releases no longer exist and cannot be installed.
- these tests have also been moved to the `build-test` workflow from the `release` workflow.
- these tests have also been updated to use the e2e test code.
4. Adds `enable-tests` job that can be used to turn tests off to speed up iterating on a single test
5. Fixes a bug where versions with `pending_download` status would not be shown correctly on the Version History page.
6. Fixes a bug where versions with `pending_download` would cause the `View Files` tab to navigate to a version that has not been downloaded yet.
7. Fixes a bug …
=> Use semver tag for all binaries

pkg/updatechecker/updatechecker.go
Fixes an issue where automatic update checks panic when interval is too short for pending updates to be fetched
Fixes #
```release-note
Fixes an issue where automatic update checks fail when the interval is too short for pending updates to be fetched.
```
NONE
=> Fix: automatic update checks panic when interval is too short for pending updates to be fetched

pkg/handlers/handlers.go, pkg/handlers/handlers_test.go, pkg/handlers/interface.go, pkg/handlers/mock/mock.go, pkg/handlers/update_checker_spec.go, pkg/helm/updates.go, pkg/online/online.go, pkg/store/kotsstore/app_store.go, pkg/store/kotsstore/kots_store.go, pkg/store/kotsstore/task_store.go, pkg/store/mock/mock.go, pkg/store/store_interface.go, pkg/updatechecker/updatechecker.go, web/src/components/modals/AutomaticUpdatesModal.jsx
- Show previously saved values when `Configure automatic updates` is opened.
- Revert non-Helm apps to use postgres for update check schedule.
Fixes #
```release-note
* Fixes an issue that caused custom automatic update schedule to not be shown after it's saved on the [Configure automatic updates](https://docs.replicated.com/enterprise/updating-apps#configure-automatic-updates).
```
NONE
=> Show automatic update check config that was previously saved
